src/objects/Contact/fields/Display_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Mailing_Country__c</fullName>
    <label>Display Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Display_ISO_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_ISO_Country__c</fullName>
    <label>Display ISO Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/IndividualRecordHelper.cls
/**
Class Name : IndividualRecordHelper
Date : 29th April 2021
created By : Surendar
Description : Individual Record Helper
**/
public class IndividualRecordHelper {
    /**
Method Name : updatewithIndividual
Date : 29th April 2021
created By : Surendar
description : updates lead/Contact with Individual Id in beofre Insert event, if individual record already preset with email.
**/
    public static void updatewithIndividual(List<sObject> newRecords){
        Set<String> emails = new Set<String>();
        Map<String, Individual> IndividualMap = new Map<String, Individual>();
        for(sObject sobj : newRecords){
            emails.add((String)sobj.get('Email'));
        }
        for(Individual ind : [SELECT Id, Email__c 
                              FROM Individual 
                              WHERE Email__c IN :emails]){
                                  IndividualMap.put(ind.Email__c, ind);
                              }
        for(sObject sObj : newRecords){
            if(IndividualMap.containsKey((String)sobj.get('Email'))){
                sObj.put('IndividualId', IndividualMap.get((String)sobj.get('Email')).Id);
            }
        }
    }
    /**
Method Name : createNewIndividual
Date : 29th April 2021
created By : Surendar
description : updates lead with Individual Id in after Insert event, 
creates new records & map with lead, if Individual record not present in system.
**/
    public static void createNewIndividual(List<sObject> newRecords){
        Map<String, Individual> IndividualMap = new Map<String, Individual>();
        List<sObject> updateRecords = new List<sObject>();
        for(sObject sObj : newRecords){
            Id recId = (Id)sObj.get('Id');
            if(sObj.get('IndividualId') == null){
                Individual newInd = new Individual();
                newInd.FirstName = (String)sObj.get('FirstName');
                newInd.LastName = (String)sObj.get('LastName');
                newInd.Email__c = (String)sObj.get('Email');
                if(recId.getSObjectType().getDescribe().getName() == 'Lead')
                    newInd.Country__c = (String)sObj.get('Display_ISO_Country__c');
                else
                    newInd.Country__c = (String)sObj.get('Display_Mailing_Country__c');
                IndividualMap.put(newInd.Email__c, newInd);
            }
        }
        if(IndividualMap != null && !IndividualMap.isEmpty()){
            insert IndividualMap.values();
            
            for(sObject sObj: newRecords){
                if(sObj.get('IndividualId') == null && IndividualMap.containsKey((String)sObj.get('Email'))){
                    sObject newRec; 
                    Id recId = (Id)sObj.get('Id');
                    if(recId.getSObjectType().getDescribe().getName() == 'Lead'){
                        newRec = new Lead();
                        newRec.put('id', recId);
                        newrec.put('IndividualId', IndividualMap.get((String)sObj.get('Email')).Id);
                    }else {
                        newRec = new Contact();
                        newRec.put('id', recId);
                        newrec.put('IndividualId', IndividualMap.get((String)sObj.get('Email')).Id);
                    }
                    updateRecords.add(newrec);
                }
            }
            if(updateRecords != null && !updateRecords.isEmpty()){
                String jsonString = json.serialize(updateRecords);
                updateSobjRecords(jsonString);
            }
        }
    }
    
    /**
Method Name: updateSobjRecords
Description: updates leads in after insert event.
**/
    @future
    public static void updateSobjRecords(String leads){
        List<sObject> sObjectList = (List<sObject>)Json.deserialize(leads, List<Lead>.class);
        database.update(sObjectList, false) ;
    }
}