src/objects/Account/fields/AR_Amount__c.field-meta.xml
<CustomField>
    <fullName>AR_Amount__c</fullName>
    <label>AR Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/classes/AccountTriggerHelperTest.cls
@isTest
public class AccountTriggerHelperTest {
    @isTest
    public static void testAccountInsert(){
        Id siteRT_Id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
       	
        Id globalParentRT_Id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId();

        Account parent = new Account(Name = 'Test ultimate ' + DateTime.now(), RecordTypeId = globalParentRT_Id);
        insert parent;
        
       	Account acct = new Account(RecordTypeId = siteRT_Id, 
                                   Name = 'Test site ' + DateTime.now(), 
                                   ParentId = parent.Id,
                                   ShippingState = 'NY',
                                   ShippingCity = 'Test City',
                                   ShippingCountry = 'IND',
                                   ShippingPostalCode = '560100',
                                   ShippingStreet = 'Test Street',
                                   Type = 'Site',
                                   AR_Amount__c = 0,
                                   Site_Use_Code__c='BILL_TO'
                                  );
        insert acct; 
        
        acct.Type = 'Customer';
        acct.AR_Amount__c = 1;
                
        update acct;  
        
        System.assertEquals(1, acct.AR_Amount__c);
        System.assertEquals('Customer', acct.Type);
    }
    
   
}