src/objects/Account/fields/Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Business_Segment__c</fullName>
    <label>Business Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAX/DIV</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>SUZ</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Italia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>HIGHYAG</fullName>
            </value>
            <value>
                <fullName>eV</fullName>
            </value>
            <value>
                <fullName>AdvMat</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>DEU</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Suwtech</fullName>
            </value>
            <value>
                <fullName>Laser Enterprise</fullName>
            </value>
            <value>
                <fullName>M Cubed</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Epiworks</fullName>
            </value>
            <value>
                <fullName>Photop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas, The</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Virgin Is.</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Qual_Required__c.field-meta.xml
<CustomField>
    <fullName>Qual_Required__c</fullName>
    <description>Select YES if this product was quoted as a product to be qualified by the customer.</description>
    <inlineHelpText>Orders where customers are performing qualification (new device or change to existing device). Contract review level 1 will be required.</inlineHelpText>
    <label>Customer Qual Req&apos;d?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Sales_Price_reflects_Opp_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price_reflects_Opp_Currency__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, user is confirming that the Sales Price entered (and other monetary value fields entered, if applicable) reflects the Opportunity Currency field value on the parent Opportunity.</description>
    <inlineHelpText>If checked, user is confirming that the Sales Price entered (and other monetary value fields entered, if applicable) reflects the Opportunity Currency field value on the parent Opportunity.</inlineHelpText>
    <label>Sales Price reflects Opp. Currency</label>
    <type>Checkbox</type>
</CustomField>

src/objects/OpportunityRatePlan__c/OpportunityRatePlan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Rate Plan</label>
    <nameField>
        <displayFormat>ORL-{00000}</displayFormat>
        <label>Opportunity Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityRatePlan__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>Opportunity Line Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

src/objects/Order/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>Ship_To_Location__r.ShippingCountry</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

src/objects/Order_Line__c/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Unit_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Selling_Price__c</fullName>
    <label>Unit Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/OrderRatePlan__c/OrderRatePlan__c.object-meta.xml
<CustomObject>
    <label>Order Rate Plan</label>
    <nameField>
        <displayFormat>ORT-{00000}</displayFormat>
        <label>Order Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderRatePlan__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Order Rate Plans</relationshipLabel>
    <relationshipName>Order_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Product2/fields/Segment_Number__c.field-meta.xml
<CustomField>
    <fullName>Segment_Number__c</fullName>
    <inlineHelpText>83 = ECOC
44 = Highyag
17 = Singapore
30 = M Cubed
13 = AMD
16 = Epiworks
2 = Global Laser Solutions</inlineHelpText>
    <label>Segment Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/USMO__c.field-meta.xml
<CustomField>
    <fullName>USMO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>USMO</label>
    <type>Checkbox</type>
</CustomField>

src/objects/QuoteRatePlan__c/QuoteRatePlan__c.object-meta.xml
<CustomObject>
    <label>Quote Rate Plan</label>
    <nameField>
        <displayFormat>QRP-{00000}</displayFormat>
        <label>Quote Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteRatePlan__c/fields/LeadTime__c.field-meta.xml
<CustomField>
    <fullName>LeadTime__c</fullName>
    <label>Lead Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ATLaS</fullName>
    </customValue>
    <customValue>
        <fullName>DBA</fullName>
    </customValue>
    <customValue>
        <fullName>Duzon</fullName>
    </customValue>
    <customValue>
        <fullName>Glovia</fullName>
    </customValue>
    <customValue>
        <fullName>IFS-CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>IFS-US</fullName>
    </customValue>
    <customValue>
        <fullName>Inxsys</fullName>
    </customValue>
    <customValue>
        <fullName>Jingsuan</fullName>
    </customValue>
    <customValue>
        <fullName>K2</fullName>
    </customValue>
    <customValue>
        <fullName>Mapics</fullName>
    </customValue>
    <customValue>
        <fullName>MRDC</fullName>
    </customValue>
    <customValue>
        <fullName>NetSuite</fullName>
    </customValue>
    <customValue>
        <fullName>OEDNRE</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle-EBS</fullName>
    </customValue>
    <customValue>
        <fullName>PACC</fullName>
    </customValue>
    <customValue>
        <fullName>PMD</fullName>
    </customValue>
    <customValue>
        <fullName>Pointman</fullName>
    </customValue>
    <customValue>
        <fullName>proALPHA</fullName>
    </customValue>
    <customValue>
        <fullName>ProMan</fullName>
    </customValue>
    <customValue>
        <fullName>SAP-CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP-US</fullName>
    </customValue>
    <customValue>
        <fullName>SiCRnD</fullName>
    </customValue>
    <customValue>
        <fullName>SSRS</fullName>
    </customValue>
    <customValue>
        <fullName>ProMan-CMG</fullName>
    </customValue>
    <customValue>
        <fullName>ProMan-PPG</fullName>
    </customValue>
    <customValue>
        <fullName>ProMan-RD</fullName>
    </customValue>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

src/classes/TestDataFactory.cls
public class TestDataFactory {
   /** public static void createCountrycodes(){
        Country_Code__c cc = new Country_Code__c(Name = 'US', Country__c = 'UNITED STATES');
        insert cc;
    } **/
    public static List<Account> createAccounts(Integer count){
        //createCountrycodes();
        List<Account> accList = new List<Account>();
        for(Integer i = 0; i< count; i++){
            accList.add(new Account(Name = 'Test Account '+i, Business_Segment__c = 'CORP',
                                   ShippingCity = 'city', ShippingCountry = 'US', CurrencyIsoCode = 'USD', Display_Shipping_Country__c = 'American Samoa'));
        }
        if(accList != null && !accList.isEmpty()){
            insert accList;
        }
        return accList;
    }
    public static List<Opportunity> createOpportunity(Integer count, String accountId){
        List<Opportunity> oppList = new List<Opportunity>();
        for(Integer i = 0; i<count; i++){
        	oppList.add(new Opportunity(name = 'test Opp '+i, AccountId = accountId,Qual_Required__c ='Yes',
        Project_Name__c   = 'Test', StageName = 'Qualified Opportunity', Legacy_Id__c = '43s3432',
                                        CloseDate = Date.today().addDays(30)));    
        }
        if(oppList != null && !oppList.isEmpty()){
            insert oppList;
        }
        return oppList;
    }
    public static List<Product2> createProducts(String segment, Integer count, Boolean usmo){
        List<Product2> prdList = new List<Product2>();
        for(Integer i=0; i<count; i++){
            prdList.add(new Product2(Name = 'Test Product' +i, ProductCode = 'code 3' +i, isActive = true, Source_System__c = 'Glovia',
                                 Source_System_Id__c='system id' +i,Usmo__c = usmo,Segment_Number__c = segment));
       
        }
        if(prdList != null && !prdList.isEmpty()){
            insert prdList;
        } 
        return prdList;
    }
    public static List<OpportunityLineItem> creatOppLine(String oppId, Integer count, String productId, String pdeId ){
        List<OpportunityLineItem> oppLines  = new List<OpportunityLineItem>();
        for(Integer i = 0; i<count; i++){
            oppLines.add(new OpportunityLineItem(OpportunityId = oppId, Product2Id = productId, UnitPrice = 1,
                                                quantity = 1, PriceBookEntryId = pdeId,Sales_Price_reflects_Opp_Currency__c  = true));
        }
        if(oppLines != null && !oppLines.isEmpty()){
            insert oppLines;
        }
        return oppLines;
    }
    public static void createOppRatePla(String lineId, decimal quantity, Decimal unitPrice){
        OpportunityRatePlan__c rate = new OpportunityRatePlan__c(OpportunityLineItem__c = lineId, LeadTime__c = '2 weeks',
                                                                SequenceNumber__c = quantity, SalesPrice__c = unitPrice);
        insert rate;
    }
    public static List<Order> createOrders(String oppId, String accId, Integer count){
        List<Order> orderList = new List<Order>();
        for(Integer i = 0; i<count; i++){
            	orderList.add(new order(OpportunityId = oppId, AccountId = accid, Name = 'test Order'+i,
                                       EffectiveDate = Date.today(), Status = 'Draft'));
        }
        if(orderList != null && !orderList.isEmpty()){
            insert orderList;
        }
        return orderList;
    } 
    public static List<Order_Line__c> createOrderLines(String orderId, String prdid,  String pbId, Integer n){
        List<Order_Line__c> oItems = new List<Order_Line__c>();
        for(Integer i = 0; i<n; i++){
            oItems.add(new Order_Line__c(Order__c = orderId, Part_Number__c = prdId, Unit_Selling_Price__c  = 10,
                                    Quantity__c = 10));
        }
        if(oItems != null && !oItems.isEmpty()){
            insert oItems;
        }
        return oItems;
    }
  /**  public static void createOrderRatePlan(String lineId, Integer sequesnceNo, Decimal unitPrice){
        OrderRatePlan__c plan = new OrderRatePlan__c(LeadTime__c = '2 weeks', OrderProduct__c = lineId,
                                                    SalesPrice__c = unitPrice, SequenceNumber__c = sequesnceNo);
        insert plan;
    } **/
    public static List<Quote> createQuote(String oppId, String pbId, integer n){
        List<Quote> qts = new List<Quote>();
        for(Integer i = 0; i<n; i++){
            qts.add(New Quote(OpportunityId = oppId, PriceBook2Id = pbId, Name = 'TestQuote'+i));
        }
        if(qts != null && !qts.isEmpty()){
            insert qts;
        }
        return qts;
    }
    public static List<Quote_Item__c> createQuoteLines(String qtId, String prdId, String pbeId, integer count){
        List<Quote_Item__c> lines = new List<Quote_Item__c>();
        for(Integer i = 0; i < count; i++){
           lines.add(new Quote_Item__c(Quote__c = qtId, Product__c  = prdId, Quantity__c = 10
                                      )); 
        }
        system.debug('lst23 ' + lines);
        if(lines != null && !lines.isEmpty()){
            insert lines;
        }
        return lines;
    }
    public static void createQuoteRatePlan(String lineId, integer seqNo, Decimal salesPrice){
        QuoteRatePlan__c plan = new QuoteRatePlan__c(QuoteLineItem__c = lineId, SalesPrice__c = salesPrice,
                                                    SequenceNumber__c = seqNo, LeadTime__c = '2 Weeks');
        insert plan;
    }
}