src/objects/Account/fields/Company_number__c.field-meta.xml
<CustomField>
    <fullName>Company_number__c</fullName>
    <description>these are the company numbers that the account is located in based on Glovia</description>
    <inlineHelpText>Company account number that Account was created under.  
01  is Dallas
02  is Germany</inlineHelpText>
    <label>Company number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10 - DSP</fullName>
            </value>
            <value>
                <fullName>15 - Industrial</fullName>
            </value>
            <value>
                <fullName>20 - Telecommunications</fullName>
            </value>
            <value>
                <fullName>30 - Medical</fullName>
            </value>
            <value>
                <fullName>25 - Automotive</fullName>
            </value>
            <value>
                <fullName>35 - Consumer</fullName>
            </value>
            <value>
                <fullName>40 - Personal Comfort</fullName>
            </value>
            <value>
                <fullName>60 - Power Generation</fullName>
            </value>
            <value>
                <fullName>80 - Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/ITAR__c.field-meta.xml
<CustomField>
    <fullName>ITAR__c</fullName>
    <label>ITAR</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NO</fullName>
                <default>true</default>
                <label>NO</label>
            </value>
            <value>
                <fullName>YES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Consumer</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10 - DSP</fullName>
            </value>
            <value>
                <fullName>15 - Industrial</fullName>
            </value>
            <value>
                <fullName>20 - Telecommunications</fullName>
            </value>
            <value>
                <fullName>30 - Medical</fullName>
            </value>
            <value>
                <fullName>25 - Automotive</fullName>
            </value>
            <value>
                <fullName>35 - Consumer</fullName>
            </value>
            <value>
                <fullName>40 - Personal Comfort</fullName>
            </value>
            <value>
                <fullName>60 - Power Generation</fullName>
            </value>
            <value>
                <fullName>80 - Contracts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Marlow_Product_BU__c.field-meta.xml
<CustomField>
    <fullName>Marlow_Product_BU__c</fullName>
    <label>Marlow Product BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Components</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Systems</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Qual_Required__c.field-meta.xml
<CustomField>
    <fullName>Qual_Required__c</fullName>
    <description>Select YES if this product was quoted as a product to be qualified by the customer.</description>
    <inlineHelpText>Orders where customers are performing qualification (new device or change to existing device). Contract review level 1 will be required.</inlineHelpText>
    <label>Customer Qual Req&apos;d?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/REACH__c.field-meta.xml
<CustomField>
    <fullName>REACH__c</fullName>
    <label>REACH</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
                <default>true</default>
                <label>NO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/Opportunity_Handler_test.cls
@isTest
public class Opportunity_Handler_test  {
    
    //basic opportunity test
    static testMethod void Opportunity_Handler_Test1 () {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
            
            User mike = new User();
            mike.Username= 'mike.white911@company.com';
            mike.Email = 'mike.white911@company.com';
            mike.Lastname = 'mike';
            mike.Firstname = 'white';
            mike.Alias = 'mwhite';
            mike.CommunityNickname = 'mwhite01';
            mike.ProfileId = [ select id, name from profile where name = 'System Administrator' ].Id;       
            mike.TimeZoneSidKey = 'GMT';
            mike.LocaleSidKey = 'en_US';
            mike.EmailEncodingKey = 'ISO-8859-1';
            mike.LanguageLocaleKey = 'en_US';
            mike.UserPermissionsMobileUser = false;
            insert mike;
            
            System.test.startTest();
            
            //Create new account
            Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId()	);
            insert globalParentAcc;
            Account a = new Account();
            a.name='Nulled Gardenia009'; 
            a.Type='Customer';
            a.CurrencyIsoCode='USD';
            a.Company_number__c='01';
            a.ShippingCity = 'New York'; 
            a.ShippingCountry ='US';
            a.ParentId = globalParentAcc.Id;
            a.Display_Shipping_Country__c ='United States';  
            a.Display_Billing_Country__c = 'United States';
            insert a; 
            
            //Create a new date & format it 
            DateTime dT = System.now();
            Date myDate = date.newinstance(dT.year(), dT.month(), dT.day());
            
            //Create a new opportunity
            Opportunity o = new Opportunity();
            o.name='Gardenia Sheep_opportunity';
            o.AccountId=a.Id;
            o.CloseDate=myDate;
            o.stagename='Prospect';
            o.CurrencyIsoCode='USD';
            o.Marlow_Product_BU__c='Components';
            o.Market__c='30 - Medical';
            o.ITAR__c='NO';
            o.REACH__c='NO';
            o.Qual_Required__c = 'Yes'; 
            o.Project_Name__c = 'Test';    
            insert o;
            update o;
            System.assert(o.AccountId == a.Id);     
        }
        
        System.test.stopTest();
    }
}