src/objects/Account/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Oracle_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Account_Id__c</fullName>
    <label>Oracle Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Oracle_Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Party_Id__c</fullName>
    <label>Oracle Party Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Party_Number__c.field-meta.xml
<CustomField>
    <fullName>Party_Number__c</fullName>
    <label>Party Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this RMA Request was created from a loaner, find the loaner here</inlineHelpText>
    <label>Loaner (If Applicable)</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Case / RMA Request</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Company_Name_End_Cust__c.field-meta.xml
<CustomField>
    <fullName>Company_Name_End_Cust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Email Betty Dea with end customer name and website if it cannot be found in drop down list.</inlineHelpText>
    <label>Company Name - End Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Company End Customer should be an Active Top Level Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Company_Name_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Company_Name_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Name - Ship To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 4 AND 3 AND 5</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Party</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>User can select Party Accounts or Customer Accounts</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners (Company Name)</relationshipLabel>
    <relationshipName>Loaners1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Est_Production_Date__c.field-meta.xml
<CustomField>
    <fullName>Est_Production_Date__c</fullName>
    <label>Est Production Date</label>
    <type>Date</type>
</CustomField>

src/objects/Loaner__c/fields/Project_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Project_Engineer__c</fullName>
    <label>Project Engineer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <formula>IF( RecordType.DeveloperName =&apos;Extension_Item&apos;,Loaner_Line__r.Product__r.Marketing_P_N__c,Product__r.Marketing_P_N__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketing P/N</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Ordered_Date__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Date__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner Line</label>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Order Lines (Loaner Line)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaner</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Prelim</fullName>
            </value>
            <value>
                <fullName>1stArticle</fullName>
            </value>
            <value>
                <fullName>Pre-Prod</fullName>
            </value>
            <value>
                <fullName>Experiment</fullName>
            </value>
            <value>
                <fullName>Items.Obsolete</fullName>
            </value>
            <value>
                <fullName>Mechanical engineering</fullName>
            </value>
            <value>
                <fullName>Items.Pilot</fullName>
            </value>
            <value>
                <fullName>Items.Production</fullName>
            </value>
            <value>
                <fullName>Items.Pre-Production</fullName>
            </value>
            <value>
                <fullName>Items.Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/LoanerOrderlinkbatchTest.cls
@isTest
private class LoanerOrderlinkbatchTest {
    @testSetup 
    static void setup() {
        UserRole insdieuserrole = [Select Id from UserRole Where DeveloperName ='Inside_Sales_FAE'];
        Profile usrProfile = [SELECT Id from Profile where Name ='System Administrator'];
        User insideUser = new User(LastName='Usrlast',ProfileId=usrProfile.Id,UserRoleId=insdieuserrole.id,alias ='testusr',
                                   Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                                   LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@finisar.com');
        insert insideUser;
        User sysAdm = new User(LastName='Usrlast1111',ProfileId=usrProfile.Id,alias ='trsysy',
                               Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser@finisar.com');
        system.runAs(sysAdm){
                 Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
        insert globalParentAcc;
            Account acc = new Account(name='Account ', ShippingCity = 'New York', ShippingCountry ='US',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                      billingcity='New York', billingcountry='USA',parentId=globalParentAcc.id,Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
            
            insert acc;
            Account acc1 = new Account(ParentId = globalParentAcc.Id,Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',name='Account1 ', ShippingCity = 'New York', ShippingCountry ='US',
                                       billingcity='New York test', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
            
            insert acc1;
            Account acc4 = new Account(name='Testing11/123',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ParentId=acc.Id, Party_Number__c ='203956',
                                       AccountNumber ='1234',shippingcity='Raipur',shippingcountry='US',
                                       Status__c='Active',Type='Customer',Credit_Limit__c=2.00,Oracle_Party_Id__c='8989',
                                       Oracle_Account_Id__c='7865',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId(),
                                       Legacy_Id__c ='eoqw321413242134122',Site_Use_Code__c='SHIP_TO',Org_ID__c= '2', Site_Use_Status__c='Active');
            
            insert acc4;
            Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
            String roleId =[select Id from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
            User u = createTestUser(roleId,p.Id,'Test','Case');
            
            Product2 prod = new Product2(IsActive = true,Status__c = 'Active',Name = 'Test Product',ExternalId__c = '12534', ProductCode = 'Test Product Code',Marketing_P_N__c = 'Test PN');
            insert prod;
            List<Order> orders = new List<Order>();
            List<Order_Line__c> orderLines = new List<Order_Line__c>();
            List<Loaner__c> loaners = new List<Loaner__c>();
            List<Loaner_Line__c> loanerLines = new List<Loaner_Line__c>();
            // insert 10 test data
            for (Integer i=0;i<10;i++) {
                //Orders
                orders.add(new order(AccountId=acc.Id,Status = 'Draft',Ordered_Date__c = Date.Today(),EffectiveDate = Date.Today(),Legacy_Id__c = 'Leg'+i,RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('RMA Order').getRecordTypeId(),
                                     billingcity='New York', billingcountry='USA',PoNumber = ''+i));
                //Loaners     
                loaners.add(new Loaner__c(RecordTypeId = Schema.SObjectType.Loaner__c.getRecordTypeInfosByName().get('Loaner Request').getRecordTypeId(), Company_Name_Ship_To__c = acc.Id,Company_Name_End_Cust__c = acc.Id,Project_Engineer__c='Test',Project_Name__c = 'Test',Est_Production_Date__c = Date.Today(),Address_ship_to__c = acc4.Id,
                                          Opportunity_Type__c='New Opportunity', Loaner_Duration__c='180',Loaner_Ship_From_Finisar__c = 'Factory Stock',RSM_PLM_Finisar__c = U.Id, RSM_PLM_Approval__c = U.Id,Inside_Sales_Sales_rep__c = UserInfo.getUserId(),Inside_Sales_Finisar__c = insideUser.Id));
            }
            insert orders;
            insert loaners;
            
            for(Order ord : orders){
                //OrderLines
                Integer i=0;
                orderLines.add(new Order_Line__c(Order__c = ord.Id,RecordTypeId = Schema.SObjectType.Order_Line__c.getRecordTypeInfosByName().get('Sales Order Line').getRecordTypeId(), 
                                                 Line_Id__c='l'+i));
                i++;
            }
            for(Loaner__c loan :  loaners){
                Integer i=0;
                //LonaerLines     
                loanerLines.add(new Loaner_Line__c(Loaner__c = loan.Id,RecordTypeId = Schema.SObjectType.Loaner_Line__c.getRecordTypeInfosByName().get('Loaner Item').getRecordTypeId(), Loaner_Price_100_999_column_price__c=10,
                                                   Product__c=prod.Id, Loaner_Qty__c=5,Est_Annual_Qty__c = 5,SOM__c = 5,SO_Number_Migration__c = ''+i,SO_Line_Migration__c='l'+i));
                i++;
                
            }
            insert orderLines;
            insert loanerLines;
        }  
    }
    static testmethod void test() {        
        Test.startTest();
        LoanerOrderlinkbatch uca = new LoanerOrderlinkbatch();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        //System.assertEquals(10, [select count() from contact where MailingCity = 'New York']);
    }
    public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              UserRoleId = roleId);
        return tuser;
    }
    
}