src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Global_Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Parent</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match a Global Parent Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Global_Ultimate_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match a Global Parent Account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oppty/DRs (Global Ultimate Account)</relationshipLabel>
    <relationshipName>Oppty_DRs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/recordTypes/Aftermarket.recordType-meta.xml
<RecordType>
    <fullName>Aftermarket</fullName>
    <active>true</active>
    <businessProcess>Aftermarket</businessProcess>
    <label>Aftermarket</label>
</RecordType>

src/objects/Order/fields/Batch_Flag__c.field-meta.xml
<CustomField>
    <fullName>Batch_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Flag</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/Global_Ultimate_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (AccountGlobal Ultimate Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Integration_Flag__c.field-meta.xml
<CustomField>
    <fullName>Integration_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integration Flag</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Batch_Flag__c.field-meta.xml
<CustomField>
    <fullName>Batch_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Flag</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order_Line__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Lines (Customer Name)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Integration_Flag__c.field-meta.xml
<CustomField>
    <fullName>Integration_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integration Flag</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Global_Ultimate_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Global Ultimate Account)</relationshipLabel>
    <relationshipName>Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User/fields/Legacy_Company__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Company__c</fullName>
    <description>Used to support existing processes during the org merge processes</description>
    <label>Legacy Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finisar</fullName>
            </value>
            <value>
                <fullName>Corp II-VI</fullName>
            </value>
            <value>
                <fullName>Marlow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/OrderAndOrderLineBatch_Test.cls
@isTest
private class OrderAndOrderLineBatch_Test {
	 @testSetup static void setup() {
        Profile salesUserProfile = [SELECT Id FROM Profile WHERE Name = 'Sales Profile Clone' LIMIT 1];
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        List<User>  testUserList=new List<User>();
        System.RunAs(usr)
        {
            UserRole usrRoleRec=new UserRole(Name= 'FAE'); 
            insert usrRoleRec; 
            
            for(Integer i=0;i<2;i++){
                String orgId = userInfo.getOrganizationId();
                String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
                Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
                String uniqueName = orgId + dateString + randomInt;
                testUserList.add(new User(firstname = 'Test',
                                          lastName = 'User '+(i+1),
                                          email = uniqueName + '@test' + orgId + '.org',
                                          Username = uniqueName + '@test' + orgId + '.org',
                                          EmailEncodingKey = 'ISO-8859-1',
                                          Alias = uniqueName.substring(18, 23),
                                          TimeZoneSidKey = 'America/Los_Angeles',
                                          LocaleSidKey = 'en_US',
                                          LanguageLocaleKey = 'en_US',
                                          ProfileId = salesUserProfile.Id,
                                          isActive = True,
                                          UserRoleId = usrRoleRec.Id));  
            }
            testUserList.add(new User(LastName='Usrlast1111',ProfileId=[SELECT Id from Profile where Name ='System Administrator'].Id,alias ='trsysy',Legacy_Company__c ='Finisar',
                                      Email='standarduser1@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                                      LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@finisar.com'));
            insert testUserList;
            //PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Change_Account_Ownership'];
            //insert new PermissionSetAssignment(AssigneeId = testUserList[2].id, PermissionSetId = ps.Id);
        }
        List<Account> globalParentAccList=new List<Account>();  
        globalParentAccList.add(new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId(),OwnerId=testUserList[0].Id));
        globalParentAccList.add(new Account(Name='Global Parent Test Acc1',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId(),OwnerId=testUserList[1].Id));
        insert globalParentAccList;  
        List<Account> accList=new List<Account>(); 
        for(Integer i=1;i<=6;i++){
            accList.add(new Account(Name='Test Acc '+i,Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId(),ShippingCity = 'New York', ShippingCountry ='US',
                                    ParentId=globalParentAccList[0].Id,Global_Ultimate_Parent__c=globalParentAccList[0].Id,Status__c='Active',Type='Customer'));
        }  
        insert accList;
        Integer index=1;
        List<Opportunity> oppList=new List<Opportunity>();
        for(Integer i=0;i<accList.size();i++){
            oppList.add(new Opportunity(CloseDate=System.today(),AccountId=accList[i].Id,ForecastCategoryName='Pipeline',
                                        Name='Test Opp '+index,StageName='Qualifying',Project_Name__c='Test',RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftermarket').getRecordTypeId()));
            index++;
        } 
        insert oppList;
        List<Order> orderList=new List<Order>();
        index=1;
        for(Opportunity eachOpp:oppList){
            orderList.add(new Order(Legacy_Id__c='12345'+index,OpportunityId=eachOpp.Id,AccountId=eachOpp.AccountId,Name='Test Quote '+index,
                                    EffectiveDate=System.today(),Status='Draft',Integration_Flag__c=true,Batch_Flag__c=false));
            index++;
        }
        insert orderList;
        List<Order_Line__c> orderLineList=new List<Order_Line__c>();
        for(Order eachOrder:orderList){
            orderLineList.add(new Order_Line__c(Order__c=eachOrder.Id,Customer_Name__c=eachOrder.AccountId,Integration_Flag__c=true,Batch_Flag__c=false));
        }
        insert orderLineList;
    }
    
    @isTest static void testOrderAndOrderLineBatch() {
        User testUser=[Select Id from User where lastName='User 1'];
        Test.startTest();
        OrderAndOrderLine_Batch batchObj = new OrderAndOrderLine_Batch();
        DataBase.executeBatch(batchObj);
        Test.stopTest();
        List<Order> orderList=[Select Id from Order where Integration_Flag__c=true and Global_Ultimate_Account__c!=null];
        List<Order_Line__c> orderLineList=[Select Id from Order_Line__c where Integration_Flag__c=true];
        List<Order_Line__Share> orderLineShrList=[Select Id from Order_Line__Share where UserOrGroupId=:testUser.Id and AccessLevel='Read'
                                         and RowCause='Manual' and ParentId in: orderLineList];
        
        System.assertEquals(6,orderList.size());
        System.assertEquals(orderLineList.size(),orderLineShrList.size());
    }
    
     @isTest static void testOrderAndOrderLineBatchScheduler() {
        Test.startTest();
        OrderAndOrderLineBatch_Scheduler schObj = new OrderAndOrderLineBatch_Scheduler();
        Date today=System.today();
        String CRON_EXP ='0 0 0 '+today.day()+' '+today.month()+' ? *'; 
        String jobId = System.schedule('Schedule to update Account Name',CRON_EXP,schObj);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }
    
    @isTest static void testDoSubListHelperMethod() {
        Test.startTest();
        List<Order> orderList=[Select Id from Order where Integration_Flag__c=true];
        List<List<Sobject>> sObjectList=new List<List<Sobject>>();
        OrderAndOrderLineBatch_Helper.doSubList(orderList,2,sObjectList);
        System.assertEquals(3,sObjectList.size());
        Test.stopTest();
    }
    
      @isTest static void testSendEmailHelperMethod() {
        Test.startTest();
        string csvHeader = 'Record Id,Object Name,Operation, Error \n';
    	string mainContent = csvHeader;
		string errStr = '12345,Order,Update,Test Error occured\n';
        mainContent += errStr;
        OrderAndOrderLineBatch_Helper.sendEmail(mainContent);
        System.assertEquals(1, Limits.getEmailInvocations());
        Test.stopTest();
    }
}