src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Global_Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Parent</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match a Global Parent Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zero Dollar Inbound and Outbound ( No Dollar Amount Involved)</fullName>
            </value>
            <value>
                <fullName>Credit Inbound and rebill Outbound ( Both Inbound &amp; Outbound POs Must Show Same Amount and Quantity</fullName>
            </value>
            <value>
                <fullName>Return For Credit Only, No Outbound Rebill Involved</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return From Customer Name</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (From Customer Name)</relationshipLabel>
    <relationshipName>Return_From_Customer_RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dead on Arrival</fullName>
            </value>
            <value>
                <fullName>Fail at customer</fullName>
            </value>
            <value>
                <fullName>Field failure / Fail at end-customer</fullName>
            </value>
            <value>
                <fullName>Sample / Demo /Loaner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Finisar_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Finisar_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The sales manager associated with this RMA Request</inlineHelpText>
    <label>Finisar Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Found_By__c.field-meta.xml
<CustomField>
    <fullName>Found_By__c</fullName>
    <label>Found By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Found_By</valueSetName>
    </valueSet>
</CustomField>

src/objects/Case/fields/Part_Numbers_s__c.field-meta.xml
<CustomField>
    <fullName>Part_Numbers_s__c</fullName>
    <label>Part Numbers(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Requested_Service__c.field-meta.xml
<CustomField>
    <fullName>Requested_Service__c</fullName>
    <inlineHelpText>What is the requested service for this RMA?</inlineHelpText>
    <label>Requested Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failure Verification Only</fullName>
            </value>
            <value>
                <fullName>Failure Analysis</fullName>
            </value>
            <value>
                <fullName>Rework / Upgrade (No FA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Loaner Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Address</description>
    <label>Ship-To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship-To Address)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Ship_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Customer Name</description>
    <label>Ship To Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship To Customer)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Case/recordTypes/HY.recordType-meta.xml
<RecordType>
    <fullName>HY</fullName>
    <active>true</active>
    <businessProcess>HY</businessProcess>
    <label>HY</label>
</RecordType>

src/objects/Contact/fields/Display_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Mailing_Country__c</fullName>
    <label>Display Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/recordTypes/Aftermarket.recordType-meta.xml
<RecordType>
    <fullName>Aftermarket</fullName>
    <active>true</active>
    <businessProcess>Aftermarket</businessProcess>
    <label>Aftermarket</label>
</RecordType>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Lines (Customer Name)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

src/objects/User/fields/Legacy_Company__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Company__c</fullName>
    <description>Used to support existing processes during the org merge processes</description>
    <label>Legacy Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finisar</fullName>
            </value>
            <value>
                <fullName>Corp II-VI</fullName>
            </value>
            <value>
                <fullName>Marlow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/Found_By.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar FAE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar PE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>FoundBy on Case object</description>
    <masterLabel>Found By</masterLabel>
</GlobalValueSet>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/GlobalParentOwnerBatch_Test.cls
@isTest
private class GlobalParentOwnerBatch_Test {
    @testSetup static void setup() {
        Profile salesUserProfile = [SELECT Id FROM Profile WHERE Name = 'One II-VI Sales Rep' LIMIT 1];
        //UserRole faeRole = [SELECT Id FROM UserRole WHERE Name LIKE  '%FAE%' LIMIT 1];
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        List<User>  testUserList=new List<User>();
        System.RunAs(usr)
        {
            UserRole usrRoleRec=new UserRole(Name= 'FAE'); 
            insert usrRoleRec; 
            
            for(Integer i=0;i<2;i++){
                String orgId = userInfo.getOrganizationId();
                String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
                Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
                String uniqueName = orgId + dateString + randomInt;
                testUserList.add(new User(firstname = 'Test',
                                          lastName = 'User '+(i+1),
                                          email = uniqueName + '@test' + orgId + '.org',
                                          Username = uniqueName + '@test' + orgId + '.org',
                                          EmailEncodingKey = 'ISO-8859-1',
                                          Alias = uniqueName.substring(18, 23),
                                          TimeZoneSidKey = 'America/Los_Angeles',
                                          LocaleSidKey = 'en_US',
                                          LanguageLocaleKey = 'en_US',
                                          ProfileId = salesUserProfile.Id,
                                          isActive = True,
                                          UserRoleId = usrRoleRec.Id));  
            }
            testUserList.add(new User(LastName='Usrlast1111',ProfileId=[SELECT Id from Profile where Name ='System Administrator'].Id,alias ='trsysy',Legacy_Company__c ='Finisar',
                                      Email='standarduser1@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                                      LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@finisar.com'));
            insert testUserList;
            //PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Change_Account_Ownership'];
            //insert new PermissionSetAssignment(AssigneeId = testUserList[2].id, PermissionSetId = ps.Id);
        }
        List<Account> globalParentAccList=new List<Account>();  
        globalParentAccList.add(new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId(),OwnerId=testUserList[0].Id));
        globalParentAccList.add(new Account(Name='Global Parent Test Acc1',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId(),OwnerId=testUserList[1].Id));
        insert globalParentAccList;  
        List<Account> accList=new List<Account>(); 
        for(Integer i=1;i<=6;i++){
            accList.add(new Account(Name='Test Acc '+i,Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId(),ShippingCity = 'New York', ShippingCountry ='US',
                                    ParentId=globalParentAccList[0].Id,Global_Ultimate_Parent__c=globalParentAccList[0].Id,Status__c='Active',Type='Customer'));
        }  
        accList.add(new Account(Name='Site Test Acc',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId(),Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                ParentId=globalParentAccList[0].Id,Global_Ultimate_Parent__c=globalParentAccList[0].Id,Site_Use_Code__c='SHIP_TO',Status__c='Active',
                                Site_Use_Status__c='Active',shippingcity='New York',shippingcountry='US',Type='Site',
                                Org_ID__c= '2'));
        insert accList;
        List<Contact> contactList=new List<Contact>();
        Integer index=1;
        for(Integer i=0;i<accList.size()-1;i++){
            contactList.add(new Contact(FirstName='Test ',LastName='Contact '+index,AccountId=accList[i].Id,MailingCountry='United States',Display_Mailing_Country__c='United States'));
            index++;
        }  
        insert contactList;
        List<Opportunity> oppList=new List<Opportunity>();
        index=1;
        for(Integer i=0;i<accList.size()-1;i++){
            oppList.add(new Opportunity(CloseDate=System.today(),AccountId=accList[i].Id,ForecastCategoryName='Pipeline',
                                        Name='Test Opp '+index,StageName='Qualifying',Project_Name__c='Test',RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftermarket').getRecordTypeId()));
            index++;
        } 
        insert oppList;
        List<Quote> quoteList=new List<Quote>();
        index=1;
        for(Opportunity eachOpp:oppList){
            quoteList.add(new Quote(OpportunityId=eachOpp.Id,Account__c=eachOpp.AccountId,Name='Test Quote '+index));
            index++;
        }
        insert quoteList;
        List<Order> orderList=new List<Order>();
        index=1;
        for(Opportunity eachOpp:oppList){
            orderList.add(new Order(Legacy_Id__c='12345'+index,OpportunityId=eachOpp.Id,AccountId=eachOpp.AccountId,Name='Test Quote '+index,
                                    EffectiveDate=System.today(),Status='Draft'));
            index++;
        }
        insert orderList;
        List<Order_Line__c> orderLineList=new List<Order_Line__c>();
        //index=1;
        for(Order eachOrder:orderList){
            orderLineList.add(new Order_Line__c(Order__c=eachOrder.Id,Customer_Name__c=eachOrder.AccountId));
            //index++;
        }
        insert orderLineList;
        List<Case> caseList=new List<Case>();
        
        for(Integer i=0;i<accList.size()-1;i++){
            /*caseList.add(new Case(RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId(),Failure_Location__c='Dead on Arrival',AccountId=accList[i].Id,
Finisar_Sales_Manager__c=UserInfo.getUserId(),Requested_Service__c='Loaner Return',Billing_Type__c='Others',
Ship_To_Address__c=accList[6].Id,Ship_To_Customer__c=accList[i].Id));*/
            caseList.add(new Case(RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('HY').getRecordTypeId(),Found_By__c='Customer',Part_Numbers_s__c='12345',AccountId=accList[i].Id,
                                  FAE__c=testUserList[0].Id,Subject='Test Case '+i));
        }  
        insert caseList;
    }
    
    @isTest static void testGlobalParentOwnerBatch() {
        User sysAdmin=[Select Id from User where userName='testuser1@finisar.com'];
        User testUser=[Select Id from User where lastName='User 2'];
        Account globalParentAcc=[Select Id from Account where Name='Global Parent Test Acc'];
        globalParentAcc.OwnerId=testUser.Id;
        System.runAs(sysAdmin){
            update globalParentAcc;
        }
        Test.startTest();
        GlobalParentOwner_Batch batchObj = new GlobalParentOwner_Batch();
        DataBase.executeBatch(batchObj);
        Test.stopTest();
        List<Contact> cntctList=[Select Id from Contact];
        List<ContactShare> cntctShrList=[Select Id from ContactShare where UserOrGroupId=:testUser.Id and ContactAccessLevel='Read'
                                         and RowCause='Manual' and ContactId in: cntctList];
        
        System.assertEquals(cntctList.size(),cntctShrList.size());
    }
    
    @isTest static void testGlobalParentAccountChange() {
        Account globalParentAcc=[Select Id,OwnerId from Account where Name='Global Parent Test Acc'];
        Account globalParentAcc1=[Select Id,OwnerId from Account where Name='Global Parent Test Acc1'];
        List<Account> accList=[Select Id from Account where RecordType.Name='Customer Account'];
        for(Account eachAcc:accList){
            eachAcc.Changed_Global_Parent_Old_Owner__c=globalParentAcc.OwnerId;
            eachAcc.Global_Ultimate_Parent__c=globalParentAcc1.Id;
        }
        update accList;
        Test.startTest();
        GlobalParentOwnerBatch_Helper.deleteAndInsertShareRecords(accList, false);
        Test.stopTest();
        List<Contact> cntctList=[Select Id from Contact];
        List<ContactShare> cntctShrList=[Select Id from ContactShare where UserOrGroupId=:globalParentAcc1.OwnerId and ContactAccessLevel='Read'
                                         and RowCause='Manual' and ContactId in: cntctList];
        
        System.assertEquals(cntctList.size(),cntctShrList.size());
    }
    
    @isTest static void testGlobalParentOwnerBatchScheduler() {
        User sysAdmin=[Select Id from User where userName='testuser1@finisar.com'];
        User testUser=[Select Id from User where lastName='User 2'];
        Account globalParentAcc=[Select Id from Account where Name='Global Parent Test Acc'];
        globalParentAcc.OwnerId=testUser.Id;
        System.runAs(sysAdmin){
            update globalParentAcc;
        }
        Test.startTest();
        GlobalParentOwnerBatch_Scheduler schObj = new GlobalParentOwnerBatch_Scheduler();
        Date today=System.today();
        String CRON_EXP ='0 0 0 '+today.day()+' '+today.month()+' ? *'; 
        String jobId = System.schedule('Schedule to update Account Name',CRON_EXP,schObj);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }
        
}