src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Contact/fields/Display_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Mailing_Country__c</fullName>
    <label>Display Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Display_ISO_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_ISO_Country__c</fullName>
    <label>Display ISO Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/createIndividulforOldRecordsBatchTest.cls
@isTest(seeAllData = false)
private class createIndividulforOldRecordsBatchTest {
    @testSetup static void methodName() {
        Lead newLd  = new Lead();
        newLd.LastName = 'Lastname';
        newLd.FirstName = 'Leadf';
        newLd.Email = 'Lastname.Leadf@lead.com';
        newLd.Display_ISO_Country__c = 'United States';
        newLd.Company = 'ii-vi';
        newLd.Country = 'US';
        insert newLd;
    }
    static testmethod void contactForGDPRtest() { 
        Account globalParentAcc=new Account(Name='Global Parent Test Acc',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
        insert globalParentAcc;
        Account acc = new Account(name='Account ',ParentId=globalParentAcc.Id, Display_Billing_Country__c ='United States',
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acc;
        Account acc1 = new Account(ParentId = globalParentAcc.Id,name='Account1 ', Display_Billing_Country__c ='United States',
                                   billingcity='New York test', billingcountry='USA',Status__c='Active',Type='Party',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acc1;
        List<Contact> conlist = new List<Contact>(); 
        Contact c = new Contact(FirstName = 'Test',LastName = 'Contact',Display_Mailing_Country__c='United States',AccountId = acc.Id,MailingCountry='United States',Email='rest@vv.com');
        conlist.add(c); 
        insert conlist;
        c.IndividualId = null;
        update c;
        Test.startTest();
        createIndividulforOldRecordsBatch bat = new createIndividulforOldRecordsBatch(null, false);
        database.executeBatch(bat);
        Test.stopTest();
    }
    @isTest
    static void testLeadTrigger(){
        Lead newLd  = [select id, IndividualId from Lead limit 1];
        newLd.IndividualId = null;
        update newLd;
        system.debug('newLd'+newLd.IndividualId);
        delete [Select id from Individual];
        
        String leadQuery = 'SELECT Id, Name,FirstName, LastName, Email,IndividualId, Display_ISO_Country__c FROM Lead WHERE IndividualId = null ';
        test.startTest();
        List<lead> ldl = [SELECT Id, Name,FirstName, LastName, Email,IndividualId, Display_ISO_Country__c FROM Lead WHERE IndividualId = null];
        system.debug('ld'+ldl);
        createIndividulforOldRecordsBatch bat = new createIndividulforOldRecordsBatch(null, false);
        database.executeBatch(bat);
        test.stopTest();
        Lead ld =[SELECT Id, IndividualId FROM Lead LIMIT 1];
        system.assert(ld.IndividualId != null, 'Individual recors mapped with Lead');
    }
}