src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zero Dollar Inbound and Outbound ( No Dollar Amount Involved)</fullName>
            </value>
            <value>
                <fullName>Credit Inbound and rebill Outbound ( Both Inbound &amp; Outbound POs Must Show Same Amount and Quantity</fullName>
            </value>
            <value>
                <fullName>Return For Credit Only, No Outbound Rebill Involved</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CFO_User__c.field-meta.xml
<CustomField>
    <fullName>CFO_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CFO User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases4</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return From Customer Name</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (From Customer Name)</relationshipLabel>
    <relationshipName>Return_From_Customer_RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CustomerRef_RMANo__c.field-meta.xml
<CustomField>
    <fullName>CustomerRef_RMANo__c</fullName>
    <inlineHelpText>RMA Number</inlineHelpText>
    <label>CustomerRef/RMANo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Data_n_W_BU_GM__c.field-meta.xml
<CustomField>
    <fullName>Data_n_W_BU_GM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data n/W BU GM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/EndCustomerInbound__c.field-meta.xml
<CustomField>
    <fullName>EndCustomerInbound__c</fullName>
    <description>Inbound End Customer</description>
    <inlineHelpText>Inbound End Customer</inlineHelpText>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Finisar_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Finisar_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The sales manager associated with this RMA Request</inlineHelpText>
    <label>Finisar Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/OpticalIC_BU_GM__c.field-meta.xml
<CustomField>
    <fullName>OpticalIC_BU_GM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpticalIC BU GM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Outbound_RMA_PO__c.field-meta.xml
<CustomField>
    <fullName>Outbound_RMA_PO__c</fullName>
    <inlineHelpText>PO/Reference Number Used for shiping the RMA parts to Customer(i.e. Outbound RMA PO#)</inlineHelpText>
    <label>Outbound RMA PO#</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Requested_Service__c.field-meta.xml
<CustomField>
    <fullName>Requested_Service__c</fullName>
    <inlineHelpText>What is the requested service for this RMA?</inlineHelpText>
    <label>Requested Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failure Verification Only</fullName>
            </value>
            <value>
                <fullName>Failure Analysis</fullName>
            </value>
            <value>
                <fullName>Rework / Upgrade (No FA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Loaner Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Address</description>
    <label>Ship-To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship-To Address)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Ship_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Customer Name</description>
    <label>Ship To Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship To Customer)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/SVP_of_Sales__c.field-meta.xml
<CustomField>
    <fullName>SVP_of_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP of Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RMACases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Wavelength_BU_GM__c.field-meta.xml
<CustomField>
    <fullName>Wavelength_BU_GM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wavelength BU GM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/X3DSensing_BU_GM__c.field-meta.xml
<CustomField>
    <fullName>X3DSensing_BU_GM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3DSensing BU GM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RMACases2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <description>Lookup field to User to Point SVP for user role VP</description>
    <label>SVP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <description>Lookup field to User to point to VP for User role RSM</description>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>VP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/CaseApprovalEmailServicehandlerTest.cls
@isTest
public class CaseApprovalEmailServicehandlerTest {
    @testsetup static void testData(){
        Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=getRecordTypeIdByName('Global Parent'));
        insert globalParentAcc;
        Account acc = new Account(name='Account1 ', Shippingcity='Hyderabad',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', Shippingcountry='US',ParentId=globalParentAcc.Id,
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acc;
       Account siteacc = new Account(name='AccountSite ', Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                      shippingcity='New York',Site_Use_Code__c='SHIP_TO',Site_Use_Status__c='Active',parentId=acc.id, shippingcountry='US',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId());
        insert siteacc;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='CFO' LIMIT 1].Id;
        String roleId2 =[select Id from UserRole where Name='VP of AMERICAS - WESTERN' LIMIT 1].Id;
        String FAEEngineer =[select Id from UserRole where Name='FA Engineer SNY' LIMIT 1].Id; 
        String roleId3 =[select Id from UserRole where Name='EVP' LIMIT 1].Id; 
        User u = createTestUser(roleId,p.Id,'Test','adas');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert u;
        }
       User u1 = createTestUser(FAEEngineer,p.Id,'Test1','Datan/W');
        User u2 = createTestUser(FAEEngineer,p.Id,'Test2','opticalIC');
         User u3 = createTestUser(roleId2,p.Id,'Test3','Wavelength');
         User u4 = createTestUser(FAEEngineer,p.Id,'Test4','3DSensing');
         User u5 = createTestUser(roleId3,p.Id,'Test5','SVP');
        
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert u1;
            insert u2;insert u3;insert u4;insert u5;
        }
        u.VP__c = u3.Id;
        u.email = 'kurt.adzema@finisar.com';
        u.SVP__c = u5.Id;
        update u;
        case case1 = new case(Finisar_Sales_Manager__c = u1.Id,Customer_Name__c=acc.id,CFO_User__c =u.id,Wavelength_BU_GM__c=u2.Id,SVP_of_Sales__c=u5.Id,X3DSensing_BU_GM__c=u2.Id,Data_n_W_BU_GM__c=u2.Id,OpticalIC_BU_GM__c=u2.Id ,Billing_Type__c ='Return For Credit Only, No Outbound Rebill Involved',Status ='Open', 
                              Ship_To_Customer__c=acc.id, Ship_To_Address__c =siteacc.id,Outbound_RMA_PO__c='456543',Requested_Service__c='Failure Analysis',CustomerRef_RMANo__c='345654',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId(),EndCustomerInbound__c = 'ec');
        insert case1;
        system.debug('Testing5677 -- ' + case1.id); 
        IF(Approval.isLocked(case1.id)) {
            Approval.unlock(case1.Id);
        }
  Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(case1.Id);
        req1.setSubmitterId(u.id);
        Approval.ProcessResult result = Approval.process(req1); 
    }
     static testmethod void caseApprovalReminder2() { 
        Case cs1 =[select id from case limit 1];
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='CFO' LIMIT 1].Id;
        user u = [select id,UserRoleId,profileid,vp__c,svp__c,email from user where lastname='adas' and isActive=true LIMIT 1];
         string arprv1  = 'Action:Approve';
        sendInboundEmail(u,cs1,arprv1);  
         System.debug('test executed');
    }
    static testmethod void caseApprovalReminder() { 
        Test.startTest();
        Case cs1 =[select id from case limit 1];
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='CFO' LIMIT 1].Id;
        user u = [select id,UserRoleId,profileid,vp__c,svp__c,email from user where lastname='adas' and isActive=true LIMIT 1];
        string arprv  = 'Action: Reject';
        sendInboundEmail(u,cs1,arprv);      
        Test.stopTest();
    }
  
  
    static void sendInboundEmail(user u,case quoteObj , string approveReject) {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        // setup the data for the email
        email.subject = 'case:'+quoteObj.id+' has been forwarded for your approval by';
        env.fromAddress = u.Email;
        String body =    approveReject; 
        body = body+'\r\n';
        body = body+'Comments in between the apostrophes to append to this notification'; 
        body = body+'\r\n';
        body = body+'Case Id : ['+quoteObj.id+']' ;
        System.debug('body'+body);
        email.plainTextBody =body;
        CaseApprovalEmailServicehandler approvalEmailObj =    New CaseApprovalEmailServicehandler();
        approvalEmailObj.handleInboundEmail(email, env);
    }
    
    public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = lName + '@huronconsultinggroup.com',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              isActive = True,
                              UserRoleId = roleId);
        return tuser;
    }
    
     static testmethod void cancelRMARequest(){
         Case cs1 =[select id from case where CustomerRef_RMANo__c ='345654' limit 1];
         RmaRequestCancellation.cancelRmaRequest(New List<Id>{cs1.Id});
    }
    
    static Id getRecordTypeIdByName(String recordTypeName){
       return [Select Id from RecordType where Name=:recordTypeName].Id;
    }
}