src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Global_Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Ultimate Parent</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match a Global Parent Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Global Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Global_Parent.recordType-meta.xml
<RecordType>
    <fullName>Global_Parent</fullName>
    <active>true</active>
    <label>Global Parent</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return From Customer Name</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (From Customer Name)</relationshipLabel>
    <relationshipName>Return_From_Customer_RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CustomerRef_RMANo__c.field-meta.xml
<CustomField>
    <fullName>CustomerRef_RMANo__c</fullName>
    <inlineHelpText>RMA Number</inlineHelpText>
    <label>CustomerRef/RMANo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Finisar_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Finisar_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The sales manager associated with this RMA Request</inlineHelpText>
    <label>Finisar Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Found_By__c.field-meta.xml
<CustomField>
    <fullName>Found_By__c</fullName>
    <label>Found By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Found_By</valueSetName>
    </valueSet>
</CustomField>

src/objects/Case/fields/Outbound_RMA_PO__c.field-meta.xml
<CustomField>
    <fullName>Outbound_RMA_PO__c</fullName>
    <inlineHelpText>PO/Reference Number Used for shiping the RMA parts to Customer(i.e. Outbound RMA PO#)</inlineHelpText>
    <label>Outbound RMA PO#</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/PLM__c.field-meta.xml
<CustomField>
    <fullName>PLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PLM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_RMA_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Requested_Service__c.field-meta.xml
<CustomField>
    <fullName>Requested_Service__c</fullName>
    <inlineHelpText>What is the requested service for this RMA?</inlineHelpText>
    <label>Requested Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failure Verification Only</fullName>
            </value>
            <value>
                <fullName>Failure Analysis</fullName>
            </value>
            <value>
                <fullName>Rework / Upgrade (No FA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Loaner Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Address</description>
    <label>Ship-To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship-To Address)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Ship_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Customer Name</description>
    <label>Ship To Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship To Customer)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Forecast__c/fields/Actual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Actual_Revenue__c</fullName>
    <label>Actual Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Forecast__c/fields/PLM__c.field-meta.xml
<CustomField>
    <fullName>PLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PLM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Forecast__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Forecasts1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/globalValueSets/Found_By.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar FAE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar PE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>FoundBy on Case object</description>
    <masterLabel>Found By</masterLabel>
</GlobalValueSet>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/FileUploadControllerTest.cls
@isTest
public class FileUploadControllerTest {
 @isTest
    static void UploadCSV(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id,name from UserRole where Name='RMA Admin' LIMIT 1].Id;
         User u = createTestUser(roleId,p.Id,'Test','Case');
          System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
         Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Global_Parent').getRecordTypeId());
        insert globalParentAcc;
        
         Account acc = new Account(name='Account ', Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                  billingcity='New York',ShippingCity = 'New York', ShippingCountry ='US',ParentId = globalParentAcc.Id, Global_Ultimate_Parent__c=globalParentAcc.Id,billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        Account acc1 = new Account(ParentId = acc.Id,name='Account1 ',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', Legacy_Id__c='1234',ShippingCity = 'Test',ShippingCountry ='US',ShippingState ='NE',ShippingPostalCode ='63572',ShippingStreet = 'Test4',
                billingcity='New York test',Site_Use_Code__c = 'SHIP_TO',Site_Use_Status__c= 'Active', billingcountry='US',Status__c='Active',Type='Reseller',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId());
        
        insert acc1;
         case cs = new Case(Found_By__c='Customer', 
                                  Ship_To_Address__c = acc1.Id,Customer_Name__c=acc.id,Ship_To_Customer__c=acc.id,Outbound_RMA_PO__c='234534',CustomerRef_RMANo__c='67545',Requested_Service__c='Failure Verification Only',  Status='Open',Finisar_Sales_Manager__c=u.id,RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId());
        
        insert cs;
        
        case case2 = new Case(Found_By__c='Customer', 
                                  Ship_To_Address__c = acc1.Id,Customer_Name__c=acc.id,Ship_To_Customer__c=acc.id,Outbound_RMA_PO__c='234534',CustomerRef_RMANo__c='67545',Requested_Service__c='Failure Verification Only',  Status='Pending RMA Admin Review',Finisar_Sales_Manager__c=u.id,RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId());
        
        insert case2;
        string content1 = 'SerialNumber,Description,ReturnReason,POPriceType,SpecialInstructions +\n+ 2345,test,Product Failure,Other,test\n+ 23456,test,,Other,test'; 
        boolean header = True;
        
         string content2 = 'SerialNumber,Description,ReturnReason,POPriceType,SpecialInstructions +\n+ 2345,test,Product Failure,Other,test\n+ 23456,test,Rework,Other,test'; 
        boolean header2 = True;
         string content3 = 'SerialNumber,Description,ReturnReason,POPriceType,SpecialInstructions +\n+ 2345,test,Product Failure,Other,test\n+ 23456,test,Rework,Other,test'; 
        boolean header3 = True;
         string content4 = 'SerialNumber,Description,ReturnReason,POPriceType,SpecialInstructions +\n+ ,,,Product Failure!,Other!,test\n+ ,test,Rework,Other,test'; 
        boolean header4 = True;
         string content5 = 'SerialNumber,Description,ReturnReason,POPriceType,SpecialInstructions +\n+ 2345,test,Product Failure,Other,test\n+ 23456,test,Rework'; 
        boolean header5 = True;
        
        Test.startTest();
        FileUploadController.parseCSV(content1,header,cs.id);
        
        FileUploadController.parseCSV(content2,header2,cs.id);
          FileUploadController.parseCSV(content3,header3,case2.id);
        FileUploadController.parseCSV(content4,header4,case2.id);
        FileUploadController.parseCSV(content5,header5,cs.id);
        Forecast__c fct = new Forecast__c(PLM__c= u.Id);
        insert fct;
        fct.Actual_Revenue__c = 2343;
        fct.RSM__c = U.Id;
        update fct;
        Test.stopTest();
        
    }
    @isTest
    static void ForesatShareTriggerTest(){
    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id,name from UserRole where Name='RMA Admin' LIMIT 1].Id;
         User u = createTestUser(roleId,p.Id,'Test','Case');
          System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
        Forecast__c fct = new Forecast__c(RSM__c= u.Id);
        insert fct;
        Test.StartTest();
        fct.Actual_Revenue__c = 2343;
        fct.PLM__c = U.Id;
        update fct;
        Test.stopTest();
        
    }
     public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              UserRoleId = roleId);
        return tuser;
    }
}