src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Found_By__c.field-meta.xml
<CustomField>
    <fullName>Found_By__c</fullName>
    <label>Found By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Found_By</valueSetName>
    </valueSet>
</CustomField>

src/objects/Case/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this RMA Request was created from a loaner, find the loaner here</inlineHelpText>
    <label>Loaner (If Applicable)</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Case / RMA Request</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Part_Numbers_s__c.field-meta.xml
<CustomField>
    <fullName>Part_Numbers_s__c</fullName>
    <label>Part Numbers(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Contact/fields/Display_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Mailing_Country__c</fullName>
    <label>Display Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Address_ship_to__c.field-meta.xml
<CustomField>
    <fullName>Address_ship_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship to Locations for Company Name Ship to</description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (1 AND 3)) AND 4 AND 5 AND 6</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Company_Name_Ship_To__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Company_Name_Ship_To__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Org_ID__c</field>
            <operation>equals</operation>
            <value>2</value>
        </filterItems>
        <infoMessage>If a Company Ship to is selected, then, the address related to company ship to is shown by default. User can override this filter</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners (Address)</relationshipLabel>
    <relationshipName>ShiptoLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Company_Name_End_Cust__c.field-meta.xml
<CustomField>
    <fullName>Company_Name_End_Cust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Email Betty Dea with end customer name and website if it cannot be found in drop down list.</inlineHelpText>
    <label>Company Name - End Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Company End Customer should be an Active Top Level Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Company_Name_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Company_Name_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Name - Ship To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 4 AND 3 AND 5</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Party</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>User can select Party Accounts or Customer Accounts</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners (Company Name)</relationshipLabel>
    <relationshipName>Loaners1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Est_Production_Date__c.field-meta.xml
<CustomField>
    <fullName>Est_Production_Date__c</fullName>
    <label>Est Production Date</label>
    <type>Date</type>
</CustomField>

src/objects/Loaner__c/fields/Inside_Sales_Finisar__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Finisar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales-Finisar</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND (2 OR (3 AND 4))) OR ( NOT (1) AND 2))</booleanFilter>
        <filterItems>
            <field>$Source.Loaner_Ship_From_Finisar__c</field>
            <operation>notEqual</operation>
            <value>Factory Stock</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>contains</operation>
            <value>Inside_Sales_FAE</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>equals</operation>
            <value>Betty</value>
        </filterItems>
        <filterItems>
            <field>User.LastName</field>
            <operation>equals</operation>
            <value>Dea</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LoanersInsideSales</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Inside_Sales_Sales_rep__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Sales_rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales-Sales Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Firm_Name_Sales_rep__c</field>
            <operation>equals</operation>
            <valueField>User.Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Sales Rep Firm Name should match Inside sales-Sales Rep -Contact -AccountId</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners_Inside_Sales_Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Duration__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Duration__c</fullName>
    <inlineHelpText>SVP approval needed if over 180 days or for &quot;No Return&quot; sample request.</inlineHelpText>
    <label>Loaner Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loaner_Duration</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Ship_From_Finisar__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Ship_From_Finisar__c</fullName>
    <inlineHelpText>Keep Default=&quot;Factory Stock&quot; for any loaner shipping from factory through Sales Order.  Use &quot;Transfer From Existing Loaner&quot; for loaner transfer only.  Do not change to other choices unless you have discussed with Betty.</inlineHelpText>
    <label>Loaner Ship From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ship_From</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Select &quot;New Opportunity&quot; only if this loaner links to an Opportunity in Salesforce.Then there should only be 1 P/N on this loaner which matches to the Opportunity P/N.Select any other choice if this is a stand-alone loaner which can include multiple P/Ns.</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Opportunity</fullName>
            </value>
            <value>
                <fullName>New Opportunity - &lt; 100K SAM</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity -  Demand already forecasted</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity - Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Project_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Project_Engineer__c</fullName>
    <label>Project Engineer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <formula>TEXT(Opportunity.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Type</label>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Type_of_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Pricing__c</fullName>
    <inlineHelpText>Blanket Price Agreement creates/updates customer price list. Dist Quote generates S&amp;D# for Distributor to ship standard parts to customer at lower price than current Disti Cost. Fixed-One Time Order does not update customer price list or generate S&amp;D#.</inlineHelpText>
    <label>Type of Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blanket Price Agreement</fullName>
            </value>
            <value>
                <fullName>Dist Quote</fullName>
            </value>
            <value>
                <fullName>Fixed - One Time Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User/fields/Legacy_Company__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Company__c</fullName>
    <description>Used to support existing processes during the org merge processes</description>
    <label>Legacy Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finisar</fullName>
            </value>
            <value>
                <fullName>Corp II-VI</fullName>
            </value>
            <value>
                <fullName>Marlow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/Found_By.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar FAE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar PE</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Finisar R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>FoundBy on Case object</description>
    <masterLabel>Found By</masterLabel>
</GlobalValueSet>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/Loaner_Duration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>90</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>365</fullName>
    </customValue>
    <customValue>
        <fullName>No_Return</fullName>
        <label>No Return</label>
    </customValue>
    <masterLabel>Loaner Duration</masterLabel>
</GlobalValueSet>

src/globalValueSets/Ship_From.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Factory Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Returned Loaner Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer From Existing Loaner</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Ship From</masterLabel>
</GlobalValueSet>

src/classes/AccessTriggersTest.cls
@isTest
public class AccessTriggersTest {
    
    @testSetup static void createData(){
        UserRole insdieuserrole = [Select Id from UserRole Where DeveloperName ='Inside_Sales_FAE'];
        Profile usrProfile = [SELECT Id from Profile where Name ='System Administrator'];
        User insideUser = new User(LastName='Usrlast',ProfileId=usrProfile.Id,UserRoleId=insdieuserrole.id,alias ='testusr',
                                   Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                                   LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@finisar.com');
        insert insideUser;
       User guestUser = new User(LastName='Usrlast1234',ProfileId=[SELECT Id FROM Profile WHERE Name = 'Custom Web to Case Profile'].Id,alias ='siteusr',
                                   Email='siteguestusr@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                                   LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='siteguestusr@finisar.com');
        insert guestUser;
        User sysAdm = new User(LastName='Usrlast1111',ProfileId=usrProfile.Id,alias ='trsysy',Legacy_Company__c ='Finisar',
                               Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser@finisar.com');
        system.runAs(sysAdm){
            Case caseObj = New Case(Found_By__c='Customer',Part_Numbers_s__c='12313',Status='Open',SuppliedEmail='test@gmail.com',OwnerId=guestUser.Id);
            insert caseObj;
            Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
            insert globalParentAcc;
            Account acc = new Account(name='Account ',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ParentId = globalParentAcc.Id,  ShippingCity = 'New York', ShippingCountry ='US',
                                      billingcity='New York', billingcountry='US',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
            insert acc;
            Account acc1 = new Account(ParentId = acc.Id,name='Account1 ', Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                       billingcity='New York test', billingcountry='US',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId(), Org_ID__c= '2',
                                      Site_Use_Code__c='SHIP_TO',Site_Use_Status__c='Active', ShippingCity = 'New York', ShippingCountry ='US');
            
            insert acc1;
            
            Contact cntct=new Contact(FirstName='Test',LastName='Contact',Email='test@gmail.com',MailingCountry='United States',Display_Mailing_Country__c='United States');
            insert cntct;
            
            Loaner__c loaner = new Loaner__c(RecordTypeId = Schema.SObjectType.Loaner__c.getRecordTypeInfosByName().get('Loaner Request').getRecordTypeId(), Company_Name_Ship_To__c = acc.Id,Company_Name_End_Cust__c = acc.Id,Project_Engineer__c='Test',Project_Name__c = 'Test',Est_Production_Date__c = Date.Today(),Address_ship_to__c = acc1.Id,
                                             Opportunity_Type__c='New Opportunity', Loaner_Duration__c='180',Loaner_Ship_From_Finisar__c = 'Factory Stock',Inside_Sales_Sales_rep__c = UserInfo.getUserId(),Inside_Sales_Finisar__c = insideUser.id);
            insert loaner;
            
            Quote quoteObj = new Quote(Name ='test',Status='Draft',Type_of_Pricing__c='Fixed - One Time Order',ExpirationDate = System.today()+1,
                                       Account__c=acc.id);
            insert quoteObj;   
        }
        
    }
    
    TestMethod static void testCaseTrigger(){
        Case caseObj = [Select id from Case];
    }
    
    TestMethod static void testLoanerTrigger(){
        Loaner__c loanerObj = [Select id,Loaner_Duration__c from Loaner__c Limit 1];
        loanerObj.Loaner_Duration__c = '90';
        update loanerObj;
    }
    
    TestMethod static void testQuoteTrigger(){
        User tstUsr=[Select Id from User where userName='testuser@finisar.com'];
        System.runAs(tstUsr){
            Quote quoteObj = [Select id,ExpirationDate from Quote Limit 1];
            quoteObj.ExpirationDate = System.today() +2;
            update quoteObj;
        }
    }
}