src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A - OOW</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Return - NTF</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <label>Legacy Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Detail__c/FA_FV_Detail__c.object-meta.xml
<CustomObject>
    <label>FV/FA Detail</label>
    <nameField>
        <displayFormat>FV/FA Analysis - {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FV/FA Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FA_FV_Detail__c/fields/FA_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>FA_Completion_Date__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

src/objects/FA_FV_Detail__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FV/FA</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>FV/FA Details</relationshipLabel>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>This is the serial number to which this FA / FV is relevant</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Serial_Number__c</referenceTo>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please select the status for this FA or FV subject to the following guidance:
-  
-  
-</inlineHelpText>
    <label>Detail Status (Junction)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Evaluating</fullName>
                <isActive>false</isActive>
                <label>Evaluating</label>
            </value>
            <value>
                <fullName>Finalizing</fullName>
                <isActive>false</isActive>
                <label>Finalizing</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <description>Oracle - Update this field</description>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;/lightning/cmp/c__FAFVCustomUIQuickAction?c__recordId=&quot;+Id, &apos;FA FV&apos;,&apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FA FV</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaner</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Prelim</fullName>
            </value>
            <value>
                <fullName>1stArticle</fullName>
            </value>
            <value>
                <fullName>Pre-Prod</fullName>
            </value>
            <value>
                <fullName>Experiment</fullName>
            </value>
            <value>
                <fullName>Items.Obsolete</fullName>
            </value>
            <value>
                <fullName>Mechanical engineering</fullName>
            </value>
            <value>
                <fullName>Items.Pilot</fullName>
            </value>
            <value>
                <fullName>Items.Production</fullName>
            </value>
            <value>
                <fullName>Items.Pre-Production</fullName>
            </value>
            <value>
                <fullName>Items.Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Serial_Number__c/Serial_Number__c.object-meta.xml
<CustomObject>
    <description>This is the serial numbers for an RMA request which will be populated from Oracle</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Serial_Number__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <inlineHelpText>Please select the disposition for this serial number</inlineHelpText>
    <label>Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>N/A - OOW</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Return - NTF</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>FA / FV</fullName>
                <isActive>false</isActive>
                <label>FA / FV</label>
            </value>
            <value>
                <fullName>Loaner Return Record</fullName>
                <isActive>false</isActive>
                <label>Loaner Return Record</label>
            </value>
            <value>
                <fullName>Return to Stock</fullName>
                <isActive>false</isActive>
                <label>Return to Stock</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Serial_Number__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <inlineHelpText>This is the RMA order line to which this serial number is related</inlineHelpText>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Serial_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Serial Number Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Serial_Number_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <nameField>
        <label>Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Steps__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FA / FV</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/FAFVCustomUITest.cls
@isTest
public class FAFVCustomUITest {
 @isTest
    public static void getFAFVDetail(){
        Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
        insert globalParentAcc;
        Account acc = new Account(name='Account ',ParentId=globalParentAcc.Id,ShippingCity = 'New York', ShippingCountry ='US',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        
        Order oRec= new Order(AccountId = acc.id,Type='RMA Order',Status='Draft',Legacy_Id__c='test123',RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('RMA Order').getRecordTypeId(),
                             EffectiveDate = System.today()+1);
        insert oRec;
        Product2 prdRec = new Product2(Name = 'Test1',ProductCode = '12343',Marketing_P_N__c ='7865',Status__c='Concept',ExternalId__c  ='765453');
        insert prdRec;
        Order_Line__c olRec = new Order_Line__c(Order__c=oRec.id,RecordTypeId = Schema.SObjectType.Order_Line__c.getRecordTypeInfosByName().get('RMA Order Line').getRecordTypeId(),RMA_Received_Date__c= System.today(),Part_Number__c= prdRec.id);
        insert olRec;
        
        Serial_Number__c sRec = new Serial_Number__c(Order_Line__c=olRec.id,Disposition__c='Rework');
        insert sRec;
        Serial_Number__c sRec1 = new Serial_Number__c(Order_Line__c=olRec.id,Disposition__c='Rework');
        insert sRec1;
        Serial_Number__c sRec2 = new Serial_Number__c(Order_Line__c=olRec.id,Disposition__c='Rework');
        insert sRec2;
        
        FA_FV_Analysis__c fRec = new FA_FV_Analysis__c(Name= 'test',RecordTypeId = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FA Analysis').getRecordTypeId()); 
        insert fRec;
        
        FA_FV_Analysis__c fRec1 = new FA_FV_Analysis__c(Name= 'test1',RecordTypeId = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FV Analysis').getRecordTypeId()); 
        insert fRec1;
        
         FA_FV_Analysis__c FAFvFinalRecord = new FA_FV_Analysis__c(Name= 'updateInprogress',RecordTypeId = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FA Analysis').getRecordTypeId()); 
        insert FAFvFinalRecord;
        
        FA_FV_Detail__c fdRec = new FA_FV_Detail__c(Serial_Number__c =sRec.id,FA_FV__c=fRec.id,FA_Completion_Date__c= system.today());
        insert fdRec;
        
        FA_FV_Detail__c fdRec1 = new FA_FV_Detail__c(Serial_Number__c =sRec1.id,FA_FV__c=fRec1.id,FA_Completion_Date__c= system.today());
        insert fdRec1;
        
        FA_FV_Detail__c fdRec2 = new FA_FV_Detail__c(Serial_Number__c =sRec2.id,FA_FV__c=fRec1.id,FA_Completion_Date__c= system.today());
        insert fdRec2;
        
        List<FA_FV_Analysis__c> FAFVList = new  List<FA_FV_Analysis__c>();
        FAFVList.add(fRec);
        FAFVList.add(fRec1);
        
        Failure_Modes__c fc= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        Failure_Modes__c fc1= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        Failure_Modes__c fc2= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        Failure_Modes__c fc3= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        Failure_Modes__c fc4= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        Failure_Modes__c fmode5= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        
        List<Failure_Modes__c> fcList = new List<Failure_Modes__c>();
        fcList.add(fc);
        fcList.add(fc1);
        fcList.add(fc2);
        fcList.add(fc3);
        fcList.add(fc4);
        
        
        Steps__c  steps = new Steps__c(Name='test',FA_FV__c=fRec.id,FA_Findings__c='testtt',Comments__c='test',FA_Steps_Description_FA_Steps__c='testt');
        Steps__c  steps1 = new Steps__c(Name='test',FA_FV__c=fRec.id,FA_Findings__c='testtt',Comments__c='test',FA_Steps_Description_FA_Steps__c='testt');
        Steps__c  steps2 = new Steps__c(Name='test',FA_FV__c=fRec.id,FA_Findings__c='testtt',Comments__c='test',FA_Steps_Description_FA_Steps__c='testt');
        Steps__c  steps3 = new Steps__c(Name='test',FA_FV__c=fRec.id,FA_Findings__c='testtt',Comments__c='test',FA_Steps_Description_FA_Steps__c='testt');
        Steps__c  steps4 = new Steps__c(Name='test',FA_FV__c=fRec.id,FA_Findings__c='testtt',Comments__c='test',FA_Steps_Description_FA_Steps__c='testt');
        List<Steps__c> stepList = new List<Steps__c>();
        stepList.add(steps);
        stepList.add(steps1);
        stepList.add(steps2);
        stepList.add(steps3);
        stepList.add(steps4);
       
        FA_FV_Detail__c fdRecc = new FA_FV_Detail__c(Serial_Number__c =sRec.id,FA_FV__c=fRec.id,FA_Completion_Date__c= system.today());
        FA_FV_Detail__c fdRecc1 = new FA_FV_Detail__c(Serial_Number__c =sRec1.id,FA_FV__c=fRec1.id,FA_Completion_Date__c= system.today());
        FA_FV_Detail__c fdRecc2 = new FA_FV_Detail__c(Serial_Number__c =sRec2.id,FA_FV__c=fRec1.id,FA_Completion_Date__c= system.today());
        list<FA_FV_Detail__c> DetailLists  = new list<FA_FV_Detail__c>();
        DetailLists.add(fdRecc);
        DetailLists.add(fdRecc1);
        DetailLists.add(fdRecc2);
        
        Test.startTest();
        FAFVCustomUI.getFAFVRecord(oRec.id);
        FAFVCustomUI.saveFAFV(fdRec2, FAFVList);
        FAFVCustomUI.savefCodeRec(fcList);
        FAFVCustomUI.saveStepsRec(stepList);
        FAFVCustomUI.saveSnoRec(DetailLists);
        FAFVCustomUI.getFAFVrelatedList(fRec.id, olRec.id);
        FAFVCustomUI.deleteRow(fdRecc.id);
        Test.stopTest();
        
    }
}