src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Office location that a Sale originated from.</description>
    <inlineHelpText>MID = Dallas
MIE = Europe
MIA = Asia
MIJ = Japan</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>MID</fullName>
            </value>
            <value>
                <fullName>MIE</fullName>
            </value>
            <value>
                <fullName>MIJ</fullName>
            </value>
            <value>
                <fullName>HOUSE (80)</fullName>
            </value>
            <value>
                <fullName>II-VI (Internal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Global_Parent.recordType-meta.xml
<RecordType>
    <fullName>Global_Parent</fullName>
    <active>true</active>
    <label>Global Parent</label>
</RecordType>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Opportunity/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Next_12_Months_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Next_12_Months_Revenue__c</fullName>
    <inlineHelpText>Next 12 Months Revenue from Open Opportunities</inlineHelpText>
    <label>Next 12 Months Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Opportunity/fields/Next_Action_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Action_Due_Date__c</fullName>
    <label>Next Action Due Date</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAS - WESTERN</fullName>
            </value>
            <value>
                <fullName>AMERICAS - EASTERN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/QuoteNewButtonControllerTest.cls
@isTest
public class QuoteNewButtonControllerTest {
    @isTest
    static void createQuote(){ 
         PageReference pageRef = Page.QuoteNewButtonPage;
        Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Global_Parent').getRecordTypeId()	);
        insert globalParentAcc;
        Account acc = new Account(name='Account ', Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',
                                  billingcity='New York', ParentId =globalParentAcc.id, billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id,name from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
         User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
        Opportunity opp = new Opportunity(Name='Test',AccountId=acc.id,Project_Name__c='Test',StageName='Open - Discussion',Type='New',CloseDate=System.today(),
                                        Next_12_Months_Revenue__c=10, Market_Segment__c='Consumer',Region__c='JAPAN',RSM__c=u.id,NextStep='test',Next_Action_Due_Date__c=System.today()+2);
        insert opp;
        
        Quote qrec = new Quote(Account__c=acc.id);
        List<String> acclist = new List<String>();
        acclist.add(String.valueof(acc.id));
        string AccIds = String.valueof(acc.id);
        Test.startTest();
        
        QuoteNewButtonController.saveQuote(acclist);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.standardController(qrec);
        QuoteNewButtonController controller = new QuoteNewButtonController(sc); 
        controller.redirect();
        QuoteNewButtonController.getOpportunityRec(opp.id);
        QuoteNewButtonController.saveQuote1(AccIds);
        Test.stopTest();
    }
    
    public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              UserRoleId = roleId);
        return tuser;
    }

}