src/objects/Account/fields/Display_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Billing_Country__c</fullName>
    <label>Display Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/Display_Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Display_Shipping_Country__c</fullName>
    <label>Display Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ISO_Countries</valueSetName>
    </valueSet>
</CustomField>

src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Saleschannel value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Sales Channel)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaner</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Prelim</fullName>
            </value>
            <value>
                <fullName>1stArticle</fullName>
            </value>
            <value>
                <fullName>Pre-Prod</fullName>
            </value>
            <value>
                <fullName>Experiment</fullName>
            </value>
            <value>
                <fullName>Items.Obsolete</fullName>
            </value>
            <value>
                <fullName>Mechanical engineering</fullName>
            </value>
            <value>
                <fullName>Items.Pilot</fullName>
            </value>
            <value>
                <fullName>Items.Production</fullName>
            </value>
            <value>
                <fullName>Items.Pre-Production</fullName>
            </value>
            <value>
                <fullName>Items.Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/PrimarySalesperson__c.field-meta.xml
<CustomField>
    <fullName>PrimarySalesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Salesperson</description>
    <inlineHelpText>Select the Finisar Regional Sales Manager (RSM) who should be approving this quote.</inlineHelpText>
    <label>Primary Salesperson</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>YLee</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>cleow</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>KFalta</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>MRobin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Sales Channel)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Type_of_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Pricing__c</fullName>
    <inlineHelpText>Blanket Price Agreement creates/updates customer price list. Dist Quote generates S&amp;D# for Distributor to ship standard parts to customer at lower price than current Disti Cost. Fixed-One Time Order does not update customer price list or generate S&amp;D#.</inlineHelpText>
    <label>Type of Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blanket Price Agreement</fullName>
            </value>
            <value>
                <fullName>Dist Quote</fullName>
            </value>
            <value>
                <fullName>Fixed - One Time Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Disti_Resale_Price__c.field-meta.xml
<CustomField>
    <fullName>Disti_Resale_Price__c</fullName>
    <label>Disti Resale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Lost - Delivery</fullName>
            </value>
            <value>
                <fullName>Lost - Price</fullName>
            </value>
            <value>
                <fullName>Lost - Technical</fullName>
            </value>
            <value>
                <fullName>One Time Order Processed</fullName>
            </value>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Canceled</fullName>
            </value>
            <value>
                <fullName>Project Cancelled</fullName>
            </value>
            <value>
                <fullName>Approval Cycle Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/globalValueSets/ISO_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>A list of ISO country names.</description>
    <masterLabel>ISO Countries</masterLabel>
</GlobalValueSet>

src/classes/QuoteLineItemControllerTest.cls
@isTest
public class QuoteLineItemControllerTest {
    @isTest
    static void createQuoteLine(){
           Account globalParentAcc=new Account(Name='Global Parent Test Acc',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
        insert globalParentAcc;
        Account acc = new Account(name='Account ',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', parentId=globalParentAcc.id,ShippingCity = 'New York', ShippingCountry ='US',
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        
        Account acc1 = new Account(name='Account test',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', parentId=globalParentAcc.id,ShippingCity = 'New York', ShippingCountry ='US',
                                  billingcity='Illionis', billingcountry='USA',Status__c='Active',Type='Distributor',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('External Account').getRecordTypeId());
        
        insert acc1;
        system.debug('acc1=='+acc1);
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id,name from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
         User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
                String roleId2 =[select Id,name from UserRole where Name='Marketing Admin WSS' LIMIT 1].Id;
          User u2 = createTestUser(roleId2,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u2;
        }
         Opportunity opp = New Opportunity(Name = acc.Name+' Opp',RSM__c = u.id,Project_Name__c = 'test',
                                          StageName = 'Open - Discussion', AccountId = acc.Id, CloseDate = date.today().addDays(365));
        insert opp;
        Product2 prod = new Product2(IsActive = true,Status__c = 'Active',BU_Code__c = '0040',Name = 'Test Product',ExternalId__c = '12534', ProductCode = 'Test Product Code',Marketing_P_N__c = 'Test PN');
        insert prod;
        
        
        Quote qrec = new Quote(Name ='test',Status='Draft',OpportunityId =opp.id,PrimarySalesperson__c =u2.id,Type_of_Pricing__c='Fixed - One Time Order',ExpirationDate = System.today()+1,
                               Account__c=acc.id);
        insert qrec;
        system.debug('qrec==='+qrec);
        List<Quote_Item__c> qList = new List<Quote_Item__c>();
        Quote_Item__c qLine1 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=23,Target_Price__c=4564.77,Line_Status__c='Draft');
        insert qLine1;
        qList.add(qLine1);
          list<id> qtList = new list<id>();
          qtList.add(qLine1.id);
        Quote_Item__c qLine2 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=23,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine3 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=25,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine4 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=26,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine5 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=25,Target_Price__c=4564.77,Line_Status__c='Draft');
        qList.add(qLine2);
        qList.add(qLine3);
        qList.add(qLine4);
        qList.add(qLine5);
        String s = JSON.serialize(qList);
        Test.startTest();
        QuoteLineItemController.updatePLM(qtList);
        QuoteLineItemController.getQuoteLineItem(qrec.id);
        //QuoteLineItemController.saveQuoteLineItem(s,qrec.id);
        //QuoteLineItemController.getLineStatus(qLine1.id);
        QuoteLineItemController.sendRequesttoInformatica(qrec.id);
        QuoteLineItemController.validateRulesRecords(qrec.id);
        QuoteLineItemController.deleteLoanerLineItem(qLine1);
        Test.stopTest();
        
    }
 public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              UserRoleId = roleId);
        return tuser;
    }
    
  @isTest
    static void createQuoteLine2(){  
        
            Account globalParentAcc=new Account(Name='Global Parent Test Acc2',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States',ShippingCity = 'New York', ShippingCountry ='US',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Parent').getRecordTypeId());
        insert globalParentAcc;
        Account acc = new Account(name='Account ',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', parentId=globalParentAcc.id,ShippingCity = 'New York', ShippingCountry ='US',
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        
        Account acc1 = new Account(name='Account test2',Display_Shipping_Country__c ='United States',   Display_Billing_Country__c = 'United States', parentId=globalParentAcc.id,ShippingCity = 'New York', ShippingCountry ='US',
                                  billingcity='Illionis', billingcountry='USA',Status__c='Active',Type='Distributor',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc1;
        system.debug('acc1=='+acc1);
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id,name from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
         User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
                   String roleId2 =[select Id,name from UserRole where Name='Marketing Admin WSS' LIMIT 1].Id;
          User u2 = createTestUser(roleId2,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u2;
        }
         Opportunity opp = New Opportunity(Name = acc.Name+' Opp',RSM__c = u.id,Project_Name__c = 'test',
                                          StageName = 'Open - Discussion', AccountId = acc.Id, CloseDate = date.today().addDays(365));
        insert opp;
        Product2 prod = new Product2(IsActive = true,Status__c = 'Active',BU_Code__c = '0040',Name = 'Test Product',ExternalId__c = '12534', ProductCode = 'Test Product Code',Marketing_P_N__c = 'Test PN');
        insert prod;
        Account acountObj = [select id ,recordtypeid,recordtype.name,status__c,type from account where name='Account test2' limit 1];
        System.debug('acountObj'+acountObj);
        
        Quote qrec = new Quote(Name ='test1',OpportunityId =opp.id,Status='Draft',PrimarySalesperson__c =u2.id,Type_of_Pricing__c='Dist Quote',ExpirationDate = System.today()+1,
                               Account__c=acc.id,sales_channel__c=acc1.Id);
        system.debug('qrec----'+acc1.Type + 'status ' + acc1.Status__c);
        insert qrec;
        List<Quote_Item__c> qList = new List<Quote_Item__c>();
        Quote_Item__c qLine1 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=23,Disti_Resale_Price__c=5600.05,Target_Price__c=4564.77,Line_Status__c='Draft');
        insert qLine1;
        qList.add(qLine1);
        list<id> qtList = new list<id>();
        qtList.add(qLine1.id);
        Quote_Item__c qLine2 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=23,Disti_Resale_Price__c=5600.05,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine3 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=25,Disti_Resale_Price__c=5600.05,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine4 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=26,Disti_Resale_Price__c=5600.05,Target_Price__c=4564.77,Line_Status__c='Draft');
        Quote_Item__c qLine5 = new Quote_Item__c(Quote__c= qrec.id,Product__c=prod.id,Quantity__c=25,Disti_Resale_Price__c=5600.05,Target_Price__c=4564.77,Line_Status__c='Draft');
        qList.add(qLine2);
        qList.add(qLine3);
        qList.add(qLine4);
        qList.add(qLine5);
     
        String s = JSON.serialize(qList);
        Test.startTest();
        QuoteLineItemController.updatePLM(qtList);
        QuoteLineItemController.getQuoteLineItem(qrec.id);
        QuoteLineItemController.saveQuoteLineItem(qList,qrec.id);
        //QuoteLineItemController.getLineStatus(qLine1.id);
        QuoteLineItemController.sendRequesttoInformatica(qrec.id);
        QuoteLineItemController.validateRulesRecords(qrec.id);
        QuoteLineItemController.deleteLoanerLineItem(qLine1);
        
        
        //Quote Approval Controller Test cases
        
        Id appRecordIdId = [select id from Quote limit 1].Id;
        List<String> appRecordId = new List<String>();
        appRecordId.add(appRecordIdId);
        QuoteApprovalController.QuoteQuery([select id from Quote limit 1].Id);
        QuoteApprovalController.ApproveRecords(appRecordId,[select id from Quote limit 1].Id);
        QuoteApprovalController.RejectRecords(appRecordId);
        QuoteApprovalController.ReasignRecords(appRecordId,'test@mail.com',[select id from Quote limit 1].Id);
        
        Test.stopTest();
    }
}