src/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/classes/AccountExportController.cls
public with sharing class AccountExportController {

    public transient List<account> accList { get; set; }
   // public transient List<account> accList1 { get; set; }
    public transient List<List<account>> accList1 { get; set; }
    public AccountExportController(){
    accList1 = new List<List<account>>();
    accList  = [select id,name,External_Id__c,Legacy_Id__c from account limit 10000];
   /* integer noofAcc = [select count() from account];
    for(integer i = 0; i<noofAcc ; i++){
        accList  = [select id,name,External_Id__c,Legacy_Id__c from account limit 10000];
    }*/
    //accList1 = new List<List<account>>();
    //integer noofAcc = [select count() from account];
   /* for(integer i = 0; i< noofAcc/10000 ; i++){
    accList = new List<Account>();
    integer offsetv = i*10000;
    string acQuery = 'select id,name,External_Id__c,Legacy_Id__c from account limit 10000 OFFSET '+offsetv;
    accList  = database.query(acQuery );
    accList1.add(accList);
    }*/
    
    }
}