src/objects/Account/fields/GrandParentId__c.field-meta.xml
<CustomField>
    <fullName>GrandParentId__c</fullName>
    <formula>Parent.Parent.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GrandParentId</label>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <label>Price List</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>All Active non site accounts</description>
    <inlineHelpText>All Active non site accounts</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Account.ParentId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Customer)</relationshipLabel>
    <relationshipName>CustomerQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <formula>IF( PriceListSelected__c &lt;&gt;&apos;&apos;, PriceListSelected__c ,
	IF(Site__r.Price_List__c &lt;&gt; &apos;&apos;, Site__r.Price_List__c,
		IF(Customer__r.Price_List__c &lt;&gt; &apos;&apos;,Customer__r.Price_List__c ,
			IF( Account__r.Price_List__c &lt;&gt; &apos;&apos;,Account__r.Price_List__c ,
				IF( Sales_Channel__r.Sales_Channel_Code__c = &apos;VAR SYNNEX_US&apos;  , 
					IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot;, &apos;FNSR VAR REP PRICE LIST&apos;,
						IF(CreatedBy.Profile.Name = &quot;Finisar Partner Community User (Disti Users)&quot;, &apos;FNSR VAR DISTI PRICE LIST&apos;, &apos;FNSR VAR RSM PRICE LIST&apos;) 
					),
					IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot;, &apos;FNSR REP PRICE LIST&apos;,
					IF(CreatedBy.Profile.Name = &quot;Finisar Partner Community User (Disti Users)&quot;, &apos;FNSR DISTRIBUTOR PRICE LIST&apos;, &apos;FNSR RSM PRICE LIST&apos;)
				)
			)
		)
	)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price List</label>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/PriceListSelected__c.field-meta.xml
<CustomField>
    <fullName>PriceListSelected__c</fullName>
    <label>PriceListSelected</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/QuoteCreatorProfile__c.field-meta.xml
<CustomField>
    <fullName>QuoteCreatorProfile__c</fullName>
    <formula>CreatedBy.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QuoteCreatorProfile</label>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Site)</relationshipLabel>
    <relationshipName>SiteQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Type_of_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Pricing__c</fullName>
    <inlineHelpText>Blanket Price Agreement creates/updates customer price list. Dist Quote generates S&amp;D# for Distributor to ship standard parts to customer at lower price than current Disti Cost. Fixed-One Time Order does not update customer price list or generate S&amp;D#.</inlineHelpText>
    <label>Type of Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blanket Price Agreement</fullName>
            </value>
            <value>
                <fullName>Dist Quote</fullName>
            </value>
            <value>
                <fullName>Fixed - One Time Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/PriceListController.cls
public class PriceListController {
@AuraEnabled
    public static WrapperClass PriceListQuery(Id quoteId){
        WrapperClass PriceListWrapper = new WrapperClass();
        String AccountId;
        String CostumerId;
        String SiteId;
        String QuoteCreatorProfile ;
        String PricingType;
        String ErrMessage;
        // fetch Account details from Quote
        if(quoteId != null) {
           Quote Quotedata = new Quote();
            Quotedata = [SELECT Id,Account__c,Type_of_Pricing__c,Customer__c,Site__c,QuoteCreatorProfile__c FROM Quote where ID = :quoteId];
            AccountId = Quotedata.Account__c;
            CostumerId = Quotedata.Customer__c;
            SiteId = Quotedata.Site__c;
            PricingType = Quotedata.Type_of_Pricing__c;
            QuoteCreatorProfile = Quotedata.QuoteCreatorProfile__c;
        }
        if(PricingType != 'Blanket Price Agreement'){
            ErrMessage = 'PriceList Selection is available only for Blanket Price Agreement Quotes';
        }
        
        //fetch All PriceLists
        String GrandparentId ;
        List<Account> AccountPriceLists = new List<Account>();
        if((AccountId != '') && (AccountId != Null)){
                            GrandparentId = AccountId.substring(0,15);
                            AccountPriceLists = [SELECT Price_List__c FROM Account where 
                                                                    (((ID = :AccountId) OR (ParentId =:AccountId) OR (GrandParentId__c =:GrandparentId))
                                                                     AND ((Price_List__c != '') AND (Price_List__c != Null)
                                                                     ))];
        									}
        // fetch distinct PriceLists
        List<Account> DistinctPriceList = new List<Account>();
        for(Account Temp: AccountPriceLists){
            Boolean found = false;
            for(Integer i=0; i< DistinctPriceList.size(); i++){
            if(Temp.Price_List__c.equalsIgnoreCase(DistinctPriceList[i].Price_List__c)){ 
            found=true;
            break;
            }
            }
            if(!found)
            DistinctPriceList.add(Temp);
        	}
        
        // Insert Creator PriceList
        Account QuoteCreatorPriceList = new Account(Name= 'TempPricelist');
        if(QuoteCreatorProfile == 'Finisar Partner Community User'){
            QuoteCreatorPriceList.Price_List__c = 'FNSR REP PRICE LIST';
        }else{
            QuoteCreatorPriceList.Price_List__c = 'FNSR RSM PRICE LIST';
        }
        DistinctPriceList.add(QuoteCreatorPriceList);
        System.debug(AccountPriceLists);
        System.debug(GrandparentId);
        PriceListWrapper.AccountPriceListOutput = DistinctPriceList;
        PriceListWrapper.errorMessage = ErrMessage;
        return PriceListWrapper;
    }
 
@AuraEnabled
    public static String PriceListUpdate(Id quoteId, String pricelist){ 
        System.debug(pricelist);
        System.debug(quoteId);
        if(quoteId != null) {
            Quote Quotedata = new Quote();
            Quotedata = [SELECT Id,PriceListSelected__c FROM Quote where ID = :quoteId];
            Quotedata.PriceListSelected__c = pricelist;
            update Quotedata;
        } 
        Return pricelist;
    } 
    
    public class WrapperClass {
        @AuraEnabled public List<Account> AccountPriceListOutput;
        @AuraEnabled public String errorMessage;
    }
}