src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Commisions__c/Commisions__c.object-meta.xml
<CustomObject>
    <label>Commisions</label>
    <nameField>
        <displayFormat>Commision-{000000}</displayFormat>
        <label>Commisions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commisions__c/fields/Commisions_Change__c.field-meta.xml
<CustomField>
    <fullName>Commisions_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commisions Change</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Commisions__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Commisions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name10__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm  Name10</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name10)</relationshipLabel>
    <relationshipName>Commisions9</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name1__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name2__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name2)</relationshipLabel>
    <relationshipName>Commisions1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name3__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name3)</relationshipLabel>
    <relationshipName>Commisions2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name4__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name4)</relationshipLabel>
    <relationshipName>Commisions3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name5__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name5</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name5)</relationshipLabel>
    <relationshipName>Commisions4</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name6__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name6</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name6)</relationshipLabel>
    <relationshipName>Commisions5</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name7__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name7</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name7)</relationshipLabel>
    <relationshipName>Commisions6</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name8__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name8</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name8)</relationshipLabel>
    <relationshipName>Commisions7</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name9__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name9</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name9)</relationshipLabel>
    <relationshipName>Commisions8</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Commisions__c.field-meta.xml
<CustomField>
    <fullName>Commisions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commisions</label>
    <referenceTo>Commisions__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/classes/OrderAndLineItemsAccessBatch.cls
public class OrderAndLineItemsAccessBatch implements Database.Batchable < sObject > {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        String Query = 'select id,Order_Line__c,Order_Line__r.Order__c,Salesrep_Name1__c,Salesrep_Name1__r.Name,Salesrep_Name1__r.Legacy_Id__c ,Salesrep_Name2__c,Salesrep_Name2__r.Name,Salesrep_Name2__r.Legacy_Id__c ,Salesrep_Name3__c,Salesrep_Name3__r.Name,Salesrep_Name3__r.Legacy_Id__c ,Salesrep_Name4__c ,Salesrep_Name4__r.Name,Salesrep_Name4__r.Legacy_Id__c,Salesrep_Name5__c,Salesrep_Name5__r.Name,Salesrep_Name5__r.Legacy_Id__c ,Salesrep_Name6__c,Salesrep_Name6__r.Name ,Salesrep_Name6__r.Legacy_Id__c,Salesrep_Name7__c,Salesrep_Name7__r.Name,Salesrep_Name7__r.Legacy_Id__c ,Salesrep_Name8__c ,Salesrep_Name8__r.Name,Salesrep_Name8__r.Legacy_Id__c,Salesrep_Name9__c ,Salesrep_Name9__r.Name,Salesrep_Name9__r.Legacy_Id__c,Salesrep_Name10__c,Salesrep_Name10__r.Name,Salesrep_Name10__r.Legacy_Id__c,Commisions_Change__c from commisions__C where Commisions_Change__c = true';
        return Database.getQueryLocator(Query);
    }
    public void execute(Database.BatchableContext BC, List < Commisions__c > scope) {
        System.debug('In OrderAndLineItemsAccessBatch'+Scope);
        Map<id,Commisions__c> mapOfCommisions = New Map<id,Commisions__c>(scope);
        List < Order_Line__share > orderLineShareToBeUpdated = New List < Order_Line__share > ();
        List < ordershare > orderShareToBeUpdated = New List < ordershare > ();
        List < Commisions__c > commisionsObjToBeupdated = New List < Commisions__c > ();
        Map < Id, List < String >> mapAccountOrderLine = New Map < Id, List < String >> ();
        Set< String > setOfAccountNameAndLegacyCode = New Set< String > ();
        map < String, Id > mapOfGroupNameAndId = New Map < String, Id > ();
        map<id,id> mapoforderLineAndOrder = New Map<id,id>();
        For(Commisions__c commisionsObj: scope) {
            If(commisionsObj.Salesrep_Name1__c != Null && commisionsObj.Order_Line__c!=Null) {
                If(mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name1__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > { commisionsObj.Salesrep_Name1__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name1__r.Legacy_Id__c + '%');
            }
            
            IF(commisionsObj.Salesrep_Name2__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name2__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > { commisionsObj.Salesrep_Name2__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name2__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Salesrep_Name3__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name3__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name3__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name3__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Salesrep_Name4__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name4__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name4__r.Legacy_Id__c
                        });
                }
                mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name4__r.Legacy_Id__c + '%');
				setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name4__r.Legacy_Id__c + '%');
			}
            IF(commisionsObj.Salesrep_Name5__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name5__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name5__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name5__r.Legacy_Id__c + '%');
            }
            IF(commisionsObj.Salesrep_Name6__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name6__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > { commisionsObj.Salesrep_Name6__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name6__r.Legacy_Id__c + '%');
            }
            IF(commisionsObj.Salesrep_Name7__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name7__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name7__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name7__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Salesrep_Name8__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name8__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > { commisionsObj.Salesrep_Name8__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name8__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Salesrep_Name9__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add( commisionsObj.Salesrep_Name9__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name9__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name9__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Salesrep_Name10__c != Null && commisionsObj.Order_Line__c!=Null) {
                If (mapAccountOrderLine.containskey(commisionsObj.Order_Line__c)) {
                    mapAccountOrderLine.get(commisionsObj.Order_Line__c).add(commisionsObj.Salesrep_Name10__r.Legacy_Id__c);
                }
                Else {
                    mapAccountOrderLine.put(commisionsObj.Order_Line__c, New List < String > {commisionsObj.Salesrep_Name10__r.Legacy_Id__c
                        });
                }
                setOfAccountNameAndLegacyCode.add(commisionsObj.Salesrep_Name10__r.Legacy_Id__c + '%');
            }
            If(commisionsObj.Order_Line__c!=Null  && commisionsObj.Order_Line__r.Order__c!=Null){
                mapoforderLineAndOrder.put(commisionsObj.Order_Line__c,commisionsObj.Order_Line__r.Order__c);
            }
            commisionsObj.Commisions_Change__c = False;
            commisionsObjToBeupdated.add(commisionsObj);
        }
        //
        For(Group groupObj: [select id, Name from Group where Name like: setOfAccountNameAndLegacyCode]) {
            mapOfGroupNameAndId.put(groupObj.Name,groupObj.Id);
        }
        //
        //
        System.debug('scope'+scope);
        System.debug('setOfAccountNameAndLegacyCode'+setOfAccountNameAndLegacyCode);
        System.debug('mapAccountOrderLine' + mapAccountOrderLine);
        System.debug('mapOfGroupNameAndId'+mapOfGroupNameAndId);
        if (mapAccountOrderLine.size() > 0) {
            for (id orderLineId: mapAccountOrderLine.keyset()) {
                if(mapAccountOrderLine.get(orderLineId).size()>0){
                    for(String groupName:mapAccountOrderLine.get(orderLineId)){
                        if(mapOfGroupNameAndId.containskey(groupName)){
                            Order_Line__share orderLineshareObj = new Order_Line__share();
                            orderLineshareObj.parentid = orderLineId;
                            orderLineshareObj.AccessLevel = 'Read';
                            orderLineshareObj.UserOrGroupId = mapOfGroupNameAndId.get(groupName);
                            orderLineShareToBeUpdated.add(orderLineshareObj);
                            if(mapoforderLineAndOrder.containskey(orderLineId)){
                                ordershare orderShareObj = New ordershare();
                                orderShareObj.OrderId = mapoforderLineAndOrder.get(orderLineId);
                                orderShareObj.OrderAccessLevel = 'Read';
                                orderShareObj.UserOrGroupId = mapOfGroupNameAndId.get(groupName);
                                orderShareToBeUpdated.add(orderShareObj);
                            }}}}}
            if (orderLineShareToBeUpdated.size() > 0) {
                upsert orderLineShareToBeUpdated;
            }
            if (orderShareToBeUpdated.size() > 0) {
                upsert orderShareToBeUpdated;
            }
        }
        	if (commisionsObjToBeupdated.size() > 0) {
                update commisionsObjToBeupdated;
            }
    }
    public void finish(Database.BatchableContext BC) {
        Database.executeBatch(New OrderAndLineItemsRmaAccessBatch());
    }
}