src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Commisions__c/Commisions__c.object-meta.xml
<CustomObject>
    <label>Commisions</label>
    <nameField>
        <displayFormat>Commision-{000000}</displayFormat>
        <label>Commisions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commisions__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Commisions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name10__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm  Name10</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name10)</relationshipLabel>
    <relationshipName>Commisions9</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name1__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name2__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name2)</relationshipLabel>
    <relationshipName>Commisions1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name3__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name3)</relationshipLabel>
    <relationshipName>Commisions2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name4__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name4)</relationshipLabel>
    <relationshipName>Commisions3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name5__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name5</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name5)</relationshipLabel>
    <relationshipName>Commisions4</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name6__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name6</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name6)</relationshipLabel>
    <relationshipName>Commisions5</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name7__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name7</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name7)</relationshipLabel>
    <relationshipName>Commisions6</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name8__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name8</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name8)</relationshipLabel>
    <relationshipName>Commisions7</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Commisions__c/fields/Salesrep_Name9__c.field-meta.xml
<CustomField>
    <fullName>Salesrep_Name9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesrep Firm Name9</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commisions (Salesrep Name9)</relationshipLabel>
    <relationshipName>Commisions8</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Disti_Name__c.field-meta.xml
<CustomField>
    <fullName>Disti_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disti Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Order_Changed__c.field-meta.xml
<CustomField>
    <fullName>Order_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Changed</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/Ordered_Date__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Date__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Commisions__c.field-meta.xml
<CustomField>
    <fullName>Commisions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commisions</label>
    <referenceTo>Commisions__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/classes/OrderAndLineItemsAccessSchedulableTest.cls
@isTest(seeAllData= false)
private class OrderAndLineItemsAccessSchedulableTest {
    testMethod static void testSchedule(){
        List<Account> accList = TestDataUtilityClass.createAccounts();
        
        order ord = new order(AccountId = accList[0].Id, 
                              Type ='Sales Order',Legacy_Id__c = 'ordleg', 
                              Ordered_Date__c = Date.today(),
                              Status='Draft',
                              EffectiveDate = Date.today(),
                              Order_Changed__c = true,
                              Disti_Name__c = accList[0].Id,
                              RecordTypeId = Schema.SObjectType.order.getRecordTypeInfosByName().get('Sales Order').getRecordTypeId());
        insert ord;
        Order_Line__c ordLine = new Order_Line__c(order__c = ord.Id);
        insert ordLine;
        Commisions__c commision = new Commisions__c(Order_Line__c = ordLine.Id,
                                                    Salesrep_Name1__c = accList[0].id,
                                                    Salesrep_Name2__c = accList[0].id,
                                                    Salesrep_Name3__c = accList[0].id,
                                                    Salesrep_Name4__c = accList[0].id,
                                                    Salesrep_Name5__c = accList[0].id,
                                                    Salesrep_Name6__c = accList[0].id,
                                                    Salesrep_Name7__c = accList[0].id,
                                                    Salesrep_Name8__c = accList[0].id,
                                                    Salesrep_Name9__c = accList[0].id);
        Commisions__c commision1 = new Commisions__c(Order_Line__c = ordLine.Id,
                                                     Salesrep_Name1__c = accList[0].id,
                                                     Salesrep_Name2__c = accList[0].id,
                                                     Salesrep_Name3__c = accList[0].id,
                                                     Salesrep_Name4__c = accList[0].id,
                                                     Salesrep_Name5__c = accList[0].id,
                                                     Salesrep_Name6__c = accList[0].id,
                                                     Salesrep_Name7__c = accList[0].id,
                                                     Salesrep_Name8__c = accList[0].id,
                                                     Salesrep_Name9__c = accList[0].id,
                                                     Salesrep_Name10__c = accList[0].id);
        insert commision;
        insert commision1;
        Test.StartTest();
        OrderAndLineItemsAccessSchedulable sh1 = new OrderAndLineItemsAccessSchedulable();      
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, sh1);
        Test.stopTest();
    }
}