src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Disti_Name__c.field-meta.xml
<CustomField>
    <fullName>Disti_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disti Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Order_Changed__c.field-meta.xml
<CustomField>
    <fullName>Order_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Changed</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the related RMA Request</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Request#</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>RMA_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/OrderAndLineItemsRmaAccessBatch.cls
public class OrderAndLineItemsRmaAccessBatch implements Database.Batchable < sObject > {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String Query = 'Select id,ownerid,RMA_Request__r.OwnerID,Disti_Name__c,Disti_Name__r.Name,Disti_Name__r.Legacy_Id__c,(select id from RMA_Lines__r),RMA_Request__c from Order where Order_Changed__c = true';
        return Database.getQueryLocator(Query);
    }
    public void execute(Database.BatchableContext BC, List < Order > scope) {
        List < Caseshare > caseRecordListToBeUpdated = New List < Caseshare > ();
        List < order_line__share > orderLineTobeUpdated = New List < order_line__share > ();
        Map <Id, order > orderMapTobeUpdated = New Map <Id, order > ();
        List<OrderShare> orderShareList = New List<OrderShare>();
        Map<Id,String> groupNameMap = New Map<Id,String>();
        Map<String,Id> mapOfGroupNameAndId = New Map<String,Id>();
        Map<Id,Id> caseownerOrderMap = New Map<Id,Id>();
        Map<Id,Order> mapOfOrderfromScope = New Map<Id,Order>(scope);
        for (order orderObj: scope) {
            If (orderObj.RMA_Request__r.OwnerID != Null) {
                caseownerOrderMap.put(orderObj.RMA_Request__r.OwnerID,orderObj.Id);
            }
            If(orderObj.Disti_Name__c!=Null){
                groupNameMap.put(orderObj.Id,orderObj.Disti_Name__r.Legacy_Id__c+'%');
            }
            orderObj.Order_Changed__c = false;
            orderMapTobeUpdated.put(orderObj.id,orderObj);
        }
        IF(caseownerOrderMap.size()>0){
            For(User userObj :[Select id,IsPortalEnabled from User where id in:caseownerOrderMap.keyset() and IsActive=true]){
                IF(userObj.IsPortalEnabled){
                    OrderShare orderShareObj = New OrderShare();
                    orderShareObj.OrderId = caseownerOrderMap.get(userObj.Id);
                    orderShareObj.OrderAccessLevel = 'Read';
                    orderShareObj.UserOrGroupId =userObj.Id;
                    orderShareList.add(orderShareObj);
                    IF(mapOfOrderfromScope.get(caseownerOrderMap.get(userObj.Id)).RMA_Lines__r.size()>0){
                        For (order_line__c orderLineObj: mapOfOrderfromScope.get(caseownerOrderMap.get(userObj.Id)).RMA_Lines__r) {
                            order_line__share orderLineshareObj = new order_line__share();
                            orderLineshareObj.ParentId = orderLineObj.Id;
                            orderLineshareObj.UserOrGroupId = userObj.Id;
                            orderLineshareObj.AccessLevel = 'Read';
                            orderLineTobeUpdated.add(orderLineshareObj);
                        }
                    }
                }
            }
        }
        For(Group groupObj: [select id, Name from Group where Name like: groupNameMap.values()]) {
            mapOfGroupNameAndId.put(groupObj.Name,groupObj.Id);
        }
        If(groupNameMap.size()>0){
            for(id orderId:groupNameMap.keyset()){
                if(mapOfGroupNameAndId.containskey(groupNameMap.get(orderId).remove('%'))){
                    OrderShare orderShareObj = New OrderShare();
                    orderShareObj.OrderId = orderId;
                    orderShareObj.OrderAccessLevel = 'Read';
                    orderShareObj.UserOrGroupId =mapOfGroupNameAndId.get(groupNameMap.get(orderId).remove('%'));
                    orderShareList.add(orderShareObj);
                }}
        }
        If (caseRecordListToBeUpdated.size() > 0) {
            upsert caseRecordListToBeUpdated;
        }
        If (orderLineTobeUpdated.size() > 0) {
            upsert orderLineTobeUpdated;
        }
        If (orderMapTobeUpdated.size() > 0) {
            update orderMapTobeUpdated.values();
        }
        
        If(orderShareList.size()>0){
            upsert orderShareList;
        }
    }
    public void finish(Database.BatchableContext BC) {
        
    }
    
}