src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return From Customer Name</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (From Customer Name)</relationshipLabel>
    <relationshipName>Return_From_Customer_RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CustomerRef_RMANo__c.field-meta.xml
<CustomField>
    <fullName>CustomerRef_RMANo__c</fullName>
    <inlineHelpText>RMA Number</inlineHelpText>
    <label>CustomerRef/RMANo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Finisar_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Finisar_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The sales manager associated with this RMA Request</inlineHelpText>
    <label>Finisar Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Outbound_RMA_PO__c.field-meta.xml
<CustomField>
    <fullName>Outbound_RMA_PO__c</fullName>
    <inlineHelpText>PO/Reference Number Used for shiping the RMA parts to Customer(i.e. Outbound RMA PO#)</inlineHelpText>
    <label>Outbound RMA PO#</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Requested_Service__c.field-meta.xml
<CustomField>
    <fullName>Requested_Service__c</fullName>
    <inlineHelpText>What is the requested service for this RMA?</inlineHelpText>
    <label>Requested Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failure Verification Only</fullName>
            </value>
            <value>
                <fullName>Failure Analysis</fullName>
            </value>
            <value>
                <fullName>Rework / Upgrade (No FA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Loaner Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Address</description>
    <label>Ship-To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship-To Address)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Ship_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Customer Name</description>
    <label>Ship To Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship To Customer)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/classes/RMACaseDeleteTest.cls
@isTest
public class RMACaseDeleteTest {
    
    @isTest
    public static void updateCase1(){
        String aMsg = '';
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
        User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
        
        Account acc = new Account(name='Account ', 
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
         Id recordid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId();
        insert acc;
        Account acc1 = new Account(ParentId = acc.Id,name='Account1 ', Legacy_Id__c='1234',ShippingCity = 'Test',ShippingCountry ='Test1',ShippingState ='Test3',ShippingPostalCode ='63572',ShippingStreet = 'Test4',
                billingcity='New York test',Site_Use_Code__c ='SHIP_TO',Site_Use_Status__c='Active', billingcountry='USA',Status__c='Active',Type='Reseller',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId());
        
        insert acc1;
        case c= new case(Status='Closed',RecordTypeId = recordid,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                         Ship_To_Address__c = acc1.Id,Outbound_RMA_PO__c='Test',Ship_To_Customer__c=acc.id ,Return_Reason__c='Other');
        insert c;
        Test.startTest();
        try{
            delete c;
        }
        catch(exception e)
        {
            aMsg = e.getMessage();
        }
        
        System.Assert(aMsg.contains('RMA Case cannot be deleted in current status.'));

        Test.stopTest();
        
    }
    public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                                lastName = lName,
                                email = uniqueName + '@test' + orgId + '.org',
                                Username = uniqueName + '@test' + orgId + '.org',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                ProfileId = profId,
                                UserRoleId = roleId);
        return tuser; 
    }   
}