src/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <description>Concatenated value of Oracle Party Id and Oracle Account ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Concatenated value of Oracle Party Id and Oracle Account ID.</inlineHelpText>
    <label>Legacy Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/FA_FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Status__c</fullName>
    <description>FA/FV Status Inprogress and Finalised</description>
    <inlineHelpText>Setting the FV/FA Status to Finalized will lock the record from future editing</inlineHelpText>
    <label>FV/FA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <label>Legacy Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Detail__c/FA_FV_Detail__c.object-meta.xml
<CustomObject>
    <label>FV/FA Detail</label>
    <nameField>
        <displayFormat>FV/FA Analysis - {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FV/FA Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FA_FV_Detail__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FV/FA</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>FV/FA Details</relationshipLabel>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>This is the serial number to which this FA / FV is relevant</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Serial_Number__c</referenceTo>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please select the status for this FA or FV subject to the following guidance:
-  
-  
-</inlineHelpText>
    <label>Detail Status (Junction)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Evaluating</fullName>
                <isActive>false</isActive>
                <label>Evaluating</label>
            </value>
            <value>
                <fullName>Finalizing</fullName>
                <isActive>false</isActive>
                <label>Finalizing</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Ordered_Date__c.field-meta.xml
<CustomField>
    <fullName>Ordered_Date__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;/lightning/cmp/c__FAFVCustomUIQuickAction?c__recordId=&quot;+Id, &apos;FA FV&apos;,&apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FA FV</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Serial_Number__c/Serial_Number__c.object-meta.xml
<CustomObject>
    <description>This is the serial numbers for an RMA request which will be populated from Oracle</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Serial_Number__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <inlineHelpText>This is the RMA order line to which this serial number is related</inlineHelpText>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Serial_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Serial Number Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Serial_Number_Status</valueSetName>
    </valueSet>
</CustomField>

src/classes/FAFVStatusBatchTest.cls
@isTest(seeAllData=false)
private class FAFVStatusBatchTest {
    testMethod static void testBatch(){
        List<Account> accList = TestDataUtilityClass.createAccounts();
        
        order ord = new order(AccountId = accList[0].Id, 
                              Type ='Sales Order',Legacy_Id__c = 'ordleg', 
                              Ordered_Date__c = Date.today(),
                              Status='Draft',
                              EffectiveDate = Date.today(),
                             RecordTypeId = Schema.SObjectType.order.getRecordTypeInfosByName().get('Sales Order').getRecordTypeId());
        insert ord;
        Order_Line__c ordLine = new Order_Line__c(order__c = ord.Id);
        insert ordLine;
        List<Serial_Number__c> serLst = new List<Serial_Number__c>();
        Serial_Number__c serialnum = new Serial_Number__c(Name = 'abcded',Order_Line__c = ordLine.Id, Status__c = 'Closed');
        insert serialnum;
        Serial_Number__c serialnum1 = new Serial_Number__c(Name = 'abcded',Order_Line__c = ordLine.Id, Status__c = 'Closed');
        insert serialnum1;
        FA_FV_Analysis__c fafv= new FA_FV_Analysis__c(Name = 'Fa Analysis',
                                                      FA_FV_Status__c = 'Finalized',
                                                      RecordTypeId =  Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FA Analysis').getRecordTypeId()
                                                     );
        FA_FV_Analysis__c fafv1= new FA_FV_Analysis__c(Name = 'Fv Analysis',
                                                       FA_FV_Status__c = 'Finalized',
                                                      RecordTypeId =  Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FV Analysis').getRecordTypeId()
                                                     );
        insert fafv;
        insert fafv1;
        FA_FV_Detail__c fafvde = new FA_FV_Detail__c(RecordTypeId = Schema.SObjectType.FA_FV_Detail__c.getRecordTypeInfosByName().get('FA/FV Detail').getRecordTypeId(),
                                                    	FA_FV__c = fafv.Id, Serial_Number__c = serialnum.Id,
                                                    Status__c = 'Complete');
        FA_FV_Detail__c fafvde1 = new FA_FV_Detail__c(RecordTypeId = Schema.SObjectType.FA_FV_Detail__c.getRecordTypeInfosByName().get('FA/FV Detail').getRecordTypeId(),
                                                    	FA_FV__c = fafv1.Id, Serial_Number__c = serialnum1.Id,
                                                     Status__c = 'Complete');
        insert fafvde;
        insert fafvde1;
        test.startTest();
        FAFVStatusBatch bat = new FAFVStatusBatch();
        database.executeBatch(bat);
        test.stopTest();
    }
}