src/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Office location that a Sale originated from.</description>
    <inlineHelpText>MID = Dallas
MIE = Europe
MIA = Asia
MIJ = Japan</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>MID</fullName>
            </value>
            <value>
                <fullName>MIE</fullName>
            </value>
            <value>
                <fullName>MIJ</fullName>
            </value>
            <value>
                <fullName>HOUSE (80)</fullName>
            </value>
            <value>
                <fullName>II-VI (Internal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/FV_Report_Region_CC_Address_Mapping__mdt/FV_Report_Region_CC_Address_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>FV Report Region CC Address Mapping</label>
    <pluralLabel>FV Report Region CC Address Mappings</pluralLabel>
</CustomObject>

src/objects/FV_Report_Region_CC_Address_Mapping__mdt/fields/CC_Address__c.field-meta.xml
<CustomField>
    <fullName>CC_Address__c</fullName>
    <description>CC Address separated by ;</description>
    <label>CC Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/FV_Report_Region_CC_Address_Mapping__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BER</fullName>
                <default>true</default>
                <label>BER</label>
            </value>
            <value>
                <fullName>CMI</fullName>
            </value>
            <value>
                <fullName>DAL</fullName>
            </value>
            <value>
                <fullName>EUG</fullName>
            </value>
            <value>
                <fullName>IPH</fullName>
            </value>
            <value>
                <fullName>ISR</fullName>
            </value>
            <value>
                <fullName>PHL</fullName>
            </value>
            <value>
                <fullName>SHG</fullName>
            </value>
            <value>
                <fullName>SNY</fullName>
            </value>
            <value>
                <fullName>SYD</fullName>
            </value>
            <value>
                <fullName>WXI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/SelectedSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SelectedSerialNumber__c</fullName>
    <label>SelectedSerialNumber</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Order_Line__c/fields/Ship_From_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Inventory__c</fullName>
    <inlineHelpText>For RMA Orders, this is the Receiving site. Otherwise, it is the Ship from site.</inlineHelpText>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/classes/CreateFVReport.cls
public with sharing class CreateFVReport {

    public PageReference DownloadFV() {
        return new PageReference('/apex/FVDownload?selectedSerialNumber'+serialId );
    }

    
    public static String orderlineId {get;set;}
    public static String serialId {get;set;}
    public static boolean showAlert { get; set; }
    public static boolean showError { get; set; }
    public static String showMessage { get; set; }
    public static Order_line__c ol { get; set; }
    public CreateFVReport(){
        System.debug('Inside Constructor');
        orderlineId = ApexPages.currentPage().getParameters().get('orderLine');
        serialId =ApexPages.currentPage().getParameters().get('selectedSerialNumber');
        ol = [SELECT Id, Name FROM Order_line__c
              WHERE ID = :orderlineId];
        System.debug(orderlineId);
        System.debug(serialId);
    }
    
    public static void sendFVReportThroughEmail(){
        try{
            List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
            Order_line__c orderLineObj = New Order_Line__c(Id=ApexPages.currentPage().getParameters().get('orderLine'),SelectedSerialNumber__c= ApexPages.currentPage().getParameters().get('selectedSerialNumber'));
            update orderLineObj;
            Order_line__c RSMDetailsObj = [Select Id,RSM__c,RSM__r.Email,Ship_From_Inventory__c 
                                           from Order_line__c 
                                           where id =: orderLineObj.Id];    
            EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'FVReportEmailComponent'];
            FV_Report_Region_CC_Address_Mapping__mdt ccRegionMetaDataRecord;
            IF(RSMDetailsObj.Ship_From_Inventory__c!=Null){
                ccRegionMetaDataRecord =[Select id,masterlabel,region__c,CC_Address__c from FV_Report_Region_CC_Address_Mapping__mdt 
                                         where region__c=: RSMDetailsObj.Ship_From_Inventory__c Limit 1];   
            }
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(et.id);
            mail.setToAddresses(New List < String > {
                RSMDetailsObj.RSM__r.Email
                    });
            mail.setTargetObjectId(RSMDetailsObj.RSM__c);
            mail.setSaveAsActivity(False);
            IF(ccRegionMetaDataRecord.CC_Address__c!=Null){
                mail.setCcAddresses(ccRegionMetaDataRecord.CC_Address__c.split(';'));
            }
            mail.setWhatId(RSMDetailsObj.Id);
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'FinisarCRM'];
            mail.setOrgWideEmailAddressId(owea[0].id);
            mailList.add(mail);
            System.debug('MailList'+mailList );
            Messaging.sendEmail(mailList);
            showMessage ='Email sent Successfully';
            showAlert = True;
        }
        catch(Exception e){
            showMessage = e.getMessage();
            showError = true;
        }
    }
    
    public static pageReference downloadrep(){
        return new pageReference('apex/FVDownload');
    }
}