src/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Office location that a Sale originated from.</description>
    <inlineHelpText>MID = Dallas
MIE = Europe
MIA = Asia
MIJ = Japan</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MIA</fullName>
            </value>
            <value>
                <fullName>MID</fullName>
            </value>
            <value>
                <fullName>MIE</fullName>
            </value>
            <value>
                <fullName>MIJ</fullName>
            </value>
            <value>
                <fullName>HOUSE (80)</fullName>
            </value>
            <value>
                <fullName>II-VI (Internal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CreatedBy.CompanyName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Design_Registration__c.field-meta.xml
<CustomField>
    <fullName>Design_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Design Registration</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/Duplicate_Design_Registration__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Design_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to Identify Duplicate Design Registration 
(Customer Part Numbers of  OLI of Current record are same with Customer Part Numbers of  OLI of Current Lookup)</description>
    <label>Duplicate Design Registration</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Duplicate Design Registration</relationshipLabel>
    <relationshipName>Opptys_DRs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Lost_Cancelled_Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Cancelled_Rejected_Reason__c</fullName>
    <label>Lost/Cancelled/Rejected Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price Request Only</fullName>
            </value>
            <value>
                <fullName>Concept Viability Study Only</fullName>
            </value>
            <value>
                <fullName>Uncompetitive Pricing</fullName>
            </value>
            <value>
                <fullName>Unable to meet Technical Specification</fullName>
            </value>
            <value>
                <fullName>Alternative Technology Chosen</fullName>
            </value>
            <value>
                <fullName>Part not available (NPI)</fullName>
            </value>
            <value>
                <fullName>Long Lead Time</fullName>
            </value>
            <value>
                <fullName>Project Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Project lost by customer</fullName>
            </value>
            <value>
                <fullName>Product Cancelled by II-VI</fullName>
            </value>
            <value>
                <fullName>No evidence of active support of customer ??</fullName>
            </value>
            <value>
                <fullName>Customer demand changed</fullName>
            </value>
            <value>
                <fullName>Customer decided on using a different II-VI PN</fullName>
            </value>
            <value>
                <fullName>Customer did not accept T&apos;s &amp; C&apos;s</fullName>
            </value>
            <value>
                <fullName>Bought from OEM</fullName>
            </value>
            <value>
                <fullName>Bought from competitor (Price)</fullName>
            </value>
            <value>
                <fullName>Bought from competitor (technical)</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Entry Error</fullName>
            </value>
            <value>
                <fullName>Transferred to distributor</fullName>
            </value>
            <value>
                <fullName>Disti was Promoting Competitive solution (for Design Reg)</fullName>
            </value>
            <value>
                <fullName>Disti’s end Customer preferences change (for Design Reg)</fullName>
            </value>
            <value>
                <fullName>Disti’s Lack of inventory and pipeline (for Design Reg)</fullName>
            </value>
            <value>
                <fullName>New Region Assigned</fullName>
            </value>
            <value>
                <fullName>Customer decided on using a different Finisar PN</fullName>
                <isActive>false</isActive>
                <label>Customer decided on using a different Finisar PN</label>
            </value>
            <value>
                <fullName>Disti&apos;s end Customer preferences change (for Design Reg)</fullName>
                <isActive>false</isActive>
                <label>Disti&apos;s end Customer preferences change (for Design Reg)</label>
            </value>
            <value>
                <fullName>Factory Leadtimes, can&apos;t support volume/schedule</fullName>
                <isActive>false</isActive>
                <label>Factory Leadtimes, can&apos;t support volume/schedule</label>
            </value>
            <value>
                <fullName>Factory Leadtimes, can’t support volume/schedule</fullName>
                <isActive>false</isActive>
                <label>Factory Leadtimes, can’t support volume/schedule</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Price</fullName>
                <isActive>false</isActive>
                <label>Price</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Lost_To__c.field-meta.xml
<CustomField>
    <fullName>Lost_To__c</fullName>
    <label>Lost To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acacia</fullName>
            </value>
            <value>
                <fullName>Accelink</fullName>
            </value>
            <value>
                <fullName>AOI</fullName>
            </value>
            <value>
                <fullName>CoAdna*</fullName>
            </value>
            <value>
                <fullName>FOIT (Foxconn Optical Interconnect Technology)</fullName>
            </value>
            <value>
                <fullName>FOC (Fujitsu Optical Components)</fullName>
            </value>
            <value>
                <fullName>Hisense</fullName>
            </value>
            <value>
                <fullName>II-VI</fullName>
            </value>
            <value>
                <fullName>Innolight</fullName>
            </value>
            <value>
                <fullName>JDSU*</fullName>
            </value>
            <value>
                <fullName>Lumentum</fullName>
            </value>
            <value>
                <fullName>NeoPhotonics</fullName>
            </value>
            <value>
                <fullName>Nistica*</fullName>
            </value>
            <value>
                <fullName>Oclaro</fullName>
            </value>
            <value>
                <fullName>Source</fullName>
            </value>
            <value>
                <fullName>Sumitomo</fullName>
            </value>
            <value>
                <fullName>Mellanox</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Acacia</fullName>
                <isActive>false</isActive>
                <label>Acacia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Next_12_Months_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Next_12_Months_Revenue__c</fullName>
    <inlineHelpText>Next 12 Months Revenue from Open Opportunities</inlineHelpText>
    <label>Next 12 Months Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Opportunity/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <displayFormat>Opp-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Number</label>
    <type>AutoNumber</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAS - WESTERN</fullName>
            </value>
            <value>
                <fullName>AMERICAS - EASTERN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Rep_Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Rep_Firm_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Firm Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Rep Firm value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Sales Rep Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>RepFirmAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Saleschannel value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Sales Channel)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Sum_of_SAM__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_SAM__c</fullName>
    <label>Sum of SAM</label>
    <summarizedField>OpportunityLineItem.SAM__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Opportunity/fields/SumofASP__c.field-meta.xml
<CustomField>
    <fullName>SumofASP__c</fullName>
    <label>SumofASP</label>
    <summarizedField>OpportunityLineItem.UnitPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/classes/OpportunityEmailCustomComponent.cls
/*
  Created By Rajavardhan 
  To Query Duplicate  Opportunities Which needs to be displayed in DR Submission CMP 
  To Query Opportunity Fields to be displayed in Loaner Approval Email Template 
 
*/

public class OpportunityEmailCustomComponent {

    
    public Opportunity currOpportunity{get;set;}
    public Id OpportunityId {get;set;}
    public String getInstanceurl()
    {
        return System.url.getSalesforceBaseUrl().toExternalForm();
    }
    public Opportunity getOpportunityRecord()
    {
        String query ='SELECT Id,Number__c,NextStep,Next_12_Months_Revenue__c,Lost_Cancelled_Rejected_Reason__c,Lost_To__c,StageName,Project_Name__c,RSM__r.Name,Type,Rep_Firm_Name__r.Name,Market_Segment__c,Sales_Channel__r.Name,Design_Registration__c,CreatedBy.Name,Region__c,Company__c,Account.Name FROM Opportunity where Id= :OpportunityId';
        Opportunity Opp =Database.query(query);
        return opp;
        
    }
    public List<Opportunity> getduplicateOpportunities()
    {
        List<Opportunity> duplicateOpportunities;
        if(currOpportunity != null){
         duplicateOpportunities=[SELECT Id,Name,Duplicate_Design_Registration__c,Number__c,Project_Name__c,Company__c,Sales_Channel__r.Name,Sales_Channel__c,TotalOpportunityQuantity,SumofASP__c,Sum_of_SAM__c FROM Opportunity WHERE Duplicate_Design_Registration__c =:currOpportunity.Id and Duplicate_Design_Registration__c != null ];
        
            return duplicateOpportunities;
        }
        else
        return duplicateOpportunities;
    }
}