src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/OpportunityTeamMemberHelper_test.cls
@istest(seeAllData = false)
public class OpportunityTeamMemberHelper_test{
    @testSetup static void testData() {
        List<Account> accLst = new List<Account>();
        List<Opportunity> oppLst = new List<Opportunity>();
        Account acct = new Account(Name= 'APPLE COMPUTER INC', Status__c='Active',
                                   recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acct;
        Account acc1 = new Account(Name= 'STRATEGIC SALES INC', Status__c='Active',
                                   recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acc1;
        Opportunity opp = New Opportunity(Name = acct.Name+' Opp',RSM__c ='0051N000007GPjaQAG',Project_Name__c = 'test',
                                          StageName = 'Open - Discussion', AccountId = acct.Id, CloseDate = date.today().addDays(365));
        insert opp;
        Opportunity opp1 = New Opportunity(Name = acct.Name+' Opp',RSM__c ='0051N000007GPjTQAW',Project_Name__c = 'test',
                                          StageName = 'Open - Discussion', AccountId = acc1.Id, CloseDate = date.today().addDays(365));
        insert opp1;
    }
    @istest
    static void testAddMember(){
        system.debug('opp list '+[select id from account]);
        List<Opportunity> opplst =[Select Id,RSM__c from Opportunity];
        test.startTest();
        OpportunityTeamMemberHelper.addRsmTeamMembers(opplst);
        test.stopTest();
    }
}