src/objects/Account/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RSM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Status_Approval__c.field-meta.xml
<CustomField>
    <fullName>Status_Approval__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loaner_Line_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/CPN_Description__c.field-meta.xml
<CustomField>
    <fullName>CPN_Description__c</fullName>
    <label>CPN/Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Est_Annual_Qty__c.field-meta.xml
<CustomField>
    <fullName>Est_Annual_Qty__c</fullName>
    <label>Est Annual Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Generic_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Generic_Product_Family__c</fullName>
    <label>Generic Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <isActive>false</isActive>
                <label>Not Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <formula>SAM__c * SOM__c</formula>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Price_100_999_column_price__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Price_100_999_column_price__c</fullName>
    <inlineHelpText>Fill out if system does not auto-populate.</inlineHelpText>
    <label>Loaner Price (100-999 column price)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Qty__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Qty__c</fullName>
    <label>Loaner Qty</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Return_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Return_Carrier__c</fullName>
    <label>Loaner Return Carrier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Manual_Return_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Manual_Return_Due_Date__c</fullName>
    <inlineHelpText>User Can Enter Date to return Loaner Item</inlineHelpText>
    <label>Manual Return Due Date</label>
    <type>Date</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <label>Part Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Customized</fullName>
            </value>
            <value>
                <fullName>Do not transfer</fullName>
            </value>
            <value>
                <fullName>Cannot be converted</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/fields/Part_Type_Notes__c.field-meta.xml
<CustomField>
    <fullName>Part_Type_Notes__c</fullName>
    <inlineHelpText>* Only Betty can edit this field.</inlineHelpText>
    <label>Part Type Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected, Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>IF(RecordType.DeveloperName=&apos;Extension_Item&apos;,TEXT(Loaner_Line__r.Product__r.Product_Family__c) ,TEXT(Product__r.Product_Family__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Production_Price_ASP__c.field-meta.xml
<CustomField>
    <fullName>Production_Price_ASP__c</fullName>
    <label>Production Price (ASP)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SAM__c.field-meta.xml
<CustomField>
    <fullName>SAM__c</fullName>
    <formula>Production_Price_ASP__c * Est_Annual_Qty__c</formula>
    <label>SAM($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SOM__c.field-meta.xml
<CustomField>
    <fullName>SOM__c</fullName>
    <inlineHelpText>Share of Market (%)</inlineHelpText>
    <label>SOM(%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/User_Notes__c.field-meta.xml
<CustomField>
    <fullName>User_Notes__c</fullName>
    <label>User Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner Line</label>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Order Lines (Loaner Line)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <description>Part type information pulled from Pointman via integration.</description>
    <label>Part Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <description>Lookup field to User to Point SVP for user role VP</description>
    <label>SVP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <description>Lookup field to User to point to VP for User role RSM</description>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>VP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/globalValueSets/Loaner_Line_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Sales Order</fullName>
    </customValue>
    <masterLabel>Loaner Line Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OCM</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OIG</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/LineItemController.cls
public class LineItemController {
    
    @AuraEnabled
    public static List<Loaner_Line__c> getLoanerLineItem(Id recordId){ 
        Id devRecordTypeId = Schema.SObjectType.Loaner_Line__c.getRecordTypeInfosByName().get('Loaner Item').getRecordTypeId();
        Id devReadRecordTypeId = Schema.SObjectType.Loaner_Line__c.getRecordTypeInfosByName().get('Loaner Item Pending Sales Record Type').getRecordTypeId();
        Id devReadOnlyRecordTypeId = Schema.SObjectType.Loaner_Line__c.getRecordTypeInfosByName().get('Loaner Item Read Only').getRecordTypeId();
        List<Loaner_Line__c> lineItemList =[Select id,Name,Loaner__c,Loaner__r.Status_Approval__c,Product__c,Product__r.Name,Product__r.Id,Line_Total__c,Loaner_Price_100_999_column_price__c,Production_Price_ASP__c,Est_Annual_Qty__c,
                                            SOM__c,SAM__c,Generic_Product_Family__c,Line_Status__c,Loaner_Qty__c,RSM__c,VP__c,SVP__c,CPN_Description__c,Other_Description__c,Loaner_Return_Carrier__c,
                                            User_Notes__c,Part_Type_Notes__c,Manual_Return_Due_Date__c,Part_Type__c,Admin_Status__c,Manual_Update__c,Error_Message__c,Integration_Status__c,Initial_Error_Message__c,Order_Line__c,Process_Date__c,Loaner_Ship_From__c,Admin_Extn_Reason__c,Number_of_Extensions__c,Total_Extended_Days__c,
                                            Extend_Line__c,SO_Line_Number__c,Marketing_P_N__c,Loaner_Total__c,recordtypeid,Recordtype.Name,Loaner_Return_Ship_Date__c,Loaner_Return_Tracking_Number__c,RSM__r.name,VP__r.name,SVP__r.name,order_line__r.name 
                                            from Loaner_Line__c where Loaner__c =:recordId and (recordtypeid =:devRecordTypeId OR recordtypeid =:devReadRecordTypeId OR recordtypeid =:devReadOnlyRecordTypeId )]; 
        if(lineItemList.size()>0) {
            return lineItemList;
        }    
        return null;
    }
    
    @AuraEnabled
    public static  Map<String,String> getRecordType(Id recordId){ 
        Map<String,String> lineItemLableValue = new Map<String,String>();
        Loaner_Line__c lc = [select recordtype.name,Product__c,Product__r.name from Loaner_Line__c where id=:recordId];
        lineItemLableValue.put('RecordType',lc.recordtype.name);
        lineItemLableValue.put('ProductName',lc.Product__r.name);
        System.debug('recordtype=='+lineItemLableValue);
        return lineItemLableValue;
    } 
    
    @AuraEnabled
    public static  String getLoanerStatus(Id recordId){ 
        loaner__c lc = [select status_approval__c from loaner__c where id=:recordId];
        return lc.status_approval__c;
    }
    
    @AuraEnabled
    public static Boolean getUserPermission(){ 
        Boolean hasPermission = FeatureManagement.checkPermission('Loaner_Line_Permission');
        system.debug('hasPermission----'+hasPermission);
        return hasPermission;
    }
    
    
    @AuraEnabled
    public static WrapperClass saveLoanerLineItem(List<Loaner_Line__c> ListLineItem, String recordId){
        system.debug('ListLineItem=='+ListLineItem);
        WrapperClass loanerWrapper = new WrapperClass();
        List<String> wssProducts = new List<String>();
        List<String> nonWssProducts = new List<String>();
        List<Id> ProductIds = new List<Id>();
        for(Loaner_Line__c line : ListLineItem){
            //ProductIds.add(line.Product__c);//20200805_ramprakash: Commented to fix the product selection issue
            ProductIds.add(line.Product__c);//20200805_ramprakash: Added to fix the product selection issue
        }
        system.debug('ProductIds'+ProductIds);
        for(Product2 prd : [SELECT Id, BU_Code__c, Product_Family__c 
                            FROM Product2 
                            WHERE Id IN :ProductIds]){
                                if(prd.BU_Code__c == '0040' && 
                                   prd.Product_Family__c != 'WSS-OIG' &&
                                   prd.Product_Family__c != 'WSS-OCM' ){
                                       wssProducts.add(prd.Id); 
                                   }  else {
                                       nonWssProducts.add(prd.Id);
                                   }
                            }
        if(!wssProducts.isEmpty() && !nonWssProducts.isEmpty()){
            loanerWrapper.errorMessage = 'WSS & Non-WSS Items cannot be added on the same Loaner Request.';
            return loanerWrapper;
        }
        system.debug('wssProducts@@' + wssProducts);
         system.debug('Role.oducts@@' + [ SELECT id, RSM_PLM_Finisar__c,Project_Name__c FROM Loaner__c WHERE Id = : recordId]);
        String rsmRole = [SELECT id, RSM_PLM_Finisar__r.UserRole.Name FROM Loaner__c WHERE Id = : recordId].RSM_PLM_Finisar__r.UserRole.Name;
        system.debug('rsmrole@@' + rsmRole);
        if(!rsmRole.contains('WSS') && !wssProducts.isEmpty()){
            loanerWrapper.errorMessage = 'Header RSM should be WSS User';
            return loanerWrapper;
        }
        Id devRecordTypeId = Schema.SObjectType.Loaner_Line__c.getRecordTypeInfosByName().get('Loaner Item').getRecordTypeId();
        List<Loaner_Line__c> insertLineItem = new List<Loaner_Line__c>();
        for(Loaner_Line__c lItem :ListLineItem){
            Loaner_Line__c newlItem = new Loaner_Line__c();
            newlItem=lItem;
            if( newlItem.Loaner__c == null){
                newlItem.Loaner__c = recordId;
                newlItem.RecordTypeId=devRecordTypeId;
                
            }
            if(newlItem.Line_Status__c == null ||newlItem.Line_Status__c == ''){
                newlItem.Line_Status__c ='Draft';
                
            }    
            newlItem.Product__c =lItem.Product__r.Id;//20200805_ramprakash: Added to fix the product selection issue
            newlItem.Product__r = null;
            //newlItem.Product__c = lItem.Product__c; //20200805_ramprakash: Commented to fix the product selection issue
            insertLineItem.add(newlItem);
        }
        if(insertLineItem.size()>0) {
            try{
                upsert insertLineItem;
                loanerWrapper.loanerItemList=insertLineItem;
            }catch(Exception e) {
                String str = e.getMessage();
                String finalString = str.substringAfter('error:');
                loanerWrapper.errorMessage = finalString;
                
            } 
        }
        System.debug('loanerWrapper1===='+loanerWrapper);
        return loanerWrapper;
    }
    
    @AuraEnabled    
    public static String  sendRequesttoInformatica(String loanerid)
    {   
        String callOutError ='';
        //Loaner__c lRec =[select name from Loaner__c where id=:loanerid];
        try{
            servicesInformaticaComRtPrcCaiLoan LoanerRequestInf = new servicesInformaticaComRtPrcCaiLoan();
            servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_main_Service Loanerservicesend = new  servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_main_Service();
            servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_mainResponse_element response =Loanerservicesend.Prc_cai_loaner_main(loanerid); 
            if(response.error_message != null){
                return response.error_message;
            }
            
            String validation ='';
            System.debug('validation before'+validation);
            validation = validateRecords(loanerid);
            System.debug('validation after'+validation);
            if(validation!=''){
                return validation;
            }
            
        }
        catch(Exception e)
        {
            System.debug('errprmessage=='+e.getMessage());
            callOutError = e.getMessage();
        }
        
        if(callOutError != null || callOutError !=''){
            return callOutError;
        }
        return '';
        
    }
    @AuraEnabled
    public static String validateRecords(String recordId){
        sobject loanerObj = RecordApprovalDao.getHeaderRecord(recordId);
          system.debug('loanerObj@@@ ' + loanerObj.getSObjects('Loaner_Lines__r'));
          if(loanerObj.getSObjects('Loaner_Lines__r')!=Null){
            for(sobject sobj:loanerObj.getSObjects('Loaner_Lines__r')){
                For(String fieldName :CommonConstants.LoanerLineRequiredFields){
                    system.debug('fieldName====='+fieldName);
                    If(sobj.get(fieldName)==Null){
                        system.debug('sobj.get(fieldName)====='+sobj.get(fieldName));
                        String fieldlabel = CommonConstants.LoanerLineRequiredFieldsLable.get(fieldName);
                        system.debug('fieldlabel====='+fieldlabel);
                        return ' Required Field '+fieldlabel+ ' Must be Filled For Line Item '+sobj.get('Name');
                    } 
                }
            }
        }
        for(String fieldName : CommonConstants.LoanerRequiredFields){
            If(loanerObj.get(fieldName)==Null){
                String LoanerOpportunityType =(String) loanerObj.get('Opportunity_Type__c');
                if(fieldName.equalsIgnoreCase('Opportunity__c') && LoanerOpportunityType.equalsIgnoreCase('New Opportunity'))
                {
                    String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                    return ' Required Field '+fieldlabel+ ' Must be Filled As Opportunity Type is ' +loanerObj.get('Opportunity_Type__c');
                }
                else if(!fieldName.equalsIgnoreCase('Opportunity__c'))
                { 
                    String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                    return ' Required Field '+fieldlabel+ ' Must be Filled';
                }
            }
        }
      
      
        return '';
    }
    
    @AuraEnabled
    public static String validateRecordsONSaveAndClose(String recordId){
        sobject loanerObj = RecordApprovalDao.getHeaderRecord(recordId);
          
        if(loanerObj.getSObjects('Loaner_Lines__r')!=Null){
            for(sobject sobj:loanerObj.getSObjects('Loaner_Lines__r')){
                For(String fieldName :CommonConstants.LoanerLineRequiredFields){
                    system.debug('fieldName====='+fieldName);
                    If(sobj.get(fieldName)==Null && fieldName !='Loaner_Price_100_999_column_price__c'){
                        system.debug('sobj.get(fieldName)====='+sobj.get(fieldName));
                        String fieldlabel = CommonConstants.LoanerLineRequiredFieldsLable.get(fieldName);
                        system.debug('fieldlabel====='+fieldlabel);
                        return ' Required Field '+fieldlabel+ ' Must be Filled For Line Item '+sobj.get('Name');
                    } 
                }
            }
        }
        for(String fieldName : CommonConstants.LoanerRequiredFields){
            If(loanerObj.get(fieldName)==Null){
                String LoanerOpportunityType =(String) loanerObj.get('Opportunity_Type__c');
                if(fieldName.equalsIgnoreCase('Opportunity__c') && LoanerOpportunityType.equalsIgnoreCase('New Opportunity'))
                {
                    String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                    return ' Required Field '+fieldlabel+ ' Must be Filled As Opportunity Type is ' +loanerObj.get('Opportunity_Type__c');
                }
                else if(!fieldName.equalsIgnoreCase('Opportunity__c'))
                { 
                    String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                    return ' Required Field '+fieldlabel+ ' Must be Filled';
                }
            }
        }
      
        return '';
    }
    public class WrapperClass {
        @AuraEnabled public List<Loaner_Line__c> loanerItemList;
        @AuraEnabled public String errorMessage;
    }
    
    @AuraEnabled
    public static String deleteLoanerLineItem(Loaner_Line__c lonerLine){ 
        system.debug('lonerLine'+lonerLine);
        String messageRec ='';
        try {
            delete lonerLine;
            messageRec ='Record deleted Succesfully';
        }catch (Exception e){
            messageRec = e.getMessage();
        }
        system.debug('messageRec=='+messageRec);
        return messageRec;
    }
}