src/objects/Account/fields/Sales_Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel_Code__c</fullName>
    <label>Sales Channel Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Pricing_Effective_By__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Effective_By__c</fullName>
    <label>Pricing Effective By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Date</fullName>
            </value>
            <value>
                <fullName>Ship Date</fullName>
                <default>true</default>
                <label>Ship Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Pricing_Effective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Effective_Start_Date__c</fullName>
    <inlineHelpText>This field is only relevant for Blanket Price Agreement quotes. Once the quote lines are approved, the customer price list will be updated with the new price using this Pricing Effective Start Date. This has to be today&apos;s date or a future date.</inlineHelpText>
    <label>Pricing Effective Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Quote/fields/PrimarySalesperson__c.field-meta.xml
<CustomField>
    <fullName>PrimarySalesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Salesperson</description>
    <inlineHelpText>Select the Finisar Regional Sales Manager (RSM) who should be approving this quote.</inlineHelpText>
    <label>Primary Salesperson</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>YLee</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>cleow</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>KFalta</value>
        </filterItems>
        <filterItems>
            <field>User.Alias</field>
            <operation>equals</operation>
            <value>MRobin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/S_D_End_Date__c.field-meta.xml
<CustomField>
    <fullName>S_D_End_Date__c</fullName>
    <label>S&amp;D End Date</label>
    <type>Date</type>
</CustomField>

src/objects/Quote/fields/S_D_End_Date_Reason__c.field-meta.xml
<CustomField>
    <fullName>S_D_End_Date_Reason__c</fullName>
    <label>S&amp;D End Date Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/S_D_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>S_D_Start_Date__c</fullName>
    <label>S&amp;D Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Quote/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Sales Channel)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Sales_Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel_Code__c</fullName>
    <formula>Sales_Channel__r.Sales_Channel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Channel Code</label>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Ship_Debit__c.field-meta.xml
<CustomField>
    <fullName>Ship_Debit__c</fullName>
    <externalId>true</externalId>
    <label>Ship &amp; Debit #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/Type_of_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Pricing__c</fullName>
    <inlineHelpText>Blanket Price Agreement creates/updates customer price list. Dist Quote generates S&amp;D# for Distributor to ship standard parts to customer at lower price than current Disti Cost. Fixed-One Time Order does not update customer price list or generate S&amp;D#.</inlineHelpText>
    <label>Type of Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blanket Price Agreement</fullName>
            </value>
            <value>
                <fullName>Dist Quote</fullName>
            </value>
            <value>
                <fullName>Fixed - One Time Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/VAR_SI__c.field-meta.xml
<CustomField>
    <fullName>VAR_SI__c</fullName>
    <label>VAR/SI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VAR_SI</valueSetName>
    </valueSet>
</CustomField>

src/objects/Quote/fields/VAR_SI_Disti_EC__c.field-meta.xml
<CustomField>
    <fullName>VAR_SI_Disti_EC__c</fullName>
    <label>VAR/SI Disti/EC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Disti_Margin__c.field-meta.xml
<CustomField>
    <fullName>Disti_Margin__c</fullName>
    <formula>( Disti_Resale_Price__c  -  Target_Price__c ) /  Disti_Resale_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Disti Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/objects/Quote_Item__c/fields/Disti_Resale_Price__c.field-meta.xml
<CustomField>
    <fullName>Disti_Resale_Price__c</fullName>
    <label>Disti Resale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Lost - Delivery</fullName>
            </value>
            <value>
                <fullName>Lost - Price</fullName>
            </value>
            <value>
                <fullName>Lost - Technical</fullName>
            </value>
            <value>
                <fullName>One Time Order Processed</fullName>
            </value>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Canceled</fullName>
            </value>
            <value>
                <fullName>Project Cancelled</fullName>
            </value>
            <value>
                <fullName>Approval Cycle Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/Marketing_PN__c.field-meta.xml
<CustomField>
    <fullName>Marketing_PN__c</fullName>
    <formula>Product__r.Marketing_P_N__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketing PN</label>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/Sales_Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel_Code__c</fullName>
    <formula>Quote__r.Sales_Channel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Channel Code</label>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/globalValueSets/VAR_SI.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>9 to 5 computer</fullName>
    </customValue>
    <customValue>
        <fullName>AAJ Networks</fullName>
    </customValue>
    <customValue>
        <fullName>Abba</fullName>
    </customValue>
    <customValue>
        <fullName>ABCOM</fullName>
    </customValue>
    <customValue>
        <fullName>ACE Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Advantec</fullName>
    </customValue>
    <customValue>
        <fullName>Aeon Computing</fullName>
    </customValue>
    <customValue>
        <fullName>AFL Hyperscale</fullName>
    </customValue>
    <customValue>
        <fullName>Agile IT</fullName>
    </customValue>
    <customValue>
        <fullName>Allied Business Machines</fullName>
    </customValue>
    <customValue>
        <fullName>All Solutions Inc</fullName>
    </customValue>
    <customValue>
        <fullName>Alpha Micro Components USA</fullName>
    </customValue>
    <customValue>
        <fullName>Amax</fullName>
    </customValue>
    <customValue>
        <fullName>AmiStar</fullName>
    </customValue>
    <customValue>
        <fullName>Anixter</fullName>
    </customValue>
    <customValue>
        <fullName>Apollo Informations Sys Group</fullName>
    </customValue>
    <customValue>
        <fullName>Applied Computer (ACS)</fullName>
    </customValue>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>BahFed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar None Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing Bright Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>BlackLake Security</fullName>
    </customValue>
    <customValue>
        <fullName>Broadnet Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>BUR-TECH SOLUTIONS LLC</fullName>
    </customValue>
    <customValue>
        <fullName>Burwood Group</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridge Computer</fullName>
    </customValue>
    <customValue>
        <fullName>Cavar SA</fullName>
    </customValue>
    <customValue>
        <fullName>CDW</fullName>
    </customValue>
    <customValue>
        <fullName>Cirrascale</fullName>
    </customValue>
    <customValue>
        <fullName>ClearShark</fullName>
    </customValue>
    <masterLabel>VAR/SI</masterLabel>
</GlobalValueSet>

src/classes/QuoteTemplateController.cls
public with sharing class QuoteTemplateController {
    public Quote qteRec {get;set;}
    public QuoteTemplateController() {
        String qId = ApexPages.currentPage().getParameters().get('Id');
        system.debug('qid'+qId);
        qteRec = [SELECT id, name, Account__c, Account.name,Account.AccountNumber,Status,Type_of_Pricing__c,
                  ExpirationDate,Pricing_Effective_By__c, PrimarySalesperson__c,Pricing_Effective_Start_Date__c,
                  Ship_Debit__c , S_D_Start_Date__c, S_D_End_Date__c,S_D_End_Date_Reason__c, VAR_SI__c,
                  VAR_SI_Disti_EC__c ,Sales_Channel__c, Sales_Channel_Code__c ,
                  (Select id,Name, Product__c,Marketing_PN__c,Line_Status__c,Target_Price__c,Disti_Resale_Price__c,Quantity__c,
                   Disti_Margin__c from Quote_Items__r) from Quote Where Id =:qId];
    }
    
    @AuraEnabled
    public static Quote getQuoteDetails(String recId){
        return [SELECT id, name, Account__c, Account.name,Account.AccountNumber,Status,Type_of_Pricing__c,
                ExpirationDate,Pricing_Effective_By__c, PrimarySalesperson__c,Pricing_Effective_Start_Date__c,
                Ship_Debit__c , S_D_Start_Date__c, S_D_End_Date__c,S_D_End_Date_Reason__c, VAR_SI__c,
                VAR_SI_Disti_EC__c ,Sales_Channel__c, Sales_Channel_Code__c ,
                (Select id,Name, Product__c,Marketing_PN__c,Line_Status__c,Target_Price__c,Disti_Resale_Price__c,Quantity__c,
                 Disti_Margin__c from Quote_Items__r) from Quote Where Id =:recId];
    }
}