src/objects/Account/fields/SAP_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_ID__c</fullName>
    <description>Unique SAP Customer ID used for interface</description>
    <externalId>true</externalId>
    <label>SAP Customer ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Collect_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Collect_Account_Number__c</fullName>
    <description>Customer shipping account number to bill.</description>
    <inlineHelpText>Customer shipping account number to bill.</inlineHelpText>
    <label>Collect Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Do_not_partial__c.field-meta.xml
<CustomField>
    <fullName>Do_not_partial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not partial</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/Drop_Ship__c.field-meta.xml
<CustomField>
    <fullName>Drop_Ship__c</fullName>
    <inlineHelpText>Drop Ship information to be merged onto NAPO</inlineHelpText>
    <label>Drop Ship</label>
    <type>TextArea</type>
</CustomField>

src/objects/Opportunity/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oppty/DRs (End Customer Lookup)</relationshipLabel>
    <relationshipName>Oppty_DRs1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/IncoTerms__c.field-meta.xml
<CustomField>
    <fullName>IncoTerms__c</fullName>
    <label>IncoTerms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DAT</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>DEQ</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Named_Place__c.field-meta.xml
<CustomField>
    <fullName>Named_Place__c</fullName>
    <label>Named Place</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Partials_Permitted__c.field-meta.xml
<CustomField>
    <fullName>Partials_Permitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partials Permitted</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/PBCR__c.field-meta.xml
<CustomField>
    <fullName>PBCR__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Partial By Complete Release</inlineHelpText>
    <label>PBCR</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>Customer purchase order number</description>
    <inlineHelpText>Enter the customer&apos;s PO number, if given.</inlineHelpText>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary (Shipping) Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Received_By__c.field-meta.xml
<CustomField>
    <fullName>Received_By__c</fullName>
    <label>Received By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Customer Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PrePaid</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FedEx Priority 1</fullName>
            </value>
            <value>
                <fullName>FedEx Priority 2</fullName>
            </value>
            <value>
                <fullName>FedEx SAT First</fullName>
            </value>
            <value>
                <fullName>FedEx SAT Priority</fullName>
            </value>
            <value>
                <fullName>FedEx Standard</fullName>
            </value>
            <value>
                <fullName>FedEx 2 Day AM</fullName>
            </value>
            <value>
                <fullName>FedEx 2 Day</fullName>
            </value>
            <value>
                <fullName>FedEx Express Saver</fullName>
            </value>
            <value>
                <fullName>FedEx Ground</fullName>
            </value>
            <value>
                <fullName>FedEx Intl Economy</fullName>
            </value>
            <value>
                <fullName>FedEx Intl Priority</fullName>
            </value>
            <value>
                <fullName>Hand Carry</fullName>
            </value>
            <value>
                <fullName>Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>LTL Freight Service</fullName>
            </value>
            <value>
                <fullName>UPS Next Day 8:30AM</fullName>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
            </value>
            <value>
                <fullName>UPS Next Day Saver</fullName>
            </value>
            <value>
                <fullName>UPS SAT AM</fullName>
            </value>
            <value>
                <fullName>UPS SAT</fullName>
            </value>
            <value>
                <fullName>UPS 2 Day Air AM</fullName>
            </value>
            <value>
                <fullName>UPS 2 Day Air</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
            </value>
            <value>
                <fullName>UPS Intl Expedited</fullName>
            </value>
            <value>
                <fullName>UPS Intl Express</fullName>
            </value>
            <value>
                <fullName>UPS Intl Saver</fullName>
            </value>
            <value>
                <fullName>UPS Intl Standard</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>USPS</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Shipping_Comments__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Comments__c</fullName>
    <inlineHelpText>Use the following codes first, before adding additional Shipping info
PP = Partials Permitted
DNP = Do NOT Partial
DNSE = Do NOT Ship Early
PBCR = Partials By Complete Release
ALSO LIST PAYMENT TERMS FOR ACCOUNTING / SHIPPING</inlineHelpText>
    <label>Shipping Comments</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <inlineHelpText>Special instructions to be merged onto NAPO.</inlineHelpText>
    <label>Special Instructions</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Order/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <formula>Order__r.End_Customer__c</formula>
    <label>End Customer</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order_Product_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Sequence_Number__c</fullName>
    <label>Order Product Sequence Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Order_Line__c/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/classes/SalesOrderUtilClassNew.cls
public with sharing class SalesOrderUtilClassNew {
    
    //This method returns a comma seperated string of all the standard fields of the object
    public static String getObjectFields(String objectName) {
        String sQuery = '';
        Map<String, Schema.SObjectField> objectFieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();
        for(Schema.SObjectField column: objectFieldMap.values()) {
            sQuery += column+', ';
        }
        sQuery = sQuery.substring(0, sQuery.length()-2);
        sQuery += ' ';
        return sQuery;
    }
    
    public static Order  getOrder(String sOrderId) {
        String sQuery = 'SELECT ';
        sQuery += 'Opportunity.Do_not_partial__c,Opportunity.Drop_Ship__c,Opportunity.End_Customer__c,Opportunity.End_Customer__r.Name,';
        sQuery += 'Opportunity.Partials_Permitted__c,Opportunity.PBCR__c,Opportunity.PO_Number__c,Opportunity.Shipping_Carrier__c,';
        sQuery += 'Opportunity.Shipping_Comments__c,Opportunity.Special_Instructions__c,Opportunity.Description,';
        sQuery += 'BillToContact.Phone,BillToContact.Name,Account.SAP_Customer_ID__c,Primary_Shipping_Contact__r.Name,Primary_Shipping_Contact__r.Phone,';
        sQuery += 'Opportunity.End_Customer__r.SAP_Customer_ID__c,Opportunity.Received_By__c,';
        sQuery += 'Opportunity.Ship_Method__c,Opportunity.Collect_Account_Number__c,Opportunity.IncoTerms__c,Opportunity.Named_Place__c,';
        sQuery += getObjectFields('Order');
        sQuery += ' FROM Order ';
        sQuery += ' WHERE Id =: sOrderId';
        sQuery = String.escapeSingleQuotes(sQuery);
        Order orderObject = Database.query(sQuery);
        return orderObject;
    }
    
    public static list<Order_Line__c>  getOrderProducts(String sOrderId) {
        String sQuery = 'SELECT Product2.Name, '+getObjectFields('Order_Line__c') +' FROM Order_Line__c WHERE OrderId =: sOrderId ORDER BY Order_Product_Sequence_Number__c ASC';
        sQuery = String.escapeSingleQuotes(sQuery);
        list<Order_Line__c> listOrderProduct = Database.query(sQuery);
        return listOrderProduct;
    }
    /**
* This method convertDateToString
* @return dateString
*/
    public static String convertDateToString(Date dateValue) {
        String dateString = '';
        if (dateValue != null) {
            Datetime dt = datetime.newInstance(dateValue.year(), dateValue.month(),dateValue.day());
            dateString = dt.format('yyyy-MM-dd'); //formatting complies with SOQL
        }
        return dateString; 
    }
    public static User getUser(String sOwnerId) {
        User user = [select email,CommunityNickname from User where id =:sOwnerId];
        return user;
    }
}