src/objects/Account/fields/Site_Use_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Code__c</fullName>
    <label>Site Use Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Site_Use_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Use_Status__c</fullName>
    <label>Site Use Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site &amp; Address details of an Account</description>
    <label>Site</label>
</RecordType>

src/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Return From Customer Name</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (From Customer Name)</relationshipLabel>
    <relationshipName>Return_From_Customer_RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CustomerRef_RMANo__c.field-meta.xml
<CustomField>
    <fullName>CustomerRef_RMANo__c</fullName>
    <inlineHelpText>RMA Number</inlineHelpText>
    <label>CustomerRef/RMANo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Finisar_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Finisar_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The sales manager associated with this RMA Request</inlineHelpText>
    <label>Finisar Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Outbound_RMA_PO__c.field-meta.xml
<CustomField>
    <fullName>Outbound_RMA_PO__c</fullName>
    <inlineHelpText>PO/Reference Number Used for shiping the RMA parts to Customer(i.e. Outbound RMA PO#)</inlineHelpText>
    <label>Outbound RMA PO#</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Requested_Service__c.field-meta.xml
<CustomField>
    <fullName>Requested_Service__c</fullName>
    <inlineHelpText>What is the requested service for this RMA?</inlineHelpText>
    <label>Requested Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failure Verification Only</fullName>
            </value>
            <value>
                <fullName>Failure Analysis</fullName>
            </value>
            <value>
                <fullName>Rework / Upgrade (No FA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Loaner Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Address</description>
    <label>Ship-To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship-To Address)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Ship_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship-To Customer Name</description>
    <label>Ship To Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3)) AND 4</booleanFilter>
        <errorMessage>Value does not exist or does not match any Customer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases / RMA Requests (Ship To Customer)</relationshipLabel>
    <relationshipName>Cases_RMA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/RMA_Request_Line__c/RMA_Request_Line__c.object-meta.xml
<CustomObject>
    <label>RMA Request Line</label>
    <nameField>
        <label>Customer Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMA_Request_Line__c/fields/Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Org_Code__c</fullName>
    <inlineHelpText>The Org Code</inlineHelpText>
    <label>Org Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/PO_Price__c.field-meta.xml
<CustomField>
    <fullName>PO_Price__c</fullName>
    <label>PO Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original PO</fullName>
                <default>true</default>
                <label>Original PO</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <inlineHelpText>Why is the part being returned</inlineHelpText>
    <label>Return Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Failure</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Rework/Re-test</fullName>
            </value>
            <value>
                <fullName>Customer Accommodation</fullName>
            </value>
            <value>
                <fullName>Sample/Demo Return</fullName>
            </value>
            <value>
                <fullName>Product Failure</fullName>
            </value>
            <value>
                <fullName>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</fullName>
                <isActive>false</isActive>
                <label>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</label>
            </value>
            <value>
                <fullName>AA</fullName>
                <isActive>false</isActive>
                <label>AA</label>
            </value>
            <value>
                <fullName>ASAS</fullName>
                <isActive>false</isActive>
                <label>ASAS</label>
            </value>
            <value>
                <fullName>DFD</fullName>
                <isActive>false</isActive>
                <label>DFD</label>
            </value>
            <value>
                <fullName>DSD</fullName>
                <isActive>false</isActive>
                <label>DSD</label>
            </value>
            <value>
                <fullName>Faulty CFP2 causing OTL Loss of Lane Alignment</fullName>
                <isActive>false</isActive>
                <label>Faulty CFP2 causing OTL Loss of Lane Alignment</label>
            </value>
            <value>
                <fullName>Functional</fullName>
                <isActive>false</isActive>
                <label>Functional</label>
            </value>
            <value>
                <fullName>Loss Of Signal</fullName>
                <isActive>false</isActive>
                <label>Loss Of Signal</label>
            </value>
            <value>
                <fullName>Loss of frame alarm flapping</fullName>
                <isActive>false</isActive>
                <label>Loss of frame alarm flapping</label>
            </value>
            <value>
                <fullName>OO</fullName>
                <isActive>false</isActive>
                <label>OO</label>
            </value>
            <value>
                <fullName>Pluggable alarm occurred</fullName>
                <isActive>false</isActive>
                <label>Pluggable alarm occurred</label>
            </value>
            <value>
                <fullName>Ports would not validate</fullName>
                <isActive>false</isActive>
                <label>Ports would not validate</label>
            </value>
            <value>
                <fullName>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</fullName>
                <isActive>false</isActive>
                <label>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</label>
            </value>
            <value>
                <fullName>SDS</fullName>
                <isActive>false</isActive>
                <label>SDS</label>
            </value>
            <value>
                <fullName>TEST UAT</fullName>
                <isActive>false</isActive>
                <label>TEST UAT</label>
            </value>
            <value>
                <fullName>TXing errors</fullName>
                <isActive>false</isActive>
                <label>TXing errors</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>alarms raised</fullName>
                <isActive>false</isActive>
                <label>alarms raised</label>
            </value>
            <value>
                <fullName>as</fullName>
                <isActive>false</isActive>
                <label>as</label>
            </value>
            <value>
                <fullName>asa</fullName>
                <isActive>false</isActive>
                <label>asa</label>
            </value>
            <value>
                <fullName>dsds</fullName>
                <isActive>false</isActive>
                <label>dsds</label>
            </value>
            <value>
                <fullName>sdsda</fullName>
                <isActive>false</isActive>
                <label>sdsda</label>
            </value>
            <value>
                <fullName>upgrade to firmware 35 per details and file attached in FAE case</fullName>
                <isActive>false</isActive>
                <label>upgrade to firmware 35 per details and file attached in FAE case</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <inlineHelpText>This is the RMA Request to which this line item looks up</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RMA Request Lines</relationshipLabel>
    <relationshipName>RMA_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/CancelRMACaseTest.cls
@isTest
public class CancelRMACaseTest{

     @isTest
    public static void updateCase(){
        
         Account acc = new Account(name='Account ', 
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        
        Account acc1 = new Account(name='Account test', 
                                  billingcity='Illionis',ParentId=acc.id, billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc1;
        Account shiptocustomer = new Account(name='AccountCustomer1 ', 
                                   ParentId=acc1.Id,Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId());
        insert shiptocustomer;
         Account siteacc = new Account(name='AccountSite ', 
                                      shippingcity='New York',Site_Use_Code__c='SHIP_TO',Site_Use_Status__c='Active',parentId=shiptocustomer.id, shippingcountry='USA',Status__c='Active',Type='Site',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId());
        insert siteacc;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
        User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
        system.debug('u==='+u);
        system.debug('acc==='+acc);
        system.debug('acc1==='+acc1);
        Id recordid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId();
        system.debug('recordid==='+recordid);
        case c= new case(Status='Open',RecordTypeId = recordid,Ship_To_Address__c=siteacc.id,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc1.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id);
        insert c;
        case c1= new case(Status='Open',RecordTypeId = recordid,Ship_To_Address__c=siteacc.id,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc1.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id,Return_Reason__c='Rework');
        insert c1;
        
        case c2= new case(Status='Open',RecordTypeId = recordid,Ship_To_Address__c=siteacc.id,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc1.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id ,Return_Reason__c='Rework');
        insert c2;
        
        RMA_Request_Line__c rmaLine = new RMA_Request_Line__c(RMA_Request__c=c.id,name='test',Return_Reason__c='Rework');
        
        RMA_Request_Line__c rmaLine2 = new RMA_Request_Line__c(RMA_Request__c=c1.id,name='test2',Return_Reason__c='Rework',PO_Price__c='Other');
        insert rmaLine2;
        RMA_Request_Line__c rmaLine3 = new RMA_Request_Line__c(RMA_Request__c=c2.id,name='test1',Org_Code__c='KOR',Return_Reason__c='Rework');
        insert rmaLine3;
        
        insert rmaLine;
        Test.startTest();
        CancelRMACase.getDetailsCondition(c.id);
        CancelRMACase.getDetailsCondition(c1.id);
        CancelRMACase.getDetailsCondition(c2.id);
        Test.stopTest(); 
    }
     @isTest
    public static void updateCase1(){
        
         Account acc = new Account(name='Account ', 
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc;
        
 		Account shiptocustomer = new Account(name='AccountCustomer1 ', 
                                   ParentId=acc.Id,Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId());
        insert shiptocustomer;
         Account siteacc = new Account(name='AccountSite ', 
                                      shippingcity='New York',Site_Use_Code__c='SHIP_TO',Site_Use_Status__c='Active',parentId=shiptocustomer.id, shippingcountry='USA',Status__c='Active',Type='Site',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId());
        insert siteacc;
   
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
        User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
             insert u;
        }
        system.debug('u==='+u);
        system.debug('acc==='+acc);
        Id recordid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RMA Request').getRecordTypeId();
        system.debug('recordid==='+recordid);
        case c= new case(Status='Open',RecordTypeId = recordid,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Ship_To_Address__c=siteacc.id,Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id ,Return_Reason__c='Rework');
        insert c;
        case c1= new case(Status='Open',RecordTypeId = recordid,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Ship_To_Address__c=siteacc.id,Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id,Return_Reason__c='Rework');
        insert c1;
        
        case c2= new case(Status='Open',RecordTypeId = recordid,Finisar_Sales_Manager__c= u.id,Customer_Name__c=acc.id,AccountId=acc.id,Requested_Service__c='Loaner Return',CustomerRef_RMANo__c='Test',
                        Ship_To_Address__c=siteacc.id,Outbound_RMA_PO__c='Test',Ship_To_Customer__c=shiptocustomer.id,Return_Reason__c='Rework');
        insert c2;
        
        RMA_Request_Line__c rmaLine = new RMA_Request_Line__c(RMA_Request__c=c.id,name='test',Return_Reason__c='Rework',
                                                              PO_Price__c='Other',Org_Code__c='KOR',End_Customer__c='Testtt');
        insert rmaLine;
        RMA_Request_Line__c rmaLine1 = new RMA_Request_Line__c(RMA_Request__c=c.id,name='test1',End_Customer__c='test1',Return_Reason__c='Rework');
        insert rmaLine1;
        
         RMA_Request_Line__c rmaLine2 = new RMA_Request_Line__c(RMA_Request__c=c1.id,name='test',Return_Reason__c='Rework',PO_Price__c='Other');
        insert rmaLine2;
        RMA_Request_Line__c rmaLine22 = new RMA_Request_Line__c(RMA_Request__c=c1.id,name='test2',Return_Reason__c='Rework',PO_Price__c='Other');
        insert rmaLine22;
        
        RMA_Request_Line__c rmaLine3 = new RMA_Request_Line__c(RMA_Request__c=c2.id,name='test1',Org_Code__c='KOR',Return_Reason__c='Rework');
        insert rmaLine3;
        
        /*RMA_Request_Line__c rmaLine4 = new RMA_Request_Line__c(RMA_Request__c=c2.id,name='test1',Error_Message__c='Serial Number is not Valid');
        insert rmaLine4;*/
        
        RMA_Request_Line__c rmaLine33 = new RMA_Request_Line__c(RMA_Request__c=c2.id,name='test3',Return_Reason__c='Rework',PO_Price__c='Other');
        insert rmaLine33;
        
        Test.startTest();
        CancelRMACase.getDetailsCondition(c.id);
        CancelRMACase.getDetailsCondition(c1.id);
        CancelRMACase.getDetailsCondition(c2.id);
        FA_FV_Analysis__c fRec = new FA_FV_Analysis__c(Name= 'test',Legacy_Id__c = '12342',RecordTypeId = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FA Analysis').getRecordTypeId()); 
        insert fRec;
        Failure_Modes__c fc= new Failure_Modes__c(FAFV_Analysis__c =fRec.id,Fault_Specification__c='Defective',PDC_Level_2__c='Crack',PIC_Level_1__c =
                                                  'Component',PDC_Level_1__c='Flex',PIC_Level_2__c='Adhesive/Epoxy',Site__c='IPH' );
        insert fc;
        Delete fc;
        Test.stopTest();
    }
     public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                                lastName = lName,
                                email = uniqueName + '@test' + orgId + '.org',
                                Username = uniqueName + '@test' + orgId + '.org',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                ProfileId = profId,
                                UserRoleId = roleId);
        return tuser; 
    }
}