src/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Case/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text( Status )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <description>Lookup field to User to Point SVP for user role VP</description>
    <label>SVP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <description>Lookup field to User to point to VP for User role RSM</description>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>VP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/classes/GDPREmailServiceHandlerTest.cls
@isTest
public class GDPREmailServiceHandlerTest {
    
    @isTest
    static void testData(){
        Account acc = new Account(name='Account ', 
                                  billingcity='New York', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        insert acc;
        Account acc1 = new Account(ParentId = acc.Id,name='Account1 ', 
                                   billingcity='New York test', billingcountry='USA',Status__c='Active',Type='Customer',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Top Level Account').getRecordTypeId());
        
        insert acc1;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        String roleId =[select Id from UserRole where Name='RSM of AMERICAS - WESTERN' LIMIT 1].Id;
        String roleId2 =[select Id from UserRole where Name='VP of AMERICAS - WESTERN' LIMIT 1].Id;
        String roleId3 =[select Id from UserRole where Name='EVP' LIMIT 1].Id;
        User u = createTestUser(roleId,p.Id,'Test','Case');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert u;
        }
        User u1 = createTestUser(roleId2,p.Id,'Test1','Case1');
        User u2 = createTestUser(roleId3,p.Id,'Test2','Case2');
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert u1;
            insert u2;
        }
        u.VP__c = u1.Id;
        u.SVP__c = u2.Id;
        System.debug('u1'+u1.Id);
        System.debug('u2'+u2.Id);
        update u;
        Contact c = new Contact(FirstName = 'Test',LastName = 'Contact',AccountId = acc.Id,MailingCountry='United States',Email='rest@vv.com');
        insert c;
        Test.startTest();
        sendInboundEmail(u,c);
        sendInboundEmail1(u,c);
        Test.stopTest();
        
    }  
    
    static void sendInboundEmail(user u,Contact conObj) {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        Messaging.InboundEmail.Header hditem= new Messaging.InboundEmail.Header();
        email.headers=new Messaging.InboundEmail.Header[1]; 
        hditem.name='Date'; 
        hditem.value='Tue, 28 Dec 2018 14:08:37 -0700'; 
        email.headers[0]=hditem;
        // setup the data for the email
        email.subject = 'RE:Opt-In Contact';
        env.fromAddress = u.Email;
        email.ccAddresses = new String[] {'dataprivacy@finisar.com'};
        String body = 'Opt-In'; 
        body = body+'\r\n';
        body = body+'For Finisar Use Only: ['+conObj.Id+']';
        
        System.debug('body=='+body);
        email.htmlBody =body;
        system.debug('email.headers==='+email.headers);
        system.debug('email.htmlBody==='+email.htmlBody);
        GDPREmailServiceHandler contactEmailObj =    New GDPREmailServiceHandler();
        contactEmailObj.handleInboundEmail(email, env);
    }
    static void sendInboundEmail1(user u,Contact conObj) {
        system.debug('Insideeeee==');
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        Messaging.InboundEmail.Header hditem= new Messaging.InboundEmail.Header();
        email.headers=new Messaging.InboundEmail.Header[1]; 
        hditem.name='Date'; 
        hditem.value='Tue, 28 Dec 2018 14:08:37 -0700'; 
        email.headers[0]=hditem;
        // setup the data for the email
        email.subject = 'Opt-In Contact';
        env.fromAddress = u.Email;
        email.ccAddresses = new String[] {'dataprivacy@finisar.com'};
        String body = 'Dear'; 
        body = body+'\r\n';
        body = body+'For Finisar Use Only: ['+conObj.Id+']';
        
        System.debug('body1=='+body);
        email.htmlBody =body;
        system.debug('email.headers1==='+email.headers);
        system.debug('email.htmlBody1==='+email.htmlBody);
        GDPREmailServiceHandler contactEmailObj =    New GDPREmailServiceHandler();
        contactEmailObj.handleInboundEmail(email, env);
    }
    public static User createTestUser(Id roleId, Id profID, String fName, String lName) {
        String orgId = userInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              isActive = True,
                              UserRoleId = roleId);
        return tuser;
    }
}