src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <formula>Order__r.End_Customer__c</formula>
    <label>End Customer</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <formula>Part_Number__r.Marketing_Family__c</formula>
    <label>Marketing Family</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(Part_Number__r.Product_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Ship_From_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Inventory__c</fullName>
    <inlineHelpText>For RMA Orders, this is the Receiving site. Otherwise, it is the Ship from site.</inlineHelpText>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Serial_Number_Owner__mdt/RMA_Serial_Number_Owner__mdt.object-meta.xml
<CustomObject>
    <label>RMA Serial Number Owner</label>
    <pluralLabel>RMA Serial Number Owners</pluralLabel>
</CustomObject>

src/objects/RMA_Serial_Number_Owner__mdt/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Serial_Number_Owner__mdt/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <label>Marketing Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/OrderlineOwnerupdate.cls
public class OrderlineOwnerupdate {
    public static void updateOwnerAtOrderLines(List<Order_Line__c> newOrderLineList1, Set<String> productGroupSet1){
        List<Order_Line__c> newOrderLineList = [select id,name,createdDate,Marketing_Family__c,End_Customer__c,Ship_From_Inventory__c,Product_Group__c 
                                                from order_line__c 
                                                where OwnerId = '0051N000007GUI3QAO' and Ship_From_Inventory__c ='IPH' and createdDate > 2020-09-01T00:01:14.000+0000] ;
        Set<String> productGroupSet = new Set<String>();
        List<Order_Line__c> updatlines = new List<Order_Line__c>();
        for(Order_Line__c line : newOrderLineList){
            productGroupSet.add(line.Product_Group__c);
        }
        Map<String,List<RMA_Serial_Number_Owner__mdt>> medtMap = New Map<String,List<RMA_Serial_Number_Owner__mdt>>();
        Set<String> userEmailSet = New Set<String>();
        Map<String,User> UserEmailObjMap = New Map<String,User>();
        For(RMA_Serial_Number_Owner__mdt mdt :[Select id,Owner__c,End_Customer__c,Marketing_Family__c,Product_Group__c,Location__c 
                                                                        from RMA_Serial_Number_Owner__mdt 
                                                                        where Product_Group__c in:productGroupSet]){
                                                                            IF(medtMap.containskey(mdt.Product_Group__c)){
                                                                                medtMap.get(mdt.Product_Group__c).add(mdt);
                                                                            }
                                                                            else{
                                                                                medtMap.put(mdt.Product_Group__c,New List<RMA_Serial_Number_Owner__mdt>{mdt});
                                                                            } 
                                                                            userEmailSet.add(mdt.Owner__c);                                                   
                                                                        }
        IF(!medtMap.isempty()){
            For(User userObj : [Select id,email from user where email in:userEmailSet and IsActive=True]){
                UserEmailObjMap.put(userObj.email,userObj);
            }
            For(Order_line__c orderlineObj:newOrderLineList){
                System.debug('orderlineObj'+orderlineObj);
                
                IF(medtMap.containskey(orderlineObj.Product_Group__c)){
                    
                    For(RMA_Serial_Number_Owner__mdt metaDataObj: medtMap.get(orderlineObj.Product_Group__c)){
                        System.debug(metaDataObj.Location__c.equalsIgnoreCase(orderlineObj.Ship_From_Inventory__c));
                        IF(!metaDataObj.Location__c.equalsIgnoreCase(orderlineObj.Ship_From_Inventory__c)){
                            continue;
                        }
                        IF(!String.isBlank(orderlineObj.Marketing_Family__c) && !(metaDataObj.Marketing_Family__c.contains(orderlineObj.Marketing_Family__c)|| metaDataObj.Marketing_Family__c.equalsignorecase('All'))){
                            continue;
                        }
                        IF(((!String.isBlank(orderlineObj.End_Customer__c) && orderlineObj.End_Customer__c.contains(metaDataObj.End_Customer__c))||
                            metaDataObj.End_Customer__c.equalsignorecase('All')||
                            metaDataObj.End_Customer__c.equalsignorecase('others')) &&
                           UserEmailObjMap.containskey(metaDataObj.Owner__c)){
                               orderlineObj.OwnerId = UserEmailObjMap.get(metaDataObj.Owner__c).Id;
                               System.debug('orderlineObj'+orderlineObj);
                               updatlines.add(orderlineObj);
                           }
                    }
                }
            }
        }
        system.debug('orderlineObj '+updatlines);
    }
    
}