src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderRatePlan__c/OrderRatePlan__c.object-meta.xml
<CustomObject>
    <label>Order Rate Plan</label>
    <nameField>
        <displayFormat>ORT-{00000}</displayFormat>
        <label>Order Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderRatePlan__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Order Rate Plans</relationshipLabel>
    <relationshipName>Order_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/classes/OrderRatePlan_Controller.cls
public with sharing class OrderRatePlan_Controller {
    public List<OrderRatePlan__c> orderTier{get; set;}
    public Order_Line__c orLine{get; set;}
    public OrderRatePlan_Controller(ApexPages.StandardController controller) {
        if(!test.isRunningTest())
            controller.addFields(New List<String> {'TotalPrice__c', 'Quantity__c'});
        orLine = (Order_Line__c)controller.getRecord();
        system.debug('oppline id '+orLine.Id);
        List<OrderRatePlan__c> plans = [SELECT Id, OrderProduct__c, SalesPrice__c, SequenceNumber__c, LeadTime__c
                                        FROM OrderRatePlan__c 
                                        WHERE OrderProduct__c = :orLine.Id ORDER BY SequenceNumber__c asc];
        if(plans != null && !plans.isEmpty()){
            orderTier = plans;
        } else {
            orderTier = new List<OrderRatePlan__c>();
            OrderRatePlan__c rate = new OrderRatePlan__c();
            orderTier .add(rate);
        }
    }
    public pageReference addNewRow(){
        OrderRatePlan__c rate = new OrderRatePlan__c();
        orderTier.add(rate);
        return null;
    }
    public pageReference saveAction(){
        List<OrderRatePlan__c> plans = new List<OrderRatePlan__c>();
        for(OrderRatePlan__c plan : orderTier ){
            if(plan.SequenceNumber__c != null && plan.SalesPrice__c !=0){
                plan.OrderProduct__c = orline.Id;
                plans.add(plan);
                if(plan.SequenceNumber__c < orLine.Quantity__c){
                    orLine.TotalPrice__c = plan.SalesPrice__c;
                }
            }
        }
        if(plans != null && !plans.isEmpty()){
            upsert plans;
            update orLine;
        }
        return new pageReference('/'+orLine.Id);
    }
    public pageReference CancelAction(){
        return new pageReference('/'+orLine.Id);
    }
    
}