src/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityRatePlan__c/OpportunityRatePlan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Rate Plan</label>
    <nameField>
        <displayFormat>ORL-{00000}</displayFormat>
        <label>Opportunity Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityRatePlan__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>Opportunity Line Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/classes/AddRatePlanController.cls
public with sharing class AddRatePlanController {
    public List<OpportunityRatePlan__c> ratePlans {get; set;}
    public OpportunityLineItem oppLine{get; set;}
    public AddRatePlanController(ApexPages.StandardController controller) {
        if(!test.isRunningTest()){
            controller.addFields(New List<String> {'UnitPrice', 'Quantity'});
        }
        oppLine = (OpportunityLineItem)controller.getRecord();
        List<OpportunityRatePlan__c> plans = [SELECT Id, OpportunityLineItem__c, SalesPrice__c, SequenceNumber__c, Description__c,LeadTime__c
                                              FROM OpportunityRatePlan__c 
                                              WHERE OpportunityLineItem__c = :oppLine.Id ORDER BY SequenceNumber__c asc];
        if(plans != null && !plans.isEmpty()){
            ratePlans = plans;
        } else {
            ratePlans = new List<OpportunityRatePlan__c>();
            OpportunityRatePlan__c rate = new OpportunityRatePlan__c();
            ratePlans .add(rate);
        }
        
    }
    public pageReference addNewRow(){
        OpportunityRatePlan__c rate = new OpportunityRatePlan__c();
        ratePlans .add(rate);
        return null;
    }
    public pageReference saveAction(){
        List<OpportunityRatePlan__c> plans = new List<OpportunityRatePlan__c>();
        List<OpportunityRatePlan__c> deletePlans = new List<OpportunityRatePlan__c>();
        for(OpportunityRatePlan__c plan : ratePlans ){
            system.debug('plan'+plan);
            if(plan.SequenceNumber__c != null && (plan.SalesPrice__c ==0 || plan.SalesPrice__c == null)){
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.ERROR, 'Sales price should be Provided'));
                return null;
            }
            if(plan.SequenceNumber__c != null && plan.SalesPrice__c !=0){
                plan.OpportunityLineItem__c = oppline.Id;
                plans.add(plan);
                if(plan.SequenceNumber__c < oppLine.Quantity){
                    oppLine.UnitPrice = plan.SalesPrice__c;
                }
            } else {
                if(plan.Id != null)
                    deletePlans.add(plan);
            }
        }
        if(plans != null && !plans.isEmpty()){
            upsert plans;
            update oppLine;
        }
        if(deletePlans != null && !deletePlans.isEmpty()){
            delete deletePlans;
        }
        return new pageReference('/'+oppLine.Id);
    }
    public pageReference CancelAction(){
        return new pageReference('/'+oppLine.Id);
    }
}