src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/CA_Required__c.field-meta.xml
<CustomField>
    <fullName>CA_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Required</label>
    <type>Checkbox</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Containment__c.field-meta.xml
<CustomField>
    <fullName>Containment__c</fullName>
    <label>Containment</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Corrective_Action__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Action__c</fullName>
    <label>Corrective Action</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <inlineHelpText>FA Findings</inlineHelpText>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FA_FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Status__c</fullName>
    <description>FA/FV Status Inprogress and Finalised</description>
    <inlineHelpText>Setting the FV/FA Status to Finalized will lock the record from future editing</inlineHelpText>
    <label>FV/FA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Failure_Mechanism__c.field-meta.xml
<CustomField>
    <fullName>Failure_Mechanism__c</fullName>
    <label>Failure Mechanism</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Final_Function_Test__c.field-meta.xml
<CustomField>
    <fullName>Final_Function_Test__c</fullName>
    <label>Final Function Test</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Final_Functional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Final_Functional_Comments__c</fullName>
    <label>Final/Functional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FV_Findings__c.field-meta.xml
<CustomField>
    <fullName>FV_Findings__c</fullName>
    <label>FV Findings</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/RC_Analysis__c.field-meta.xml
<CustomField>
    <fullName>RC_Analysis__c</fullName>
    <label>RC Analysis</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Risk_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment__c</fullName>
    <label>Risk Assessment</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IPH</fullName>
            </value>
            <value>
                <fullName>SNY</fullName>
            </value>
            <value>
                <fullName>SYD</fullName>
            </value>
            <value>
                <fullName>WXI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Temp_BERT__c.field-meta.xml
<CustomField>
    <fullName>Temp_BERT__c</fullName>
    <label>Temp BERT</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Temp_Bert_Comments__c.field-meta.xml
<CustomField>
    <fullName>Temp_Bert_Comments__c</fullName>
    <label>Temp Bert Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/VMI__c.field-meta.xml
<CustomField>
    <fullName>VMI__c</fullName>
    <label>VMI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/VMI_Comments__c.field-meta.xml
<CustomField>
    <fullName>VMI_Comments__c</fullName>
    <label>VMI Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/recordTypes/FA_Analysis.recordType-meta.xml
<RecordType>
    <fullName>FA_Analysis</fullName>
    <active>true</active>
    <label>FA Analysis</label>
</RecordType>

src/objects/FA_FV_Analysis__c/recordTypes/FV_Analysis.recordType-meta.xml
<RecordType>
    <fullName>FV_Analysis</fullName>
    <active>true</active>
    <label>FV Analysis</label>
</RecordType>

src/objects/Failure_Modes__c/Failure_Modes__c.object-meta.xml
<CustomObject>
    <label>Failure Modes</label>
    <nameField>
        <displayFormat>Failure Mode - {00000000}</displayFormat>
        <label>Failure Modes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failure Modes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Failure_Modes__c/fields/FAFV_Analysis__c.field-meta.xml
<CustomField>
    <fullName>FAFV_Analysis__c</fullName>
    <label>FV/FA Analysis</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Failure Modes</relationshipLabel>
    <relationshipName>Failure_Modes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Failure_Modes__c/fields/PDC_Level_1__c.field-meta.xml
<CustomField>
    <fullName>PDC_Level_1__c</fullName>
    <label>PDC Level 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Site__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10GCDRLDPA</fullName>
            </value>
            <value>
                <fullName>BH1</fullName>
            </value>
            <value>
                <fullName>BH Laser</fullName>
            </value>
            <value>
                <fullName>Breakout</fullName>
            </value>
            <value>
                <fullName>Bulkhead</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Capacitor</fullName>
            </value>
            <value>
                <fullName>Ceramic capacitor</fullName>
            </value>
            <value>
                <fullName>CLEI Label</fullName>
            </value>
            <value>
                <fullName>COF</fullName>
            </value>
            <value>
                <fullName>COF Window</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
            </value>
            <value>
                <fullName>DFB25</fullName>
            </value>
            <value>
                <fullName>DFB Laser</fullName>
            </value>
            <value>
                <fullName>EEPROM</fullName>
            </value>
            <value>
                <fullName>EMI Collar</fullName>
            </value>
            <value>
                <fullName>FCC</fullName>
            </value>
            <value>
                <fullName>Firmware</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Gold Finger</fullName>
            </value>
            <value>
                <fullName>Header pin / Riser board</fullName>
            </value>
            <value>
                <fullName>Heat sink, Lid, Ring Frame</fullName>
            </value>
            <value>
                <fullName>Hotbar</fullName>
            </value>
            <value>
                <fullName>I32X1B</fullName>
                <label>I32X</label>
            </value>
            <value>
                <fullName>ICDR3A</fullName>
                <label>ICDR</label>
            </value>
            <value>
                <fullName>Inductor</fullName>
            </value>
            <value>
                <fullName>Interface board</fullName>
            </value>
            <value>
                <fullName>Isolator</fullName>
            </value>
            <value>
                <fullName>Laser Driver</fullName>
            </value>
            <value>
                <fullName>Leadframe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Failure_Modes__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IPH</fullName>
            </value>
            <value>
                <fullName>WXI</fullName>
            </value>
            <value>
                <fullName>SNY</fullName>
            </value>
            <value>
                <fullName>SYD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <nameField>
        <label>Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Steps__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Steps__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FA / FV</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Steps__c/fields/FA_Steps_Description_FA_Steps__c.field-meta.xml
<CustomField>
    <fullName>FA_Steps_Description_FA_Steps__c</fullName>
    <inlineHelpText>Please enter information about what you did during this step. Can be used for future processes and may become part of the FAR.</inlineHelpText>
    <label>FA Steps / Description (FA Steps)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/classes/CloneFAFVRecord.cls
public class CloneFAFVRecord {
    
    @AuraEnabled
    public static String  getFAFVRecord(String FAFVRecId)
    {
        system.debug('FAFVRecId'+FAFVRecId);
        FA_FV_Analysis__c FAFVAnalysis;
        String FAFVAnalysisqueryfields = String.join(CommonConstants.FAAnalysisFields, ',');
        String FAFVAnalysisquery = 'select '+FAFVAnalysisqueryfields +' FROM FA_FV_Analysis__c WHERE Id =:FAFVRecId';
        List<Steps__c> stepsList;
        List<Failure_Modes__c> failuremodesList;
        String stepsfields =String.join(CommonConstants.StepFields, ',');
        String StepFieldsQuery = 'select '+stepsfields+' FROM Steps__c WHERE FA_FV__c =:FAFVRecId';
        String failuremodefields =String.join(CommonConstants.FailureModes, ',');
        String failuremodequery = 'select '+failuremodefields +' FROM Failure_Modes__c WHERE FAFV_Analysis__c=:FAFVRecId';
         String cloneFAFVName ;
        FA_FV_Analysis__c newFAFVRecord;
        try{
            FAFVAnalysis = Database.query(FAFVAnalysisquery);
            stepsList =Database.query(StepFieldsQuery);
            failuremodesList = Database.query(failuremodequery);
            newFAFVRecord =cloneFAFV(FAFVAnalysis);
            if(newFAFVRecord.Id != NULL)
            {
                System.debug('cloned FAFV Record'+newFAFVRecord.Id);
                cloneSteps(stepsList,newFAFVRecord);
                cloneFailureModes(failuremodesList,newFAFVRecord );
                cloneFAFVName =newFAFVRecord.Name;
            }
                
        }
        catch(QueryException e)
        {
            System.debug('************Query Exception'+e.getLineNumber()+'  '+e.getMessage());
        }
        
      
      if(cloneFAFVName != null)  return newFAFVRecord.Id;
      else return null;
    }
    public static FA_FV_Analysis__c cloneFAFV(FA_FV_Analysis__c oldFAFVRecord)
    {
        
        FA_FV_Analysis__c newFAFVAnalysis = new FA_FV_Analysis__c();
        try{
            
            if(oldFAFVRecord.RecordType.DeveloperName =='FA_Analysis')
            {
              
                newFAFVAnalysis.CA_Required__c =oldFAFVRecord.CA_Required__c;
                newFAFVAnalysis.RecordTypeId = oldFAFVRecord.RecordTypeId;
                newFAFVAnalysis.FA_FV_Status__c ='InProgress';
                newFAFVAnalysis.Site__c = oldFAFVRecord.Site__c;
                newFAFVAnalysis.Name =oldFAFVRecord.Name +'Clone';
                newFAFVAnalysis.FA_Findings__c =oldFAFVRecord.FA_Findings__c;
                newFAFVAnalysis.RC_Analysis__c =oldFAFVRecord.RC_Analysis__c;
                newFAFVAnalysis.Containment__c=oldFAFVRecord.Containment__c;
                newFAFVAnalysis.Failure_Mechanism__c=oldFAFVRecord.Failure_Mechanism__c;
                newFAFVAnalysis.Corrective_Action__c=oldFAFVRecord.Corrective_Action__c;
                newFAFVAnalysis.Conclusion__c=oldFAFVRecord.Conclusion__c;
                newFAFVAnalysis.Risk_Assessment__c =oldFAFVRecord.Risk_Assessment__c;
                
                insert newFAFVAnalysis;
                
            }
            else if(oldFAFVRecord.RecordType.DeveloperName =='FV_Analysis')
            {
                newFAFVAnalysis.RecordTypeId = oldFAFVRecord.RecordTypeId;
                newFAFVAnalysis.FA_FV_Status__c ='InProgress';
                newFAFVAnalysis.Name =oldFAFVRecord.Name +'Clone';
                newFAFVAnalysis.CA_Required__c =oldFAFVRecord.CA_Required__c;
                newFAFVAnalysis.Site__c = oldFAFVRecord.Site__c;
                newFAFVAnalysis.FV_Findings__c =oldFAFVRecord.FV_Findings__c;
                
                newFAFVAnalysis.Temp_BERT__c =oldFAFVRecord.Temp_BERT__c;
                newFAFVAnalysis.Temp_Bert_Comments__c =oldFAFVRecord.Temp_Bert_Comments__c;
                newFAFVAnalysis.VMI__c =oldFAFVRecord.VMI__c;
                newFAFVAnalysis.VMI_Comments__c =oldFAFVRecord.VMI_Comments__c;
                newFAFVAnalysis.Final_Function_Test__c =oldFAFVRecord.Final_Function_Test__c;
                newFAFVAnalysis.Final_Functional_Comments__c =oldFAFVRecord.Final_Functional_Comments__c;
                  insert newFAFVAnalysis;
            }
            
        }
        catch(DMLException e)
        {
            System.debug('**************DML EXCEPTION'+e.getLineNumber()+'   '+e.getStackTraceString());
           
        }
        catch(Exception e)
        {
            System.debug('*********FA ANALYSIS*****DML EXCEPTION'+e.getLineNumber()+'   '+e.getStackTraceString());
            
        }
        return newFAFVAnalysis;
    }
      public static void cloneSteps( List<Steps__c> stepsCloneList,FA_FV_Analysis__c newFAFVAnalysis )
    {
        System.debug('*************Inside Steps**************');
        List<Steps__c> newStepsList= new  List<Steps__c>();
        try{
            for(Steps__c oldstep :stepsCloneList )
            {
                newStepsList.add(new Steps__c(
                  Name =oldstep.Name,
                     FA_FV__c=newFAFVAnalysis.Id,
                   FA_Steps_Description_FA_Steps__c =oldstep.FA_Steps_Description_FA_Steps__c));
            }
            insert newStepsList;
        }
        catch(Exception e)
        {
            System.debug('**************STEPS DML EXCEPTION'+e.getLineNumber()+'   '+e.getStackTraceString());
        }
    }
      public static void cloneFailureModes( List<Failure_Modes__c> failuremodesCloneList,FA_FV_Analysis__c newFAFVAnalysis )
    {
         System.debug('*************Inside Failure Modes**************');
        List<Failure_Modes__c> newfailuremodesList= new  List<Failure_Modes__c>();
        try{
            for(Failure_Modes__c oldfailuremode :failuremodesCloneList )
            {
                newfailuremodesList.add(new Failure_Modes__c(
                  	PDC_Level_1__c =oldfailuremode.PDC_Level_1__c,
                    PDC_Level_2__c =oldfailuremode.PDC_Level_2__c,
                    PIC_Level_1__c =oldfailuremode.PIC_Level_1__c,
                    PIC_Level_2__c =oldfailuremode.PIC_Level_2__c,
                    Site__c =oldfailuremode.Site__c,
                     FAFV_Analysis__c=newFAFVAnalysis.Id,
                    Fault_Specification__c =oldfailuremode.Fault_Specification__c,
                    Component_Description__c =oldfailuremode.Component_Description__c,
                   Traceability_Information__c =oldfailuremode.Traceability_Information__c));
            }
            insert newfailuremodesList;
        }
        catch(Exception e)
        {
            System.debug('**************Failure_Modes__c DML EXCEPTION'+e.getLineNumber()+'   '+e.getStackTraceString());
        }
    }
    
}