src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/FA_FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Status__c</fullName>
    <description>FA/FV Status Inprogress and Finalised</description>
    <inlineHelpText>Setting the FV/FA Status to Finalized will lock the record from future editing</inlineHelpText>
    <label>FV/FA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Detail__c/FA_FV_Detail__c.object-meta.xml
<CustomObject>
    <label>FV/FA Detail</label>
    <nameField>
        <displayFormat>FV/FA Analysis - {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FV/FA Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FA_FV_Detail__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FV/FA</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>FV/FA Details</relationshipLabel>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>This is the serial number to which this FA / FV is relevant</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Serial_Number__c</referenceTo>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Please select the status for this FA or FV subject to the following guidance:
-  
-  
-</inlineHelpText>
    <label>Detail Status (Junction)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Evaluating</fullName>
                <isActive>false</isActive>
                <label>Evaluating</label>
            </value>
            <value>
                <fullName>Finalizing</fullName>
                <isActive>false</isActive>
                <label>Finalizing</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Serial_Number__c/Serial_Number__c.object-meta.xml
<CustomObject>
    <description>This is the serial numbers for an RMA request which will be populated from Oracle</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Serial_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Serial Number Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Serial_Number_Status</valueSetName>
    </valueSet>
</CustomField>

src/classes/FAFVStatusBatch.cls
public class FAFVStatusBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext jobcontext)
    {
        
        String FAFVDetail ='select Id,Status__c,FA_FV__r.FA_FV_Status__c,Serial_Number__c ,Serial_Number__r.Status__c from FA_FV_Detail__c';
        return Database.getQueryLocator(FAFVDetail);
		        
    }
	public void execute(Database.BatchableContext jobcontext, List<FA_FV_Detail__c> FAFVDetails)
    {
        
         List<FA_FV_Detail__c> updatedFAFVDetail = new  List<FA_FV_Detail__c>();
        List<FA_FV_Detail__c> updatedFAFVDetailForFAFVFinalized = new  List<FA_FV_Detail__c>();
        try{
           
        for( FA_FV_Detail__c FAFVDetailRecord:FAFVDetails )
        {
         	if(FAFVDetailRecord.Serial_Number__r.Status__c =='Closed' && FAFVDetailRecord.Status__c=='In Progress')
            {
                FAFVDetailRecord.Status__c ='Complete';
                updatedFAFVDetail.add(FAFVDetailRecord);
            }
            else if(FAFVDetailRecord.FA_FV__r.FA_FV_Status__c =='Finalized' && FAFVDetailRecord.Status__c=='In Progress')
            {
                FAFVDetailRecord.Status__c ='Complete';
                updatedFAFVDetailForFAFVFinalized.add(FAFVDetailRecord);
            }
            
            
        }
      
		if(updatedFAFVDetail.size()>0)
            Database.update(updatedFAFVDetail);
        if(updatedFAFVDetailForFAFVFinalized.size()>0)
			Database.update(updatedFAFVDetailForFAFVFinalized);
        }
        catch(Exception e)
        {
            System.debug('  '+e.getMessage());
        }
        
        
        
       
        
        
    }
    public void finish(Database.BatchableContext jobcontext)
    {
        
    }
}