src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/FA_FV_Status__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Status__c</fullName>
    <description>FA/FV Status Inprogress and Finalised</description>
    <inlineHelpText>Setting the FV/FA Status to Finalized will lock the record from future editing</inlineHelpText>
    <label>FV/FA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/FAFVAnalysisTriggerHelper.cls
public with sharing class FAFVAnalysisTriggerHelper {

     public static void beforeUpdate(List<FA_FV_Analysis__c> newFAFVlist,Map<Id,FA_FV_Analysis__c> oldFAFVMap)
    {
        
            for(FA_FV_Analysis__c newFAFVAnalysis : newFAFVlist)
            {
                FA_FV_Analysis__c oldFAFVAnalysis = oldFAFVMap.get(newFAFVAnalysis.id);
                if(oldFAFVAnalysis.FA_FV_Status__c == newFAFVAnalysis.FA_FV_Status__c &&  newFAFVAnalysis.FA_FV_Status__c == 'Finalized'  )
                {
                    newFAFVAnalysis.addError('User cannot Update FA or FV Analysis  when FA FV Status is \'Finalized \'');
                }
                if(oldFAFVAnalysis.FA_FV_Status__c != newFAFVAnalysis.FA_FV_Status__c &&  oldFAFVAnalysis.FA_FV_Status__c == 'Finalized'  )
                {
                    newFAFVAnalysis.addError('User cannot Update FA or FV Analysis  when FA FV Status is \'Finalized \'');
                }
            }
    }
     public static void beforeDelete(List<FA_FV_Analysis__c> oldFAFVlist)
    {
        for(FA_FV_Analysis__c oldFAFVAnalysis : oldFAFVlist)
            {
                
                if(oldFAFVAnalysis.FA_FV_Status__c == 'Finalized' )
                {
                    oldFAFVAnalysis.addError('User cannot Delete FA or FV Analysis  when FA FV Status is \'Finalized \'');
                }
            }
    }
    
}