src/objects/Quote/recordTypes/Transfer_Quote.recordType-meta.xml
<RecordType>
    <fullName>Transfer_Quote</fullName>
    <active>true</active>
    <label>Transfer Quote</label>
</RecordType>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/TQ_Currency__c.field-meta.xml
<CustomField>
    <fullName>TQ_Currency__c</fullName>
    <label>TQ Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/Transfer_Currency_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Currency_Amount__c</fullName>
    <label>Transfer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/QuoteRatePlan__c/QuoteRatePlan__c.object-meta.xml
<CustomObject>
    <label>Quote Rate Plan</label>
    <nameField>
        <displayFormat>QRP-{00000}</displayFormat>
        <label>Quote Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteRatePlan__c/fields/LeadTime__c.field-meta.xml
<CustomField>
    <fullName>LeadTime__c</fullName>
    <label>Lead Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Rate Plans</relationshipLabel>
    <relationshipName>Quote_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/TQ_Currency__c.field-meta.xml
<CustomField>
    <fullName>TQ_Currency__c</fullName>
    <label>TQ Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/QuoteLineItemTriggerHelper.cls
public class QuoteLineItemTriggerHelper {
    public static void updateConverionValue(List<Quote_Item__c> lineItems){
        system.debug('in lineItems'+lineItems);
        Map<String, Double> rateConvertionMap = new Map<String, Double>();
        for(DatedConversionRate conVal : [SELECT Id,Isocode, StartDate,NextStartDate, ConversionRate 
                                          FROM DatedConversionRate 
                                          WHERE StartDate <= :date.today() and NextStartDate > :date.today()]){
                                              rateConvertionMap.put(conVal.IsoCode, conVal.ConversionRate); 
                                          }
        for(Quote_Item__c  item : lineItems){
            if(item.CurrencyIsoCode  != item.TQ_Currency__c && item.TQ_Currency__c != null){
                system.debug('item.UnitPrice '+item.Target_Price__c  );
               /* if(item.UnitPrice != 0){
                    system.debug('item.Transfer_Currency_Amount__c'+item.Transfer_Currency_Amount__c);
                    item.Transfer_Currency_Amount__c = (item.UnitPrice/rateConvertionMap.get(item.CurrencyIsoCode)) * rateConvertionMap.get(item.TQ_Currency__c) ;
                } else */if(item.Transfer_Currency_Amount__c != null){
                    system.debug('item.Transfer_Currency_Amount__c'+item.Transfer_Currency_Amount__c);
                    item.Target_Price__c   = (item.Transfer_Currency_Amount__c / rateConvertionMap.get(item.TQ_Currency__c)) * rateConvertionMap.get(item.CurrencyIsoCode);
                }
                
            }
        }
    }
    
    public static void updateConverionValue(Map<Id, Quote_Item__c > newLineItems, Map<Id, Quote_Item__c > oldLineItems){
        Id transferRecordtypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Transfer_Quote').getRecordTypeId();
         Map<String, Double> rateConvertionMap = new Map<String, Double>();
        for(DatedConversionRate conVal : [SELECT Id,Isocode, StartDate,NextStartDate, ConversionRate 
                                          FROM DatedConversionRate 
                                          WHERE StartDate <= :date.today() and NextStartDate > :date.today()]){
                                              rateConvertionMap.put(conVal.IsoCode, conVal.ConversionRate); 
                                          }
        for(Quote_Item__c  newItem :newLineItems.values()){
            Quote_Item__c  oldItem = oldLineItems.get(newItem.Id);
            if(newItem.TQ_Currency__c != null && newItem.CurrencyIsoCode != newItem.TQ_Currency__c){
                if(oldItem.Transfer_Currency_Amount__c != newItem.Transfer_Currency_Amount__c){
                    newItem.Target_Price__c   = (newItem.Transfer_Currency_Amount__c / rateConvertionMap.get(newItem.TQ_Currency__c)) * rateConvertionMap.get(newItem.CurrencyIsoCode);
                }
             /*   if(oldItem.UnitPrice != newItem.UnitPrice){
                    newItem.Transfer_Currency_Amount__c = (newItem.UnitPrice / rateConvertionMap.get(newItem.CurrencyIsoCode)) * rateConvertionMap.get(newItem.TQ_Currency__c);
                }*/
            }
        }
    }
    
    public static void updateunitPrice(List<Quote_Item__c > newItems, Map<Id, Quote_Item__c > oldMap){
        List<Quote_Item__c > qUpdatedLines = new List<Quote_Item__c >();
        Map<Id, Quote_Item__c > updateMap = new Map<Id, Quote_Item__c >();
        for(Quote_Item__c  line : newItems){
            if(line.Quantity__c  != null && line.Quantity__c  != oldMap.get(line.id).Quantity__c ){
                updateMap.put(line.Id, line);
            }
        }
        if(updateMap != null && !updateMap.isEmpty()){
            for(QuoteRatePlan__c rate : [SELECT Id, LeadTime__c, SalesPrice__c, SequenceNumber__c, QuoteLineItem__c
                                         FROM QuoteRatePlan__c 
                                         WHERE QuoteLineItem__c IN : updateMap.keySet() order BY SequenceNumber__c]){
                                             if(updateMap.get(rate.QuoteLineItem__c).Quantity__c  >= rate.SequenceNumber__c){
                                                 updateMap.get(rate.QuoteLineItem__c).Quantity__c  = rate.SalesPrice__c;
                                             } 
                                         }
        }
    }
}