src/objects/PLM_Approval_Matrix__mdt/PLM_Approval_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>PLM Approval Matrix</label>
    <pluralLabel>PLM Approval Matrix</pluralLabel>
</CustomObject>

src/objects/PLM_Approval_Matrix__mdt/fields/Configuration_Segment4__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment4__c</fullName>
    <label>Configuration (Segment4)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/ConfigurationNotOperator__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ConfigurationNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Detector_Segment7__c.field-meta.xml
<CustomField>
    <fullName>Detector_Segment7__c</fullName>
    <label>Detector (Segment7)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/DetectorNotOperator__c.field-meta.xml
<CustomField>
    <fullName>DetectorNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DetectorNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Family_Segment2__c.field-meta.xml
<CustomField>
    <fullName>Family_Segment2__c</fullName>
    <label>Family (Segment2)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/FamilySegmentNotOperator__c.field-meta.xml
<CustomField>
    <fullName>FamilySegmentNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FamilySegmentNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Form_Factor_Segment3__c.field-meta.xml
<CustomField>
    <fullName>Form_Factor_Segment3__c</fullName>
    <label>Form Factor (Segment3)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/FormFactorNotOperator__c.field-meta.xml
<CustomField>
    <fullName>FormFactorNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FormFactorNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Laser_Segment6__c.field-meta.xml
<CustomField>
    <fullName>Laser_Segment6__c</fullName>
    <label>Laser (Segment6)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/LaserNotOperator__c.field-meta.xml
<CustomField>
    <fullName>LaserNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LaserNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Market_Application_Segment5__c.field-meta.xml
<CustomField>
    <fullName>Market_Application_Segment5__c</fullName>
    <label>Market Application (Segment5)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/MarketAppNotOperator__c.field-meta.xml
<CustomField>
    <fullName>MarketAppNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MarketAppNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Product_Group_Segment1__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_Segment1__c</fullName>
    <label>Product Group (Segment1)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Upper_Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Upper_Approval_Level__c</fullName>
    <label>Upper Approval Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Form_Factor__c.field-meta.xml
<CustomField>
    <fullName>Form_Factor__c</fullName>
    <label>Form Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>168 PIN</fullName>
            </value>
            <value>
                <fullName>17PIN</fullName>
            </value>
            <value>
                <fullName>1RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>1X20 PIN</fullName>
            </value>
            <value>
                <fullName>28PIN</fullName>
            </value>
            <value>
                <fullName>2RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>2X10 PIN</fullName>
            </value>
            <value>
                <fullName>2X5 PIN</fullName>
            </value>
            <value>
                <fullName>2X6 PIN</fullName>
            </value>
            <value>
                <fullName>2X7 PIN</fullName>
            </value>
            <value>
                <fullName>300 PIN</fullName>
            </value>
            <value>
                <fullName>300PIN-LFF</fullName>
            </value>
            <value>
                <fullName>300PIN-SFF</fullName>
            </value>
            <value>
                <fullName>3RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>41PN CNSMR</fullName>
            </value>
            <value>
                <fullName>9PIN</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER MODULE</fullName>
            </value>
            <value>
                <fullName>BOA</fullName>
            </value>
            <value>
                <fullName>CDFP</fullName>
            </value>
            <value>
                <fullName>CFP</fullName>
            </value>
            <value>
                <fullName>CFP2</fullName>
            </value>
            <value>
                <fullName>CFP4</fullName>
            </value>
            <value>
                <fullName>CFP8</fullName>
            </value>
            <value>
                <fullName>Chip</fullName>
            </value>
            <value>
                <fullName>Chip-on-Carrier</fullName>
            </value>
            <value>
                <fullName>CUSTOMENCL</fullName>
            </value>
            <value>
                <fullName>CUSTOM LINECARD</fullName>
            </value>
            <value>
                <fullName>CXP</fullName>
            </value>
            <value>
                <fullName>DIE</fullName>
            </value>
            <value>
                <fullName>ENDURANCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Config__c.field-meta.xml
<CustomField>
    <fullName>Product_Config__c</fullName>
    <label>Product Config</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4CHWDMXCVR</fullName>
            </value>
            <value>
                <fullName>8CHWDMXCVR</fullName>
            </value>
            <value>
                <fullName>ANTEC</fullName>
            </value>
            <value>
                <fullName>AZNA-CML</fullName>
            </value>
            <value>
                <fullName>BETA/GAMMA</fullName>
            </value>
            <value>
                <fullName>BIG BEAR</fullName>
            </value>
            <value>
                <fullName>BROADWAY</fullName>
            </value>
            <value>
                <fullName>C-COR</fullName>
            </value>
            <value>
                <fullName>CADDO</fullName>
            </value>
            <value>
                <fullName>CWDMPASS</fullName>
            </value>
            <value>
                <fullName>DWDMPASS</fullName>
            </value>
            <value>
                <fullName>EQUALIZED</fullName>
            </value>
            <value>
                <fullName>FIRA</fullName>
            </value>
            <value>
                <fullName>GENNUM</fullName>
            </value>
            <value>
                <fullName>I32X</fullName>
            </value>
            <value>
                <fullName>ICDR</fullName>
            </value>
            <value>
                <fullName>IFFO</fullName>
            </value>
            <value>
                <fullName>INTERLEAVE</fullName>
            </value>
            <value>
                <fullName>IPX</fullName>
            </value>
            <value>
                <fullName>KODEOS</fullName>
            </value>
            <value>
                <fullName>MICROSEMI</fullName>
            </value>
            <value>
                <fullName>MOTOROLA</fullName>
            </value>
            <value>
                <fullName>OMEGA</fullName>
            </value>
            <value>
                <fullName>OPTIUM</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PARALLEL</fullName>
            </value>
            <value>
                <fullName>PATHFINDER</fullName>
            </value>
            <value>
                <fullName>RED-C</fullName>
            </value>
            <value>
                <fullName>SAMSUNG</fullName>
            </value>
            <value>
                <fullName>SMART LDPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Family_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Text__c</fullName>
    <formula>TEXT( Product_Family__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family Text</label>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;10 GIG</fullName>
            </value>
            <value>
                <fullName>100 GIG</fullName>
            </value>
            <value>
                <fullName>10 GIG</fullName>
            </value>
            <value>
                <fullName>16-32 GIG</fullName>
            </value>
            <value>
                <fullName>200 GIG</fullName>
            </value>
            <value>
                <fullName>25 GIG</fullName>
            </value>
            <value>
                <fullName>3D SENSORS</fullName>
            </value>
            <value>
                <fullName>400 GIG</fullName>
            </value>
            <value>
                <fullName>40 GIG</fullName>
            </value>
            <value>
                <fullName>800 GIG</fullName>
            </value>
            <value>
                <fullName>ACCESSORIES</fullName>
            </value>
            <value>
                <fullName>ACTIVES</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER</fullName>
            </value>
            <value>
                <fullName>ANALOG</fullName>
            </value>
            <value>
                <fullName>ANALOG-ISR</fullName>
            </value>
            <value>
                <fullName>ANALOG-US</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>CDAUI-16</fullName>
            </value>
            <value>
                <fullName>CDAUI-8</fullName>
            </value>
            <value>
                <fullName>LW/SONET MODULE</fullName>
            </value>
            <value>
                <fullName>LWMODULES</fullName>
            </value>
            <value>
                <fullName>NETWORK TOOLS</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-CHIP</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-OTHER</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-TRX</fullName>
            </value>
            <value>
                <fullName>PASSIVES</fullName>
            </value>
            <value>
                <fullName>ROADM</fullName>
            </value>
            <value>
                <fullName>SUB 10 GIG</fullName>
            </value>
            <value>
                <fullName>SWMODULES</fullName>
            </value>
            <value>
                <fullName>SW MODULES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/S_D_End_Date__c.field-meta.xml
<CustomField>
    <fullName>S_D_End_Date__c</fullName>
    <label>S&amp;D End Date</label>
    <type>Date</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/S_D_Line_End_Date__c.field-meta.xml
<CustomField>
    <fullName>S_D_Line_End_Date__c</fullName>
    <label>S&amp;D Line End Date</label>
    <type>Date</type>
</CustomField>

src/classes/QuoteLinesHelper.cls
public class QuoteLinesHelper {
    public static Boolean isUpdatedQuoteSDEndDate = False;
    public static void updatedQuoteSDEnddate(List<Quote_Item__c> quoteItems, Map<Id,Quote_Item__c> oldMap){
        IF(!isUpdatedQuoteSDEndDate){
            isUpdatedQuoteSDEndDate =True;
            List<Id>quoteIds = new List<Id>();
            Map<Id, Date> quoteEndateMap = new Map<Id, Date>();
            Set<Id> noEndDateQuotes = new Set<Id>();
            List<Quote> updateQuotes = new List<Quote>();
            for(Quote_Item__c quoteItm : quoteItems){
                if(quoteItm.S_D_Line_End_Date__c != null && 
                   oldMap.get(quoteItm.Id).S_D_Line_End_Date__c != quoteItm.S_D_Line_End_Date__c)
                    quoteIds.add(quoteItm.Quote__c);
            }
            if(quoteIds != null && !quoteIds.isEmpty()){
                for(Quote_Item__c qItem : [SELECT Id, Quote__c,S_D_Line_End_Date__c 
                                           FROM Quote_Item__c 
                                           WHERE Quote__c IN :quoteIds]){
                                               if(qItem.S_D_Line_End_Date__c != null){
                                                   if(!noEndDateQuotes.contains(qItem.Quote__c)){
                                                       if(quoteEndateMap.containsKey(qItem.Quote__c)){
                                                           if(quoteEndateMap.get(qItem.Quote__c) < qItem.S_D_Line_End_Date__c)
                                                               quoteEndateMap.put(qItem.Quote__c, qItem.S_D_Line_End_Date__c);
                                                       } else{
                                                           quoteEndateMap.put(qItem.Quote__c, qItem.S_D_Line_End_Date__c);
                                                       }
                                                   } else {
                                                       if(quoteEndateMap.containsKey(qItem.Quote__c))
                                                           quoteEndateMap.remove(qItem.Quote__c);
                                                   }
                                               } else {
                                                   noEndDateQuotes.add(qItem.Quote__c);
                                               }
                                           }
                system.debug('noEndDateQuotes'+noEndDateQuotes);
                system.debug('quoteEndateMap'+quoteEndateMap);
                for(Quote qte :[SELECT Id,S_D_End_Date__c 
                                FROM Quote
                                WHERE Id IN :quoteEndateMap.keyset()]){
                                    if(qte.S_D_End_Date__c != quoteEndateMap.get(qte.Id)){
                                        qte.S_D_End_Date__c = quoteEndateMap.get(qte.Id);
                                        updateQuotes.add(qte);
                                    }
                                }
                system.debug('updateQuotes'+updateQuotes);
                if(updateQuotes != null && !updateQuotes.isEmpty()){
                    try{
                        update updateQuotes;
                    } catch(Exception ex){
                        system.debug('error message'+ex.getMessage());
                    }
                }
            }
        }
    }
    
    /*
Method Name : getPLMApprover
Input parameters: List of Quote Line items
Output parameter : None
Description: updates PLM Approver on quote lines based on PLM approver Matrix.
*/
    public static void getPLMApprover(List<Quote_Item__c> quoteItemList) {
        Set<String> usersSet = new Set<String>();
        Map<String, String> userNameIdMap = new Map<String, String>();
        Map<String, List<PLM_Approval_Matrix__mdt>>  productPLMApprover = new  Map<String, List<PLM_Approval_Matrix__mdt>>();
        Map<Id, Quote_Item__c> newQuoteMap = New Map<Id, Quote_Item__c>();
        Set<Id> productIdSet = new Set<Id>();  
        
        for(PLM_Approval_Matrix__mdt plmRec : [select id,Product_Group_Segment1__c,Family_Segment2__c,FamilySegmentNotOperator__c,Configuration_Segment4__c,ConfigurationNotOperator__c,FormFactorNotOperator__c,
                                               Market_Application_Segment5__c,Form_Factor_Segment3__c,MarketAppNotOperator__c,LaserNotOperator__c,Laser_Segment6__c,Detector_Segment7__c,DetectorNotOperator__c,Approver__c,Upper_Approval_Level__c
                                               from PLM_Approval_Matrix__mdt ]) {
                                                   plmRec.Product_Group_Segment1__c = plmRec.Product_Group_Segment1__c == null?'Blank':plmRec.Product_Group_Segment1__c;
                                                   if(!productPLMApprover.containsKey(plmRec.Product_Group_Segment1__c)){
                                                       productPLMApprover.put(plmRec.Product_Group_Segment1__c,new List<PLM_Approval_Matrix__mdt>{plmRec});
                                                   }else {
                                                       productPLMApprover.get(plmRec.Product_Group_Segment1__c).add(plmRec);
                                                   }
                                                   usersSet.add(plmRec.Approver__c);                                           
                                               }
        usersSet.add(Label.Default_PLM_User_Email);
        for(User uRec : [select id,name from User where isActive =: true AND Name IN :usersSet]) {
            userNameIdMap.put(uRec.Name, uRec.Id);
        }
        for(Quote_Item__c qRec:quoteItemList) {
            productIdSet.add(qRec.product__c);
        }
        Map<Id, Product2> prdMap = new Map<Id, Product2>();
        for(Product2 prd: [SELECT Id,Name,Product_Group__c,Product_Family_Text__c, 
                           Form_Factor__c,Product_Config__c,Mkt_Application__c, Laser__c, Detector__c 
                           FROM Product2 
                           WHERE Id IN :productIdSet]){
                               prdMap.put(prd.Id, prd);
                           }
        
        List<PLM_Approval_Matrix__mdt> getAllPLMBYGroup = new List<PLM_Approval_Matrix__mdt>();    
        for(Quote_Item__c prodrec :quoteItemList) {
            System.debug('prodrec'+prodrec);
            //Added product null check to avoid null pointer exception
            Product2 prd2 = new Product2();
            if(prodrec.Product__c != null){
               prd2 = prdMap.get(prodrec.Product__c); 
            }
            //list<String> userNameList = new list<String>();
            getAllPLMBYGroup.clear();
            //Added productPLMApprover map null check to avoid null pointer exception
          if(prd2.Product_Group__c != null && productPLMApprover != null && productPLMApprover.containsKey(prd2.Product_Group__c)  ){
                if(productPLMApprover.get(prd2.Product_Group__c) != null){
                getAllPLMBYGroup.addall(productPLMApprover.get(prd2.Product_Group__c));
            
               }
                
                //May22 Changes addition of all blank Records into Map also.So they could be taken for calculation 
                
                getAllPLMBYGroup.addall(productPLMApprover.get('Blank'));
            }else {
                getAllPLMBYGroup.addall(productPLMApprover.get('Blank'));
            }
            
            if(getAllPLMBYGroup.size()>0) {
                for(PLM_Approval_Matrix__mdt plmRec: getAllPLMBYGroup) {
                    if(plmRec.Family_Segment2__c != null && 
                       plmRec.Family_Segment2__c != '' && 
                       (String.isNotBlank(prd2.Product_Family_Text__c) && plmRec.Family_Segment2__c.contains(prd2.Product_Family_Text__c)) &&
                       plmRec.FamilySegmentNotOperator__c == true ){
                           continue;
                       } else if (plmRec.Family_Segment2__c == null || 
                                  (String.isNotBlank(prd2.Product_Family_Text__c) && plmRec.Family_Segment2__c.contains(prd2.Product_Family_Text__c))  || 
                                  plmRec.FamilySegmentNotOperator__c == true) {
                                      if(plmRec.Form_Factor_Segment3__c != null && 
                                         (String.isNotBlank(prd2.Form_Factor__c) && plmRec.Form_Factor_Segment3__c.contains(prd2.Form_Factor__c)) && 
                                         plmRec.FormFactorNotOperator__c == true){
                                             continue;
                                         } else if (plmRec.Form_Factor_Segment3__c == null || 
                                                    (String.isNotBlank(prd2.Form_Factor__c) && plmRec.Form_Factor_Segment3__c.contains(prd2.Form_Factor__c)) ||  
                                                    plmRec.FormFactorNotOperator__c == true) { 
                                                        if(plmRec.Configuration_Segment4__c != null && 
                                                           (String.isNotBlank(prd2.Product_Config__c) && plmRec.Configuration_Segment4__c.contains(prd2.Product_Config__c)) && 
                                                           plmRec.ConfigurationNotOperator__c == true){
                                                               continue;
                                                           } else if (plmRec.Configuration_Segment4__c == null || 
                                                                      (String.isNotBlank(prd2.Product_Config__c) && plmRec.Configuration_Segment4__c.contains(prd2.Product_Config__c)) ||  
                                                                      plmRec.ConfigurationNotOperator__c == true) {
                                                                          if(plmRec.Market_Application_Segment5__c !=null && 
                                                                             (String.isNotBlank(prd2.Mkt_Application__c) && plmRec.Market_Application_Segment5__c.contains(prd2.Mkt_Application__c)) && 
                                                                             plmRec.MarketAppNotOperator__c == true){
                                                                                 continue;
                                                                             }else if (plmRec.Market_Application_Segment5__c == null || 
                                                                                       (String.isNotBlank(prd2.Mkt_Application__c) && plmRec.Market_Application_Segment5__c.contains(prd2.Mkt_Application__c)) ||
                                                                                       plmRec.MarketAppNotOperator__c == true) {
                                                                                           if(plmRec.Laser_Segment6__c != null && 
                                                                                              (String.isNotBlank(prd2.Laser__c) && plmRec.Laser_Segment6__c.contains(prd2.Laser__c)) && 
                                                                                              plmRec.LaserNotOperator__c == true){
                                                                                                  continue;
                                                                                              } else if (plmRec.Laser_Segment6__c == null || 
                                                                                                         (String.isNotBlank(prd2.Laser__c) && plmRec.Laser_Segment6__c.contains(prd2.Laser__c)) ||  
                                                                                                         plmRec.LaserNotOperator__c == true) { 
                                                                                                             if(plmRec.Detector_Segment7__c !=null && 
                                                                                                                (String.isNotBlank(prd2.Detector__c) && plmRec.Detector_Segment7__c.contains(prd2.Detector__c)) && 
                                                                                                                plmRec.DetectorNotOperator__c == true){
                                                                                                                    continue;
                                                                                                                } else if(plmRec.Detector_Segment7__c == null || 
                                                                                                                          (String.isNotBlank(prd2.Detector__c) && plmRec.Detector_Segment7__c.contains(prd2.Detector__c)) || 
                                                                                                                          plmRec.DetectorNotOperator__c == true) {
                                                                                                                              prodrec.PLM_Approver__c = userNameIdMap.get(plmRec.Approver__c);
                                                                                                                              prodrec.Approver_3M__c = userNameIdMap.get(plmRec.Upper_Approval_Level__c);
                                                                                                                              newQuoteMap.put(prodrec.id, prodrec);
                                                                                                                          }
                                                                                                         } else  {
                                                                                                             continue;
                                                                                                         }
                                                                                           
                                                                                       } else {
                                                                                           continue;
                                                                                       }
                                                                      }else {
                                                                          continue;
                                                                      }
                                                        
                                                    } else {
                                                        continue;
                                                    }
                                  }
                    else {
                        continue;
                    }
                    
                }
                //May22 Changes defaulting to betty when no Plm is there.Label contains betty's name       
                IF(!newQuoteMap.containskey(prodrec.Id) && userNameIdMap.containskey(Label.Default_PLM_User_Email)){
                    prodrec.PLM_Approver__c = userNameIdMap.get(Label.Default_PLM_User_Email);
                    newQuoteMap.put(prodrec.id, prodrec);
                }
            }
        }
    }
    public static void updateBuonQuote(List<Quote_Item__c> deletedLines){
        Set<Id> quoteIds = new Set<Id>();
        Map<Id, String> quoteMap = new Map<Id, String>();
        for(Quote_Item__c line : deletedLines){
            quoteIds.add(line.Quote__c);
            quoteMap.put(line.Quote__c, null);
        }
        for(Quote_Item__c lin : [SELECT Id,Product__r.BU_Code__c, Quote__c, Product__r.Product_Family__c
                                 FROM Quote_Item__c 
                                 WHERE Quote__c IN :quoteMap.keySet()]){
                                     if(lin.Product__r.BU_Code__c == '0040' &&
                                        lin.Product__r.Product_Family__c != 'WSS-OIG' && 
                                        lin.Product__r.Product_Family__c != 'WSS-OCM'){
                                            quoteMap.put(lin.Quote__c, 'WSS');
                                        } else{
                                            quoteMap.put(lin.Quote__c, 'Non WSS');
                                        }
                                 }
        List<Quote> updateQuotes = new List<Quote>();
        for(Id quoteId :quoteMap.keySet()){
            updateQuotes.add(new Quote(Id = quoteId, BusinessUnit__c = quoteMap.get(quoteId)));
        }
        if(updateQuotes != null && !updateQuotes.isEmpty()){
            update updateQuotes;
        }
    }
}