src/objects/PLM_Approval_Matrix__mdt/PLM_Approval_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>PLM Approval Matrix</label>
    <pluralLabel>PLM Approval Matrix</pluralLabel>
</CustomObject>

src/objects/PLM_Approval_Matrix__mdt/fields/Configuration_Segment4__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment4__c</fullName>
    <label>Configuration (Segment4)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/ConfigurationNotOperator__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ConfigurationNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Detector_Segment7__c.field-meta.xml
<CustomField>
    <fullName>Detector_Segment7__c</fullName>
    <label>Detector (Segment7)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/DetectorNotOperator__c.field-meta.xml
<CustomField>
    <fullName>DetectorNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DetectorNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Family_Segment2__c.field-meta.xml
<CustomField>
    <fullName>Family_Segment2__c</fullName>
    <label>Family (Segment2)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/FamilySegmentNotOperator__c.field-meta.xml
<CustomField>
    <fullName>FamilySegmentNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FamilySegmentNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Form_Factor_Segment3__c.field-meta.xml
<CustomField>
    <fullName>Form_Factor_Segment3__c</fullName>
    <label>Form Factor (Segment3)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/FormFactorNotOperator__c.field-meta.xml
<CustomField>
    <fullName>FormFactorNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FormFactorNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Laser_Segment6__c.field-meta.xml
<CustomField>
    <fullName>Laser_Segment6__c</fullName>
    <label>Laser (Segment6)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/LaserNotOperator__c.field-meta.xml
<CustomField>
    <fullName>LaserNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LaserNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Market_Application_Segment5__c.field-meta.xml
<CustomField>
    <fullName>Market_Application_Segment5__c</fullName>
    <label>Market Application (Segment5)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/MarketAppNotOperator__c.field-meta.xml
<CustomField>
    <fullName>MarketAppNotOperator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MarketAppNotOperator</label>
    <type>Checkbox</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Product_Group_Segment1__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_Segment1__c</fullName>
    <label>Product Group (Segment1)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/PLM_Approval_Matrix__mdt/fields/Upper_Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Upper_Approval_Level__c</fullName>
    <label>Upper Approval Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Form_Factor__c.field-meta.xml
<CustomField>
    <fullName>Form_Factor__c</fullName>
    <label>Form Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>168 PIN</fullName>
            </value>
            <value>
                <fullName>17PIN</fullName>
            </value>
            <value>
                <fullName>1RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>1X20 PIN</fullName>
            </value>
            <value>
                <fullName>28PIN</fullName>
            </value>
            <value>
                <fullName>2RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>2X10 PIN</fullName>
            </value>
            <value>
                <fullName>2X5 PIN</fullName>
            </value>
            <value>
                <fullName>2X6 PIN</fullName>
            </value>
            <value>
                <fullName>2X7 PIN</fullName>
            </value>
            <value>
                <fullName>300 PIN</fullName>
            </value>
            <value>
                <fullName>300PIN-LFF</fullName>
            </value>
            <value>
                <fullName>300PIN-SFF</fullName>
            </value>
            <value>
                <fullName>3RU CHASSIS</fullName>
            </value>
            <value>
                <fullName>41PN CNSMR</fullName>
            </value>
            <value>
                <fullName>9PIN</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER MODULE</fullName>
            </value>
            <value>
                <fullName>BOA</fullName>
            </value>
            <value>
                <fullName>CDFP</fullName>
            </value>
            <value>
                <fullName>CFP</fullName>
            </value>
            <value>
                <fullName>CFP2</fullName>
            </value>
            <value>
                <fullName>CFP4</fullName>
            </value>
            <value>
                <fullName>CFP8</fullName>
            </value>
            <value>
                <fullName>Chip</fullName>
            </value>
            <value>
                <fullName>Chip-on-Carrier</fullName>
            </value>
            <value>
                <fullName>CUSTOMENCL</fullName>
            </value>
            <value>
                <fullName>CUSTOM LINECARD</fullName>
            </value>
            <value>
                <fullName>CXP</fullName>
            </value>
            <value>
                <fullName>DIE</fullName>
            </value>
            <value>
                <fullName>ENDURANCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Config__c.field-meta.xml
<CustomField>
    <fullName>Product_Config__c</fullName>
    <label>Product Config</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4CHWDMXCVR</fullName>
            </value>
            <value>
                <fullName>8CHWDMXCVR</fullName>
            </value>
            <value>
                <fullName>ANTEC</fullName>
            </value>
            <value>
                <fullName>AZNA-CML</fullName>
            </value>
            <value>
                <fullName>BETA/GAMMA</fullName>
            </value>
            <value>
                <fullName>BIG BEAR</fullName>
            </value>
            <value>
                <fullName>BROADWAY</fullName>
            </value>
            <value>
                <fullName>C-COR</fullName>
            </value>
            <value>
                <fullName>CADDO</fullName>
            </value>
            <value>
                <fullName>CWDMPASS</fullName>
            </value>
            <value>
                <fullName>DWDMPASS</fullName>
            </value>
            <value>
                <fullName>EQUALIZED</fullName>
            </value>
            <value>
                <fullName>FIRA</fullName>
            </value>
            <value>
                <fullName>GENNUM</fullName>
            </value>
            <value>
                <fullName>I32X</fullName>
            </value>
            <value>
                <fullName>ICDR</fullName>
            </value>
            <value>
                <fullName>IFFO</fullName>
            </value>
            <value>
                <fullName>INTERLEAVE</fullName>
            </value>
            <value>
                <fullName>IPX</fullName>
            </value>
            <value>
                <fullName>KODEOS</fullName>
            </value>
            <value>
                <fullName>MICROSEMI</fullName>
            </value>
            <value>
                <fullName>MOTOROLA</fullName>
            </value>
            <value>
                <fullName>OMEGA</fullName>
            </value>
            <value>
                <fullName>OPTIUM</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PARALLEL</fullName>
            </value>
            <value>
                <fullName>PATHFINDER</fullName>
            </value>
            <value>
                <fullName>RED-C</fullName>
            </value>
            <value>
                <fullName>SAMSUNG</fullName>
            </value>
            <value>
                <fullName>SMART LDPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Family_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Text__c</fullName>
    <formula>TEXT( Product_Family__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family Text</label>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;10 GIG</fullName>
            </value>
            <value>
                <fullName>100 GIG</fullName>
            </value>
            <value>
                <fullName>10 GIG</fullName>
            </value>
            <value>
                <fullName>16-32 GIG</fullName>
            </value>
            <value>
                <fullName>200 GIG</fullName>
            </value>
            <value>
                <fullName>25 GIG</fullName>
            </value>
            <value>
                <fullName>3D SENSORS</fullName>
            </value>
            <value>
                <fullName>400 GIG</fullName>
            </value>
            <value>
                <fullName>40 GIG</fullName>
            </value>
            <value>
                <fullName>800 GIG</fullName>
            </value>
            <value>
                <fullName>ACCESSORIES</fullName>
            </value>
            <value>
                <fullName>ACTIVES</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER</fullName>
            </value>
            <value>
                <fullName>ANALOG</fullName>
            </value>
            <value>
                <fullName>ANALOG-ISR</fullName>
            </value>
            <value>
                <fullName>ANALOG-US</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>CDAUI-16</fullName>
            </value>
            <value>
                <fullName>CDAUI-8</fullName>
            </value>
            <value>
                <fullName>LW/SONET MODULE</fullName>
            </value>
            <value>
                <fullName>LWMODULES</fullName>
            </value>
            <value>
                <fullName>NETWORK TOOLS</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-CHIP</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-OTHER</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-TRX</fullName>
            </value>
            <value>
                <fullName>PASSIVES</fullName>
            </value>
            <value>
                <fullName>ROADM</fullName>
            </value>
            <value>
                <fullName>SUB 10 GIG</fullName>
            </value>
            <value>
                <fullName>SWMODULES</fullName>
            </value>
            <value>
                <fullName>SW MODULES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/RMA_Request_Line__c.object-meta.xml
<CustomObject>
    <label>RMA Request Line</label>
    <nameField>
        <label>Customer Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMA_Request_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>RMA Request Lines</relationshipLabel>
    <relationshipName>RMA_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <inlineHelpText>This is the RMA Request to which this line item looks up</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RMA Request Lines</relationshipLabel>
    <relationshipName>RMA_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/RMARequestLineHelper.cls
public class RMARequestLineHelper {
    /*
Method Name : updateCasePLM
Input parameters: List of RMA Line items
Output parameter : None
Description: updates PLM Approver on case based on PLM approver Matrix.
*/ 
    public static void updateCasePLM(List<RMA_Request_Line__c> rmas){
        Set<Id> rmaIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        //Set<String> usersSet = new Set<String>();
        Map<Id, Set<Id>> rmaProductMap = new Map<Id, Set<Id>>();
        Map<Id, String> productPlmMap = new Map<Id, String>();
        Map<String, Id> userMap = new Map<String, Id>();
        List<PLM_Approval_Matrix__mdt> getAllPLMBYGroup = new List<PLM_Approval_Matrix__mdt>();
        Map<String, List<PLM_Approval_Matrix__mdt>>  productPLMApprover = new  Map<String, List<PLM_Approval_Matrix__mdt>>();
        for(RMA_Request_Line__c line : rmas){
            rmaIds.add(line.RMA_Request__c);
        }
        for(RMA_Request_Line__c allLine : [SELECT Id,Product__c,RMA_Request__c 
                                           FROM RMA_Request_Line__c
                                           WHERE RMA_Request__c IN : rmaIds]){
                                               if(rmaProductMap.containsKey(allLine.RMA_Request__c)){
                                                   rmaProductMap.get(allLine.RMA_Request__c).add(allLine.Product__c);
                                               } else {
                                                   rmaProductMap.put(allLine.RMA_Request__c, new Set<Id>{allLine.Product__c});
                                               }
                                               productIds.add(allLine.Product__c);
                                           }
        for(PLM_Approval_Matrix__mdt plmRec : [select id,Product_Group_Segment1__c,Family_Segment2__c,FamilySegmentNotOperator__c,Configuration_Segment4__c,ConfigurationNotOperator__c,FormFactorNotOperator__c,
                                               Market_Application_Segment5__c,Form_Factor_Segment3__c,MarketAppNotOperator__c,LaserNotOperator__c,Laser_Segment6__c,Detector_Segment7__c,DetectorNotOperator__c,Approver__c,Upper_Approval_Level__c
                                               from PLM_Approval_Matrix__mdt ]) {
                                                   plmRec.Product_Group_Segment1__c = plmRec.Product_Group_Segment1__c == null?'Blank':plmRec.Product_Group_Segment1__c;
                                                   if(!productPLMApprover.containsKey(plmRec.Product_Group_Segment1__c)){
                                                       productPLMApprover.put(plmRec.Product_Group_Segment1__c,new List<PLM_Approval_Matrix__mdt>{plmRec});
                                                   }else {
                                                       productPLMApprover.get(plmRec.Product_Group_Segment1__c).add(plmRec);
                                                   }
                                                  // usersSet.add(plmRec.Approver__c);                                           
                                               }
        for(Product2 prd: [SELECT Id,Name,Product_Group__c,Product_Family_Text__c, 
                           Form_Factor__c,Product_Config__c,Mkt_Application__c, Laser__c, Detector__c 
                           FROM Product2 
                           WHERE Id IN :productIds]){
                               getAllPLMBYGroup.clear();
                               if(prd.Product_Group__c != null && 
                                  productPLMApprover.containsKey(prd.Product_Group__c)){
                                      getAllPLMBYGroup.addall(productPLMApprover.get(prd.Product_Group__c));
                                      getAllPLMBYGroup.addall(productPLMApprover.get('Blank'));
                                  }else {
                                      getAllPLMBYGroup.addall(productPLMApprover.get('Blank'));
                                  }
                               
                               for(PLM_Approval_Matrix__mdt plmRec: getAllPLMBYGroup) {
                                   if(plmRec.Family_Segment2__c != null && 
                                      plmRec.Family_Segment2__c != '' && 
                                      (String.isNotBlank(prd.Product_Family_Text__c) && 
                                       plmRec.Family_Segment2__c.contains(prd.Product_Family_Text__c)) &&
                                      plmRec.FamilySegmentNotOperator__c == true ){
                                          continue;
                                      } else if (plmRec.Family_Segment2__c == null || 
                                                 (String.isNotBlank(prd.Product_Family_Text__c) && 
                                                  plmRec.Family_Segment2__c.contains(prd.Product_Family_Text__c))  || 
                                                 plmRec.FamilySegmentNotOperator__c == true) {
                                                     if(plmRec.Form_Factor_Segment3__c != null && 
                                                        (String.isNotBlank(prd.Form_Factor__c) && 
                                                         plmRec.Form_Factor_Segment3__c.contains(prd.Form_Factor__c)) && 
                                                        plmRec.FormFactorNotOperator__c == true){
                                                            continue;
                                                        } else if (plmRec.Form_Factor_Segment3__c == null || 
                                                                   (String.isNotBlank(prd.Form_Factor__c) &&
                                                                    plmRec.Form_Factor_Segment3__c.contains(prd.Form_Factor__c)) ||  
                                                                   plmRec.FormFactorNotOperator__c == true) { 
                                                                       if(plmRec.Configuration_Segment4__c != null && 
                                                                          (String.isNotBlank(prd.Product_Config__c) && 
                                                                           plmRec.Configuration_Segment4__c.contains(prd.Product_Config__c)) && 
                                                                          plmRec.ConfigurationNotOperator__c == true){
                                                                              continue;
                                                                          } else if (plmRec.Configuration_Segment4__c == null || 
                                                                                     (String.isNotBlank(prd.Product_Config__c) && 
                                                                                      plmRec.Configuration_Segment4__c.contains(prd.Product_Config__c)) ||  
                                                                                     plmRec.ConfigurationNotOperator__c == true) {
                                                                                         if(plmRec.Market_Application_Segment5__c !=null && 
                                                                                            (String.isNotBlank(prd.Mkt_Application__c) && 
                                                                                             plmRec.Market_Application_Segment5__c.contains(prd.Mkt_Application__c)) && 
                                                                                            plmRec.MarketAppNotOperator__c == true){
                                                                                                continue;
                                                                                            }else if (plmRec.Market_Application_Segment5__c == null || 
                                                                                                      (String.isNotBlank(prd.Mkt_Application__c) &&
                                                                                                       plmRec.Market_Application_Segment5__c.contains(prd.Mkt_Application__c)) ||
                                                                                                      plmRec.MarketAppNotOperator__c == true) {
                                                                                                          if(plmRec.Laser_Segment6__c != null && 
                                                                                                             (String.isNotBlank(prd.Laser__c) && 
                                                                                                              plmRec.Laser_Segment6__c.contains(prd.Laser__c)) && 
                                                                                                             plmRec.LaserNotOperator__c == true){
                                                                                                                 continue;
                                                                                                             } else if (plmRec.Laser_Segment6__c == null || 
                                                                                                                        (String.isNotBlank(prd.Laser__c) && 
                                                                                                                         plmRec.Laser_Segment6__c.contains(prd.Laser__c)) ||  
                                                                                                                        plmRec.LaserNotOperator__c == true) { 
                                                                                                                            if(plmRec.Detector_Segment7__c !=null && 
                                                                                                                               (String.isNotBlank(prd.Detector__c) && 
                                                                                                                                plmRec.Detector_Segment7__c.contains(prd.Detector__c)) && 
                                                                                                                               plmRec.DetectorNotOperator__c == true){
                                                                                                                                   continue;
                                                                                                                               } else if(plmRec.Detector_Segment7__c == null || 
                                                                                                                                         (String.isNotBlank(prd.Detector__c) && 
                                                                                                                                          plmRec.Detector_Segment7__c.contains(prd.Detector__c)) || 
                                                                                                                                         plmRec.DetectorNotOperator__c == true) {
                                                                                                                                             productPlmMap.put(prd.id, plmRec.Approver__c);
                                                                                                                                             // prodrec.PLM_Approver__c = userNameIdMap.get(plmRec.Approver__c);
                                                                                                                                             //  prodrec.Approver_3M__c = userNameIdMap.get(plmRec.Upper_Approval_Level__c);
                                                                                                                                             //  newQuoteMap.put(prodrec.id, prodrec);
                                                                                                                                         }
                                                                                                                        } else  {
                                                                                                                            continue;
                                                                                                                        }
                                                                                                          
                                                                                                      } else {
                                                                                                          continue;
                                                                                                      }
                                                                                     }else {
                                                                                         continue;
                                                                                     }
                                                                       
                                                                   } else {
                                                                       continue;
                                                                   }
                                                 }
                                   else {
                                       continue;
                                   }
                                   
                               }
                           }
        Map<Id, string> casePlmMap = new Map<Id, String>();
        system.debug('rmaProductMap'+rmaProductMap);
        for(Id caseId : rmaProductMap.keySet()){
            String plm = '';
            for(Id productId : rmaProductMap.get(caseId)){
                if(productPlmMap.containsKey(productId) && String.isEmpty(plm)){
                    plm = productPlmMap.get(productId);
                } else if(productPlmMap.containsKey(productId) && plm != productPlmMap.get(productId)){
                    plm = 'Steffen Koehler';
                }
            }
            casePlmMap.put(caseId, plm);
        }
        for(User usr :[SELECT Id, Name FROM User WHERE Name IN :casePlmMap.values()]){
            userMap.put(usr.Name, usr.Id);
        }
        List<Case> updateCasePLM = new List<Case>();
        for(id caseId : casePlmMap.keySet()){
            Case cs = new Case(Id = caseId, PLM__c = userMap.get(casePlmMap.get(caseId)));
            updateCasePLM.add(cs);
        }
        system.debug('updateCasePLM'+updateCasePLM);
        if(updateCasePLM != null && !updateCasePLM.isEmpty()){
            update updateCasePLM;
        }
    }
    
}