src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Approval_From__c.field-meta.xml
<CustomField>
    <fullName>Approval_From__c</fullName>
    <formula>IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot; ,IF( Target_Price__c &lt; RSM_Min__c ,&apos;BothApprovers&apos;, IF( Target_Price__c &lt; REP_Min__c ,&apos;RSM&apos;,IF(ISNULL(RSM_Min__c)||ISNULL(REP_Min__c),&apos;BothApprovers&apos;,&apos;None&apos;))), 
IF(ISNULL(RSM_Min__c),IF(OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), 
IF( Target_Price__c &lt; RSM_Min__c,IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)) ,&apos;None&apos;,&apos;RSM&apos;))))</formula>
    <label>Approval From</label>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Lost - Delivery</fullName>
            </value>
            <value>
                <fullName>Lost - Price</fullName>
            </value>
            <value>
                <fullName>Lost - Technical</fullName>
            </value>
            <value>
                <fullName>One Time Order Processed</fullName>
            </value>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Canceled</fullName>
            </value>
            <value>
                <fullName>Project Cancelled</fullName>
            </value>
            <value>
                <fullName>Approval Cycle Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/PLM_Approval__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approval__c</fullName>
    <label>PLM Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/PLM_Approver__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PLM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>PLM Approver</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>MVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approval__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approval__c</fullName>
    <label>RSM Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/QuoteReminderBatch.cls
public class QuoteReminderBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select id,targetobjectId,(Select id,ActorId,OriginalActorId from workitems) from processInstance where TargetObject.Name like 'QN-%' and status ='Pending']);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug('scope'+scope);
        Map<Id,Set<Id>> quoteItemsPendingForApprovalMap = New Map<Id,Set<Id>>();
        Map<Id,MAP<Id,String>> mapOfQuoteIdCreatorIdEmail = New Map<Id,MAP<Id,String>>();
        Map<Id,List<Quote_Item__c>> mapOfQuoteIdAndLineItems = New Map<Id,List<Quote_Item__c>>();
        List<Quote_Item__c> ListOfRSMApprovers = New List<Quote_Item__c>();
        List<Quote_Item__c> ListOfPLmApprovers = New List<Quote_Item__c>();
        Map<Id,Quote_Item__c> mapOfQuoteItemToBeUpdated = New Map<Id,Quote_Item__c>();
        For(sobject sobj:scope){
            System.debug('sobj'+sobj);
            IF(sobj.getSObjects('workitems')!=Null){
                FOR(processInstanceWorkItem piwObj :sobj.getSObjects('workitems')){
                    IF(quoteItemsPendingForApprovalMap.containskey((Id)sobj.get('TargetObjectId'))){
                        quoteItemsPendingForApprovalMap.get((Id)sobj.get('TargetObjectId')).add(piwObj.OriginalActorId);
                    }Else{
                        quoteItemsPendingForApprovalMap.put((Id)sobj.get('TargetObjectId'),New Set<ID>{piwObj.OriginalActorId});
                        
                    }
                }
            }
        }
        For(Quote_Item__c quoteItemObj:[Select Id,Quote__c,Quote__r.createdByID,Quote__r.createdBy.Email,RSM_Approver__c,PLM_Approver__c,Line_Status__c,Approval_From__c,RSM_Approval__c,PLM_Approval__c 
                                        from Quote_Item__c 
                                        where id in :quoteItemsPendingForApprovalMap.keySet() And Approval_From__c ='BothApprovers']){
            If(mapOfQuoteIdAndLineItems.containskey(quoteItemObj.quote__c)){
                mapOfQuoteIdAndLineItems.get(quoteItemObj.quote__c).add(quoteItemObj);
            }
            else{
                mapOfQuoteIdAndLineItems.put(quoteItemObj.quote__c,New List<Quote_Item__c>{quoteItemObj});
            }
            
        }
        For(Id quoteId:mapOfQuoteIdAndLineItems.keyset()){
            Boolean RSmApproverPresent =False;
            Boolean PLMApproverPresent = False;
            Map<ID,String> mapofcreatorIdandEmail = New Map<ID,String>();
            // mapofcreatorIdandEmail.put(mapOfQuoteIdAndLineItems.get(quoteId).get(0).Quote__r.createdByID,mapOfQuoteIdAndLineItems.get(quoteId).get(0).Quote__r.createdBy.Email));
            For(Quote_Item__c quoteItemObj :mapOfQuoteIdAndLineItems.get(quoteId)){
                mapofcreatorIdandEmail.put(mapOfQuoteIdAndLineItems.get(quoteId).get(0).Quote__r.createdByID,mapOfQuoteIdAndLineItems.get(quoteId).get(0).Quote__r.createdBy.Email);
                IF(quoteItemsPendingForApprovalMap.get(quoteItemObj.Id).contains(quoteItemObj.RSM_Approver__c)){
                    RSmApproverPresent = True;
                }
                IF(quoteItemsPendingForApprovalMap.get(quoteItemObj.Id).contains(quoteItemObj.PLM_Approver__c)){
                    PLMApproverPresent = True;
                }
            }
            IF(RSmApproverPresent ^ PLMApproverPresent){
                mapOfQuoteIdCreatorIdEmail.put(quoteId,mapofcreatorIdandEmail);
                IF(RSmApproverPresent){
                    ListOfPLMApprovers.addall(mapOfQuoteIdAndLineItems.get(quoteId));
                }
                IF(PLMApproverPresent){
                    ListOfRSMApprovers.addall(mapOfQuoteIdAndLineItems.get(quoteId));
                }
                
            }
        }
        FOR(Quote_Item__c quoteItemObj:ListOfRSMApprovers){
            quoteItemObj.RSM_Approval__c ='Approved';
            quoteItemObj.PLM_Approval__c = 'Approval Pending';
            mapOfQuoteItemToBeUpdated.put(quoteItemObj.Id,quoteItemObj);
        }
        FOR(Quote_Item__c quoteItemObj:ListOfPLMApprovers){
            quoteItemObj.PLM_Approval__c ='Approved';
            quoteItemObj.RSM_Approval__c = 'Approval Pending';
            mapOfQuoteItemToBeUpdated.put(quoteItemObj.Id,quoteItemObj);
            
        }
        
        IF(!mapOfQuoteItemToBeUpdated.isempty()){
            update mapOfQuoteItemToBeUpdated.values();
        }
        System.debug('QuoteCreatorIdSet'+mapOfQuoteIdCreatorIdEmail);
        List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
        EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Quote_Reminder_To_Creator_Reminder'];
        FOR(Id quoteId :mapOfQuoteIdCreatorIdEmail.keySet()){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(et.id);
            mail.setToAddresses(New List < String > {
                mapOfQuoteIdCreatorIdEmail.get(quoteId).values().get(0)
                    });
            mail.setTargetObjectId(new list<Id>(mapOfQuoteIdCreatorIdEmail.get(quoteId).keyset())[0]);
            mail.setSaveAsActivity(false);
            mail.setWhatId(quoteId);
            mailList.add(mail);
        }
        System.debug('MailList'+mailList );
        Messaging.sendEmail(mailList);
    }
    
    public void finish(Database.BatchableContext BC){
    }
}