src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Approval_From__c.field-meta.xml
<CustomField>
    <fullName>Approval_From__c</fullName>
    <formula>IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot; ,IF( Target_Price__c &lt; RSM_Min__c ,&apos;BothApprovers&apos;, IF( Target_Price__c &lt; REP_Min__c ,&apos;RSM&apos;,IF(ISNULL(RSM_Min__c)||ISNULL(REP_Min__c),&apos;BothApprovers&apos;,&apos;None&apos;))), 
IF(ISNULL(RSM_Min__c),IF(OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), 
IF( Target_Price__c &lt; RSM_Min__c,IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)) ,&apos;None&apos;,&apos;RSM&apos;))))</formula>
    <label>Approval From</label>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/PLM_Approver__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PLM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>PLM Approver</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>MVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/SendEmailsToRSMPLM.cls
public class SendEmailsToRSMPLM {
    
     public class QuoteParameters{
        @InvocableVariable(required=true)
        public Id quoteId;
        @InvocableVariable(required=true)
        public String TemplateName;
		 @InvocableVariable(required=true)	        
         public String Status; 
    }
    
    @InvocableMethod
    public static void sendEmailsToRSMandPLM(QuoteParameters[] quoteParamters) {
        set<id> userIds = New Set<id>();
        List<String> statusList = quoteParamters.get(0).Status.split(',');
        System.debug('statusList'+statusList);
        List<Quote_item__c> quoteItemsList = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(quoteParamters.get(0).quoteId,statusList);
        System.debug('quoteItemsList'+quoteItemsList);
        if(quoteItemsList.size()>0){
            for(Quote_item__c qitemObj:quoteItemsList){
                if(qitemObj.RSM_Approver__c!=Null && (qitemObj.Approval_From__c=='BothApprovers' || qitemObj.approval_From__c=='RSM')){
                    userIds.add(qitemObj.RSM_Approver__c);
                    System.debug('userIds'+userIds);
                }
                if(qitemObj.PLM_Approver__c!=Null && (qitemObj.Approval_From__c=='BothApprovers' || qitemObj.approval_From__c=='PLM')){
                    userIds.add(qitemObj.PLM_Approver__c);
                    System.debug('userIds'+userIds);
                }
            }
            
            RecordsLineItemApprovalHelper.sendEmailwithTemplete(userIds,quoteParamters.get(0).quoteId,quoteParamters.get(0).TemplateName);
        }
    }
}