src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/PLM_Approver__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PLM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>PLM Approver</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>MVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/SendReminderEmailToRSMPLM.cls
public class SendReminderEmailToRSMPLM {
	public class QuoteParameters 
    {@InvocableVariable(required = true)
		public Id quoteId;
     @InvocableVariable(required = true)
		public String TemplateName;
     @InvocableVariable(required = true)
		public String Status;
	}

	@InvocableMethod
	public static void sendEmailsToRSMandPLM(QuoteParameters[] quoteParamters) {
		set < id > userIds = New Set < id > ();
		List < String > statusList = quoteParamters.get(0).Status.split(',');
		List < Quote_item__c > quoteItemsList = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(quoteParamters.get(0).quoteId, statusList);
		Map < Id,set < id >> mapOfApprovalPending = New Map < Id,set < id >> ();
		for (ProcessInstanceWorkitem piwObj: [Select Id, ActorId, ProcessInstance.TargetObjectId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId in :quoteItemsList]) {
			if (mapOfApprovalPending.containskey(piwObj.ProcessInstance.TargetObjectId)) {
				mapOfApprovalPending.get(piwObj.ProcessInstance.TargetObjectId).add(piwObj.ActorId);
			}
			else {
				mapOfApprovalPending.put(piwObj.ProcessInstance.TargetObjectId, New Set < Id > {
					piwObj.ActorId
				});
			}
		}

		if (quoteItemsList.size() > 0) {
			for (Quote_item__c qitemObj: quoteItemsList) {
				IF(mapOfApprovalPending.containskey(qitemObj.id)) {
					If(qitemObj.RSM_Approver__c != Null && mapOfApprovalPending.get(qitemObj.id).contains(qitemObj.RSM_Approver__c)) {
						userIds.add(qitemObj.RSM_Approver__c);
					}
					If(qitemObj.PLM_Approver__c != Null && mapOfApprovalPending.get(qitemObj.id).contains(qitemObj.PLM_Approver__c)) {
						userIds.add(qitemObj.PLM_Approver__c);
					}
				}
			}

			RecordsLineItemApprovalHelper.sendEmailwithTemplete(userIds, quoteParamters.get(0).quoteId, quoteParamters.get(0).TemplateName);
		}
	}
}