src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Case/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Containment__c.field-meta.xml
<CustomField>
    <fullName>Containment__c</fullName>
    <label>Containment</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Corrective_Action__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Action__c</fullName>
    <label>Corrective Action</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Customer_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Serial_Number__c</fullName>
    <label>Customer Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Date_Code__c.field-meta.xml
<CustomField>
    <fullName>Date_Code__c</fullName>
    <label>Date Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <inlineHelpText>FA Findings</inlineHelpText>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Failure_Mechanism__c.field-meta.xml
<CustomField>
    <fullName>Failure_Mechanism__c</fullName>
    <label>Failure Mechanism</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/RC_Analysis__c.field-meta.xml
<CustomField>
    <fullName>RC_Analysis__c</fullName>
    <label>RC Analysis</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Risk_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment__c</fullName>
    <label>Risk Assessment</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/recordTypes/FA_Analysis.recordType-meta.xml
<RecordType>
    <fullName>FA_Analysis</fullName>
    <active>true</active>
    <label>FA Analysis</label>
</RecordType>

src/objects/FA_FV_Detail__c/FA_FV_Detail__c.object-meta.xml
<CustomObject>
    <label>FV/FA Detail</label>
    <nameField>
        <displayFormat>FV/FA Analysis - {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FV/FA Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FA_FV_Detail__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FV/FA</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>FV/FA Details</relationshipLabel>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>This is the serial number to which this FA / FV is relevant</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Serial_Number__c</referenceTo>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/Failure_Modes__c/Failure_Modes__c.object-meta.xml
<CustomObject>
    <label>Failure Modes</label>
    <nameField>
        <displayFormat>Failure Mode - {00000000}</displayFormat>
        <label>Failure Modes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failure Modes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Failure_Modes__c/fields/FAFV_Analysis__c.field-meta.xml
<CustomField>
    <fullName>FAFV_Analysis__c</fullName>
    <label>FV/FA Analysis</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Failure Modes</relationshipLabel>
    <relationshipName>Failure_Modes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Order/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <description>Oracle - Update this field</description>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the related RMA Request</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <formula>Order__r.End_Customer__c</formula>
    <label>End Customer</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;/lightning/cmp/c__FAFVCustomUIQuickAction?c__recordId=&quot;+Id, &apos;FA FV&apos;,&apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FA FV</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/FA_FV_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Completion_Date__c</fullName>
    <label>FA/FV Completion Date</label>
    <summarizedField>Serial_Number__c.RMA_Completion_Date__c</summarizedField>
    <summaryForeignKey>Serial_Number__c.Order_Line__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Order_Line__c/fields/Marketing_Part__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Part__c</fullName>
    <formula>Part_Number__r.Marketing_P_N__c</formula>
    <label>Marketing Part #</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Request#</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>RMA_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Serial_Number__c/Serial_Number__c.object-meta.xml
<CustomObject>
    <description>This is the serial numbers for an RMA request which will be populated from Oracle</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Serial_Number__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/Customer_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Serial_Number__c</fullName>
    <label>Customer Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/Date_Code__c.field-meta.xml
<CustomField>
    <fullName>Date_Code__c</fullName>
    <label>Date Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/FA_FV_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Completion_Date__c</fullName>
    <label>FV/FA Completion Date</label>
    <summarizedField>FA_FV_Detail__c.FA_Completion_Date__c</summarizedField>
    <summaryForeignKey>FA_FV_Detail__c.Serial_Number__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Serial_Number__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <inlineHelpText>This is the RMA order line to which this serial number is related</inlineHelpText>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <nameField>
        <label>Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Steps__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Steps__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FA / FV</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Steps__c/fields/FA_Steps_Description_FA_Steps__c.field-meta.xml
<CustomField>
    <fullName>FA_Steps_Description_FA_Steps__c</fullName>
    <inlineHelpText>Please enter information about what you did during this step. Can be used for future processes and may become part of the FAR.</inlineHelpText>
    <label>FA Steps / Description (FA Steps)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/classes/createFAReports.cls
public class createFAReports {
    public static List<serialNumberFAAnalysisWrapper> serialNumbertable {get;set;}
    public static Order_line__c ol { get; set; }
    public static List<Serial_Number__c> sN { get; set; }
    public static List<FA_FV_Analysis__c> fA { get; set; }
    public static Map<Id,set<String>> FAtoSNMap { get; set; }
    public createFAReports() {
        Id orderlineId = ApexPages.currentPage().getParameters().get('orderLine');
        String serialId =ApexPages.currentPage().getParameters().get('selectedSerialNumber');
        system.debug('serialId ===='+serialId);
        List<String> lstserialId = serialId.split(',');
        ol=getOrderlineData(orderlineId);
        sN = getSerialNumberData(lstserialId);
        fA = getFAFVData(lstserialId);
        serialNumbertable= prepareMapforSerialNumberTable(lstserialId);
    }
    public Double offset{get{
        TimeZone tz = UserInfo.getTimeZone();
        //Milliseconds to Day
        return tz.getOffset(DateTime.now()) / (1000 * 3600 * 24.0);
    }
                        }
    public static Order_line__c getOrderlineData(Id orderlineId)
    {
        Order_line__c orderLine = [select id,Name,order__r.RMA_Request__r.CaseNumber,order__r.PoNumber,RMA_Received_Date__c,Owner.name,FA_FV_Completion_Date__c,order__r.Account.name,Part_Number__r.name,order__r.End_Customer__c,Marketing_Part__c
                                   from Order_line__c where id=:orderlineId];
        return orderLine;
    }
    public static List<serialNumberFAAnalysisWrapper> prepareMapforSerialNumberTable(List<String> lstserialId)
    {
        List<serialNumberFAAnalysisWrapper> snWrapper = new  List<serialNumberFAAnalysisWrapper>();
        sN = getSerialNumberData(lstserialId);
        Map<Id,FA_FV_Detail__c> FAFVDetailMap = new Map<Id,FA_FV_Detail__c>([select Id,FA_FV__c,FA_FV__r.Name,FA_FV__r.FA_Findings__c,Serial_Number__c,Serial_Number__r.Order_Line__r.Return_Reason__c, Serial_Number__r.Name,Serial_Number__r.Date_Code__c From FA_FV_Detail__c where Serial_Number__c in :lstserialId and FA_FV__r.RecordType.DeveloperName='FA_Analysis']);
        Integer count=0;
        for(FA_FV_Detail__c FAFVDetail :FAFVDetailMap.values())
        {
            count++;
            serialNumberFAAnalysisWrapper serialNumberMap = new serialNumberFAAnalysisWrapper();
            serialNumberMap.rowindex =count;
            serialNumberMap.serialNumber=FAFVDetail.Serial_Number__r.Name;
            serialNumberMap.DateCode=FAFVDetail.Serial_Number__r.Date_Code__c;
            serialNumberMap.CustomerReportedFailure=FAFVDetail.Serial_Number__r.Order_Line__r.Return_Reason__c;
            serialNumberMap.FAFindings=FAFVDetail.FA_FV__r.FA_Findings__c;
            serialNumberMap.FAAnalysis=FAFVDetail.FA_FV__r.Name;
            snWrapper.add(serialNumberMap);
            
        }
        
        return snWrapper;
    }
    
    public static List<Serial_Number__c> getSerialNumberData(List<String> lstserialId){
        List<Serial_Number__c> lstSerial =[Select id,Name,Customer_Serial_Number__c,Date_Code__c,Order_Line__r.Return_Reason__c
                                           from Serial_Number__c where id IN:lstserialId];
        system.debug('lstSerial'+lstSerial);
        return lstSerial;
    }
    
    public static List<FA_FV_Analysis__c> getFAFVData(List<String> lstserialId){ 
        FAtoSNMap = new Map<Id,set<String>>();
        Id recordType = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FA Analysis').getRecordTypeId();
        Set<Id> FAFVId = new Set<Id>();
        Map<Id,List<String>> FAPam = new  Map<Id,List<String>>();
        List<FA_FV_Detail__c> FADetail =[select Serial_Number__c,Serial_Number__r.Name,Serial_Number__r.Customer_Serial_Number__c,FA_FV__c from FA_FV_Detail__c where Serial_Number__c IN:lstserialId ];
        system.debug('FADetail==='+FADetail);
        for(FA_FV_Detail__c fD:FADetail){
            FAFVId.add(fD.FA_FV__c);
            if(!FAtoSNMap.containsKey(fD.FA_FV__c)){
                FAtoSNMap.put(fD.FA_FV__c,new set<string>{fD.Serial_Number__r.Name});
            }else{
                FAtoSNMap.get(fD.FA_FV__c).add(fD.Serial_Number__r.Name);
            }
            
        } 
        System.debug('FAFVId=='+FAFVId);
        system.debug('FAPam==='+FAPam);
        system.debug('FAtoSNMap==='+FAtoSNMap);
        List<FA_FV_Analysis__c> fA = [select id,RC_Analysis__c,Conclusion__c,Failure_Mechanism__c,Containment__c,Corrective_Action__c,Risk_Assessment__c,
                                      (select id,name ,FA_Findings__c,FA_Steps_Description_FA_Steps__c from Steps__r ORDER BY Name) from FA_FV_Analysis__c where id IN:FAFVId AND recordtypeId=:recordType]; 
        System.debug('fA=='+fA);
        return fA;
    }
    
    @AuraEnabled
    public static List <Serial_Number__c> getSerialNumber(String orderID) {
        list<string> abcList = new list<string>();
        // public static list<Serial_Number__c> getSerialNumber(String orderID){
        list<Serial_Number__c> serialNoList = [select id,Name,Customer_Serial_Number__c,Order_Line__c from Serial_Number__c where Order_Line__c=:orderID ];
        for(Serial_Number__c sc : serialNoList){
            abcList.add(sc.Name) ; 
        }
        system.debug('orderID ' + orderID);
        return  serialNoList;   
    }
    
    /* @AuraEnabled
public static list<FA_FV_Analysis__c> getFADetails(list<String> serialNoID) {
list<FA_FV_Detail__c> faList = [select id,Serial_Number__c,FA_FV__c from FA_FV_Detail__c where Serial_Number__c IN : serialNoID];
list<string> faIDList = new list<string>();
for(FA_FV_Detail__c fa : faList){
faIDList.add(fa.FA_FV__c);
}
list<FA_FV_Analysis__c> faAnalysisList = [select id,Name,(select id,Name from Steps__r),(select id,Name from Failure_Modes__r) from FA_FV_Analysis__c where id IN : faIDList];

return faAnalysisList;

}*/
    
    public class serialNumberFAAnalysisWrapper
    {
        public Integer rowindex{get;set;}
        public String serialNumber{get;set;}
        public String DateCode{get;set;}
        public String CustomerReportedFailure{get;set;}
        public String  FAFindings{get;set;}
        public String FAAnalysis{get;set;}
    }
    
    
}