src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/BOM_Parts__c/BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Master Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BOM_Product_Part__c/BOM_Product_Part__c.object-meta.xml
<CustomObject>
    <label>Junction Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOM_Product_Part__c/fields/BOM_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Part__c</fullName>
    <label>Master Components</label>
    <referenceTo>BOM_Parts__c</referenceTo>
    <relationshipLabel>Junction Components</relationshipLabel>
    <relationshipName>BOM_Product_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Qual_Required__c.field-meta.xml
<CustomField>
    <fullName>Qual_Required__c</fullName>
    <description>Select YES if this product was quoted as a product to be qualified by the customer.</description>
    <inlineHelpText>Orders where customers are performing qualification (new device or change to existing device). Contract review level 1 will be required.</inlineHelpText>
    <label>Customer Qual Req&apos;d?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Ordered_BOM_Parts__c/Ordered_BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Ordered BOM Parts</label>
    <nameField>
        <label>Ordered BOM Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered BOM Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ordered_BOM_Parts__c/fields/BOM_Product_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Product_Part__c</fullName>
    <label>BOM Product Part</label>
    <referenceTo>BOM_Product_Part__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <label>Opportunity Product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/classes/CloneOpportunityExtensionTest.cls
@isTest
private class CloneOpportunityExtensionTest {
@testSetup static void data() {
        Test.loadData(Pricebook2.sObjectType, 'PriceListTestdata');
        List<Account> acc = TestDataFactory.createAccounts(1);
        system.debug('price book '+[Select id,Name from Pricebook2]);
        system.debug('standard '+ Test.getStandardPricebookId());
        List<Opportunity> opp = TestDataFactory.createOpportunity(1, acc[0].Id);
        List<Product2> prd = TestDataFactory.createProducts('2', 2, false);
        List<Pricebook2> pricel = [Select Id from Pricebook2 Where Name = 'Legacy Marlow Products' AND CurrencyIsoCode = 'USD'];
        system.debug('pricel '+pricel);
        opp[0].Pricebook2Id = pricel[0].Id;
        opp[0].CurrencyIsoCode = 'USD';
        update opp;
        PriceBookEntry pb = [Select Id from PriceBookEntry Where product2Id = :prd[0].Id AND CurrencyIsoCode = 'USD' AND PriceBook2Id = :pricel[0].Id limit 1];
        List<OpportunityLineItem> oppLines = TestDataFactory.creatOppLine(opp[0].Id, 2, prd[0].Id, pb.id);
    BOM_Parts__c bp = new BOM_Parts__c();
    bp.Name = 'test';
    insert bp;
    BOM_Product_Part__c   bpp = new BOM_Product_Part__c(); 
    bpp.BOM_Part__c   = bp.id;
 bpp.Name = 'test'; 
    insert bpp;
    Ordered_BOM_Parts__c obp = new Ordered_BOM_Parts__c();
    obp.OpportunityProduct__c = oppLines[0].id;
    obp.BOM_Product_Part__c  = bpp.id;
    insert obp;
        TestDataFactory.createOppRatePla(oppLines[0].Id, 10, 100);
    }
    @isTest
    static void testcloneOpp(){
        Opportunity opp = [SELECT Id, Name,Project_Name__c,Qual_Required__c,CurrencyIsoCode,Amount,StageName, CloseDate, AccountId, Pricebook2Id FROM Opportunity LIMIT 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        CloneOpportunityExtension testcloneOpp = new CloneOpportunityExtension(sc);
        testcloneOpp.cloneOpp();
        test.stopTest();
    }
}