src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Business_Unit_Name_Product_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Name_Product_Rollup__c</fullName>
    <description>Created for territory management.</description>
    <label>Business Unit Name (Product Rollup)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Qual_Required__c.field-meta.xml
<CustomField>
    <fullName>Qual_Required__c</fullName>
    <description>Select YES if this product was quoted as a product to be qualified by the customer.</description>
    <inlineHelpText>Orders where customers are performing qualification (new device or change to existing device). Contract review level 1 will be required.</inlineHelpText>
    <label>Customer Qual Req&apos;d?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Business_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Name__c</fullName>
    <description>This field is populated using a field update and is updated to the parent Product: Business Unit Name field when Created By field is not equal to NULL (essentially, upon record creation), whenever the record is saved.</description>
    <inlineHelpText>This field is populated using a field update and is updated to the parent Product: Business Unit Name field whenever the record is saved.</inlineHelpText>
    <label>Business Unit Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unspecified</fullName>
            </value>
            <value>
                <fullName>Data Networking</fullName>
            </value>
            <value>
                <fullName>Optical Interconnect</fullName>
            </value>
            <value>
                <fullName>3D Sensing</fullName>
            </value>
            <value>
                <fullName>WSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Business_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Name__c</fullName>
    <formula>IF(ISPICKVAL(Business_Unit__c, &quot;CC00&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC10&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC11&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC12&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC13&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC14&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC15&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC20&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC21&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC22&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC23&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC24&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC25&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC30&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC31&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC32&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC50&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC51&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC60&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC61&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC75&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC85&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PC60&quot;), &quot;Power&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;PC61&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PC62&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS60&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS61&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS63&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY00&quot;), &quot;Systems&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY10&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY20&quot;), &quot;Systems&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY30&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY60&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY61&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY62&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY63&quot;), &quot;Systems&quot;,&quot;N/A&quot;
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit Name</label>
    <type>Text</type>
</CustomField>

src/classes/trgRollUpToOpportunityTest.cls
@IsTest(seeAllData = true)
    public class trgRollUpToOpportunityTest{
        private static testmethod void trgRollUpToOpportunityTest1(){
        Account acc = new Account();
        acc.name='Test Account';
        Test.StartTest();
            insert acc;
            Pricebook2 standardPB;
            standardPB = [SELECT Id, Name FROM PriceBook2 Limit 1];
            
            opportunity opp = new opportunity();
            opp.Name='Test';
            opp.Pricebook2ID = standardPB.Id;
            opp.CloseDate =date.today().addDays(5);
            opp.AccountId =acc.id;
            opp.StageName ='Closed Won';
            opp.Qual_Required__c = 'Yes';
            opp.Business_Unit__c = 'Power';
            insert opp;
            System.AssertEquals(opp.Pricebook2ID,standardPB.Id);
             
            Product2 p = new Product2();
            p.ProductCode = 'Test';
            p.Name = 'TestName';
            p.description ='On Premise License';
            p.isactive=true;
            insert p;
            System.assertEquals(p.isactive, true);
            
            PricebookEntry pe = new PricebookEntry();
            pe.Product2Id = p.Id;
            pe.Pricebook2Id = standardPB.Id;
            pe.UnitPrice = 1000;
            pe.IsActive = true;
            insert pe;
            
            OpportunityLineItem oli = new OpportunityLineItem();
            oli.OpportunityId = opp.Id;
            oli.PricebookEntryId = pe.Id;
            oli.Quantity = 1;
            oli.UnitPrice = 1000;
            oli.Business_Unit_Name__c = 'Systems';
            insert oli; 
            
            OpportunityLineItem oli1 = new OpportunityLineItem();
            oli1.OpportunityId = opp.Id;
            oli1.PricebookEntryId = pe.Id;
            oli1.Quantity = 1;
            oli1.UnitPrice = 1000;
            oli1.Business_Unit_Name__c = 'Systems';
            insert oli1;  
            
            opp.Business_Unit_Name_Product_Rollup__c = oli1.Business_Unit_Name__c;
            update opp;
            system.AssertEquals(opp.Business_Unit_Name_Product_Rollup__c,'Systems');
        Test.StopTest();
    }
    
 
   
            
}