src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Collect_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Collect_Account_Number__c</fullName>
    <description>Customer shipping account number to bill.</description>
    <inlineHelpText>Customer shipping account number to bill.</inlineHelpText>
    <label>Collect Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Drop_Ship__c.field-meta.xml
<CustomField>
    <fullName>Drop_Ship__c</fullName>
    <inlineHelpText>Drop Ship information to be merged onto NAPO</inlineHelpText>
    <label>Drop Ship</label>
    <type>TextArea</type>
</CustomField>

src/objects/Opportunity/fields/IncoTerms__c.field-meta.xml
<CustomField>
    <fullName>IncoTerms__c</fullName>
    <label>IncoTerms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>DAT</fullName>
            </value>
            <value>
                <fullName>DDP</fullName>
            </value>
            <value>
                <fullName>DDU</fullName>
            </value>
            <value>
                <fullName>DEQ</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>EXW</fullName>
            </value>
            <value>
                <fullName>FAS</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Named_Place__c.field-meta.xml
<CustomField>
    <fullName>Named_Place__c</fullName>
    <label>Named Place</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>Customer purchase order number</description>
    <inlineHelpText>Enter the customer&apos;s PO number, if given.</inlineHelpText>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Received_By__c.field-meta.xml
<CustomField>
    <fullName>Received_By__c</fullName>
    <label>Received By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Customer Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PrePaid</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FedEx Priority 1</fullName>
            </value>
            <value>
                <fullName>FedEx Priority 2</fullName>
            </value>
            <value>
                <fullName>FedEx SAT First</fullName>
            </value>
            <value>
                <fullName>FedEx SAT Priority</fullName>
            </value>
            <value>
                <fullName>FedEx Standard</fullName>
            </value>
            <value>
                <fullName>FedEx 2 Day AM</fullName>
            </value>
            <value>
                <fullName>FedEx 2 Day</fullName>
            </value>
            <value>
                <fullName>FedEx Express Saver</fullName>
            </value>
            <value>
                <fullName>FedEx Ground</fullName>
            </value>
            <value>
                <fullName>FedEx Intl Economy</fullName>
            </value>
            <value>
                <fullName>FedEx Intl Priority</fullName>
            </value>
            <value>
                <fullName>Hand Carry</fullName>
            </value>
            <value>
                <fullName>Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>LTL Freight Service</fullName>
            </value>
            <value>
                <fullName>UPS Next Day 8:30AM</fullName>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
            </value>
            <value>
                <fullName>UPS Next Day Saver</fullName>
            </value>
            <value>
                <fullName>UPS SAT AM</fullName>
            </value>
            <value>
                <fullName>UPS SAT</fullName>
            </value>
            <value>
                <fullName>UPS 2 Day Air AM</fullName>
            </value>
            <value>
                <fullName>UPS 2 Day Air</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
            </value>
            <value>
                <fullName>UPS Intl Expedited</fullName>
            </value>
            <value>
                <fullName>UPS Intl Express</fullName>
            </value>
            <value>
                <fullName>UPS Intl Saver</fullName>
            </value>
            <value>
                <fullName>UPS Intl Standard</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>USPS</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Shipping_Comments__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Comments__c</fullName>
    <inlineHelpText>Use the following codes first, before adding additional Shipping info
PP = Partials Permitted
DNP = Do NOT Partial
DNSE = Do NOT Ship Early
PBCR = Partials By Complete Release
ALSO LIST PAYMENT TERMS FOR ACCOUNTING / SHIPPING</inlineHelpText>
    <label>Shipping Comments</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <inlineHelpText>Special instructions to be merged onto NAPO.</inlineHelpText>
    <label>Special Instructions</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/recordTypes/Aftermarket.recordType-meta.xml
<RecordType>
    <fullName>Aftermarket</fullName>
    <active>true</active>
    <businessProcess>Aftermarket</businessProcess>
    <label>Aftermarket</label>
</RecordType>

src/objects/Order/fields/Account_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_SAP_ID__c</fullName>
    <label>Account SAP ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/End_Customer_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_SAP_ID__c</fullName>
    <label>End Customer SAP ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/SAP_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_Type__c</fullName>
    <label>SAP Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Rush</fullName>
            </value>
            <value>
                <fullName>Rush with Assembly</fullName>
            </value>
            <value>
                <fullName>Scheduling Agreement</fullName>
            </value>
            <value>
                <fullName>Free-of-Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/User/fields/Legacy_Company__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Company__c</fullName>
    <description>Used to support existing processes during the org merge processes</description>
    <label>Legacy Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finisar</fullName>
            </value>
            <value>
                <fullName>Corp II-VI</fullName>
            </value>
            <value>
                <fullName>Marlow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CreateSalesOrderInSAPTest.cls
@isTest(seeAllData = false)
private class CreateSalesOrderInSAPTest {
    @testSetup static void data() {
       	Test.loadData(Pricebook2.sObjectType, 'PriceListTestdata');
        List<Account> acc = TestDataFactory.createAccounts(1);
        system.debug('price book '+[Select id,Name from Pricebook2]);
        system.debug('standard '+ Test.getStandardPricebookId());
        List<Opportunity> opp = TestDataFactory.createOpportunity(1, acc[0].Id);
        List<Product2> prd = TestDataFactory.createProducts('2', 2, false);
        List<Pricebook2> pricel = [Select Id from Pricebook2 Where Name = 'Legacy Marlow Products' AND CurrencyIsoCode = 'USD'];
        opp[0].Pricebook2Id = pricel[0].Id;
        opp[0].CurrencyIsoCode = 'USD';
        update opp;
        PriceBookEntry pb = [Select Id from PriceBookEntry Where product2Id = :prd[0].Id AND CurrencyIsoCode = 'USD' AND PriceBook2Id = :pricel[0].Id limit 1];
        List<OpportunityLineItem> oppLines = TestDataFactory.creatOppLine(opp[0].Id, 2, prd[0].Id, pb.id);
        
        /*TestDataFactory.createOppRatePla(oppLines[0].Id, 10, 100);
        List<Order> orders = TestDataFactory.createOrders(opp[0].Id, acc[0].Id, 1);
        orders[0].Pricebook2Id = pricel[0].Id;
        update orders;
        List<Order_Line__c> items = TestDataFactory.createOrderLines(orders[0].Id, prd[0].Id, pb.Id, 2);*/        
    }
    @isTest
    static void testCreateOrderInSAP(){
        test.startTest();
        List<Opportunity> opp1=[Select Id from Opportunity LIMIT 1];
        List<OpportunityLineItem> oppLine=[Select Id,OpportunityId,Product2Id,PriceBookEntryId from OpportunityLineItem LIMIT 1];
        User sysAdm = new User(LastName='Usrlast1111',ProfileId=[SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,alias ='trsysy',Legacy_Company__c ='Corp II-VI',
                               Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser@finisar.com');
        system.runAs(sysAdm){
            opp1[0].stageName='Closed Won';
            opp1[0].RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftermarket').getRecordTypeId();
            update opp1[0];
        }
        Order ord = [select id, OpportunityId from Order limit 1];
        TestDataFactory.createOrderItems(ord.Id, oppLine[0].Product2Id, oppLine[0].PriceBookEntryId, 1);
        Opportunity opp = new Opportunity();
        opp.Id = ord.OpportunityId;
        opp.Drop_Ship__c = 'Drp ship';
        opp.PO_Number__c = 'PO123';
        opp.Received_By__c = 'Email';
        opp.Shipping_Carrier__c = 'FedEx Priority 1';
        opp.Description = 'Description';
        opp.Shipping_Comments__c = 'Shipping Comments';
        opp.Special_Instructions__c = 'Special Instructions';
        opp.Ship_Method__c = 'PrePaid';
        opp.Collect_Account_Number__c = '12344';
        opp.IncoTerms__c = 'CFR';
        opp.Named_Place__c = 'Named Place';
        update opp;
        ord.SAP_Order_Type__c = 'Standard';
        ord.Account_SAP_ID__c = 'SPID';
        ord.ActivatedDate = Date.today();
        ord.EndDate = Date.today().AddDays(30);
        ord.End_Customer_SAP_ID__c = 'endCus';
        update ord;
        ApexPages.StandardController sc = new ApexPages.StandardController(ord);
        CreateSalesOrderInSAP testorderCre = new CreateSalesOrderInSAP(sc);
        testorderCre.createSalesOrderInSAP();
        testorderCre.returnToOrder();
        testorderCre.updateOrderFields(ord.Id, '21331', 'Completed');
        testorderCre.updateOrderFields(ord.Id, '', 'Sync Error');
        test.stopTest();
    }
    @isTest
    static void testCreateOrderInSAP1(){
        test.startTest();
        List<Opportunity> opp1=[Select Id from Opportunity LIMIT 1];
        List<OpportunityLineItem> oppLine=[Select Id,OpportunityId,Product2Id,PriceBookEntryId from OpportunityLineItem LIMIT 1];
        User sysAdm = new User(LastName='Usrlast1111',ProfileId=[SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,alias ='trsysy',Legacy_Company__c ='Corp II-VI',
                               Email='standarduser@testorg.com',EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testuser@finisar.com');
        system.runAs(sysAdm){
            opp1[0].stageName='Closed Won';
            opp1[0].RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftermarket').getRecordTypeId();
            update opp1[0];
        }
        Order ord = [select id, OpportunityId from Order limit 1];
        TestDataFactory.createOrderItems(ord.Id, oppLine[0].Product2Id, oppLine[0].PriceBookEntryId, 1);

        
        ApexPages.StandardController sc = new ApexPages.StandardController(ord);
        CreateSalesOrderInSAP testorderCre = new CreateSalesOrderInSAP(sc);
        testorderCre.createSalesOrderInSAP();
        testorderCre.returnToOrder();
        testorderCre.updateOrderFields(ord.Id, '21331', 'Completed');
        testorderCre.updateOrderFields(ord.Id, '', 'Sync Error');
        test.stopTest();
    }
}