src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Qual_Required__c.field-meta.xml
<CustomField>
    <fullName>Qual_Required__c</fullName>
    <description>Select YES if this product was quoted as a product to be qualified by the customer.</description>
    <inlineHelpText>Orders where customers are performing qualification (new device or change to existing device). Contract review level 1 will be required.</inlineHelpText>
    <label>Customer Qual Req&apos;d?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unspecified</fullName>
            </value>
            <value>
                <fullName>Data Networking</fullName>
            </value>
            <value>
                <fullName>Optical Interconnect</fullName>
            </value>
            <value>
                <fullName>3D Sensing</fullName>
            </value>
            <value>
                <fullName>WSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestTrgUpdateOppProScheduleDate.cls
@IsTest(Seealldata=true)
public class TestTrgUpdateOppProScheduleDate{
    private static testmethod void trgUpdateOppProScheduleDateTest(){
        Account acc = new Account();
        acc.name='Test Account';
        insert acc;
        
        Pricebook2 standardPB = [SELECT Id, Name FROM PriceBook2 Limit 1];
        
        opportunity opp = new opportunity();
        opp.Name='Test';
        opp.Pricebook2ID = standardPB.Id ;
        opp.CloseDate=date.today().addDays(5);
        opp.AccountId=acc.id;
        opp.StageName='Closed Won';
        opp.Business_Unit__c = 'Power';
        opp.Qual_Required__c ='Yes';
        opp.Project_Name__c   = 'Test'; 
        insert opp;
         
        
        Product2 p = new Product2();
        p.ProductCode = 'Test';
        p.Name = 'TestName';
        p.description ='On Premise License';
        p.isactive=true;
        insert p;
        System.assertEquals(p.isactive, true);
        
        PricebookEntry pe = new PricebookEntry();
        pe.Product2Id = p.Id;
        pe.Pricebook2Id = standardPB.Id;
        pe.UnitPrice = 1000;
        pe.IsActive = true;
        insert pe;
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.PricebookEntryId = pe.Id;
        oli.Quantity = 1;
        oli.UnitPrice = 1000;
        insert oli; 
          OpportunityLineItem oli2 = new OpportunityLineItem();
        oli2.OpportunityId = opp.Id;
        oli2.PricebookEntryId = pe.Id;
        oli2.Quantity = 3;
        oli2.UnitPrice = 10000;
        insert oli2; 
         OpportunityLineItem oli3 = new OpportunityLineItem();
        oli3.OpportunityId = opp.Id;
        oli3.PricebookEntryId = pe.Id;
        oli3.Quantity = 3;
        oli3.UnitPrice = 10000;
        insert oli3; 
        
        update oli;  
        
    }
}