src/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer Account</label>
</RecordType>

src/objects/Case/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/FA_FV_Analysis__c.object-meta.xml
<CustomObject>
    <label>FV/FA Analysis</label>
    <nameField>
        <label>FV/FA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FV/FA Analysis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FA_FV_Analysis__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Containment__c.field-meta.xml
<CustomField>
    <fullName>Containment__c</fullName>
    <label>Containment</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Corrective_Action__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Action__c</fullName>
    <label>Corrective Action</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Customer_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Serial_Number__c</fullName>
    <label>Customer Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Date_Code__c.field-meta.xml
<CustomField>
    <fullName>Date_Code__c</fullName>
    <label>Date Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <inlineHelpText>FA Findings</inlineHelpText>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Failure_Mechanism__c.field-meta.xml
<CustomField>
    <fullName>Failure_Mechanism__c</fullName>
    <label>Failure Mechanism</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Final_Function_Test__c.field-meta.xml
<CustomField>
    <fullName>Final_Function_Test__c</fullName>
    <label>Final Function Test</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Final_Functional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Final_Functional_Comments__c</fullName>
    <label>Final/Functional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/FV_Findings__c.field-meta.xml
<CustomField>
    <fullName>FV_Findings__c</fullName>
    <label>FV Findings</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/RC_Analysis__c.field-meta.xml
<CustomField>
    <fullName>RC_Analysis__c</fullName>
    <label>RC Analysis</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Risk_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment__c</fullName>
    <label>Risk Assessment</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/Temp_BERT__c.field-meta.xml
<CustomField>
    <fullName>Temp_BERT__c</fullName>
    <label>Temp BERT</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Analysis__c/fields/VMI__c.field-meta.xml
<CustomField>
    <fullName>VMI__c</fullName>
    <label>VMI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/FA_FV_Detail__c/FA_FV_Detail__c.object-meta.xml
<CustomObject>
    <label>FV/FA Detail</label>
    <nameField>
        <displayFormat>FV/FA Analysis - {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FV/FA Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FA_FV_Detail__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FV/FA</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>FV/FA Details</relationshipLabel>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/FA_FV_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>This is the serial number to which this FA / FV is relevant</inlineHelpText>
    <label>Serial Number</label>
    <referenceTo>Serial_Number__c</referenceTo>
    <relationshipName>FA_FV_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/objects/Order/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <description>Oracle - Update this field</description>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the related RMA Request</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <formula>Order__r.End_Customer__c</formula>
    <label>End Customer</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;/lightning/cmp/c__FAFVCustomUIQuickAction?c__recordId=&quot;+Id, &apos;FA FV&apos;,&apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FA FV</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/FA_FV_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Completion_Date__c</fullName>
    <label>FA/FV Completion Date</label>
    <summarizedField>Serial_Number__c.RMA_Completion_Date__c</summarizedField>
    <summaryForeignKey>Serial_Number__c.Order_Line__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Order_Line__c/fields/Marketing_Part__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Part__c</fullName>
    <formula>Part_Number__r.Marketing_P_N__c</formula>
    <label>Marketing Part #</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Order_Line_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Request_Type__c</fullName>
    <description>This field shows the value of Request Type copied down from the Order header</description>
    <formula>Order__r.Request_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows the value of Request Type copied down from the Order header</inlineHelpText>
    <label>Order Line Request Type</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Reported_Problem__c.field-meta.xml
<CustomField>
    <fullName>Reported_Problem__c</fullName>
    <label>Reported Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RMA_Received_Date__c</fullName>
    <label>RMA Received Date</label>
    <type>Date</type>
</CustomField>

src/objects/Order_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Request#</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>RMA_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/SelectedSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SelectedSerialNumber__c</fullName>
    <label>SelectedSerialNumber</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Order_Line__c/fields/SO_Number_Formula__c.field-meta.xml
<CustomField>
    <fullName>SO_Number_Formula__c</fullName>
    <formula>Order__r.PoNumber + &quot; - &quot; + Line__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SO Number</label>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/Serial_Number__c.object-meta.xml
<CustomObject>
    <description>This is the serial numbers for an RMA request which will be populated from Oracle</description>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Serial_Number__c/fields/Conclusion__c.field-meta.xml
<CustomField>
    <fullName>Conclusion__c</fullName>
    <label>Conclusion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/Customer_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Serial_Number__c</fullName>
    <label>Customer Serial Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/Date_Code__c.field-meta.xml
<CustomField>
    <fullName>Date_Code__c</fullName>
    <label>Date Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Serial_Number__c/fields/FA_FV_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>FA_FV_Completion_Date__c</fullName>
    <label>FV/FA Completion Date</label>
    <summarizedField>FA_FV_Detail__c.FA_Completion_Date__c</summarizedField>
    <summaryForeignKey>FA_FV_Detail__c.Serial_Number__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Serial_Number__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <inlineHelpText>This is the RMA order line to which this serial number is related</inlineHelpText>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <nameField>
        <label>Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Steps__c/fields/FA_Findings__c.field-meta.xml
<CustomField>
    <fullName>FA_Findings__c</fullName>
    <label>FA Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Steps__c/fields/FA_FV__c.field-meta.xml
<CustomField>
    <fullName>FA_FV__c</fullName>
    <label>FA / FV</label>
    <referenceTo>FA_FV_Analysis__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Steps__c/fields/FA_Steps_Description_FA_Steps__c.field-meta.xml
<CustomField>
    <fullName>FA_Steps_Description_FA_Steps__c</fullName>
    <inlineHelpText>Please enter information about what you did during this step. Can be used for future processes and may become part of the FAR.</inlineHelpText>
    <label>FA Steps / Description (FA Steps)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/classes/FvReportCustomComponentController.cls
public class FvReportCustomComponentController {
    
    public static String orderlineId {get;set;}
    public String SelectedSerialNo {get;set;}
    public Order_line__c orderline { get; set; }
    public List<Serial_Number__c> serialnumberList { get; set; }
    public  List<FA_FV_Detail__c> fafvdetaillist {get;set;}
    public static List<FA_FV_Analysis__c> fvAnalysisList { get; set; }
    public static Map<Id,set<String>> fatosnMap { get; set; }
    public static Boolean displaySendEmailButton {get;set;} 
    public static String serialId {get;set;} 
    public Double offset{get{
        TimeZone tz = UserInfo.getTimeZone();
        //Milliseconds to Day
        return tz.getOffset(DateTime.now()) / (1000 * 3600 * 24.0);
    }
                        }
    public FvReportCustomComponentController()
    {
        displaySendEmailButton = True;
        //this.serialnumberList = getSerialNumberData(lstserialId);
        //this.fvAnalysisList = getFAFVData(lstserialId);
        //this.serialNumbertable= prepareMapforSerialNumberTable(lstserialId);
    }
    
    public static Order_line__c getOrderlineData()
    {
       IF(String.isBlank(orderlineId)){
            orderlineId = ApexPages.currentPage().getParameters().get('orderLine');
        }
        
        Order_line__c orderLine = [select id,Reported_Problem__c,Order_Line_Request_Type__c,SO_Number_Formula__c ,Name,order__r.RMA_Request__r.CaseNumber,order__r.PoNumber,RMA_Received_Date__c,Owner.name,FA_FV_Completion_Date__c,order__r.Account.name,Part_Number__r.name,order__r.End_Customer__c,Marketing_Part__c
                                   from Order_line__c where id=:orderlineId];
        System.debug(orderLine);
        return orderLine;
    }
    public static List<Serial_Number__c> getSerialNumberData(List<String> lstserialId){
        List<Serial_Number__c> lstSerial =[Select id,Name,Customer_Serial_Number__c,Date_Code__c,Order_Line__r.Return_Reason__c
                                           from Serial_Number__c where id IN:lstserialId];
        system.debug('lstSerial'+lstSerial);
        return lstSerial;
    }
    public static List<FA_FV_Analysis__c> getFAFVData(){ 
        IF(String.isBlank(serialId)){
            serialId =ApexPages.currentPage().getParameters().get('selectedSerialNumber');
        }
        List<String> lstserialId = serialId.split(',');
        fatosnMap = new Map<Id,set<String>>();
        Id fvRecordType = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FV Analysis').getRecordTypeId();
        Set<Id> fvids = new Set<Id>();
        Map<Id,List<String>> fvMap = new  Map<Id,List<String>>();
        List<FA_FV_Detail__c> fvdetailList =[select Serial_Number__c,Serial_Number__r.Name,Serial_Number__r.Customer_Serial_Number__c,FA_FV__c 
                                             from FA_FV_Detail__c 
                                             where Serial_Number__c IN:lstserialId ];
        system.debug('FADetail==='+fvdetailList);
        for(FA_FV_Detail__c fD:fvdetailList){
            fvids.add(fD.FA_FV__c);
            if(!fatosnMap.containsKey(fD.FA_FV__c)){
                fatosnMap.put(fD.FA_FV__c,new set<string>{fD.Serial_Number__r.Name});
            }else{
                fatosnMap.get(fD.FA_FV__c).add(fD.Serial_Number__r.Name);
            }
            
        } 
        System.debug('FAFVId=='+fvids);
        
        system.debug('FAtoSNMap==='+fatosnMap);
        List<FA_FV_Analysis__c> fvAnalysisList = [select id,Final_Function_Test__c,Temp_BERT__c, RC_Analysis__c,Failure_Mechanism__c,Containment__c,Corrective_Action__c ,Risk_Assessment__c ,Conclusion__c ,
                                                  (select id,name ,FA_Findings__c,FA_Steps_Description_FA_Steps__c from Steps__r ORDER BY CREATEDDATE)
                                                   FROM FA_FV_Analysis__c where Id in :fvids AND RecordtypeId = :fvRecordType];
        
        return fvAnalysisList;
    }
    public static List<FA_FV_Detail__c> getFVDetail()
        
    {
        IF(String.isBlank(serialId)){
            serialId =ApexPages.currentPage().getParameters().get('selectedSerialNumber');
        }
        List<String> lstserialId = serialId.split(',');
        System.debug('*********FA Detail Records**************');
        Id recordType = Schema.SObjectType.FA_FV_Analysis__c.getRecordTypeInfosByName().get('FV Analysis').getRecordTypeId();
        return [select Serial_Number__r.Name,Serial_Number__r.Date_Code__c,FA_FV__r.Name,FA_FV__r.Owner.Name,FA_FV__r.FV_Findings__c,FA_FV__r.Final_Functional_Comments__c,FA_FV__r.VMI__c,FA_FV__r.Final_Function_Test__c,FA_FV__r.Temp_BERT__c  
                From FA_FV_Detail__c 
                where Serial_Number__c in :lstserialId  and FA_FV__r.RecordTypeId =:recordType ];
    }
    
    public static void sendFVReportThroughEmail(){
        displaySendEmailButton = False;
        List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
        Order_line__c orderLineObj = New Order_Line__c(Id=ApexPages.currentPage().getParameters().get('orderLine'),SelectedSerialNumber__c= ApexPages.currentPage().getParameters().get('selectedSerialNumber'));
        update orderLineObj;
        EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'FVReportEmailComponent'];
        System.debug('After Email');
        List< Id > userList = New List < Id > {UserInfo.getUserId()};
            for (Id u : userList) {
                System.debug('User Object'+ u);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateId(et.id);
                mail.setToAddresses(New List < String > {
                    UserInfo.getUserEmail()
                        });
                mail.setTargetObjectId(u);
                mail.setSaveAsActivity(false);
                mail.setWhatId(ApexPages.currentPage().getParameters().get('orderLine'));
                //Added by surendar for SAL-3576
                OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'FinisarCRM'];
                mail.setOrgWideEmailAddressId(owea[0].id);
                //end
                mailList.add(mail);
            }
        System.debug('MailList'+mailList );
        Messaging.sendEmail(mailList);
    }
}