src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/QuoteEmailCustomComponentController.cls
public class QuoteEmailCustomComponentController {
    
    public static Id recordId { get;set; }
    public static String recordObject { get;set; }
    public static boolean quoteSummry {get;set;}
    public static boolean quoteLineItem {get;set;}
    public static boolean quoteLineItemShipAndDebit {get;set;}
    public static boolean quoteLineItemWithStatusFields {get;set;}
    public static boolean quoteLineItemsApproval {get;set;}
    public static boolean quoteFooter {get;set;}
    public static boolean quoteAllStatus {get;set;}
    public static Id recipientId {get;set;}
    public QuoteEmailCustomComponentController() {
        
    }
    public static List<String> approvalLineitemReocrds = New List<String>{}; 
        
        public list<Quote_Item__c> getLineItems(){
            List<Quote_Item__c> lineItems;
            System.debug('Get Line Items');
            lineItems = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(recordId,recipientId);
            return lineItems;
        }
    
    public list<Quote_Item__c> getLineItemsWithDifferentStatus(Id recordId,id recipientId,Set<String> Status){
        List<Quote_Item__c> lineItems;
        lineItems = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(recordId,recipientId);
        return lineItems;
    }
    
    public Quote getQuote(){
        Quote sobj;
        sobj =(Quote) RecordApprovalDao.getHeaderRecord(recordId);
        return sobj;
    } 
    
    public Case getCase(){
        case sobj;
        sobj =(case) RecordApprovalDao.getHeaderRecord(recordId);
        return sobj;
    } 
    
    public boolean getIsuserPlM(){
        List<User> userObjList = [Select Id,userrole.name from User where id=:recipientId];
        for(user userObj:userObjList){
            IF(userObj.userrole.name!=NUll && userObj.userrole.name.containsIgnoreCase('PLM')){
                System.debug('Inside If Block');
                return true;
            }
        }
        return false;
    }
    
    
    public list<Quote_Item__c> getShipAndDebitLineItems(){
        Quote sobj;
        sobj =(Quote) RecordApprovalDao.getHeaderRecord(recordId);
        return sobj.Quote_Items__r;
    }
}