src/objects/Steps__c/Steps__c.object-meta.xml
<CustomObject>
    <label>Steps</label>
    <nameField>
        <label>Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Steps__c/fields/FAFVStatus__c.field-meta.xml
<CustomField>
    <fullName>FAFVStatus__c</fullName>
    <description>Referenced to FA_FV_Status__c</description>
    <formula>TEXT(FA_FV__r.FA_FV_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FAFVStatus</label>
    <type>Text</type>
</CustomField>

src/classes/StepsTriggerHelper.cls
public with sharing class StepsTriggerHelper {

    public static void beforeUpdate(List<Steps__c> newsteplist,List<Steps__c> oldstepslist)
    {
        for(Steps__c step : newsteplist)
            {
                if(step.FAFVStatus__c =='Finalized')
                {
                    
                    step.addError('User cannot Edit step when it is \'Finalized\'');
                }
            }
    }
    
    public static void beforeDelete(List<Steps__c> oldstepslist)
    {
        for(Steps__c oldstep : oldstepslist)
            {
                if(oldstep.FAFVStatus__c =='Finalized' )
                {
                    
                    oldstep.addError('User cannot Delete step when FA FV Status is \'Finalized \'');
                }
            }
    }
    
}