src/objects/Case/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>This is the rollup of the &apos;Unit Price&apos; from all the Lines</inlineHelpText>
    <label>Line Amount Total</label>
    <summarizedField>RMA_Request_Line__c.Amount__c</summarizedField>
    <summaryForeignKey>RMA_Request_Line__c.RMA_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Case/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the Error Messages that is sent from Oracle. Sales Rep will refer to this message and correct the line items.</description>
    <label>Error Message</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/RMA_PO__c.field-meta.xml
<CustomField>
    <fullName>RMA_PO__c</fullName>
    <description>if RMA Lines PO Amount are same then RMA Line PO Amt will be copied to this field
else RMA/MISC is copied over</description>
    <label>RMA PO</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/RMA_Request_Line__c/RMA_Request_Line__c.object-meta.xml
<CustomObject>
    <label>RMA Request Line</label>
    <nameField>
        <label>Customer Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMA_Request_Line__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field will store the Error Messages that is sent from Oracle. Sales Rep will refer to this message and correct the line items.</description>
    <inlineHelpText>This field will store the Error Messages that is sent from Oracle. Sales Rep will refer to this message and correct the line items.</inlineHelpText>
    <label>Error Message</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Org_Code__c</fullName>
    <inlineHelpText>The Org Code</inlineHelpText>
    <label>Org Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/PO_Price__c.field-meta.xml
<CustomField>
    <fullName>PO_Price__c</fullName>
    <label>PO Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original PO</fullName>
                <default>true</default>
                <label>Original PO</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <inlineHelpText>Why is the part being returned</inlineHelpText>
    <label>Return Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Failure</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Rework/Re-test</fullName>
            </value>
            <value>
                <fullName>Customer Accommodation</fullName>
            </value>
            <value>
                <fullName>Sample/Demo Return</fullName>
            </value>
            <value>
                <fullName>Product Failure</fullName>
            </value>
            <value>
                <fullName>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</fullName>
                <isActive>false</isActive>
                <label>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</label>
            </value>
            <value>
                <fullName>AA</fullName>
                <isActive>false</isActive>
                <label>AA</label>
            </value>
            <value>
                <fullName>ASAS</fullName>
                <isActive>false</isActive>
                <label>ASAS</label>
            </value>
            <value>
                <fullName>DFD</fullName>
                <isActive>false</isActive>
                <label>DFD</label>
            </value>
            <value>
                <fullName>DSD</fullName>
                <isActive>false</isActive>
                <label>DSD</label>
            </value>
            <value>
                <fullName>Faulty CFP2 causing OTL Loss of Lane Alignment</fullName>
                <isActive>false</isActive>
                <label>Faulty CFP2 causing OTL Loss of Lane Alignment</label>
            </value>
            <value>
                <fullName>Functional</fullName>
                <isActive>false</isActive>
                <label>Functional</label>
            </value>
            <value>
                <fullName>Loss Of Signal</fullName>
                <isActive>false</isActive>
                <label>Loss Of Signal</label>
            </value>
            <value>
                <fullName>Loss of frame alarm flapping</fullName>
                <isActive>false</isActive>
                <label>Loss of frame alarm flapping</label>
            </value>
            <value>
                <fullName>OO</fullName>
                <isActive>false</isActive>
                <label>OO</label>
            </value>
            <value>
                <fullName>Pluggable alarm occurred</fullName>
                <isActive>false</isActive>
                <label>Pluggable alarm occurred</label>
            </value>
            <value>
                <fullName>Ports would not validate</fullName>
                <isActive>false</isActive>
                <label>Ports would not validate</label>
            </value>
            <value>
                <fullName>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</fullName>
                <isActive>false</isActive>
                <label>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</label>
            </value>
            <value>
                <fullName>SDS</fullName>
                <isActive>false</isActive>
                <label>SDS</label>
            </value>
            <value>
                <fullName>TEST UAT</fullName>
                <isActive>false</isActive>
                <label>TEST UAT</label>
            </value>
            <value>
                <fullName>TXing errors</fullName>
                <isActive>false</isActive>
                <label>TXing errors</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>alarms raised</fullName>
                <isActive>false</isActive>
                <label>alarms raised</label>
            </value>
            <value>
                <fullName>as</fullName>
                <isActive>false</isActive>
                <label>as</label>
            </value>
            <value>
                <fullName>asa</fullName>
                <isActive>false</isActive>
                <label>asa</label>
            </value>
            <value>
                <fullName>dsds</fullName>
                <isActive>false</isActive>
                <label>dsds</label>
            </value>
            <value>
                <fullName>sdsda</fullName>
                <isActive>false</isActive>
                <label>sdsda</label>
            </value>
            <value>
                <fullName>upgrade to firmware 35 per details and file attached in FAE case</fullName>
                <isActive>false</isActive>
                <label>upgrade to firmware 35 per details and file attached in FAE case</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <inlineHelpText>This is the RMA Request to which this line item looks up</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RMA Request Lines</relationshipLabel>
    <relationshipName>RMA_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/CancelRMACase.cls
public class CancelRMACase {
    
    @AuraEnabled
    public static String  getDetailsCondition(String recordId) {
        String returnMessage='';
        String endCustomer ='';
        Case caseRec = [select id,Return_Reason__c,RMA_PO__c,(select id,name,Error_Message__c,Return_Reason__c,PO_Price__c,Org_Code__c,Amount__c,End_Customer__c from 
                                                              RMA_Request_Lines__r) from case where id=:recordId];
        
        RMA_Request_Line__c rmaLine = new RMA_Request_Line__c();
        rmaLine = caseRec.RMA_Request_Lines__r[0];
        
        if(caseRec.RMA_Request_Lines__r.size()>1) {
            for(RMA_Request_Line__c rma :caseRec.RMA_Request_Lines__r){
                if(rmaLine.End_Customer__c != rma.End_Customer__c){
                    endCustomer = 'One or more serial number is having different end customer';
                    break;
                } 
                else {
                    system.debug('hello==');
                    caseRec.End_Customer__c = rmaLine.End_Customer__c;
                    
                }
                if (rmaLine.Return_Reason__c != rma.Return_Reason__c){
                    system.debug('hello1==');
                    endCustomer ='One or more serial number is having different Return Reason';
                    break;
                }
                if (rma.PO_Price__c == 'Other'){
                    system.debug('hello2==');
                    endCustomer ='One or more serial number is having POC price as Other';
                    break;
                }
                if (rma.Org_Code__c == 'KOR'){
                    system.debug('hello3==');
                    endCustomer ='One or more serial number is having Koria Organization';
                    break;
                } 
                if (rma.Error_Message__c != null && (rma.Error_Message__c.contains('Serial Number is not Valid') || rma.Error_Message__c.contains('PRODUCT CODE(External id)'))){
                    system.debug('hello4==');
                    endCustomer =rma.Error_Message__c;
                    break;
                }
                if(rma.Error_Message__c == null  && rma.Amount__c != rmaLine.Amount__c)
                {
                    caseRec.RMA_PO__c ='RMA/MISC';
                }
                else{
                    caseRec.RMA_PO__c = String.valueOf(rmaLine.Amount__c);
                }
            } 
        } else if(caseRec.RMA_Request_Lines__r.size() == 1) {
            system.debug('testttttttt====');
            if(rmaLine.End_Customer__c != null || rmaLine.End_Customer__c !='') {
                caseRec.End_Customer__c = rmaLine.End_Customer__c;
            }
            if (rmaLine.Error_Message__c != null && (rmaLine.Error_Message__c.contains('Serial Number is not Valid') || rmaLine.Error_Message__c.contains('PRODUCT CODE(External id)'))){
                system.debug('inside1');
                endCustomer =rmaLine.Error_Message__c;
                
            } else if (rmaLine.PO_Price__c == 'Other'){
                system.debug('inside2');
                endCustomer ='One or more serial number is having POC price as Other';
                
            }else if (rmaLine.Org_Code__c == 'KOR'){
                system.debug('inside3');
                endCustomer ='One or more serial number is having Koria Organization';
                
            }else if (rmaLine.Return_Reason__c != null || rmaLine.Return_Reason__c != '') {
                system.debug('inside4' +rmaLine.Return_Reason__c);
                caseRec.Return_Reason__c = String.valueOf(rmaLine.Return_Reason__c);
                
            }else{
                caseRec.RMA_PO__c = String.valueOf(rmaLine.Amount__c);
            }
        }
        
        system.debug('caseRec.End_Customer__c==='+caseRec.End_Customer__c);  
        System.debug('endCustomer==='+endCustomer);
        System.debug('rmaLine==='+rmaLine);
        if(caseRec.Return_Reason__c=='Other') {
            system.debug('hello5==');
            returnMessage= 'Case Can not be close because the Return Reason is Other';
        }else
            if(endCustomer !='' ) {
                system.debug('giisu--');
                returnMessage = endCustomer;
            } 
        else
        {
            caseRec.Status = 'Closed';
            system.debug('caseRec12=='+caseRec);
            try{
                update caseRec;
                system.debug('caseRec!!=='+caseRec+'---'+'Afterupdate' +caseRec.Return_Reason__c);
                returnMessage= 'Case is succesfully closed';
            }catch(Exception e){
                returnMessage= e.getMessage(); 
            }
            
        }
        System.debug('returnMessage==='+returnMessage); 
        return returnMessage;  
    }
}