src/objects/Case/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dead on Arrival</fullName>
            </value>
            <value>
                <fullName>Fail at customer</fullName>
            </value>
            <value>
                <fullName>Field failure / Fail at end-customer</fullName>
            </value>
            <value>
                <fullName>Sample / Demo /Loaner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Order/fields/Contribution_Profit__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Profit__c</fullName>
    <label>Contribution Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/HROCM_Order__c.field-meta.xml
<CustomField>
    <fullName>HROCM_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HROCM Order</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Contribution_Profit__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Profit__c</fullName>
    <formula>(  Unit_Selling_Price__c  -  Variable_Cost__c  )  *  Shipped_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contribution Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Line__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <formula>Order__r.End_Customer__c</formula>
    <label>End Customer</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Gross_Profit__c.field-meta.xml
<CustomField>
    <fullName>Gross_Profit__c</fullName>
    <formula>(  Unit_Selling_Price__c  -  Standard_Cost__c  )  *  Shipped_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Line__c/fields/HROCM_Line__c.field-meta.xml
<CustomField>
    <fullName>HROCM_Line__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HROCM Line</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order_Line__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <formula>Part_Number__r.Marketing_Family__c</formula>
    <label>Marketing Family</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(Part_Number__r.Product_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <formula>Unit_Selling_Price__c  *  Shipped_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order_Line__c/fields/RMAID__c.field-meta.xml
<CustomField>
    <fullName>RMAID__c</fullName>
    <label>RMAID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Ship_From_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Inventory__c</fullName>
    <inlineHelpText>For RMA Orders, this is the Receiving site. Otherwise, it is the Ship from site.</inlineHelpText>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <label>Marketing Family</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;10 GIG</fullName>
            </value>
            <value>
                <fullName>100 GIG</fullName>
            </value>
            <value>
                <fullName>10 GIG</fullName>
            </value>
            <value>
                <fullName>16-32 GIG</fullName>
            </value>
            <value>
                <fullName>200 GIG</fullName>
            </value>
            <value>
                <fullName>25 GIG</fullName>
            </value>
            <value>
                <fullName>3D SENSORS</fullName>
            </value>
            <value>
                <fullName>400 GIG</fullName>
            </value>
            <value>
                <fullName>40 GIG</fullName>
            </value>
            <value>
                <fullName>800 GIG</fullName>
            </value>
            <value>
                <fullName>ACCESSORIES</fullName>
            </value>
            <value>
                <fullName>ACTIVES</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER</fullName>
            </value>
            <value>
                <fullName>ANALOG</fullName>
            </value>
            <value>
                <fullName>ANALOG-ISR</fullName>
            </value>
            <value>
                <fullName>ANALOG-US</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>CDAUI-16</fullName>
            </value>
            <value>
                <fullName>CDAUI-8</fullName>
            </value>
            <value>
                <fullName>LW/SONET MODULE</fullName>
            </value>
            <value>
                <fullName>LWMODULES</fullName>
            </value>
            <value>
                <fullName>NETWORK TOOLS</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-CHIP</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-OTHER</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-TRX</fullName>
            </value>
            <value>
                <fullName>PASSIVES</fullName>
            </value>
            <value>
                <fullName>ROADM</fullName>
            </value>
            <value>
                <fullName>SUB 10 GIG</fullName>
            </value>
            <value>
                <fullName>SWMODULES</fullName>
            </value>
            <value>
                <fullName>SW MODULES</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Serial_Number_Owner__mdt/RMA_Serial_Number_Owner__mdt.object-meta.xml
<CustomObject>
    <label>RMA Serial Number Owner</label>
    <pluralLabel>RMA Serial Number Owners</pluralLabel>
</CustomObject>

src/objects/RMA_Serial_Number_Owner__mdt/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Serial_Number_Owner__mdt/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <label>Marketing Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OCM</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OIG</fullName>
    </customValue>
    <customValue>
        <fullName>others</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/OrderItemPLMDashboardTriggerHelper.cls
public class OrderItemPLMDashboardTriggerHelper {
    
    public static void UpdateOrderPLMDashboardDetails(List<Order_Line__c> OrderItems)
    {
        List<Order> Order = New List<Order>();
        List<Order_Line__c> OrderItemGroup = New List<Order_Line__c>();
        List<Order_Line__c> AllRelatedOrderItems = New List<Order_Line__c>();
        List<String> OrderIds = New List<String>();
        
        for(Order_Line__c OrderitmObj: OrderItems){
            OrderIds.add(OrderitmObj.Order__c);
        }
        
        AllRelatedOrderItems = [Select Order__c,Contribution_Profit__c,Gross_Profit__c,Revenue__c from Order_Line__c 
                                where Order__c IN : OrderIds];
        System.debug('AllRelatedOrderItems'+AllRelatedOrderItems);
        List<Order> DistinctOrderList = new List<Order>();
        Map<Id, order> ordermap = new Map<Id, order>();
        for(Order_Line__c temp: AllRelatedOrderItems){
            if(ordermap.containsKey(temp.Order__c)){
                order tempor = ordermap.get(temp.Order__c);
                tempor.Gross_Profit__c = tempor.Gross_Profit__c + Temp.Gross_Profit__c ;
                tempor.Contribution_Profit__c = tempor.Contribution_Profit__c + Temp.Contribution_Profit__c ;    
                tempor.Revenue__c = tempor.Revenue__c + Temp.Revenue__c ; 
                ordermap.put(tempor.Id, tempor);
            } else {
                Order OrderTemp = new Order();    
                OrderTemp.Id = Temp.Order__c;
                OrderTemp.Gross_Profit__c = Temp.Gross_Profit__c;
                OrderTemp.Contribution_Profit__c = Temp.Contribution_Profit__c; 
                OrderTemp.Revenue__c = Temp.Revenue__c ;
                ordermap.put(OrderTemp.Id, OrderTemp);
            }
        }
        if(ordermap != null && !ordermap.isEmpty()){
            //update ordermap.values();
            String jsonString = json.serialize(ordermap.values());
            system.debug('jsonString 38 '+jsonString);
            updateOrders(jsonString);
        }
        /*Boolean found = false;
for(Integer i=0; i< DistinctOrderList.size(); i++){
if(Temp.Order__c == DistinctOrderList[i].Id){ 

DistinctOrderList[i].Gross_Profit__c = DistinctOrderList[i].Gross_Profit__c + Temp.Gross_Profit__c ;
DistinctOrderList[i].Contribution_Profit__c = DistinctOrderList[i].Contribution_Profit__c + Temp.Contribution_Profit__c ;    
DistinctOrderList[i].Revenue__c = DistinctOrderList[i].Revenue__c + Temp.Revenue__c ;   
found=true;
System.debug('InsideFound'+Temp); 
System.debug('InsideFound'+DistinctOrderList);     
break;
}
}
if(!found)
{   
Order OrderTemp = new Order();    
OrderTemp.Id = Temp.Order__c;
OrderTemp.Gross_Profit__c = Temp.Gross_Profit__c;
OrderTemp.Contribution_Profit__c = Temp.Contribution_Profit__c; 
OrderTemp.Revenue__c = Temp.Revenue__c ;    
DistinctOrderList.add(OrderTemp);
System.debug('InsideNotFound'+OrderTemp); 
System.debug('InsideNotFound'+DistinctOrderList); 
}    
}
System.debug('DistinctOrderList'+DistinctOrderList);
If(DistinctOrderList.size()>0){
update DistinctOrderList;
}
*/
    }
    public static void updateOwnerAtOrderLinesonUpdate(Map<Id,Order_Line__c> oldMap, Map<Id,Order_Line__c> newMap){
        Set<String> productGroupSet = New Set<String>();
        List<Order_line__c> orderLines = new List<Order_line__c>();
        Map<Id,Order_line__c> mapOfOrderLineToBeUpdated = New Map<Id,Order_line__c>();
        FOR(Id recordId:newMap.keyset()){
            IF(newMap.get(recordId).Ship_From_Inventory__c != 'WXI'
               && oldMap.get(recordId).Part_Number__c != newMap.get(recordId).Part_Number__c && 
               newMap.get(recordId).Part_Number__c!=Null){
                   orderLines.add(newMap.get(recordId));
                   productGroupSet.add(newMap.get(recordId).Product_Group__c);
               }
        }
        if(!productGroupSet.isEmpty() && productGroupSet != null){
            updateOwnerAtOrderLines(orderlines, productGroupSet);   
        }
        
    }
    public static void insertOwnerAtOrderLinesonUpdate(List<Order_line__c> orderLineList){
        Set<String> productGroupSet = New Set<String>();
        List<Order_line__c> orderlines = new List<Order_line__c>();
        Map<Id, Order_line__c> mapOfOrderLineToBeUpdated = New Map<Id,Order_line__c>();
        FOR(Order_line__c orderLineObj : orderLineList){
            IF(orderLineObj.Ship_From_Inventory__c != 'WXI' && orderLineObj.Product_Group__c != Null){
                productGroupSet.add(orderLineObj.Product_Group__c);
                orderlines.add(orderLineObj);
            }
        }
        updateOwnerAtOrderLines(orderlines, productGroupSet);
    }
    public static void updateOwnerAtOrderLines(List<Order_Line__c> newOrderLineList,Set<String> productGroupSet){
        Map<String,List<RMA_Serial_Number_Owner__mdt>> mapOfProductGroupAndOwnerMetadata = New Map<String,List<RMA_Serial_Number_Owner__mdt>>();
        Set<String> userEmailSet = New Set<String>();
        Map<String,User> UserEmailObjMap = New Map<String,User>();
        For(RMA_Serial_Number_Owner__mdt serialNumberOwnerMetadataObj :[Select id,Owner__c,End_Customer__c,Marketing_Family__c,Product_Group__c,Location__c 
                                                                        from RMA_Serial_Number_Owner__mdt 
                                                                        where Product_Group__c in:productGroupSet]){
                                                                            IF(mapOfProductGroupAndOwnerMetadata.containskey(serialNumberOwnerMetadataObj.Product_Group__c)){
                                                                                mapOfProductGroupAndOwnerMetadata.get(serialNumberOwnerMetadataObj.Product_Group__c).add(serialNumberOwnerMetadataObj);
                                                                            }
                                                                            else{
                                                                                mapOfProductGroupAndOwnerMetadata.put(serialNumberOwnerMetadataObj.Product_Group__c,New List<RMA_Serial_Number_Owner__mdt>{serialNumberOwnerMetadataObj});
                                                                            } 
                                                                            userEmailSet.add(serialNumberOwnerMetadataObj.Owner__c);                                                   
                                                                        }
        IF(!mapOfProductGroupAndOwnerMetadata.isempty()){
            For(User userObj : [Select id,email from user where email in:userEmailSet and IsActive=True]){
                UserEmailObjMap.put(userObj.email,userObj);
            }
            For(Order_line__c orderlineObj:newOrderLineList){
                System.debug('orderlineObj'+orderlineObj);
                
                IF(mapOfProductGroupAndOwnerMetadata.containskey(orderlineObj.Product_Group__c)){
                    
                    For(RMA_Serial_Number_Owner__mdt metaDataObj:mapOfProductGroupAndOwnerMetadata.get(orderlineObj.Product_Group__c)){
                        System.debug(metaDataObj.Location__c.equalsIgnoreCase(orderlineObj.Ship_From_Inventory__c));
                        IF(!metaDataObj.Location__c.equalsIgnoreCase(orderlineObj.Ship_From_Inventory__c)){
                            continue;
                        }
                        IF(!String.isBlank(orderlineObj.Marketing_Family__c) && !(metaDataObj.Marketing_Family__c.contains(orderlineObj.Marketing_Family__c)|| metaDataObj.Marketing_Family__c.equalsignorecase('All'))){
                            continue;
                        }
                        IF(((!String.isBlank(orderlineObj.End_Customer__c) && orderlineObj.End_Customer__c.contains(metaDataObj.End_Customer__c))||
                            metaDataObj.End_Customer__c.equalsignorecase('All')||
                            metaDataObj.End_Customer__c.equalsignorecase('others')) &&
                           UserEmailObjMap.containskey(metaDataObj.Owner__c)){
                               orderlineObj.OwnerId = UserEmailObjMap.get(metaDataObj.Owner__c).Id;
                               System.debug('orderlineObj'+orderlineObj);
                           }
                    }
                }
            }
        }
    }
    // Added method to update Failure Location from Case object into Orderline Object using Serial number Rma id column 
    public static void failureLocationupdate(Map<id,Order_Line__c> newordline){ 
        List<String> ordrmaid = new List<String>();
        system.debug(newordline);
        for(Id recordid:newordline.keySet()){
            system.debug(newordline.get(recordid).Failure_Location__c);
            if ((newordline.get(recordid).rmaid__c != null && newordline.get(recordid).Failure_Location__c == null)){
                ordrmaid.add(newordline.get(recordid).rmaid__c);
            }
        }
        if(!ordrmaid.isEmpty())
            updateOrderLineLocation(newordline.keySet(), ordrmaid);
        // updateOrderLineLocation(newordline,ordrmaid);
    }
    
    public static void updateOrderLineLocation(set<id> ordline, List<String> rmaid){
        
        
        if(!rmaid.isEmpty())
        {
            List<Order_Line__c> ordlinelist = [select id,Failure_Location__c,rmaid__c from Order_Line__c where id in :ordline];
            List<Case> cs = [select id,casenumber,Failure_Location__c from Case where casenumber in :rmaid];
            List<Order_Line__c> updateorderlist = new  List<Order_Line__c>();
            Map<String,String> cs_Floc = new Map<String,String>();
            for(Case c:cs){
                cs_Floc.put(c.casenumber, c.Failure_Location__c);
            }
            for(Order_Line__c ordlnid : ordlinelist){
                //     for(Order_Line__c ordlnid : ordline.values()){
                if(cs_Floc.containsKey(ordlnid.rmaid__c))
                {
                    ordlnid.Failure_Location__c = cs_Floc.get(ordlnid.rmaid__c);
                    updateorderlist.add(ordlnid);
                }
            } 
            if(updateorderlist != null)
                update updateorderlist;
        }
        
    }
    public static void checkHROCM(List<Order_Line__c> orderLines){
        Set<Id> orderIds = new Set<Id>();
        Set<Id> PrdIds = new Set<Id>();
        List<Order> orders = new List<Order>();
        for(Order_Line__c line : orderLines){
            PrdIds.add(line.Part_Number__c);
        }
        Map<Id,Product2> prdMap = new Map<Id, Product2>([SELECT id, Name, Product_Family__c FROM Product2 WHERE Id IN :PrdIds]);
        for(Order_Line__c line : orderLines){
            if(line.Ship_From_Inventory__c == 'WXI' && 
               prdMap.containsKey(line.Part_Number__c) &&
               (prdMap.get(line.Part_Number__c).Product_Family__c == 'WSS-OCM' ||
                prdMap.get(line.Part_Number__c).Product_Family__c == 'WSS-OIG')){
                    line.HROCM_Line__c = true;
                    orderIds.add(line.Order__c);
                }
        }
        /*   for(Id orderId : orderIds){
orders.add(new order(id = orderId, HROCM_Order__c = true ));
}
if(orders != null && !orders.isEmpty()){
//update orders;
String jsonString = json.serialize(orders);
updateOrders(jsonString);
}*/
    }
    
    public static void updateOrderWarehouse(List<Order_line__c> orderlines){
        List<String> orderIds = new List<String>();
        List<Order> updatedOrder = new List<Order>();
        Set<Id> updatedIds = new Set<Id>();
        for(order_Line__c line :orderlines){
            orderIds.add(line.order__c);
        }
        Map<Id, Order> orderMap = new Map<Id, Order>([SELECT Id, HROCM_Order__c, Warehouse__c FROM Order WHERE Id IN :orderIds]);
        for(order_Line__c line :orderlines){
            if(orderMap.containsKey(line.Order__c)){
                if(line.HROCM_Line__c && !orderMap.get(line.Order__c).HROCM_Order__c){
                    orderMap.get(line.Order__c).HROCM_Order__c = true;
                    updatedIds.add(line.Order__c);
                }
                if(orderMap.get(line.Order__c).Warehouse__c != 'SYD' &&
                   orderMap.get(line.Order__c).Warehouse__c != line.Ship_From_Inventory__c){
                       orderMap.get(line.Order__c).Warehouse__c = line.Ship_From_Inventory__c;
                       updatedIds.add(line.Order__c);
                   }
            }
            
        }
        for(Id orderId : updatedIds){
            updatedOrder.add(orderMap.get(orderId));
        }
        if(updatedOrder != null && !updatedOrder.isEmpty()){
            String jsonString = json.serialize(updatedOrder);
            system.debug('jsonString 233 '+jsonString);
            updateOrders(jsonString);
        }
    }
    @future
    public static void updateOrders(String jsonOrders){
        List<Order> orderList = (List<Order>)Json.deserialize(jsonOrders, List<Order>.class);
        database.update(orderList, false) ;
    }
}