src/objects/Case/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dead on Arrival</fullName>
            </value>
            <value>
                <fullName>Fail at customer</fullName>
            </value>
            <value>
                <fullName>Field failure / Fail at end-customer</fullName>
            </value>
            <value>
                <fullName>Sample / Demo /Loaner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Failure_Location__c.field-meta.xml
<CustomField>
    <fullName>Failure_Location__c</fullName>
    <label>Failure Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/RMAID__c.field-meta.xml
<CustomField>
    <fullName>RMAID__c</fullName>
    <label>RMAID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/classes/RmaOrderLine_FailureLocationupdate.cls
public class RmaOrderLine_FailureLocationupdate {
    
    public static void failureLocationupdate(Map<id,Order_Line__c> newordline)
    { 
        
            List<String> ordrmaid = new List<String>();
         system.debug(newordline);
          for(Id recordid:newordline.keySet())
          {
              
              system.debug(newordline.get(recordid).Failure_Location__c);
             if ((newordline.get(recordid).rmaid__c != null && newordline.get(recordid).Failure_Location__c == null)){
                  ordrmaid.add(newordline.get(recordid).rmaid__c);
                
          }
            
         
          }
         if(!ordrmaid.isEmpty())
           updateOrderLineLocation(newordline.keySet(),ordrmaid);
    }
    
    public static void updateOrderLineLocation(Set<id> ordline,List<String> rmaid){
        
          
           if(!rmaid.isEmpty())
                {

                 List<Order_Line__c> ordlinelist = [select id,Failure_Location__c,rmaid__c from Order_Line__c where id in :ordline];
                 List<Case> cs = [select id,casenumber,Failure_Location__c from Case where casenumber in :rmaid];
                 List<Order_Line__c> updateorderlist = new  List<Order_Line__c>();
                 Map<String,String> cs_Floc = new Map<String,String>();
                  for(Case c:cs)
                    {
                        cs_Floc.put(c.casenumber,c.Failure_Location__c);
                     }
                  for(Order_Line__c ordlnid:ordlinelist){
                                              
                  if(cs_Floc.containsKey(ordlnid.rmaid__c))
                       {
                           ordlnid.Failure_Location__c = cs_Floc.get(ordlnid.rmaid__c);
                           updateorderlist.add(ordlnid);
                    
                   }
                  
               
              }       

          if(!updateorderlist.isEmpty())
            update updateorderlist;
           }

    
    }

}