src/objects/Case/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <label>Return Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>Serial Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <description>Case</description>
    <label>FAE Case</label>
</RecordType>

src/objects/RMA_Request_Line__c/RMA_Request_Line__c.object-meta.xml
<CustomObject>
    <label>RMA Request Line</label>
    <nameField>
        <label>Customer Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMA_Request_Line__c/fields/Brief_description_of_the_failure__c.field-meta.xml
<CustomField>
    <fullName>Brief_description_of_the_failure__c</fullName>
    <label>Brief description of the failure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/PO_Price__c.field-meta.xml
<CustomField>
    <fullName>PO_Price__c</fullName>
    <label>PO Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original PO</fullName>
                <default>true</default>
                <label>Original PO</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Return_Reason__c.field-meta.xml
<CustomField>
    <fullName>Return_Reason__c</fullName>
    <inlineHelpText>Why is the part being returned</inlineHelpText>
    <label>Return Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Failure</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Rework/Re-test</fullName>
            </value>
            <value>
                <fullName>Customer Accommodation</fullName>
            </value>
            <value>
                <fullName>Sample/Demo Return</fullName>
            </value>
            <value>
                <fullName>Product Failure</fullName>
            </value>
            <value>
                <fullName>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</fullName>
                <isActive>false</isActive>
                <label>&quot;Equipment failure,  Service outage. Verified by Telesur Network operations together with Ciena support&quot;</label>
            </value>
            <value>
                <fullName>AA</fullName>
                <isActive>false</isActive>
                <label>AA</label>
            </value>
            <value>
                <fullName>ASAS</fullName>
                <isActive>false</isActive>
                <label>ASAS</label>
            </value>
            <value>
                <fullName>DFD</fullName>
                <isActive>false</isActive>
                <label>DFD</label>
            </value>
            <value>
                <fullName>DSD</fullName>
                <isActive>false</isActive>
                <label>DSD</label>
            </value>
            <value>
                <fullName>Faulty CFP2 causing OTL Loss of Lane Alignment</fullName>
                <isActive>false</isActive>
                <label>Faulty CFP2 causing OTL Loss of Lane Alignment</label>
            </value>
            <value>
                <fullName>Functional</fullName>
                <isActive>false</isActive>
                <label>Functional</label>
            </value>
            <value>
                <fullName>Loss Of Signal</fullName>
                <isActive>false</isActive>
                <label>Loss Of Signal</label>
            </value>
            <value>
                <fullName>Loss of frame alarm flapping</fullName>
                <isActive>false</isActive>
                <label>Loss of frame alarm flapping</label>
            </value>
            <value>
                <fullName>OO</fullName>
                <isActive>false</isActive>
                <label>OO</label>
            </value>
            <value>
                <fullName>Pluggable alarm occurred</fullName>
                <isActive>false</isActive>
                <label>Pluggable alarm occurred</label>
            </value>
            <value>
                <fullName>Ports would not validate</fullName>
                <isActive>false</isActive>
                <label>Ports would not validate</label>
            </value>
            <value>
                <fullName>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</fullName>
                <isActive>false</isActive>
                <label>Problem Description: Pluggable Tx power is OOR-LO. Tried re-seating and also tried installing pluggable on different port.</label>
            </value>
            <value>
                <fullName>SDS</fullName>
                <isActive>false</isActive>
                <label>SDS</label>
            </value>
            <value>
                <fullName>TEST UAT</fullName>
                <isActive>false</isActive>
                <label>TEST UAT</label>
            </value>
            <value>
                <fullName>TXing errors</fullName>
                <isActive>false</isActive>
                <label>TXing errors</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>alarms raised</fullName>
                <isActive>false</isActive>
                <label>alarms raised</label>
            </value>
            <value>
                <fullName>as</fullName>
                <isActive>false</isActive>
                <label>as</label>
            </value>
            <value>
                <fullName>asa</fullName>
                <isActive>false</isActive>
                <label>asa</label>
            </value>
            <value>
                <fullName>dsds</fullName>
                <isActive>false</isActive>
                <label>dsds</label>
            </value>
            <value>
                <fullName>sdsda</fullName>
                <isActive>false</isActive>
                <label>sdsda</label>
            </value>
            <value>
                <fullName>upgrade to firmware 35 per details and file attached in FAE case</fullName>
                <isActive>false</isActive>
                <label>upgrade to firmware 35 per details and file attached in FAE case</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/RMA_Request_Line__c/fields/RMA_Request__c.field-meta.xml
<CustomField>
    <fullName>RMA_Request__c</fullName>
    <inlineHelpText>This is the RMA Request to which this line item looks up</inlineHelpText>
    <label>RMA Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RMA Request Lines</relationshipLabel>
    <relationshipName>RMA_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/RMA_Request_Line__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <description>This is a concatenation of the serial number and the case number for the purposes of ensuring that serial numbers are not duplicated on a single RMA Request</description>
    <externalId>true</externalId>
    <label>SerialNumber</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/RMA_Request_Line__c/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <label>Special Instructions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/classes/FileUploadController.cls
public with sharing class FileUploadController {
    
    
    @AuraEnabled
    public static String  parseCSV(String contents,Boolean skipHeaders,string caseID) 
    {
        
        List<String> errorMsgList = new List<String>();
        id uId = userinfo.getuserid() ;
        UserRecordAccess aurc =   [SELECT RecordId, HasReadAccess,HasAllAccess,HasEditAccess, HasTransferAccess, MaxAccessLevel
                                   FROM UserRecordAccess
                                   WHERE UserId =: uId
                                   AND RecordId =: caseID];
        boolean Access = aurc.HasAllAccess;
        if(Access)
        {
             List<List<String>> allFields = new List<List<String>>();
            contents = contents.replaceAll(',"""',',"DBLQT').replaceall('""",','DBLQT",');
            contents = contents.replaceAll('""','DBLQT');
            List<String> lines = new List<String>();
            try {
                lines = contents.split('\n');
                Integer num = 0;
                for(String line : lines) {
                    System.debug('  line'+line);
                    if (line.replaceAll(',','').trim().length() == 0) break;
                    List<String> fields = line.split(',');  
                    List<String> cleanFields = new List<String>();
                    String compositeField;
                    Boolean makeCompositeField = false;
                    for(String field : fields) {
                        system.debug('field'+field);
                        if (field.startsWith('"') && field.endsWith('"')) {
                            cleanFields.add(field.replaceAll('DBLQT','"'));
                        } else if (field.startsWith('"')) {
                            makeCompositeField = true;
                            compositeField = field;
                        } else if (field.endsWith('"')) {
                            compositeField += ',' + field;
                            cleanFields.add(compositeField.replaceAll('DBLQT','"'));
                            makeCompositeField = false;
                        } else if (makeCompositeField) {
                            compositeField +=  ',' + field;
                        } else {
                            cleanFields.add(field.replaceAll('DBLQT','"'));
                        }
                    }
                    system.debug('cleanFields ' + cleanFields);
                    allFields.add(cleanFields);
                    
                }             
                if (skipHeaders) allFields.remove(0);
                system.debug('allFields after removing header ' + allFields);
                list<RMA_Request_Line__c> upsertRMALines = new list<RMA_Request_Line__c>();  
              case RMAHeader = [select id, CaseNumber from case where id =:  caseID];
                for(list<string> sn : allFields){
                  
                    RMA_Request_Line__c newRMARequestLine = new RMA_Request_Line__c(); 
  		           if(sn[0] == '')
                    {
                         String serialNoMsg  ='Serial Number shouldn’t leave as blank at Row '+ (allFields.indexOf(sn)+2) +'\n';
                        errorMsgList.add(serialNoMsg);
                    }
                    else if(sn[0] != '')
                    {
                           newRMARequestLine.Name = sn[0];
					}
                    
                    if(sn[1] == '')
                    {
                         String DescripMsg  ='Description shouldn’t leave as blank at Row '+ (allFields.indexOf(sn)+2) +'\n';
                        errorMsgList.add(DescripMsg);
                    }
                    else if(sn[1] != '')
                    {
                         newRMARequestLine.Brief_description_of_the_failure__c  = sn[1];
					}
                    if(sn[2] != '' && ValidatepicklistValues('Return_Reason__c',sn[2]))
                    {
                        newRMARequestLine.Return_Reason__c = sn[2];
                    }
                    else
                    {
                        
                        String ReturnreasonMsg  ='Wrong Return Reason at Row  '+ (allFields.indexOf(sn)+2) +' \n ' ;
                        errorMsgList.add(ReturnreasonMsg);
                    }
                    if(sn[3] != '' && ValidatepicklistValues('PO_Price__c',sn[3]))
                    {
                        newRMARequestLine.PO_Price__c = sn[3];
                    }
                    else
                    {
                        
                        String PoPriceMsg  = 'Wrong PO Price Type at Row  '+(allFields.indexOf(sn)+2) +'\n';
                        errorMsgList.add(PoPriceMsg);
                    }
					if( newRMARequestLine.Name != null)
                    {
                        newRMARequestLine.Special_Instructions__c = sn[4];
                        newRMARequestLine.RMA_Request__c = RMAHeader.Id;
                        newRMARequestLine.SerialNumber__c = RMAHeader.CaseNumber +  newRMARequestLine.Name;
                        upsertRMALines.add(newRMARequestLine);
                    }
                }
                if(errorMsgList.size()==0 && upsertRMALines.size()>0)
                {
                 /*   case cs = [select id, CaseNumber from case where id =:  caseID];
                    for(RMRequestWrapper sn : upsertRMALines){
                        
                        RMA_Request_Line__c rn = new RMA_Request_Line__c(); 
                        rn.Name     = sn.sNo;
                        rn.Brief_description_of_the_failure__c     = sn.Description;
                        rn.Return_Reason__c     = sn.ReturnReason;
                        rn.PO_Price__c     = sn.POPriceType;
                        rn.Special_Instructions__c     = sn.SpecialInstructions;
                        rn.RMA_Request__c = caseID;
                        rn.SerialNumber__c = cs.CaseNumber +  sn.sNo ;       
                        rmList.add(rn);
                     
                    }*/
                    Schema.SObjectField SerialNumberField = RMA_Request_Line__c.Fields.SerialNumber__c;
                    Database.UpsertResult[] ErrorFile = Database.upsert(upsertRMALines,SerialNumberField, true);
                    System.debug('**********Records not inserted'+ErrorFile);
                    return 'SUCCESS';
                }
                else
                {
                    String errorMsg = String.join(errorMsgList,' , ');
                    return errorMsg;
                }
            }
            catch(ListException e)
            {
                errorMsgList = new List<String>();
                errorMsgList.add(e.getMessage());
                System.debug('****************'+e.getStackTraceString());
            }
            catch(DmlException e) {
                errorMsgList = new List<String>();
                System.debug('Stack trace String : ' + e.getStackTraceString());
                String dmlMessage =e.getMessage();
                if(dmlMessage.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') && dmlMessage.contains('Pending RMA Admin Review'))
                    errorMsgList.add('New Line Items can not be added when Status is in Pending RMA Admin Review');
                else
                    errorMsgList.add(dmlMessage);
                
            }
            catch(NoAccessException e)
            {
                errorMsgList = new List<String>();
                errorMsgList.add('You don\'t have permission to insert /update certain fields');
                System.debug('Access Exception: ' + e.getMessage());
            }
            catch(LimitException e)
            {
                
                System.debug('Apex CPU Limit Exception '+e.getMessage());
                return ' Salesforce CPU Time Exceeded .Please reduce file and try again';
            }
            
        }
        else 
        {
            errorMsgList = new List<String>();
            errorMsgList.add('Error! You don\'t have permission to insert RMA Lines For Case Record');
        }
        return String.join(errorMsgList, '\n'); 
    }
    
    public static Boolean  ValidatepicklistValues(String fieldApiName,String fieldvalue)
    {
        
        Schema.DescribeFieldResult fieldresult = Schema.getGlobalDescribe().get('RMA_Request_Line__c').getDescribe().fields.getMap().get(fieldApiName).getDescribe();
        List<Schema.PicklistEntry> plelist = fieldresult.getPicklistValues();
        for(Schema.PicklistEntry picklistentry:plelist)
        {
            if(fieldvalue.equalsIgnoreCase(picklistentry.getValue()) && picklistentry.isActive())
                return true;
            
        }
        return false;
    }
    
   /* public class RMRequestWrapper{
        /* @AuraEnabled public string FinisarPartNumber;
@AuraEnabled public string Amount;
@AuraEnabled public string Quantity;

        @AuraEnabled public string sNo;
        @AuraEnabled public string Description;
        @AuraEnabled public string ReturnReason;
        @AuraEnabled public string POPriceType;
        @AuraEnabled public string SpecialInstructions;
        
    }*/
}