src/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Business_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Name__c</fullName>
    <description>This field is populated using a field update and is updated to the parent Product: Business Unit Name field when Created By field is not equal to NULL (essentially, upon record creation), whenever the record is saved.</description>
    <inlineHelpText>This field is populated using a field update and is updated to the parent Product: Business Unit Name field whenever the record is saved.</inlineHelpText>
    <label>Business Unit Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unspecified</fullName>
            </value>
            <value>
                <fullName>Data Networking</fullName>
            </value>
            <value>
                <fullName>Optical Interconnect</fullName>
            </value>
            <value>
                <fullName>3D Sensing</fullName>
            </value>
            <value>
                <fullName>WSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Business_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Name__c</fullName>
    <formula>IF(ISPICKVAL(Business_Unit__c, &quot;CC00&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC10&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC11&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC12&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC13&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC14&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC15&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC20&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC21&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC22&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC23&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC24&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC25&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC30&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC31&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC32&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC50&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC51&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC60&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC61&quot;), &quot;Components&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;CC75&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;CC85&quot;), &quot;Components&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PC60&quot;), &quot;Power&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;PC61&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PC62&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS60&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS61&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;PS63&quot;), &quot;Power&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY00&quot;), &quot;Systems&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY10&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY20&quot;), &quot;Systems&quot;, 
IF(ISPICKVAL(Business_Unit__c, &quot;SY30&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY60&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY61&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY62&quot;), &quot;Systems&quot;,
IF(ISPICKVAL(Business_Unit__c, &quot;SY63&quot;), &quot;Systems&quot;,&quot;N/A&quot;
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit Name</label>
    <type>Text</type>
</CustomField>

src/classes/OpportunityProductHandler.cls
public class OpportunityProductHandler {

    public List<OpportunityLineItem> olist = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE Id IN: trigger.newmap.keyset() ];


    public OpportunityProductHandler(){
    
    }
    
    Public static void updateBUNOnOpportunityProduct(List<OpportunityLineItem> OpportunityLineItems){
        
        Set<String> ids = new Set<String>();
        for(OpportunityLineItem o : OpportunityLineItems){
            ids.add(o.Product2Id);
        }
        Map<id,Product2> myProducts = new Map<Id,Product2>([select id,Business_Unit_Name__c from product2 where id in:ids]);
        for(OpportunityLineItem o : OpportunityLineItems){
            o.Business_Unit_Name__c = myProducts.get(o.Product2Id).Business_Unit_Name__c;
        }
    }
    
    public static void RollUpBUN(List<OpportunityLineItem> OpportunityLineItems){
        if(OpportunityLineItems!=null){
            Set<String> ids = new Set<String>();
            for(OpportunityLineItem o : OpportunityLineItems){
                ids.add(o.OpportunityId);
            }
            
            List<Opportunity> Result = new List<Opportunity>();
    
            Result = [SELECT id,Business_Unit__c,(select id,OpportunityId ,Business_Unit_Name__c,TotalPrice,createddate from OpportunityLineItems  where OpportunityId  in: ids order by TotalPrice,createddate) from opportunity where id in:ids ];       
            
            map<string,string> finalmap = new map<string,string>();
            for(opportunity o : Result){
                map<string,integer> myMap1 = new map<string,integer>();    
                map<Integer,set<string>> myMap2 = new map<Integer,set<string>>();
                
                for(OpportunityLineItem a : o.OpportunityLineItems){  
                    if(a.Business_Unit_Name__c!=null && a.Business_Unit_Name__c!=''){
                        if(myMap1.containskey(a.Business_Unit_Name__c)){
                            integer i=myMap1.get(a.Business_Unit_Name__c); 
                            i=i+1;
                            myMap1.put(a.Business_Unit_Name__c,i);       
                        }else{
                            myMap1.put(a.Business_Unit_Name__c,1);       
                        }
                    }
                }
                
                for(string s : myMap1.keyset()){
                    if(myMap2.containsKey(myMap1.get(s))){
                        set<string> str = myMap2.get(myMap1.get(s));
                        str.add(s);
                        myMap2.put(myMap1.get(s),str);
                    }else{
                        set<string> str = new set<string>();
                        str.add(s);
                        myMap2.put(myMap1.get(s),str);
                    }
                }
                
                integer i=-1;
                for(integer s : myMap2.keyset()){
                    if(i==-1)   i=s;
                    else{
                        if(s>i) i=s;
                    }
                }
                set<string> dupset ;
                dupset= myMap2.get(i);
                if(dupset!=null){
                if(dupset.size()>0){
                    decimal max=-1;
                    datetime mydate;
                    string currentVal;
                    for(string d : dupset){
                        for(OpportunityLineItem a : o.OpportunityLineItems){
                            if(a.Business_Unit_Name__c!=null && a.Business_Unit_Name__c!=''){
                                if(d==a.Business_Unit_Name__c ){
                                    if(max==-1){
                                        max=a.TotalPrice;
                                        mydate=a.createddate;
                                        currentVal=a.Business_Unit_Name__c;
                                        continue;
                                    }
                                    else{
                                        if(max<a.TotalPrice){
                                            max=a.TotalPrice;
                                            mydate=a.createddate;
                                            currentVal=a.Business_Unit_Name__c;
                                        }
                                        else if(max==a.TotalPrice){
                                            if(mydate<a.createddate){
                                                mydate=a.createddate;
                                                max=a.TotalPrice;
                                                currentVal=a.Business_Unit_Name__c;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    finalmap.put(o.id,currentVal);
                }
                else{ for(string s :dupset) finalmap.put(o.id,s); }
                }
                else{
                    finalmap.put(o.id,'');
                }
            
            }
            list<opportunity> oppToUpdate = new list<opportunity>();
            for(opportunity o : Result){
                if(finalmap.containsKey(o.id)){
                    o.Business_Unit__c=finalmap.get(o.id);
                    oppToUpdate.add(o);
                }
            }
            
            if(oppToUpdate.size() > 0) {
                try {
                    Update oppToUpdate;
                } catch (Exception e) {

                    for(OpportunityLineItem ol : [SELECT Id FROM OpportunityLineItem WHERE Id IN: trigger.new]) {
                        Trigger.newMap.get(ol.Id).addError(e);                    
                    }

                }
            }

        }
    }    
}