src/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Product_Family__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unspecified</fullName>
            </value>
            <value>
                <fullName>Data Networking</fullName>
            </value>
            <value>
                <fullName>Optical Interconnect</fullName>
            </value>
            <value>
                <fullName>3D Sensing</fullName>
            </value>
            <value>
                <fullName>WSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OCM</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OIG</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/OpportunityBUUpdateBatch.cls
public class OpportunityBUUpdateBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC ){
        if(!Test.isRunningTest()){
            //return Database.getQueryLocator([select id,name,business_Unit__c from opportunity where id= '0062f00000C0ejPAAR']);  
            return Database.getQueryLocator([select id,name,business_Unit__c from opportunity where business_Unit__c = null]);  
        } else {
            return Database.getQueryLocator([select id,name,business_Unit__c from opportunity where business_Unit__c = null LIMIT 200]);
        }
        
    }
    public void execute(Database.BatchableContext BC, List<opportunity> scope) {
        Map<Id, String> opptyMap = new Map<Id, String>();
        List<Opportunity> optList = new List<Opportunity>();
        for(OpportunityLineItem line : [SELECT Id,OpportunityId, Product2id, Product2.BU_Code__c, Product2.Product_Family__c
                                        FROM OpportunityLineItem 
                                        WHERE OpportunityId IN : scope]){
                                            if(line.Product2.BU_Code__c == '0040' &&
                                               line.Product2.Product_Family__c != 'WSS-OCM' &&
                                               line.Product2.Product_Family__c != 'WSS-OIG'){
                                                   opptyMap.put(line.OpportunityId, 'WSS');
                                                   
                                               } else if(!opptyMap.containsKey(line.OpportunityId)) {
                                                   opptyMap.put(line.OpportunityId, 'non WSS');
                                               }
                                        }
        for(Id oppId : opptyMap.KeySet()){
            optList.add(new Opportunity(Id = oppId, business_Unit__c = opptyMap.get(oppId)));
        }
        if(optList != null && !optList.isEmpty()){
            database.update(optList, false) ;
        }
    }
    public void finish(Database.BatchableContext BC) {
        
    }
}