src/objects/Opportunity/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary (Shipping) Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/recordTypes/Aftermarket.recordType-meta.xml
<RecordType>
    <fullName>Aftermarket</fullName>
    <active>true</active>
    <businessProcess>Aftermarket</businessProcess>
    <label>Aftermarket</label>
</RecordType>

src/objects/OpportunityLineItem/fields/Additional_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Additional_Specifications__c</fullName>
    <label>Additional Specifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Alternate_Description__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Description__c</fullName>
    <label>Alternate Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/ConfigureBOMParts__c.field-meta.xml
<CustomField>
    <fullName>ConfigureBOMParts__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;apex/AddBOMToOpportunity?id=&quot;+Id, &apos;Components&apos;,&apos;_top&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Configure BOM Parts</label>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/II_VI_DE_Long_Description__c.field-meta.xml
<CustomField>
    <fullName>II_VI_DE_Long_Description__c</fullName>
    <label>II-VI DE Long Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <label>Lead Time</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Long_Description_English__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_English__c</fullName>
    <label>Long Description English</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Long_Description_French__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_French__c</fullName>
    <label>Long Description French</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>Use to track the customer&apos;s requested ship date.</inlineHelpText>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <description>Date the Part ix expected to be shipped.</description>
    <inlineHelpText>Date the Part ix expected to be shipped.</inlineHelpText>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityRatePlan__c/OpportunityRatePlan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Rate Plan</label>
    <nameField>
        <displayFormat>ORL-{00000}</displayFormat>
        <label>Opportunity Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityRatePlan__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>Opportunity Line Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Order/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Additional_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Additional_Specifications__c</fullName>
    <label>Additional Specifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Order_Line__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Lines (Customer Name)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <label>Lead Time</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Description__c</fullName>
    <description>This is used for Corp II-VI only.</description>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Long_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Text_Description__c</fullName>
    <description>This is used for Corp II-VI only.</description>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Order_Product_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Product_Sequence_Number__c</fullName>
    <label>Order Product Sequence Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Unit_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Selling_Price__c</fullName>
    <label>Unit Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/OrderRatePlan__c/OrderRatePlan__c.object-meta.xml
<CustomObject>
    <label>Order Rate Plan</label>
    <nameField>
        <displayFormat>ORT-{00000}</displayFormat>
        <label>Order Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderRatePlan__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Order Rate Plans</relationshipLabel>
    <relationshipName>Order_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/User/fields/Legacy_Company__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Company__c</fullName>
    <description>Used to support existing processes during the org merge processes</description>
    <label>Legacy Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finisar</fullName>
            </value>
            <value>
                <fullName>Corp II-VI</fullName>
            </value>
            <value>
                <fullName>Marlow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/OpportunityTriggerHelper.cls
public class OpportunityTriggerHelper {
    public static Boolean orderCreated = false;
    public static void createOrderonClosedOpps(Map<Id, Opportunity> oldMap, List<Opportunity> newList){
        List<Opportunity> closedownOpps = new List<Opportunity>();
        Map<Id, Order> oppOrderMap = new Map<Id, Order>();
        User loggedInUserRec=[Select Id,Legacy_Company__c from User where Id=:UserInfo.getUserId()];
        for(Opportunity opp : newList){
            //Added two additional criteria for Order and OrderLine record creation i.e.,User Legacy_Company__c='Corp II-VI' and Opp recordType='AfterMarket' 
            if(loggedInUserRec.Legacy_Company__c == 'Corp II-VI'
               && opp.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftermarket').getRecordTypeId()
               && (opp.StageName == 'Closed Won' || opp.StageName == 'Closed via PO') && 
               opp.StageName != oldMap.get(opp.Id).StageName)
            {
                closedownOpps.add(opp);
            }
        }
        for(Opportunity opp : closedownOpps){
            Order ord = new Order();
            //Added to match target and source field length
            if(opp.Name.length()>80){
               ord.Name = opp.Name.substring(0,80); 
            }else{
               ord.Name = opp.Name;
            }
            ord.AccountId = opp.AccountId;
            ord.opportunityId = opp.Id;
            ord.CurrencyIsoCode = opp.CurrencyIsoCode;
            ord.Status = 'Draft';
            ord.EffectiveDate = date.today();
            ord.Pricebook2Id = opp.Pricebook2Id;
            ord.Primary_Shipping_Contact__c = opp.Primary_Shipping_Contact__c;
            ord.Legacy_Id__c = opp.Legacy_Id__c ;
            ord.RecordTypeId= Schema.SObjectType.Order.getRecordTypeInfosByName().get('Sales Order').getRecordTypeId();
            oppOrderMap.put(opp.Id, ord);
        }
        if(oppOrderMap != null && !oppOrderMap.isEmpty()){
            insert oppOrderMap.values();
            orderCreated = true;
        }
        Map<Id, Order_Line__c> newLineMap = new Map<Id, Order_Line__c>();
        Integer sequence = 1;
        for(OpportunityLineItem oppLine : [SELECT Id, Product2Id, ProductCode, ConfigureBOMParts__c, Quantity, Description, SortOrder,
                                           UnitPrice, Subtotal, Discount, TotalPrice, PricebookEntryId, OpportunityId,Description__c,
                                           Additional_Specifications__c, II_VI_DE_Long_Description__c, Long_Description_English__c,
                                           Long_Description_French__c, Alternate_Description__c, Request_Date__c, Ship_Date__c, Lead_Time__c
                                           FROM OpportunityLineItem 
                                           WHERE OpportunityId IN :oppOrderMap.keySet() ORDER By SortOrder]){
                                               Order_Line__c  newLine = new Order_Line__c ();
                                               newLine.Order__c  = oppOrderMap.get(oppLine.OpportunityId).Id;
                                               newLine.Customer_Name__c=oppOrderMap.get(oppLine.OpportunityId).AccountId;
                                               newLine.Part_Number__c   = oppLine.Product2Id;
                                               newLine.Line_Description__c = oppLine.Description;
                                               newLine.Long_Text_Description__c = oppLine.Description__c;
                                               newLine.Quantity__c  = oppLine.Quantity;
                                               newLine.Unit_Selling_Price__c = oppLine.UnitPrice;
                                               newLine.Additional_Specifications__c = oppLine.Additional_Specifications__c;
                                               newLine.II_VI_DE_Long_Description__c = oppLine.II_VI_DE_Long_Description__c;
                                               newLine.Long_Description_English__c = oppLine.Long_Description_English__c;
                                               newLine.Long_Description_French__c = oppLine.Long_Description_French__c;
                                               newLine.Alternate_Description__c = oppLine.Alternate_Description__c;
                                               newLine.Request_Date__c = oppLine.Request_Date__c;
                                               newLine.Ship_Date__c = oppLine.Ship_Date__c;
                                               newLine.Lead_Time__c = oppLine.Lead_Time__c;
                                               if(oppLine.SortOrder != null){
                                                   newLine.Order_Product_Sequence_Number__c  = oppLine.SortOrder;
                                               }else{
                                                   newLine.Order_Product_Sequence_Number__c = sequence;
                                                   sequence = sequence+1;
                                               }
                                               
                                               newLineMap.put(oppLine.Id, newLine);
                                           }
        if(newLineMap != null && !newLineMap.isEmpty()){
            insert newLineMap.values();
        }
        List<OrderRatePlan__c> ratePlans = new List<OrderRatePlan__c>();
        for(OpportunityRatePlan__c oplan : [SELECT Id, OpportunityLineItem__c, SalesPrice__c, SequenceNumber__c, 
                                            Description__c, LeadTime__c
                                            FROM OpportunityRatePlan__c 
                                            WHERE OpportunityLineItem__c IN :newLineMap.keySet()]){
                                                OrderRatePlan__c plan = new OrderRatePlan__c();
                                                plan.OrderProduct__c = newLineMap.get(oplan.OpportunityLineItem__c).Id;
                                                plan.LeadTime__c = oplan.LeadTime__c;
                                                plan.SalesPrice__c = oplan.SalesPrice__c;
                                                plan.SequenceNumber__c = oplan.SequenceNumber__c;
                                                ratePlans.add(plan);
                                            }
        if(ratePlans != null && !ratePlans.isEmpty()){
            insert ratePlans;
        }
    }
}