src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match any RSM.</errorMessage>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Product_Family__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaner</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Prelim</fullName>
            </value>
            <value>
                <fullName>1stArticle</fullName>
            </value>
            <value>
                <fullName>Pre-Prod</fullName>
            </value>
            <value>
                <fullName>Experiment</fullName>
            </value>
            <value>
                <fullName>Items.Obsolete</fullName>
            </value>
            <value>
                <fullName>Mechanical engineering</fullName>
            </value>
            <value>
                <fullName>Items.Pilot</fullName>
            </value>
            <value>
                <fullName>Items.Production</fullName>
            </value>
            <value>
                <fullName>Items.Pre-Production</fullName>
            </value>
            <value>
                <fullName>Items.Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-DWP50</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/OpportunityTeamMemberTriggerTest.cls
@isTest(seeAllData = false)
private class OpportunityTeamMemberTriggerTest {
    @isTest
    static void testOptTemMemTrigger(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Profile']; 
        UserRole uRole = [SELECT Id FROM UserRole where DeveloperName ='RSM_of_AMERICAS_EASTERN_WSS'];
        User rsm = new User(Alias = 'rsmU', Email='standarduser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='rsmstandarduser@testorg.com', UserRoleId = uRole.Id);
        system.runAs(rsm){
      Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
            Opportunity opt = new Opportunity();
            opt.Name = 'Test Opportunity';
            opt.CloseDate = Date.today().addDays(30);
            opt.StageName = 'Open - Discussion';
            opt.Project_Name__c = 'Test Project';
            opt.Type = 'Replacement';
            opt.RSM__c = rsm.Id;
            opt.Pricebook2Id = customPB.id;
            insert opt;
            Product2 prd = new Product2();
            prd.Name = '1277';
            prd.IsActive = true;
            prd.Marketing_P_N__c = '10WSCN08LFL';
            prd.Status__c = 'Loaner';
            prd.ProductCode = '1277';
            prd.Product_Family__c = 'WSS-DWP50';
            prd.BU_Code__c = '0040';
            prd.ExternalId__c = '10WSCN08LFL';
            insert prd;
         
            PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = customPB.id,
                Product2Id = prd.Id,
                UnitPrice = 100.00,
                IsActive = true
            );
            insert pbEntry;
            OpportunityLineItem optPr = new OpportunityLineItem();
            optPr.OpportunityId = opt.Id;
            optPr.product2Id = prd.Id;
            optPr.Quantity = 100;
            optPr.TotalPrice = 1000;
            insert optpr;
            OpportunityTeamMember optem = new OpportunityTeamMember();
            optem.OpportunityId = opt.Id;
            optem.UserId = userInfo.getUserId();
            optem.OpportunityAccessLevel = 'Read';
            test.startTest();
            insert optem;
            test.stopTest();  
        }
        
    }
}