src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <formula>IF( RecordType.DeveloperName =&apos;Extension_Item&apos;,Loaner_Line__r.Product__r.Marketing_P_N__c,Product__r.Marketing_P_N__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketing P/N</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>IF(RecordType.DeveloperName=&apos;Extension_Item&apos;,TEXT(Loaner_Line__r.Product__r.Product_Family__c) ,TEXT(Product__r.Product_Family__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <label>Lead Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Product2/fields/Marketing_Family__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Family__c</fullName>
    <label>Marketing Family</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;10 GIG</fullName>
            </value>
            <value>
                <fullName>100 GIG</fullName>
            </value>
            <value>
                <fullName>10 GIG</fullName>
            </value>
            <value>
                <fullName>16-32 GIG</fullName>
            </value>
            <value>
                <fullName>200 GIG</fullName>
            </value>
            <value>
                <fullName>25 GIG</fullName>
            </value>
            <value>
                <fullName>3D SENSORS</fullName>
            </value>
            <value>
                <fullName>400 GIG</fullName>
            </value>
            <value>
                <fullName>40 GIG</fullName>
            </value>
            <value>
                <fullName>800 GIG</fullName>
            </value>
            <value>
                <fullName>ACCESSORIES</fullName>
            </value>
            <value>
                <fullName>ACTIVES</fullName>
            </value>
            <value>
                <fullName>AMPLIFIER</fullName>
            </value>
            <value>
                <fullName>ANALOG</fullName>
            </value>
            <value>
                <fullName>ANALOG-ISR</fullName>
            </value>
            <value>
                <fullName>ANALOG-US</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>CDAUI-16</fullName>
            </value>
            <value>
                <fullName>CDAUI-8</fullName>
            </value>
            <value>
                <fullName>LW/SONET MODULE</fullName>
            </value>
            <value>
                <fullName>LWMODULES</fullName>
            </value>
            <value>
                <fullName>NETWORK TOOLS</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-CHIP</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-OTHER</fullName>
            </value>
            <value>
                <fullName>OPT COMPS-TRX</fullName>
            </value>
            <value>
                <fullName>PASSIVES</fullName>
            </value>
            <value>
                <fullName>ROADM</fullName>
            </value>
            <value>
                <fullName>SUB 10 GIG</fullName>
            </value>
            <value>
                <fullName>SWMODULES</fullName>
            </value>
            <value>
                <fullName>SW MODULES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/ProductHelper.cls
public class ProductHelper {
    public static void checkGenericPNs(List<Loaner_Line__c> newList, Map<Id,Loaner_Line__c> oldMap){
        for(Loaner_Line__c line : newList){
            system.debug('line.Marketing_P_N__c'+line.Marketing_P_N__c + '  '+oldMap.get(line.Id).Marketing_P_N__c);
            Boolean samePart = compareMarketigPNs(line.Marketing_P_N__c, oldMap.get(line.Id).Marketing_P_N__c);
            if(samePart != null && !samePart){
                line.addError('Product not match');
            }
        }
        //Marketing_P_N__c
    }
    public static Boolean compareMarketigPNs(String mp2, String mp1){
        if(mp1.length() == mp2.length()){
            if(mp1.endsWithIgnoreCase('xxxx')){
                if(mp1.subString(0, mp1.indexOfIgnoreCase('xxxx')).contains('xx')){
                    String str = '10TRAAU5SPLXXX';
                    system.debug('size '+str.length());
                    system.debug('index ' + str.indexOfIgnoreCase('xxx'));
                    system.debug('sub string '+str.subString(0,str.indexOfIgnoreCase('xxx')));
                    return compareMiddlestr(mp1.removeEndIgnoreCase('xxxx'), mp2);
                }else {
                    return compareSubString(mp1.subString(0, mp1.indexOfIgnoreCase('xxxx')),mp2);
                }
            } else if(mp1.endsWithIgnoreCase('xxx')){
                if(mp1.subString(0, mp1.indexOfIgnoreCase('xxx')).contains('xx')){
                    return compareMiddlestr(mp1.removeEndIgnoreCase('xxx'), mp2);
                } else {
                    return compareSubString(mp1.subString(0, mp1.indexOfIgnoreCase('xxx')),mp2);
                }
                
            } else if(mp1.endsWithIgnoreCase('xx')){
                if(mp1.subString(0, mp1.indexOfIgnoreCase('xx')).contains('xx')){
                    return compareMiddlestr(mp1.removeEndIgnoreCase('xx'), mp2.removeEndIgnoreCase('xx'));
                } else {
                    return compareSubString(mp1.subString(0, mp1.indexOfIgnoreCase('xx')),mp2);
                }
            } else if(mp1.contains('xx')){
                return compareMiddlestr(mp1, mp2);
            } else{
                system.debug('test');
                return null;
            }
        } else{
            system.debug('different part');
            return null;
        }
        
    }
    public static Boolean compareSubString(String str1, String str2){
        if(str1.equals(str2.substring(0, str1.length()))){
            system.debug('sdfs : '+str2.substring(0, str1.length()));
            system.debug('same generic part');
            return null;
        } else {
            system.debug('different part');
            return false;
        }
    }
    public static Boolean compareMiddlestr(String str1, String str2){
        system.debug('str1 '+str1);
        str1 = str1.removeEndIgnoreCase('xx');
        system.debug('str1 '+str1);
        system.debug('str1 '+str2);
        str2 = str2.substring(0, str1.length());
        system.debug('str1 '+str2);
        system.debug('index of xx '+str1.indexOf('xx'));
        system.debug('index of xx '+str1.substring(0, str1.indexOf('xx')) );
        system.debug('index of xx '+str1.substring(str1.indexOf('xx')+2,str1.length()) );
        if(str1.substring(0, str1.indexOf('xx')).equals(str2.substring(0, str1.indexOf('xx'))) && 
           str1.substring(str1.indexOf('xx')+2,str1.length()).equals(str2.substring(str1.indexOf('xx')+2,str1.length()))){
               system.debug('same generic part');
               return null;
           } else {
               system.debug('different part');
               return false;
           }
    }
    @auraEnabled
    public static productdetails getProducts(String productCode, String produtFamily, String marketingFamily){
        List<Product2> products = new List<Product2>();
        string prdStatus ='Active';
        system.debug('productCode '+productCode+ ' produtFamily '+produtFamily+' marketingFamily' +marketingFamily);
        String query = 'Select Id, Name,Lead_Time__c,Product_Group__c,Marketing_P_N__c,Product_Family__c,Marketing_Family__c from Product2 where ';
        if(String.isNotBlank(productCode)){
            query = query+ 'Product_Group__c =:productCode';
            if(String.isNotBlank(produtFamily)){
                query = query+ ' And Product_Family__c =:produtFamily';
            }
            if(String.isNotBlank(marketingFamily)){
                query = query+ ' And Marketing_Family__c =:marketingFamily';
            }
        } else if(String.isNotBlank(produtFamily)){
            query = query+ ' Product_Family__c =:produtFamily';
            if(String.isNotBlank(marketingFamily)){
                query = query+ ' And Marketing_Family__c =:marketingFamily';
            }
        } else if(String.isNotBlank(marketingFamily)){
            query = query+ ' Marketing_Family__c =:marketingFamily';
        }
        system.debug('query '+query);
        products = database.query(query);
        system.debug('products'+products);
        productdetails prdDet = new productdetails();
        prdDet.count = products.size();
        prdDet.productList = products;
        return prdDet;
    }
    @auraEnabled
    public static List<Product2> updateProductsData(String leadTime, String products){
        system.debug('products '+products);
        List<Product2> productlst = (List<Product2>)JSON.deserialize(products, List<product2>.class) ;
        if(String.isNotBlank(leadTime)){
            for(Product2 prd :productlst){
               // prd.Lead_Time__c = leadTime;
            }
        }
        system.debug('products'+products);
        if(productlst != null && !productlst.isEmpty()){
            update productlst;
        }
            return productlst;
    }
    public class productdetails{
        @auraEnabled
        public Integer count;
        @auraEnabled
        public List<Product2> productList;
        public productdetails(){
            
        }
    }
}