src/objects/BOM_Product_Part__c/BOM_Product_Part__c.object-meta.xml
<CustomObject>
    <label>Junction Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOM_Product_Part__c/fields/English_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Description__c</fullName>
    <label>English Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/BOM_Product_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Junction Components</relationshipLabel>
    <relationshipName>JunctionComponents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary (Shipping) Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Additional_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Additional_Specifications__c</fullName>
    <label>Additional Specifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Alternate_Description__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Description__c</fullName>
    <label>Alternate Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/II_VI_DE_Long_Description__c.field-meta.xml
<CustomField>
    <fullName>II_VI_DE_Long_Description__c</fullName>
    <label>II-VI DE Long Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <label>Lead Time</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Long_Description_English__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_English__c</fullName>
    <label>Long Description English</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Long_Description_French__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_French__c</fullName>
    <label>Long Description French</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <inlineHelpText>Use to track the customer&apos;s requested ship date.</inlineHelpText>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Rich_Text_Deutsch__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_Deutsch__c</fullName>
    <label>Rich Text - Deutsch</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Rich_Text_English__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_English__c</fullName>
    <label>Rich Text - English</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <description>Date the Part ix expected to be shipped.</description>
    <inlineHelpText>Date the Part ix expected to be shipped.</inlineHelpText>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityRatePlan__c/OpportunityRatePlan__c.object-meta.xml
<CustomObject>
    <label>Opportunity Rate Plan</label>
    <nameField>
        <displayFormat>ORL-{00000}</displayFormat>
        <label>Opportunity Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityRatePlan__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>Opportunity Line Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityRatePlan__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Order/fields/Primary_Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary (Shipping) Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/Ordered_BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Ordered BOM Parts</label>
    <nameField>
        <label>Ordered BOM Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered BOM Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ordered_BOM_Parts__c/fields/BOM_Product_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Product_Part__c</fullName>
    <label>BOM Product Part</label>
    <referenceTo>BOM_Product_Part__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/Deutch_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>Deutch_Rich_Text_Description__c</fullName>
    <label>Deutsch Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/English_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Rich_Text_Description__c</fullName>
    <label>English Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <label>Opportunity Product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/recordTypes/Quote_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Quote_Record_Type</fullName>
    <active>true</active>
    <label>Normal Quote</label>
</RecordType>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Additional_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Additional_Specifications__c</fullName>
    <label>Additional Specifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Alternate_Description__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Description__c</fullName>
    <label>Alternate Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/DescriptionShort__c.field-meta.xml
<CustomField>
    <fullName>DescriptionShort__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/II_VI_DE_Long_Description__c.field-meta.xml
<CustomField>
    <fullName>II_VI_DE_Long_Description__c</fullName>
    <label>II-VI DE Long Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Long_Description_English__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_English__c</fullName>
    <label>Long Description English</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Long_Description_French__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_French__c</fullName>
    <label>Long Description French</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/Rich_Text_Deutsch__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_Deutsch__c</fullName>
    <label>Rich Text - Deutsch</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/Quote_Item__c/fields/Rich_Text_English__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_English__c</fullName>
    <label>Rich Text - English</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/Quote_Item__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>SortOrder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/QuoteRatePlan__c/QuoteRatePlan__c.object-meta.xml
<CustomObject>
    <label>Quote Rate Plan</label>
    <nameField>
        <displayFormat>QRP-{00000}</displayFormat>
        <label>Quote Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteRatePlan__c/fields/LeadTime__c.field-meta.xml
<CustomField>
    <fullName>LeadTime__c</fullName>
    <label>Lead Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Rate Plans</relationshipLabel>
    <relationshipName>Quote_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/CreateQuoteController.cls
public with sharing class CreateQuoteController {
    public Opportunity opp;
    public CreateQuoteController(ApexPages.StandardController controller) {
        if(!test.isRunningTest()){
            controller.addFields(New List<String> {'Name', 'CurrencyIsoCode','Primary_Shipping_Contact__c'});    
        }
        opp = (Opportunity)controller.getRecord();
    }
    
    public pageReference createQuote(){
        Id qtRecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Quote_Record_Type').getRecordTypeId();
        Quote newQte;
        pageReference pgRef ;
        List<OpportunityLineItem> oppLines = [SELECT Id,name, OpportunityId , Product2Id, Description, Quantity, UnitPrice,CurrencyIsoCode,Description__c,
                                              PriceBookEntryId, Additional_Specifications__c, II_VI_DE_Long_Description__c, Long_Description_English__c,
                                              Long_Description_French__c, Alternate_Description__c, Request_Date__c, Ship_Date__c, Lead_Time__c, Rich_Text_Deutsch__c,
                                              Rich_Text_English__c,SortOrder 
                                              FROM OpportunityLineItem 
                                              WHERE OpportunityId = :opp.Id Order By CreatedDate];
        system.debug('oppLines + ' + oppLines.size());
        if(oppLines != null && !oppLines.isEmpty()){
            newQte = new Quote(OpportunityId = opp.Id, Name = opp.Name, CurrencyIsoCode = opp.CurrencyIsoCode, RecordtypeId = qtRecordTypeId,
                              ContactId = opp.Primary_Shipping_Contact__c, QuoteType__c = 'Customer');
            insert newQte;
            Map<Id, Quote_Item__c > oppQteLineMap = new Map<Id, Quote_Item__c >();
            //List<QuoteLineItem> qLines = new List<QuoteLineItem>();
            for(OpportunityLineItem oLine :oppLines){
                Quote_Item__c  qLine = new Quote_Item__c (Quote__c  = newQte.Id,
                                                       Product__c  = oLine.Product2Id,
                                                        Quantity__c  = oLine.Quantity,
                                                        DescriptionShort__c  = oLine.Description__c,
                                                        UnitPrice__c = oLine.UnitPrice, 
                                                        Target_Price__c = oLine.UnitPrice,  
                                                        Alternate_Description__c = oLine.Alternate_Description__c,
                                                        II_VI_DE_Long_Description__c = oLine.II_VI_DE_Long_Description__c,
                                                        Long_Description_English__c = oLine.Long_Description_English__c,
                                                        Long_Description_French__c = oLine.Long_Description_French__c,
                                                        Additional_Specifications__c = oLine.Additional_Specifications__c,
                                                        Request_Date__c = oLine.Request_Date__c, 
                                                        Ship_Date__c = oLine.Ship_Date__c,
                                                        Lead_Time__c = oLine.Lead_Time__c,
                                                        Rich_Text_English__c = oLine.Rich_Text_English__c,
                                                        Rich_Text_Deutsch__c = oLine.Rich_Text_Deutsch__c,
                                                        SortOrder__c = oLine.SortOrder,CurrencyIsoCode=newQte.CurrencyIsoCode);
                oppQteLineMap.put(oLine.Id, qLine);
                //qLines.add(qLine);
            }
            system.debug('opp@@' + oppQteLineMap.values().Size());
            insert oppQteLineMap.values();
            List<QuoteRatePlan__c> qRatePlans = new List<QuoteRatePlan__c>();
            for(OpportunityRatePlan__c oRate : [SELECT Id, OpportunityLineItem__c, SalesPrice__c, SequenceNumber__c, LeadTime__c
                                                FROM OpportunityRatePlan__c 
                                                WHERE OpportunityLineItem__c IN :oppQteLineMap.keySet()]){
                                                    QuoteRatePlan__c plan = new QuoteRatePlan__c();
                                                    plan.QuoteLineItem__c = oppQteLineMap.get(oRate.OpportunityLineItem__c).Id;
                                                    plan.LeadTime__c = oRate.LeadTime__c;
                                                    plan.SequenceNumber__c = oRate.SequenceNumber__c;
                                                    plan.SalesPrice__c = oRate.SalesPrice__c;
                                                    qRatePlans.add(plan);
                                                }
            if(qRatePlans != null && !qRatePlans.isEmpty()){
                insert qRatePlans;
            }
            List<Ordered_BOM_Parts__c> boms = new List<Ordered_BOM_Parts__c>();
            for(Ordered_BOM_Parts__c bom : [SELECT Id,Name, BOM_Product_Part__c, Deutch_Description__c, Deutch_Rich_Text_Description__c,
                                            English_Description__c,English_Rich_Text_Description__c, OpportunityProduct__c, Position__c,
                                            Quantity__c,QuoteLineItem__c,Sequence__c
                                            FROM Ordered_BOM_Parts__c 
                                            WHERE OpportunityProduct__c IN : oppQteLineMap.keySet()]){
                                                Ordered_BOM_Parts__c newBom = bom.clone();
                                                newBom.OpportunityProduct__c = '';
                                                newBom.QuoteLineItem__c = oppQteLineMap.get(bom.OpportunityProduct__c).Id;
                                                boms.add(newBom);
                                            }
            if(boms != null && !boms.isEmpty()){
                insert boms;
            }
            pgRef = new pageReference('/'+newQte.Id);
        }else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'There are no products associated with the Opportunity.'));
            return null;
        }
        
        return pgRef;
    }
    public pageReference redirectToOpp(){
        pageReference pgRef = new pageReference('/'+opp.Id);
        return pgRef;
    }
}