src/objects/BOM_Product_Part__c/BOM_Product_Part__c.object-meta.xml
<CustomObject>
    <label>Junction Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOM_Product_Part__c/fields/English_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Description__c</fullName>
    <label>English Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/BOM_Product_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Junction Components</relationshipLabel>
    <relationshipName>JunctionComponents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <description>Pulls from Account.</description>
    <inlineHelpText>This is automatically set to pull the payment terms from the Account.</inlineHelpText>
    <label>Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/Ordered_BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Ordered BOM Parts</label>
    <nameField>
        <label>Ordered BOM Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered BOM Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ordered_BOM_Parts__c/fields/BOM_Product_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Product_Part__c</fullName>
    <label>BOM Product Part</label>
    <referenceTo>BOM_Product_Part__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/Deutch_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>Deutch_Rich_Text_Description__c</fullName>
    <label>Deutsch Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/English_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Rich_Text_Description__c</fullName>
    <label>English Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <label>Opportunity Product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <inlineHelpText>Copies value from Account, or type new value to override.</inlineHelpText>
    <label>Delivery Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/FCA__c.field-meta.xml
<CustomField>
    <fullName>FCA__c</fullName>
    <label>FCA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saxonburg, PA, USA</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Suzhou, CN</fullName>
            </value>
            <value>
                <fullName>Door-to-door</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Internal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Notes__c</fullName>
    <inlineHelpText>Used to record internal notes related to the Quote.</inlineHelpText>
    <label>Internal Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Quote/fields/International_Quote_Clause__c.field-meta.xml
<CustomField>
    <fullName>International_Quote_Clause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>International Quote Clause</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Quote/fields/Link_to_Quote_on_Server__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Quote_on_Server__c</fullName>
    <label>Link to Military Quote</label>
    <type>Url</type>
</CustomField>

src/objects/Quote/fields/Manufacture_Location__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Location__c</fullName>
    <label>Manufacture Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Singapore</fullName>
                <default>true</default>
                <label>Singapore</label>
            </value>
            <value>
                <fullName>Saxonburg, PA, USA</fullName>
            </value>
            <value>
                <fullName>Singapore / Saxonburg, PA, USA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Migrated__c.field-meta.xml
<CustomField>
    <fullName>Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migrated</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Quote/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Account manager notes; to be used on quote template</description>
    <inlineHelpText>Will show on quote PDF</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/fields/TqCurrency__c.field-meta.xml
<CustomField>
    <fullName>TqCurrency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote/fields/Validity__c.field-meta.xml
<CustomField>
    <fullName>Validity__c</fullName>
    <label>Validity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Quote/recordTypes/Quote_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Quote_Record_Type</fullName>
    <active>true</active>
    <label>Normal Quote</label>
</RecordType>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Additional_Specifications__c.field-meta.xml
<CustomField>
    <fullName>Additional_Specifications__c</fullName>
    <label>Additional Specifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Alternate_Description__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Description__c</fullName>
    <label>Alternate Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/DescriptionShort__c.field-meta.xml
<CustomField>
    <fullName>DescriptionShort__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/II_VI_DE_Long_Description__c.field-meta.xml
<CustomField>
    <fullName>II_VI_DE_Long_Description__c</fullName>
    <label>II-VI DE Long Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Long_Description_English__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_English__c</fullName>
    <label>Long Description English</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Long_Description_French__c.field-meta.xml
<CustomField>
    <fullName>Long_Description_French__c</fullName>
    <label>Long Description French</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/Rich_Text_Deutsch__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_Deutsch__c</fullName>
    <label>Rich Text - Deutsch</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/Quote_Item__c/fields/Rich_Text_English__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text_English__c</fullName>
    <label>Rich Text - English</label>
    <length>25000</length>
    <type>Html</type>
</CustomField>

src/objects/Quote_Item__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>SortOrder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/QuoteRatePlan__c/QuoteRatePlan__c.object-meta.xml
<CustomObject>
    <label>Quote Rate Plan</label>
    <nameField>
        <displayFormat>QRP-{00000}</displayFormat>
        <label>Quote Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteRatePlan__c/fields/LeadTime__c.field-meta.xml
<CustomField>
    <fullName>LeadTime__c</fullName>
    <label>Lead Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Rate Plans</relationshipLabel>
    <relationshipName>Quote_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/CloneQuoteExtension.cls
public with sharing class CloneQuoteExtension {
    public Quote oldQuote;    
    public CloneQuoteExtension(ApexPages.StandardController controller) {
        if(!test.isRunningTest()){
            controller.addFields(New List<String> {'Name', 'CurrencyIsoCode','OpportunityId','Description','ExpirationDate','QuoteType__c',
                'RecordType','Status','TqCurrency__c','Delivery_Terms__c','FCA__c','Internal_Notes__c','International_Quote_Clause__c',
                'Link_to_Quote_on_Server__c','Manufacture_Location__c','Migrated__c','Notes__c','Terms__c','Validity__c','Pricebook2Id'});    
        }
        oldQuote = (Quote)controller.getRecord();
    }
    public pageReference cloneQuote(){
        Id qtRecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Quote_Record_Type').getRecordTypeId();
        Quote newQte;
        pageReference pgRef ;
        List<Quote_Item__c > qteLines = [SELECT Id, Quote__c, Product__c,  Quantity__c, Target_Price__c,CurrencyIsoCode,DescriptionShort__c ,Rich_Text_Deutsch__c,
                                          Additional_Specifications__c, II_VI_DE_Long_Description__c, Long_Description_English__c,Rich_Text_English__c,
                                         Long_Description_French__c,SortOrder__c ,UnitPrice__c , Alternate_Description__c, Request_Date__c, Ship_Date__c, Lead_Time__c
                                         FROM Quote_Item__c  
                                         WHERE Quote__c = :oldQuote.Id];
        if(qteLines != null && !qteLines.isEmpty()){
            newQte = oldQuote.clone();
            newQte.RecordTypeId = qtRecordTypeId;
            newQte.QuoteType__c = 'Customer';
            insert newQte;
            Map<Id, Quote_Item__c> qteLineMap = new Map<Id, Quote_Item__c>();
            for(Quote_Item__c oLine :qteLines){
                Quote_Item__c qLine = new Quote_Item__c(Quote__c = newQte.Id,
                                                        Product__c = oLine.Product__c,
                                                        Quantity__c = oLine.Quantity__c,
                                                        DescriptionShort__c  = oLine.DescriptionShort__c,
                                                        Target_Price__c = oLine.Target_Price__c,
                                                        Alternate_Description__c = oLine.Alternate_Description__c,
                                                        II_VI_DE_Long_Description__c = oLine.II_VI_DE_Long_Description__c,
                                                        Long_Description_English__c = oLine.Long_Description_English__c,
                                                        Long_Description_French__c = oLine.Long_Description_French__c,
                                                        Additional_Specifications__c = oLine.Additional_Specifications__c,
                                                        Request_Date__c = oLine.Request_Date__c, 
                                                        Ship_Date__c = oLine.Ship_Date__c,
                                                        Lead_Time__c = oLine.Lead_Time__c,
                                                        SortOrder__c  = oLine.SortOrder__c,
                                                        UnitPrice__c  = oLine.UnitPrice__c,
                                                        Rich_Text_Deutsch__c = oLine.Rich_Text_Deutsch__c,
                                                        Rich_Text_English__c = oLine.Rich_Text_English__c);
                qteLineMap.put(oLine.Id, qLine);
            }
            insert qteLineMap.values();
            List<QuoteRatePlan__c> qRatePlans = new List<QuoteRatePlan__c>();
            for(QuoteRatePlan__c qRate : [SELECT Id, QuoteLineItem__c, SalesPrice__c, SequenceNumber__c, LeadTime__c
                                          FROM QuoteRatePlan__c 
                                          WHERE QuoteLineItem__c IN :qteLineMap.keySet()]){
                                              QuoteRatePlan__c plan = qRate.clone();
                                              plan.QuoteLineItem__c = qteLineMap.get(qRate.QuoteLineItem__c).Id;
                                              qRatePlans.add(plan);
                                          }
            if(qRatePlans != null && !qRatePlans.isEmpty()){
                insert qRatePlans;
            }
            List<Ordered_BOM_Parts__c> boms = new List<Ordered_BOM_Parts__c>();
            for(Ordered_BOM_Parts__c bom : [SELECT Id,Name, BOM_Product_Part__c, Deutch_Description__c, Deutch_Rich_Text_Description__c,
                                            English_Description__c,English_Rich_Text_Description__c, OpportunityProduct__c, Position__c,
                                            Quantity__c,QuoteLineItem__c,Sequence__c
                                            FROM Ordered_BOM_Parts__c 
                                            WHERE QuoteLineItem__c IN : qteLineMap.keySet()]){
                                                Ordered_BOM_Parts__c newBom = bom.clone();
                                                newBom.OpportunityProduct__c = '';
                                                newBom.QuoteLineItem__c = qteLineMap.get(bom.QuoteLineItem__c).Id;
                                                boms.add(newBom);
                                            }
            if(boms != null && !boms.isEmpty()){
                insert boms;
            }
            pgRef = new pageReference('/'+newQte.Id);
        }else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'There are no products associated with the Opportunity.'));
            return null;
        }
        return pgRef;
    }
    public pageReference redirectToOpp(){
        pageReference pgRef = new pageReference('/'+oldQuote.Id);
        return pgRef;
    }
}