src/objects/Failure_Modes__c/Failure_Modes__c.object-meta.xml
<CustomObject>
    <label>Failure Modes</label>
    <nameField>
        <displayFormat>Failure Mode - {00000000}</displayFormat>
        <label>Failure Modes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failure Modes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Failure_Modes__c/fields/PDC_Level_1__c.field-meta.xml
<CustomField>
    <fullName>PDC_Level_1__c</fullName>
    <label>PDC Level 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Site__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>10GCDRLDPA</fullName>
            </value>
            <value>
                <fullName>BH1</fullName>
            </value>
            <value>
                <fullName>BH Laser</fullName>
            </value>
            <value>
                <fullName>Breakout</fullName>
            </value>
            <value>
                <fullName>Bulkhead</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Capacitor</fullName>
            </value>
            <value>
                <fullName>Ceramic capacitor</fullName>
            </value>
            <value>
                <fullName>CLEI Label</fullName>
            </value>
            <value>
                <fullName>COF</fullName>
            </value>
            <value>
                <fullName>COF Window</fullName>
            </value>
            <value>
                <fullName>Common</fullName>
            </value>
            <value>
                <fullName>DFB25</fullName>
            </value>
            <value>
                <fullName>DFB Laser</fullName>
            </value>
            <value>
                <fullName>EEPROM</fullName>
            </value>
            <value>
                <fullName>EMI Collar</fullName>
            </value>
            <value>
                <fullName>FCC</fullName>
            </value>
            <value>
                <fullName>Firmware</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Gold Finger</fullName>
            </value>
            <value>
                <fullName>Header pin / Riser board</fullName>
            </value>
            <value>
                <fullName>Heat sink, Lid, Ring Frame</fullName>
            </value>
            <value>
                <fullName>Hotbar</fullName>
            </value>
            <value>
                <fullName>I32X1B</fullName>
                <label>I32X</label>
            </value>
            <value>
                <fullName>ICDR3A</fullName>
                <label>ICDR</label>
            </value>
            <value>
                <fullName>Inductor</fullName>
            </value>
            <value>
                <fullName>Interface board</fullName>
            </value>
            <value>
                <fullName>Isolator</fullName>
            </value>
            <value>
                <fullName>Laser Driver</fullName>
            </value>
            <value>
                <fullName>Leadframe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Failure_Modes__c/fields/PDC_Level_2__c.field-meta.xml
<CustomField>
    <fullName>PDC_Level_2__c</fullName>
    <label>PDC Level 2</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PDC_Level_1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accuracy</fullName>
            </value>
            <value>
                <fullName>ACF</fullName>
            </value>
            <value>
                <fullName>alignment guide broken</fullName>
            </value>
            <value>
                <fullName>Alignment shift</fullName>
            </value>
            <value>
                <fullName>assembly issue</fullName>
            </value>
            <value>
                <fullName>ATE bug</fullName>
            </value>
            <value>
                <fullName>AWG IL failure</fullName>
            </value>
            <value>
                <fullName>bent pin</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>Breakout fibre damage</fullName>
            </value>
            <value>
                <fullName>Broken/Damage Fiber</fullName>
            </value>
            <value>
                <fullName>Broken/Damage OE Fiber</fullName>
            </value>
            <value>
                <fullName>broken attenuator</fullName>
            </value>
            <value>
                <fullName>broken fiber</fullName>
            </value>
            <value>
                <fullName>broken flex (trace)</fullName>
            </value>
            <value>
                <fullName>broken pigtail</fullName>
            </value>
            <value>
                <fullName>broken ROSA sleeve</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>cable cut off</fullName>
            </value>
            <value>
                <fullName>Calibration</fullName>
            </value>
            <value>
                <fullName>Capacitor</fullName>
            </value>
            <value>
                <fullName>capacitor crack</fullName>
            </value>
            <value>
                <fullName>capacitor short</fullName>
            </value>
            <value>
                <fullName>CDR EOS/ESD damage</fullName>
            </value>
            <value>
                <fullName>CDR hard failure</fullName>
            </value>
            <value>
                <fullName>CDR setting issue</fullName>
            </value>
            <value>
                <fullName>CDR switch port sensitivity</fullName>
            </value>
            <value>
                <fullName>CDR weak VCO failure</fullName>
            </value>
            <value>
                <fullName>chip failure</fullName>
            </value>
            <value>
                <fullName>Cold Solder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/GteDependentPicklistTest.cls
@isTest
public class GteDependentPicklistTest {
    
    @isTest
    static void getDependentFields()
    {
        String sObjectName = 'Failure_Modes__c';
        Schema.SObjectType t = Schema.getGlobalDescribe().get(sObjectName); // obtain sObject description from the schema
        SObject s = t.newSObject();
        system.debug('sObj===='+s);
        GteDependentPicklist.getDependentMap(s,'PDC_Level_1__c','PDC_Level_2__c');
    }
}