src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Fixed_Firm_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Firm_Quote_Amount__c</fullName>
    <description>Fill out the quote amount for approvals</description>
    <label>Highest Firm/Fixed Quote USD Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <formula>IF( PriceListSelected__c &lt;&gt;&apos;&apos;, PriceListSelected__c ,
	IF(Site__r.Price_List__c &lt;&gt; &apos;&apos;, Site__r.Price_List__c,
		IF(Customer__r.Price_List__c &lt;&gt; &apos;&apos;,Customer__r.Price_List__c ,
			IF( Account__r.Price_List__c &lt;&gt; &apos;&apos;,Account__r.Price_List__c ,
				IF( Sales_Channel__r.Sales_Channel_Code__c = &apos;VAR SYNNEX_US&apos;  , 
					IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot;, &apos;FNSR VAR REP PRICE LIST&apos;,
						IF(CreatedBy.Profile.Name = &quot;Finisar Partner Community User (Disti Users)&quot;, &apos;FNSR VAR DISTI PRICE LIST&apos;, &apos;FNSR VAR RSM PRICE LIST&apos;) 
					),
					IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot;, &apos;FNSR REP PRICE LIST&apos;,
					IF(CreatedBy.Profile.Name = &quot;Finisar Partner Community User (Disti Users)&quot;, &apos;FNSR DISTRIBUTOR PRICE LIST&apos;, &apos;FNSR RSM PRICE LIST&apos;)
				)
			)
		)
	)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price List</label>
    <type>Text</type>
</CustomField>

src/classes/LookupController.cls
public without sharing class LookupController {
    
    @AuraEnabled
    public static List<sObject> searchRecord(String objectAPIName, String fieldAPIName, 
                                             List<String> moreFields, String searchText,
                                             Integer recordLimit)
    {
        List<sObject> objectList =  new List<sObject>();
        moreFields ='Party_Number__c,Type,Price_List__c'.split(',');
        searchText='\'%' + String.escapeSingleQuotes(searchText.trim()) + '%\'';
        
        String soqlQuery = 'SELECT Id, Name';
        if(!moreFields.isEmpty()){
            soqlQuery = soqlQuery + ',' + String.join(moreFields, ',') ;
        }
        soqlQuery = soqlQuery + ' FROM ' + objectAPIName + ' WHERE ' +
            + fieldAPIName +' LIKE '+ searchText + 'AND Status__c =\'Active\' AND recordType.developername=\'Party_Account\''+' LIMIT '+ recordLimit;
        objectList = Database.query(soqlQuery);
        System.debug('objectList'+objectList);
        return objectList;
    }
    
    @AuraEnabled
    public static Quote saveQuote(String aAccountId){
        System.debug('qRec--> '+aAccountId);
        Quote newqRec = new Quote();
        newqRec.Account__c = aAccountId;        
        newqRec.name= '-Quote';
        newqRec.Fixed_Firm_Quote_Amount__c = 0;
        try{
            system.debug('newqRec=='+newqRec);
            upsert newqRec;
            system.debug('newqRec1=='+newqRec);
            return newqRec;  
        }catch(Exception e) {
            System.debug('Error'+e.getMessage());
             return null;
        }
        
       
    }
}