src/objects/Quote/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select a Customer Name that already exists in our database. If the customer does not exist.  Please email Betty.Dea@Finisar.com so she can set it up.  This should be the end customer, not a Contract Manufacturer, VAR, or SI. We have other fields for these</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Account #)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>All Active non site accounts</description>
    <inlineHelpText>All Active non site accounts</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Account.ParentId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Customer)</relationshipLabel>
    <relationshipName>CustomerQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Channel</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Sales Channel)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Approval_From__c.field-meta.xml
<CustomField>
    <fullName>Approval_From__c</fullName>
    <formula>IF( CreatedBy.Profile.Name = &quot;Finisar Partner Community User&quot; ,IF( Target_Price__c &lt; RSM_Min__c ,&apos;BothApprovers&apos;, IF( Target_Price__c &lt; REP_Min__c ,&apos;RSM&apos;,IF(ISNULL(RSM_Min__c)||ISNULL(REP_Min__c),&apos;BothApprovers&apos;,&apos;None&apos;))), 
IF(ISNULL(RSM_Min__c),IF(OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), 
IF( Target_Price__c &lt; RSM_Min__c,IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)),&apos;PLM&apos;,&apos;BothApprovers&apos;), IF( OR(CONTAINS( CreatedBy.UserRole.Name,&apos;RSM&apos;),CONTAINS( CreatedBy.UserRole.Name,&apos;SOM&apos;)) ,&apos;None&apos;,&apos;RSM&apos;))))</formula>
    <label>Approval From</label>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/Disti_Resale_Price__c.field-meta.xml
<CustomField>
    <fullName>Disti_Resale_Price__c</fullName>
    <label>Disti Resale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <formula>Target_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/PLM_Approver__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PLM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>PLM Approver</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>MVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Std_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Std_List_Price__c</fullName>
    <label>Std List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/classes/QuoteApprovalController.cls
public without sharing class QuoteApprovalController {
@AuraEnabled
    public static Quote QuoteQuery(ID quoteId) {
        	//string LoginUser = UserInfo.getUserId();
        	Set<id> loginAndDelegatedUserSet = RecordApprovalDao.getUserFromDelegatedApproverID(UserInfo.getUserId());
         if(quoteId != null) {
                              return [SELECT Id, Name, QuoteNumber,Sales_Channel__r.Name,Account__r.Name,Customer__r.Name,ExpirationDate, CreatedDate,
                                              (SELECT Id, Name,Std_List_Price__c,Line_Total__c, Quantity__c,Product__r.Name ,
                                               Target_Price__c,Disti_Resale_Price__c,RSM_Approver__r.Name,PLM_Approver__r.Name,Approval_From__c
                                               FROM Quote_Items__r 
                                               where ((PLM_Approver__c In :loginAndDelegatedUserSet AND 
                                                      	(Approval_From__c =:'PLM' OR Approval_From__c = :'BothApprovers')
                                                      )
                                              			OR (RSM_Approver__c In :loginAndDelegatedUserSet AND 
                                                            (Approval_From__c =:'RSM' OR Approval_From__c = :'BothApprovers')
                                                            )
                                                     )
                                              )
                                     FROM Quote where ID = :quoteId];
            				 }
        else{
            return null;
        	}
    }

    @AuraEnabled
    public static List<string> ApproveRecords(List<String> appRecordId, String ObjId) {
        String ObjName = 'Quote';
        string LoginUser = UserInfo.getUserId();
        Set < id > LineItemsApprove = New Set < id > ();
        for(String AppId: appRecordId){
            LineItemsApprove.add(AppId);  
             }
        RecordsLineItemApprovalHelper.ApproveRecords(LineItemsApprove, ObjName, ObjId,LoginUser);
        return appRecordId;
    }
     @AuraEnabled
    public static List<string> RejectRecords(List<String> rejRecordId) {
        String ObjName = 'Quote';
        string LoginUser = UserInfo.getUserId();
        Set < id > LineItemsReject = New Set < id > ();
        for(String RejId: rejRecordId){
            LineItemsReject.add(RejId);  
             }
        RecordsLineItemApprovalHelper.RejectRecords(LineItemsReject, ObjName,LoginUser);
        return rejRecordId;
    }
    
     @AuraEnabled
    public static string ReasignRecords(List<String> reassignRecordId,String ReasignEmail, Id ObjId) {
        User currentuser=new User();
        string Result = 'Success';
        String ReassignRole = 'No Role';
        Set < id > LineItemsReAssign = New Set < id > ();
        for(String ReAssignId: reassignRecordId){
            LineItemsReAssign.add(ReAssignId);  
             }
        system.debug(ReasignEmail);system.debug(ObjId);system.debug(Result);
     	currentuser=[Select Id,Name,Email,UserRole.name from User where Id=:userinfo.getuserId()];
        User[] ReassignUserRole = [Select UserRole.name from User where Email=:ReasignEmail];
        if (ReassignUserRole.size() > 0){
           ReassignRole = ReassignUserRole[0].UserRole.name; 
        }
		
        if((currentuser.UserRole.name == ReassignRole) || (currentuser.UserRole.name == 'Sales Admin')){
           RecordsLineItemApprovalHelper.reAssignUser(ObjId, currentuser,ReasignEmail,LineItemsReAssign);
        }
        if((currentuser.UserRole.name != ReassignRole) && (currentuser.UserRole.name != 'Sales Admin'))
        {Result = 'Please enter valid email!' ;}
        system.debug(currentuser.UserRole.name);system.debug(ReassignRole);system.debug(Result);
    	
        return Result;
    }
}