src/objects/Quote/fields/Contribution_Profit__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Profit__c</fullName>
    <label>Contribution Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote/fields/Gross_Profit__c.field-meta.xml
<CustomField>
    <fullName>Gross_Profit__c</fullName>
    <label>Gross Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Contribution_Profit__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Profit__c</fullName>
    <formula>( ( Target_Price__c  -  Variable_Cost__c  )  *  Quantity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contribution Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Gross_Profit__c.field-meta.xml
<CustomField>
    <fullName>Gross_Profit__c</fullName>
    <formula>( (  Target_Price__c  -  Standard_Cost__c  ) *  Quantity__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/QuoteItemPLMDashboardTriggerHelper.cls
public class QuoteItemPLMDashboardTriggerHelper {
    
    public static void UpdateQuotePLMDashboardDetails(Map<Id,Quote> oldQuote,Map<Id,Quote> newQuote)
    {
        List<Quote> Quote = New List<Quote>();
        List<Quote_Item__c> QuoteItemGroup = New List<Quote_Item__c>();
        List<Quote> AllRelatedQuoteItems = New List<Quote>();
        List<String> QuoteIds = New List<String>();
        FOR(Id quoteId:newQuote.keySet()){
            IF(oldQuote.get(quoteId).Status!=newQuote.get(quoteId).Status && newQuote.get(quoteId).Status=='Approval Pending'){
                QuoteIds.add(quoteId);
            }
        }
        IF(!QuoteIds.isEmpty()){
            System.debug('Inside Method in pending Approval');
            List<Quote> DistinctQuoteList = new List<Quote>();
            For(Quote quoteObj:[Select Id,Contribution_Profit__c,Gross_Profit__c,(Select id,Quote__c,Contribution_Profit__c,Gross_Profit__c from Quote_Items__r) 
                                From Quote where id in :QuoteIds])
            {
                IF(quoteObj.Quote_Items__r.size()>0){
                    Decimal contribution_profit =0.0;
                    Decimal Gross_Profit = 0.0;
                    For(Quote_Item__c quoteItemObj:quoteObj.Quote_Items__r){
                        IF(quoteItemObj.Contribution_Profit__c!=Null){
                            contribution_profit =contribution_profit + quoteItemObj.Contribution_Profit__c;
                        }
                        IF(quoteItemObj.Gross_Profit__c!=Null){
                            Gross_Profit =Gross_Profit + quoteItemObj.Gross_Profit__c;
                        }
                    }
                    System.debug('contribution_profit'+contribution_profit);
                    System.debug('Gross_Profit'+Gross_Profit);
                    newQuote.get(quoteObj.Id).Contribution_Profit__c = contribution_profit;
                    newQuote.get(quoteObj.Id).Gross_Profit__c = Gross_Profit;
                }
                
            }
        }
    }
    
}