src/objects/BOM_Parts__c/BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Master Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BOM_Parts__c/fields/Deutch_Description__c.field-meta.xml
<CustomField>
    <fullName>Deutch_Description__c</fullName>
    <label>Deutsch Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/BOM_Parts__c/fields/Deutsch_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>Deutsch_Rich_Text_Description__c</fullName>
    <label>Deutsch Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/BOM_Product_Part__c/BOM_Product_Part__c.object-meta.xml
<CustomObject>
    <label>Junction Components</label>
    <nameField>
        <label>Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOM_Product_Part__c/fields/BOM_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Part__c</fullName>
    <label>Master Components</label>
    <referenceTo>BOM_Parts__c</referenceTo>
    <relationshipLabel>Junction Components</relationshipLabel>
    <relationshipName>BOM_Product_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/BOM_Product_Part__c/fields/English_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Description__c</fullName>
    <label>English Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/BOM_Product_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Junction Components</relationshipLabel>
    <relationshipName>JunctionComponents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/Ordered_BOM_Parts__c.object-meta.xml
<CustomObject>
    <label>Ordered BOM Parts</label>
    <nameField>
        <label>Ordered BOM Parts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordered BOM Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ordered_BOM_Parts__c/fields/BOM_Product_Part__c.field-meta.xml
<CustomField>
    <fullName>BOM_Product_Part__c</fullName>
    <label>BOM Product Part</label>
    <referenceTo>BOM_Product_Part__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/Deutch_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>Deutch_Rich_Text_Description__c</fullName>
    <label>Deutsch Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/English_Rich_Text_Description__c.field-meta.xml
<CustomField>
    <fullName>English_Rich_Text_Description__c</fullName>
    <label>English Rich Text Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <label>Opportunity Product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Ordered_BOM_Parts__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ordered BOM Parts</relationshipLabel>
    <relationshipName>Ordered_BOM_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/CreateOrderedPartsForQuote.cls
public with sharing class CreateOrderedPartsForQuote {
    public Quote_Item__c quoteProduct{get;set;}
    public list<ClassBOMProdWrapper> listOfClassBOMProdWrapper{get;set;}    
    public boolean isRender{get;set;}
    public list<Ordered_BOM_Parts__c> listOfBOMParts{get;set;}
    
    public CreateOrderedPartsForQuote(ApexPages.StandardController controller) {
        listOfBOMParts = new list<Ordered_BOM_Parts__c>();
        
        quoteProduct= (Quote_Item__c)controller.getRecord();
        quoteProduct= [SELECT Id, Name , Product__c, Quote__c , Quote__r.Name  
                       FROM Quote_Item__c  
                       WHERE id =:quoteProduct.id ];
        listOfClassBOMProdWrapper = new list<ClassBOMProdWrapper>();
        setOfBOMProdIds = new set<id>();        
        isRender = true;
        
        
        list<BOM_Product_Part__c> listfProdParts = [SELECT Name,Quantity__c,BOM_Part__c,English_Description__c,BOM_Part__r.Name,BOM_Part__r.Quantity__c, 
                                                    BOM_Part__r.Deutch_Description__c,BOM_Part__r.English_Description__c,BOM_Part__r.English_Rich_Text_Description__c,
                                                    BOM_Part__r.Deutsch_Rich_Text_Description__c,Sequence__c                                                                                                    
                                                    from BOM_Product_Part__c 
                                                    WHERE Product__c =: quoteProduct.Product__c
                                                    order by Sequence__c
                                                    ASC NULLS LAST];
        
        if(listfProdParts.size() == 0){
            Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.Info,'No parts are available.');
            Apexpages.addMessage(errorMessage);
            isRender = false;
        }else{
            list<Ordered_BOM_Parts__c> listOfOrderPars = [SELECT Name, Quantity__c, BOM_Product_Part__c, 
                                                          Deutch_Description__c, Deutch_Rich_Text_Description__c,
                                                          English_Description__c, English_Rich_Text_Description__c,
                                                          OpportunityProduct__c, OrderProduct__c, Position__c, QuoteLineItem__c    
                                                          from Ordered_BOM_Parts__c where QuoteLineItem__c  =: quoteProduct.id 
                                                          order by Sequence__c];
            
            listOfBOMParts.addall(listOfOrderPars);
            for(Ordered_BOM_Parts__c ord : listOfOrderPars){
                setOfBOMProdIds.add(ord.BOM_Product_Part__c);
            }
            
            ClassBOMProdWrapper classBOMProdWrapperLocal;
            for(BOM_Product_Part__c bom :listfProdParts){  
                classBOMProdWrapperLocal = new ClassBOMProdWrapper();
                if(setOfBOMProdIds.contains(bom.id)){
                    classBOMProdWrapperLocal.isAdded = 'Added';
                }
                classBOMProdWrapperLocal.bomProd = bom;
                classBOMProdWrapperLocal.isSelected = false;
                listOfClassBOMProdWrapper.add(classBOMProdWrapperLocal);
            }
        }
    }
    
    public pagereference cancel(){    
        return new pagereference('/'+quoteProduct.Quote__c);
    }
    
    
    public set<id> setOfBOMProdIds;
    public pagereference addParts(){
        for(ClassBOMProdWrapper classBOMProdWrapperLocal : listOfClassBOMProdWrapper){
            if(classBOMProdWrapperLocal.isSelected){        
                classBOMProdWrapperLocal.isAdded = 'Added';
                classBOMProdWrapperLocal.isSelected = false;
                Ordered_BOM_Parts__c ordPart = new Ordered_BOM_Parts__c();
                ordPart.QuoteLineItem__c = quoteProduct.id;
                ordPart.BOM_Product_Part__c = classBOMProdWrapperLocal.bomProd.id;
                ordPart.Name = classBOMProdWrapperLocal.bomProd.BOM_Part__r.Name;
                ordPart.Quantity__c = classBOMProdWrapperLocal.bomProd.BOM_Part__r.Quantity__c;
                ordPart.Deutch_Description__c = classBOMProdWrapperLocal.bomProd.BOM_Part__r.Deutch_Description__c;
                ordPart.English_Description__c = classBOMProdWrapperLocal.bomProd.BOM_Part__r.English_Description__c;
                ordPart.English_Rich_Text_Description__c = classBOMProdWrapperLocal.bomProd.BOM_Part__r.English_Rich_Text_Description__c;
                ordPart.Deutch_Rich_Text_Description__c = classBOMProdWrapperLocal.bomProd.BOM_Part__r.Deutsch_Rich_Text_Description__c;
                ordPart.Sequence__c = classBOMProdWrapperLocal.bomProd.Sequence__c;
                listOfBOMParts.add(ordPart);
            }
        }          
        return null;
    }
    
    public pagereference sortListByName(){
        listOfBOMParts.sort();
        return null;
    }    
    
    public pagereference sortListByPostion(){
        
        listOfBomPartWrapper = new list<BomPartWrapper>();
        BomPartWrapper BomPartWrapperLocal;
        for(Ordered_BOM_Parts__c ord : listOfBOMParts){
            setOfBOMProdIds.add(ord.BOM_Product_Part__c);
            
            BomPartWrapperLocal = new BomPartWrapper(ord);
            BomPartWrapperLocal.orderedPart = ord;
            listOfBomPartWrapper.add(BomPartWrapperLocal);
        }
        listOfBomPartWrapper.sort();
        listOfBOMParts.clear();
        
        
        for(BomPartWrapper wrap :  listOfBomPartWrapper){
            listOfBOMParts.add(wrap.orderedPart);
        }
        return null;
    }
    
    // to remove the added product
    public pagereference removeBOMOrderedProduct(){
        string bomProdRemoveLocal = ApexPages.currentPage().getParameters().get('BOMProductId');        
        for(ClassBOMProdWrapper classBOMProdWrapperLocal : listOfClassBOMProdWrapper){
            if(classBOMProdWrapperLocal.bomProd.id == bomProdRemoveLocal){
                classBOMProdWrapperLocal.isAdded = 'Available';
                break;
            }
        }
        
        
        Ordered_BOM_Parts__c ordToDelete = new Ordered_BOM_Parts__c();
        
        for(integer i=0; i <listOfBOMParts.size();i++ ){
            Ordered_BOM_Parts__c ordPart = listOfBOMParts[i];
            if(ordPart.BOM_Product_Part__c  == bomProdRemoveLocal){
                listOfBOMParts.remove(i);
                setOfBOMProdIds.remove(bomProdRemoveLocal);
                if(ordPart.id != null)
                    ordToDelete.id = ordPart.id;
                break;    
            }  
        }            
        
        if(ordToDelete.id != null){
            delete ordToDelete;
        }
        return null;
    }
    
    
    public pagereference save(){
        savepoint sp;
        try{
            sp = DataBase.setSavepoint();
            
            upsert listOfBOMParts;
            
            return new pagereference('/'+quoteProduct.id);
            
        }catch(exception ex){
            DataBase.RollBack(sp); 
            Apexpages.Message errorMessage = new Apexpages.Message(ApexPages.Severity.ERROR,'Exception occured==>>' + ex.getTypeName()+':'+ex.getMessage() + ':LINE ' + ex.getLineNumber());
            Apexpages.addMessage(errorMessage);
            return null;
        }
        //  return null;
    }
    
    
    public class ClassBOMProdWrapper{
        public BOM_Product_Part__c bomProd{get;set;}
        public String isAdded{get;set;}
        
        public boolean isSelected{get;set;}
        public ClassBOMProdWrapper(){
            isSelected = false; 
            bomProd =  new BOM_Product_Part__c();
            isAdded = 'Available';
        }
    }
    
    public list<BomPartWrapper> listOfBomPartWrapper{get;set;} 
    public class BomPartWrapper implements Comparable {
        public Ordered_BOM_Parts__c orderedPart;
        public BomPartWrapper(Ordered_BOM_Parts__c orderedPartRecord) {
            orderedPart = orderedPartRecord;
        }
        public Integer compareTo(Object compareTo) {
            BomPartWrapper compareToProdPosition = (BomPartWrapper)compareTo;
            
            // The return value of 0 indicates that both elements are equal.
            Integer returnValue = 0;
            if (orderedPart.Position__c > compareToProdPosition.orderedPart.Position__c) {
                // Set return value to a positive value.
                returnValue = 1;
            } else if (orderedPart.Position__c < compareToProdPosition.orderedPart.Position__c) {
                // Set return value to a negative value.
                returnValue = -1;
            }
            
            return returnValue;       
        }
    }
}