src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity #</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Select &quot;New Opportunity&quot; only if this loaner links to an Opportunity in Salesforce.Then there should only be 1 P/N on this loaner which matches to the Opportunity P/N.Select any other choice if this is a stand-alone loaner which can include multiple P/Ns.</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Opportunity</fullName>
            </value>
            <value>
                <fullName>New Opportunity - &lt; 100K SAM</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity -  Demand already forecasted</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity - Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/LoanerIntegration_Wsdl.cls
public class LoanerIntegration_Wsdl {
    
    public Class LoanerParameter 
    {
        @InvocableVariable(label='loanerId' required='true')
        public String loanerId;
        @InvocableVariable(label='LoanerName' required='true')
        public String LoanerName;
    }
    
    @InvocableMethod(label='LoanerService' description='Call Webservice From in This Class')
    public static  List<String> invokeService(List<LoanerParameter> LoanerParameters)
    {	
        List<String> errormessages = new List<String>();
        System.debug('Inside invokeMethod');
        LoanerIntegration_Wsdl loanerintegrationwsdl = new LoanerIntegration_Wsdl();
        for( LoanerParameter  LP : LoanerParameters)
        { System.debug('  '+LP);
         errormessages.add(sendRequesttoInformatica(LP.loanerId));}
        System.debug(errormessages);
        return errormessages;
        
    }
    public static String  sendRequesttoInformatica(String loanerid)
    {	
        try{
            servicesInformaticaComRtPrcCaiLoan LoanerRequestInf = new servicesInformaticaComRtPrcCaiLoan();
            servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_main_Service Loanerservicesend = new  servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_main_Service();
            
            servicesInformaticaComRtPrcCaiLoan.Prc_cai_loaner_mainResponse_element response =Loanerservicesend.Prc_cai_loaner_main(loanerid);
            
            String validation = validateRecords(loanerid);
            if(!String.isEmpty(validation) && response.error_message != null )
            {
                
                return  validation  + response.error_message ;
            }
             if(String.isEmpty(validation) && response.error_message != null )
            {
                
                return  response.error_message ;
            }
            if(!String.isEmpty(validation))
            {
                 return  validation;
            }
              
            return 'Validation Successfull';
            
        }
        catch(Exception e)
        {
            System.debug(' Exception Occurred '+e.getMessage() +' Line Number '+e.getLineNumber());
            return e.getMessage();
        }
    }
    
    public static String validateRecords(String recordId){
        sobject loanerObj = RecordApprovalDao.getHeaderRecord(recordId);
        for(String fieldName : CommonConstants.LoanerRequiredFields){
            If(loanerObj.get(fieldName)==Null){
                   String LoanerOpportunityType =(String) loanerObj.get('Opportunity_Type__c');
                  if(fieldName.equalsIgnoreCase('Opportunity__c') && LoanerOpportunityType.equalsIgnoreCase('New Opportunity'))
                  {
                      String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                       return ' Required Field '+fieldlabel+ ' Must be Filled As Opportunity Type is ' +loanerObj.get('Opportunity_Type__c');
                  }
                 else if(!fieldName.equalsIgnoreCase('Opportunity__c'))
                 { 
                	String fieldlabel = Schema.getGlobalDescribe().get('Loaner__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                     return ' Required Field '+fieldlabel+ ' Must be Filled';
                 }
            }
        }
        
        if(loanerObj.getSObjects('Loaner_Lines__r')!=Null){
            System.debug(loanerObj);
            for(sobject sobj:loanerObj.getSObjects('Loaner_Lines__r')){
                For(String fieldName :CommonConstants.LoanerLineRequiredFields){
                    If(sobj.get(fieldName)==NULL){
                        String fieldlabel = Schema.getGlobalDescribe().get('Loaner_Line__c').getDescribe().fields.getMap().get(fieldName).getDescribe().getLabel();
                        
                        return ' Required Field '+fieldlabel+ ' Must be Filled For Line Item '+loanerObj.get('Name');
                    } 
                }
            }
        }
        return '';
    }
}