src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>Order_Line__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SO_Line_Migration__c.field-meta.xml
<CustomField>
    <fullName>SO_Line_Migration__c</fullName>
    <label>Legacy SO Line#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SO_Number_Migration__c.field-meta.xml
<CustomField>
    <fullName>SO_Number_Migration__c</fullName>
    <label>Legacy SO Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Order/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Order_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner Line</label>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Order Lines (Loaner Line)</relationshipLabel>
    <relationshipName>Order_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/classes/LoanerOrderlinkbatch.cls
global class LoanerOrderlinkbatch implements 
    Database.Batchable<sObject>, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, SO_Line_Migration__c, SO_Number_Migration__c,Loaner__c '+'  FROM Loaner_Line__c where SO_Line_Migration__c!=null and SO_Number_Migration__c!=null'//and Loaner__r.owner.FirstName = \'Prasoon\'
        );
    }
    global void execute(Database.BatchableContext bc, List<Loaner_Line__c> scope){
        Map<String,String> soNumberLoanerIdMap = new Map<String,String>();
        Map<String,String> soLineSoNumberandLoanerLineMap = new Map<String,String>();
        Map<String,String> loanerIdandOrderIdMap = new Map<String,String>();
        Map<String,String> loanerLineIdandOrderLineIdMap = new Map<String,String>();
        for(Loaner_Line__c loanLine : scope){
            soNumberLoanerIdMap.put(loanLine.SO_Number_Migration__c,loanLine.Loaner__c);
            soLineSoNumberandLoanerLineMap.put(loanLine.SO_Line_Migration__c+';'+loanLine.SO_Number_Migration__c,loanLine.Id);
            loanerIdandOrderIdMap.put(loanLine.Loaner__c,null);
            loanerLineIdandOrderLineIdMap.put(loanLine.Id,null);
        }
        List<Order> orderList = new List<Order>();
        List<Order> orderListUpdate = new List<Order>();
        List<Order_Line__c> orderLineUpdateList = new List<Order_Line__c>();
        orderList = [SELECT Id,PoNumber,(Select Id,Line__c from RMA_Lines__r) from Order where PoNumber IN : soNumberLoanerIdMap.keySet() /*and owner.FirstName = 'Prasoon'*/];
        for(Order ord : orderList){
            if(soNumberLoanerIdMap.containsKey(ord.PoNumber)){
                ord.Loaner__c = soNumberLoanerIdMap.get(ord.PoNumber);
                loanerIdandOrderIdMap.put(soNumberLoanerIdMap.get(ord.PoNumber),ord.Id);
                orderListUpdate.add(ord);
            }
            if(ord.RMA_Lines__r!=null && ord.RMA_Lines__r.size()>0){
                for(Order_Line__c ordLine : ord.RMA_Lines__r){
                    if(soLineSoNumberandLoanerLineMap.containsKey(ordLine.Line__c+';'+ord.PoNumber)){
                        ordLine.Loaner_Line__c = soLineSoNumberandLoanerLineMap.get(ordLine.Line__c+';'+ord.PoNumber);
                        orderLineUpdateList.add(ordLine);
                        if(soLineSoNumberandLoanerLineMap.containsKey(ordLine.Line__c+';'+ord.PoNumber)){
                            loanerLineIdandOrderLineIdMap.put(soLineSoNumberandLoanerLineMap.get(ordLine.Line__c+';'+ord.PoNumber),ordLine.Id);
                        }
                    }
                }
            }
        }
        System.Debug('<<<<<<<soLineSoNumberandLoanerLineMap>>>>>>>>'+soLineSoNumberandLoanerLineMap);
        List<Loaner__c> lnlistToUpdate = new List<Loaner__c>();
        List<Loaner_Line__c> lnLinelistToUpdate = new List<Loaner_Line__c>();
        for(String loanerID : loanerIdandOrderIdMap.keySet()){
            Loaner__c ln = new Loaner__c(Id=loanerID, Order__c = loanerIdandOrderIdMap.get(loanerID));
            lnlistToUpdate.add(ln);
        }
        for(String loanerLineID : loanerLineIdandOrderLineIdMap.keySet()){
            Loaner_Line__c lln = new Loaner_Line__c(Id=loanerLineID,Order_Line__c= loanerLineIdandOrderLineIdMap.get(loanerLineID));
            lnLinelistToUpdate.add(lln);
        }
        
        if(orderListUpdate!=null && orderListUpdate.size()>0){
            update orderListUpdate;
        }   
        if(orderLineUpdateList!=null && orderLineUpdateList.size()>0){
            update orderLineUpdateList;
        }
        
        if(lnlistToUpdate!=null && lnlistToUpdate.size()>0){
            update lnlistToUpdate;
        }   
        if(lnLinelistToUpdate!=null && lnLinelistToUpdate.size()>0){
            update lnLinelistToUpdate;
        }
    }    
    global void finish(Database.BatchableContext bc){
        
    }    
}