src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Date_Reminder_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Date_Reminder_DateTime__c</fullName>
    <label>Date Reminder DateTime</label>
    <type>DateTime</type>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Ship_From_Finisar__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Ship_From_Finisar__c</fullName>
    <inlineHelpText>Keep Default=&quot;Factory Stock&quot; for any loaner shipping from factory through Sales Order.  Use &quot;Transfer From Existing Loaner&quot; for loaner transfer only.  Do not change to other choices unless you have discussed with Betty.</inlineHelpText>
    <label>Loaner Ship From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ship_From</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/RSM_PLM_Approval__c.field-meta.xml
<CustomField>
    <fullName>RSM_PLM_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Status_Approval__c.field-meta.xml
<CustomField>
    <fullName>Status_Approval__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loaner_Line_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/SVP_Id_Created_By__c.field-meta.xml
<CustomField>
    <fullName>SVP_Id_Created_By__c</fullName>
    <formula>IF( ISBLANK(RSM_PLM_Approval__r.SVP__c) ,  RSM_PLM_Finisar__c ,  RSM_PLM_Finisar__r.SVP__c )</formula>
    <label>SVP Id Created By</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/Verified_with_Betty_Dea__c.field-meta.xml
<CustomField>
    <fullName>Verified_with_Betty_Dea__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Review with Betty first before selecting [Loaner Ship From] = &quot;Returned Loaner Stock&quot; or &quot;Other&quot;.</inlineHelpText>
    <label>Verified with Betty Dea</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Loaner__c/fields/VP_PLD_Finisar__c.field-meta.xml
<CustomField>
    <fullName>VP_PLD_Finisar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Populated after submitted for approval</inlineHelpText>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners_Vp</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Extend_Date__c.field-meta.xml
<CustomField>
    <fullName>Extend_Date__c</fullName>
    <inlineHelpText>Loaner Item Extended By</inlineHelpText>
    <label>Extend To Date</label>
    <type>Date</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected, Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <description>Lookup field to User to Point SVP for user role VP</description>
    <label>SVP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <description>Lookup field to User to point to VP for User role RSM</description>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>VP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/globalValueSets/Loaner_Line_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Sales Order</fullName>
    </customValue>
    <masterLabel>Loaner Line Approval Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Ship_From.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Factory Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Returned Loaner Stock</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer From Existing Loaner</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Ship From</masterLabel>
</GlobalValueSet>

src/classes/RecordApprovalController.cls
public without Sharing class RecordApprovalController {
    
    @AuraEnabled
    public static String sendLineItemEmails(Id recordId) {
        Try {
            String Integration_Error_Msg;
            String validation_Msg;
            sobject headerObject = RecordApprovalDao.getHeaderRecord(recordId);
            system.debug('Label.Enable_and_Disable_validations_on_Loaner_Submit_For_Approval '+Label.Enable_and_Disable_validations_on_Loaner_Submit_For_Approval);
            system.debug('recordId.getSObjectType().getDescribe().getName() '+recordId.getSObjectType().getDescribe().getName());
            // Validations Specific To Loaner Class
            If(recordId.getSObjectType().getDescribe().getName().equalsIgnoreCase('Loaner__c')) {
                If(CommonConstants.LoanerRequestRecordtypeId == headerObject.get('recordTypeId') && headerObject.get('Status_Approval__c') == 'Pending Sales Order') {
                    return CommonConstants.pendingSalesorder;
                }
                
                IF(CommonConstants.LoanerRequestRecordtypeId == headerObject.get('recordTypeId')){
                    List<User> UserObj = RecordApprovalDao.getUserVPSVPDetails(New Set<ID>{UserInfo.getUserId()});
                    Boolean Userrole = False;
                    For(String role:Label.Loaner_Aproval_Roles_Allowed.split(',')){
                        If(UserObj.get(0).userrole.name.containsIgnoreCase(role)||UserObj.get(0).isportalenabled){
                            Userrole = True;
                        }
                    }
                    
                    IF(!Userrole){
                        return CommonConstants.invaliduserRole;
                    }}
                If(Label.Enable_and_Disable_validations_on_Loaner_Submit_For_Approval.equalsignorecase('True') && CommonConstants.LoanerRequestRecordtypeId == headerObject.get('recordTypeId')) {
                    String responce = LoanerIntegration_Wsdl.sendRequesttoInformatica(recordId);
                    If (!String.isEmpty(responce) && !responce.equalsIgnoreCase('Validation Successfull')) {
                        If(responce.containsIgnoreCase('Required Field')){
                            return responce;
                        }
                        Else{
                            Integration_Error_Msg = responce;
                        }
                    }
                }
                If(CommonConstants.LoanerExtensiontypeId == headerObject.get('recordTypeId') && headerObject.get('VP_PLD_Finisar__c') != Null) {
                    List<User> userList = RecordApprovalDao.getUserVPSVPDetails(New Set<ID>{(Id)headerObject.get('VP_PLD_Finisar__c')});
                    IF(userList.size()==0){
                        return CommonConstants.vpInactivereturnMessage;
                    }}
                
                If(CommonConstants.LoanerExtensiontypeId == headerObject.get('recordTypeId') && headerObject.get('VP_PLD_Finisar__c') == Null) {
                    return CommonConstants.vpEmptyreturnMessage;
                }
                If(headerObject.get('Loaner_Ship_From_Finisar__c') != Null && (headerObject.get('Loaner_Ship_From_Finisar__c') == 'Returned Loaner Stock' || headerObject.get('Loaner_Ship_From_Finisar__c') == 'Other')) {
                    IF(CommonConstants.LoanerExtensiontypeId != headerObject.get('recordTypeId') && 
                       headerObject.get('Verified_with_Betty_Dea__c') == False) {
                           return CommonConstants.VerifyWithBettyDeareturnMessage;
                       }
                }
                
                If(CommonConstants.LoanerRequestRecordtypeId != headerObject.get('recordTypeId')  && CommonConstants.LoanerExtensiontypeId != headerObject.get('recordTypeId')) {
                    return CommonConstants.recordTypeError;
                }
                
            }
            If(Label.Enable_and_Disable_validations_on_Loaner_Submit_For_Approval.equalsignorecase('True') && 
               recordId.getSObjectType().getDescribe().getName().equalsIgnoreCase('Quote')) {
                   String errMessage = checkDuplicateLineswithSameProd(recordId);
                   if(String.isBlank(errMessage)){
                       String validateRule = QuoteLineItemController.validateRulesRecords(recordId);
                       String responce = QuoteLineItemController.sendRequesttoInformatica(recordId);
                       If (!String.isEmpty(responce) && !responce.equalsIgnoreCase('Validation Successfull')
                           &&!String.isEmpty(validateRule) && !validateRule.equals('')) {
                               return responce+'\r\n'+validateRule;
                           }
                       If(!String.isEmpty(responce) && !responce.equalsIgnoreCase('Validation Successfull')) {
                           return responce;
                       }
                       If (!String.isEmpty(validateRule) && !validateRule.equals('')) {
                           return validateRule;
                       } 
                   } else {
                       return errMessage;
                   }
               }
            
            // Updating SVP,VP,RSM fields at child level for Loaner    
            String valResult = updateChildRecords(recordId, headerObject);
            
            // Common Approval Process for Quote,Loaner,Loaner Extension    
            Set < id > ApprovalEmailToIdSet = New Set < id > ();
            IF(valResult.equalsIgnoreCase('Success')) {
                Map < id, sobject > sobjectMap = New Map < id, Sobject > (RecordApprovalDao.getLineItemsRecords(recordId));
                System.debug('sobjectMap in controller' + sobjectMap);
                if (sobjectMap.values().size() > 0) {
                    List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
                    for (sobject recordObj: sobjectMap.values()) {
                        IF(Approval.isLocked((ID) recordObj.get('id'))) {
                            Approval.unlock((ID) recordObj.get('id'));
                        }
                        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                        req1.setComments('Submitting request for approval.');
                        req1.setObjectId((ID) recordObj.get('id'));
                        requests.add(req1);
                        // Approval.ProcessResult result = Approval.process(req1);
                    }
                    Approval.process(requests);
                    List < ProcessInstanceWorkitem > pItemList = RecordApprovalDao.getProcessItemWorkList(sobjectMap.keyset());
                    if (pItemList.size() > 0) {
                        for (ProcessInstanceWorkitem piwObj: pItemList) {
                            ApprovalEmailToIdSet.add(piwObj.actorid);
                        }
                        System.debug('ApprovalEmailToIdSet' + ApprovalEmailToIdSet);
                        Set < id > delegatedApproverSet = RecordApprovalDao.getDelegatedApprovedID(ApprovalEmailToIdSet);
                        ApprovalEmailToIdSet.addall(delegatedApproverSet);
                        RecordsLineItemApprovalHelper.sendEmail(ApprovalEmailToIdSet, recordId);
                        IF(recordId.getSObjectType().getDescribe().getName().equalsIgnoreCase('Loaner__c')){
                            updateDateReminderDateonLoaner(recordId);
                        }
                        If(CommonConstants.LoanerRequestRecordtypeId == headerObject.get('recordTypeId')){
                            unlockLoanerLineRecords(recordId);
                        }
                    }
                    valResult = 'processSucess';
                    System.debug('Final Integration_Error_Msg'+Integration_Error_Msg);
                    IF(!String.isEmpty(Integration_Error_Msg)){
                        return 'Line Items are sent for Approval with Error :'+Integration_Error_Msg;
                    }
                    return valResult;
                } else {
                    valResult = 'NoLineItem';
                    return valResult;
                }
            }
            else {
                return valResult;
            }
        }
        Catch(Exception e) {
            System.debug('Exception Email' + e.getMessage());
            return e.getMessage();
        }
    }
    
    public static String updateChildRecords(Id recordId, sobject sobj) {
        String validation = 'Success';
        if (sobj.getSObjectType().getDescribe().getName().equalsIgnoreCase('Loaner__c')) {
            list < sobject > sobjectsToUpdate = New List < sobject > ();
            if (sobj.getSObjects('Loaner_Lines__r') != NULL) {
                for (sobject sobjLineItems: sobj.getSObjects('Loaner_Lines__r')) {
                    if(CommonConstants.LoanerExtensionRecordtypeId == sobjLineItems.get('recordTypeId') &&
                       sobjLineItems.get('Extend_Date__c') == null){
                           validation = 'Extend to Date should be provided for '+sobjLineItems.get('Name');
                           return validation;
                       }
                    IF(sobj.get('RSM_PLM_Approval__c') != Null) {
                        sobjLineItems.put('RSM__c', sobj.get('RSM_PLM_Approval__c'));
                    }
                    IF(sobj.get('VP_PLD_Finisar__c') != NULL) {
                        sobjLineItems.put('VP__c', sobj.get('VP_PLD_Finisar__c'));
                    }
                    IF(sobj.get('SVP_Id_Created_By__c') != NULL) {
                        sobjLineItems.put('SVP__c', sobj.get('SVP__c'));
                    }
                    sobjectsToUpdate.add(sobjLineItems);
                }
                
                if (sobjectsToUpdate.size() > 0) {
                    update sobjectsToUpdate;
                }
            }
        }
        return validation;
    }
    
    @future
    public static void updateDateReminderDateonLoaner(Id RecordId){
        sobject headerObject = RecordApprovalDao.getHeaderRecord(recordId);
        System.debug('headerObject'+headerObject);
        headerObject.put('Date_Reminder_DateTime__c', System.now());
        System.debug('headerObject'+headerObject);
        update headerObject;
    }
    
    @future
    public static void unlockLoanerLineRecords(Id RecordId){
        Map < id, sobject > sobjectMap = New Map < id, Sobject > (RecordApprovalDao.getLineItemsRecords(recordId));
        If(sobjectMap.size()>0){
            for(id Id:sobjectMap.keyset()){
                IF(Approval.isLocked(Id)) {
                    Approval.unlock(Id);
                }
            }
        }
    }
    /**
Method Name : checkDuplicateLineswithSameProd
Input Parameters : String recordId- quote Id
return Parameter : String - error message
Lastupdated: Surendar - 15-10-2019
**/
    public static String checkDuplicateLineswithSameProd(String recordId){
        String errorMessage ='';
        Map<String, List<String>> prodLineMap = new Map<String, List<String>>();
        for(Quote_Item__c qtline : [SELECT Id, Name, Product__c, Product__r.Name
                                    FROM Quote_Item__c
                                    WHERE Quote__c = :recordId]){
                                        if(prodLineMap.containsKey(qtline.Product__r.name)){
                                            prodLineMap.get(qtline.Product__r.Name).add(qtline.Name);
                                        } else {
                                            prodLineMap.put(qtline.Product__r.Name, new List<String>{qtline.Name});
                                        }
                                    }
        for(String prdId :prodLineMap.keySet()){
            if(prodLineMap.get(prdId).size() >1){
                if(string.isBlank(errorMessage)){
                    errorMessage = 'Record Can not be submitted for Approval<br/>Duplicate lines found with Item '+prdId + ' for Lines :';
                } else {
                    errorMessage = errorMessage+'<br/> Duplicate lines found with Item '+prdId + ' for Lines : ';
                }
                for(String qlne : prodLineMap.get(prdId)){
                    errorMessage = errorMessage+qlne+',';
                }
                errorMessage = errorMessage.substringBeforeLast(',')+';';
            }
        }
        return errorMessage;
    }
}