src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Company_Name_End_Cust__c.field-meta.xml
<CustomField>
    <fullName>Company_Name_End_Cust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Email Betty Dea with end customer name and website if it cannot be found in drop down list.</inlineHelpText>
    <label>Company Name - End Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Company End Customer should be an Active Top Level Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Top Level Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/ECO_Number__c.field-meta.xml
<CustomField>
    <fullName>ECO_Number__c</fullName>
    <inlineHelpText>Enter valid ECO Number or put &quot;TBD&quot; if ECO Number not available yet.</inlineHelpText>
    <label>ECO Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Category__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Category__c</fullName>
    <inlineHelpText>This field links to Order Type on the Loaner SO.  It cannot be changed if selected incorrectly.  Check with Inside Sales/RSM first and make sure your selection is correct before submitting loaner for approval.</inlineHelpText>
    <label>Loaner Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qual Loaner TLC</fullName>
            </value>
            <value>
                <fullName>Standard loaner</fullName>
            </value>
            <value>
                <fullName>First Article loaner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Duration_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Duration_In_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>SVP approval needed if over 180 days or for &quot;No Return&quot; sample request.</inlineHelpText>
    <label>Loaner Duration In Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner__c/fields/Loaner_Total__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Total__c</fullName>
    <label>Loaner Total</label>
    <summarizedField>Loaner_Line__c.Loaner_Total__c</summarizedField>
    <summaryForeignKey>Loaner_Line__c.Loaner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Loaner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity #</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Select &quot;New Opportunity&quot; only if this loaner links to an Opportunity in Salesforce.Then there should only be 1 P/N on this loaner which matches to the Opportunity P/N.Select any other choice if this is a stand-alone loaner which can include multiple P/Ns.</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Opportunity</fullName>
            </value>
            <value>
                <fullName>New Opportunity - &lt; 100K SAM</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity -  Demand already forecasted</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity - Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/Status_Approval__c.field-meta.xml
<CustomField>
    <fullName>Status_Approval__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loaner_Line_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Berlin_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Est_Annual_Qty__c.field-meta.xml
<CustomField>
    <fullName>Est_Annual_Qty__c</fullName>
    <label>Est Annual Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <isActive>false</isActive>
                <label>Not Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <formula>SAM__c * SOM__c</formula>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Price_100_999_column_price__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Price_100_999_column_price__c</fullName>
    <inlineHelpText>Fill out if system does not auto-populate.</inlineHelpText>
    <label>Loaner Price (100-999 column price)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Qty__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Qty__c</fullName>
    <label>Loaner Qty</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Total__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Total__c</fullName>
    <formula>Loaner_Qty__c * Loaner_Price_100_999_column_price__c</formula>
    <label>Loaner Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <formula>IF( RecordType.DeveloperName =&apos;Extension_Item&apos;,Loaner_Line__r.Product__r.Marketing_P_N__c,Product__r.Marketing_P_N__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marketing P/N</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected, Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Production_Price_ASP__c.field-meta.xml
<CustomField>
    <fullName>Production_Price_ASP__c</fullName>
    <label>Production Price (ASP)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SAM__c.field-meta.xml
<CustomField>
    <fullName>SAM__c</fullName>
    <formula>Production_Price_ASP__c * Est_Annual_Qty__c</formula>
    <label>SAM($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SOM__c.field-meta.xml
<CustomField>
    <fullName>SOM__c</fullName>
    <inlineHelpText>Share of Market (%)</inlineHelpText>
    <label>SOM(%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/globalValueSets/Loaner_Line_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Sales Order</fullName>
    </customValue>
    <masterLabel>Loaner Line Approval Status</masterLabel>
</GlobalValueSet>

src/classes/LoanerApprovalController.cls
public without sharing class LoanerApprovalController {
@AuraEnabled
    public static Loaner__c LoanerQuery(ID loanerId) {
        	string LoginUser = UserInfo.getUserId();
         if(loanerId != null) {
                              return [SELECT Id, Name, Request__c,Status_Approval__c,ECO_Number__c,Loaner_Category__c,Opportunity__r.Name,Opportunity_Type__c,Loaner_Duration_In_Days__c,Company_Name_End_Cust__r.Name, CreatedDate,
                                              (SELECT Id, Name,Product__r.Name,Marketing_P_N__c,Loaner_Qty__c,
                                               Loaner_Price_100_999_column_price__c,Production_Price_ASP__c,Est_Annual_Qty__c,
                                               	SOM__c,SAM__c,Line_Total__c,Loaner_Total__c,Line_Status__c
                                               FROM Loaner_Lines__r
                                              )
                                     FROM Loaner__c where ID = :loanerId];
            				 }
        else{
            return null;
        	}
    }

    @AuraEnabled
    public static List<string> ApproveRecords(List<String> appRecordId, String ObjId) {
        String ObjName = 'Loaner__c';
        string LoginUser = UserInfo.getUserId();
        Set < id > LineItemsApprove = New Set < id > ();
        for(String AppId: appRecordId){
            LineItemsApprove.add(AppId);  
             }
        RecordsLineItemApprovalHelper.ApproveRecords(LineItemsApprove, ObjName, ObjId,LoginUser);
        return appRecordId;
    }
     @AuraEnabled
    public static List<string> RejectRecords(List<String> rejRecordId) {
        String ObjName = 'Loaner__c';
        string LoginUser = UserInfo.getUserId();
        Set < id > LineItemsReject = New Set < id > ();
        for(String RejId: rejRecordId){
            LineItemsReject.add(RejId);  
             }
        RecordsLineItemApprovalHelper.RejectRecords(LineItemsReject, ObjName,LoginUser);
        return rejRecordId;
    }
    
     @AuraEnabled
    public static string ReasignRecords(List<String> reassignRecordId,String ReasignEmail, Id ObjId) {
        User currentuser=new User();
        string Result = 'Success';
        String ReassignRole = 'No Role';
        Set < id > LineItemsReAssign = New Set < id > ();
        for(String ReAssignId: reassignRecordId){
            LineItemsReAssign.add(ReAssignId);  
             }
        system.debug(ReasignEmail);system.debug(ObjId);system.debug(Result);
     	currentuser=[Select Id,Name,Email,UserRole.name from User where Id=:userinfo.getuserId()];
        User[] ReassignUserRole = [Select UserRole.name from User where Email=:ReasignEmail];
        if (ReassignUserRole.size() > 0){
           ReassignRole = ReassignUserRole[0].UserRole.name; 
        }
		System.debug('currentuser'+currentuser);
        System.debug('ReassignRole'+ReassignRole);
        Boolean Reassignment = False;
        if(CommonConstants.mapOfRolesReassignment.get('Loaner__c').get(currentuser.UserRole.name).contains(ReassignRole)){
            Reassignment = True;
           RecordsLineItemApprovalHelper.reAssignUser(ObjId, currentuser,ReasignEmail,LineItemsReAssign);
        }
        if(!Reassignment)
        {Result = 'Please enter valid email!' ;}
        system.debug(currentuser.UserRole.name);system.debug(ReassignRole);system.debug(Result);
    	
        return Result;
    }
}