src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/BUCode__c.field-meta.xml
<CustomField>
    <fullName>BUCode__c</fullName>
    <label>BU Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/DistributorFirmGroupName__c.field-meta.xml
<CustomField>
    <fullName>DistributorFirmGroupName__c</fullName>
    <formula>Firm_Name_Distributor__r.Legacy_Id__c</formula>
    <label>DistributorFirmGroupName</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/Inside_Sales_Finisar__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Finisar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales-Finisar</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND (2 OR (3 AND 4))) OR ( NOT (1) AND 2))</booleanFilter>
        <filterItems>
            <field>$Source.Loaner_Ship_From_Finisar__c</field>
            <operation>notEqual</operation>
            <value>Factory Stock</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>contains</operation>
            <value>Inside_Sales_FAE</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>equals</operation>
            <value>Betty</value>
        </filterItems>
        <filterItems>
            <field>User.LastName</field>
            <operation>equals</operation>
            <value>Dea</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LoanersInsideSales</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/InsideSalesActiveCheck__c.field-meta.xml
<CustomField>
    <fullName>InsideSalesActiveCheck__c</fullName>
    <formula>Inside_Sales_Finisar__r.IsActive</formula>
    <label>InsideSalesActiveCheck</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Loaner__c/fields/RSM_PLM_Finisar__c.field-meta.xml
<CustomField>
    <fullName>RSM_PLM_Finisar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RSM Finisar</description>
    <label>RSM Finisar</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/RSMEmail__c.field-meta.xml
<CustomField>
    <fullName>RSMEmail__c</fullName>
    <formula>RSM_PLM_Approval__r.FirstName +&apos; &apos;+RSM_PLM_Approval__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSM Email</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/RSMFinisarActiveCheck__c.field-meta.xml
<CustomField>
    <fullName>RSMFinisarActiveCheck__c</fullName>
    <formula>RSM_PLM_Finisar__r.IsActive</formula>
    <label>RSMFinisarActiveCheck</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Loaner__c/fields/SalesRepFirmGroup__c.field-meta.xml
<CustomField>
    <fullName>SalesRepFirmGroup__c</fullName>
    <formula>Firm_Name_Sales_rep__r.Legacy_Id__c</formula>
    <label>SalesRepFirmGroup</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/VP_PLD_Finisar__c.field-meta.xml
<CustomField>
    <fullName>VP_PLD_Finisar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Populated after submitted for approval</inlineHelpText>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaners_Vp</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected, Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>IF(RecordType.DeveloperName=&apos;Extension_Item&apos;,TEXT(Loaner_Line__r.Product__r.Product_Family__c) ,TEXT(Product__r.Product_Family__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

src/objects/Loaner_Line__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner_Line__c/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loaner_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <description>Lookup field to User to Point SVP for user role VP</description>
    <label>SVP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <description>Lookup field to User to point to VP for User role RSM</description>
    <label>VP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>VP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>TSS Admin</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <relationshipName>VP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/VPSVP_Mapping__mdt/VPSVP_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>VPSVP Mapping Meta data for Loaner approval Process</description>
    <label>VPSVP Mapping</label>
    <pluralLabel>VPSVP Mappings</pluralLabel>
</CustomObject>

src/objects/VPSVP_Mapping__mdt/fields/RSMName__c.field-meta.xml
<CustomField>
    <fullName>RSMName__c</fullName>
    <label>RSM Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/VPSVP_Mapping__mdt/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <label>SVP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/VPSVP_Mapping__mdt/fields/VP__c.field-meta.xml
<CustomField>
    <fullName>VP__c</fullName>
    <label>VP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OCM</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OIG</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/LoanerShareTriggerHelper.cls
public class LoanerShareTriggerHelper {
    
    public static void accessToSalesOrDistributor(Map<id,Loaner__c> LoanerMap){
        System.debug('accessToInsideSales');
        sYSTEM.debug('LoanerMap'+LoanerMap);
        Set<String> salesAndDistributorgroup = New Set<String>();
        Map<String,Id> mapGroupNameAndId = New Map<String,Id>();
        for(Loaner__c LoanerObj:LoanerMap.values()){
            System.debug('LoanerObj'+LoanerObj);
            If(LoanerObj.SalesRepFirmGroup__c!=Null){
                salesAndDistributorgroup.add(LoanerObj.SalesRepFirmGroup__c);
            }
            IF(LoanerObj.DistributorFirmGroupName__c!=Null){
                salesAndDistributorgroup.add(LoanerObj.DistributorFirmGroupName__c);
            }
            
        }
        System.debug('salesChannelgroup'+salesAndDistributorgroup);
        List<group> groupList =[select id,name from group where name in:salesAndDistributorgroup];
        System.debug('groupList'+groupList);
        if(groupList.size()>0){
            for(group groupObj :groupList){
                mapGroupNameAndId.put(groupObj.name,groupObj.Id);
            }
        }
        List<Loaner__Share> LoanerShareList = New List<Loaner__Share>();
        for(Loaner__c LoanerObj:LoanerMap.values()){
            IF(mapGroupNameAndId.containskey(LoanerObj.SalesRepFirmGroup__c)){
                Loaner__Share LoanerShareObj = New Loaner__Share();
                LoanerShareObj.parentId = LoanerObj.Id;
                LoanerShareObj.AccessLevel ='Edit';
                LoanerShareObj.UserOrGroupId = mapGroupNameAndId.get(LoanerObj.SalesRepFirmGroup__c);
                LoanerShareList.add(LoanerShareObj);
            }
            IF(mapGroupNameAndId.containskey(LoanerObj.DistributorFirmGroupName__c)){
                Loaner__Share LoanerShareObj = New Loaner__Share();
                LoanerShareObj.parentId = LoanerObj.Id;
                LoanerShareObj.AccessLevel ='Edit';
                LoanerShareObj.UserOrGroupId = mapGroupNameAndId.get(LoanerObj.DistributorFirmGroupName__c);
                LoanerShareList.add(LoanerShareObj);
            }
        }
        System.debug('LoanerShareList'+LoanerShareList);
        If(LoanerShareList.size()>0){
            upsert LoanerShareList;
        }
    } 
    
    public static void removeAccessToInsideSales(Map<id,Loaner__c> LoanerMap, Map<id,Loaner__c> loanerNewMap){
        System.debug('removeAccessToInsideSales');
        Set<String> salesAndDistributorgroup = New Set<String>();
        Map<String,Id> mapGroupNameAndId = New Map<String,Id>();
        for(Loaner__c LoanerObj:LoanerMap.values()){
            If(LoanerObj.SalesRepFirmGroup__c != Null && 
               loanerNewMap.get(LoanerObj.Id).SalesRepFirmGroup__c != LoanerObj.SalesRepFirmGroup__c){
                   salesAndDistributorgroup.add(LoanerObj.SalesRepFirmGroup__c);
               }
            IF(LoanerObj.DistributorFirmGroupName__c != Null && 
               loanerNewMap.get(LoanerObj.Id).DistributorFirmGroupName__c != LoanerObj.DistributorFirmGroupName__c){
                   salesAndDistributorgroup.add(LoanerObj.DistributorFirmGroupName__c);
               }
        }
        List<group> groupList =[select id,name from group where name in:salesAndDistributorgroup];
        List<Loaner__Share> LoanerShareList = [Select id from Loaner__Share where parentId in:LoanerMap.keyset() And UserOrGroupId in:groupList];
        System.debug('LoanerShareList'+LoanerShareList);
        if(LoanerShareList.size()>0){
            delete LoanerShareList;
        }
    }
    
    public static void updateSalesRepAndDistributorShare(Map<id,Loaner__c> LoanerNewMap,Map<id,Loaner__c> LoanerOldMap){
        Map<Id,Loaner__c> LoanerToBeUpdatedMap = New Map<Id,Loaner__c>();
        Map<Id,Loaner__c> LoanerToBeRemovedMap = New Map<Id,Loaner__c>();
        for(Loaner__c LoanerObj : LoanerNewMap.values()){
            if(LoanerOldMap.get(LoanerObj.Id).SalesRepFirmGroup__c!= LoanerObj.SalesRepFirmGroup__c||
               LoanerOldMap.get(LoanerObj.Id).DistributorFirmGroupName__c!= LoanerObj.DistributorFirmGroupName__c){
                   LoanerToBeUpdatedMap.put(LoanerObj.Id,LoanerObj);
                   LoanerToBeRemovedMap.put(LoanerObj.Id,LoanerOldMap.get(LoanerObj.Id));
               }
        }
        If(LoanerToBeUpdatedMap.size()>0){
            accessToSalesOrDistributor(LoanerToBeUpdatedMap);
            //  removeAccessToInsideSales(LoanerToBeRemovedMap);
            removeAccessToInsideSales(LoanerToBeRemovedMap, LoanerNewMap);
        }
    }
    
    public static void accessToinsideSalesAndRSM(List<loaner__c> newLoanerList){
        List<Loaner__Share> LoanerShareList = New List<Loaner__Share>();
        For(loaner__c loanObj:newLoanerList){
            IF(loanObj.Inside_Sales_Finisar__c!=Null && loanObj.CreatedById!=loanObj.Inside_Sales_Finisar__c && loanObj.InsideSalesActiveCheck__c){
                LoanerShareList.add(EditLoanerShareObjectAccess(loanObj,loanObj.Inside_Sales_Finisar__c));
            }
            IF(loanObj.RSM_PLM_Finisar__c!=Null && loanObj.CreatedById!=loanObj.RSM_PLM_Finisar__c && loanObj.RSMFinisarActiveCheck__c){
                LoanerShareList.add(EditLoanerShareObjectAccess(loanObj,loanObj.RSM_PLM_Finisar__c));
            }
        }
        IF(LoanerShareList.size()>0){
            insert LoanerShareList;
        }
    }
    
    public static void accessToinsideSalesAndRSM(Map<Id,loaner__c> oldLoanerMap,Map<Id,loaner__c> newLoanerMap){
        List<Loaner__Share> LoanerShareList = New List<Loaner__Share>();
        for(Id loanerId:newLoanerMap.keyset()){
            If(oldLoanerMap.get(loanerId).Inside_Sales_Finisar__c!=newLoanerMap.get(loanerId).Inside_Sales_Finisar__c && newLoanerMap.get(loanerId).createdById!=newLoanerMap.get(loanerId).Inside_Sales_Finisar__c && newLoanerMap.get(loanerId).InsideSalesActiveCheck__c){
                Loaner__Share loanshareObj = EditLoanerShareObjectAccess(newLoanerMap.get(loanerId),newLoanerMap.get(loanerId).Inside_Sales_Finisar__c);
                LoanerShareList.add(loanshareObj);
            }
            If(oldLoanerMap.get(loanerId).RSM_PLM_Finisar__c!=newLoanerMap.get(loanerId).RSM_PLM_Finisar__c && newLoanerMap.get(loanerId).createdById!=newLoanerMap.get(loanerId).RSM_PLM_Finisar__c && newLoanerMap.get(loanerId).RSMFinisarActiveCheck__c){
                Loaner__Share loanshareObj = EditLoanerShareObjectAccess(newLoanerMap.get(loanerId),newLoanerMap.get(loanerId).RSM_PLM_Finisar__c);
                LoanerShareList.add(loanshareObj);
            }
        }
        IF(LoanerShareList.size()>0){
            upsert LoanerShareList;
        }
    }
    
    public static Loaner__Share EditLoanerShareObjectAccess(Loaner__c loanerObj,Id userId){
        Loaner__Share LoanerShareObj = New Loaner__Share();
        LoanerShareObj.parentId = loanerObj.Id;
        LoanerShareObj.AccessLevel ='Edit';
        LoanerShareObj.UserOrGroupId =userId;
        return LoanerShareObj;
    }
    
    /**
* Method Name: updateVPSVP
* Input Parameter: List<Loaner__c> 
* output parameters: NA
* Description : updates VP and SVP on loaner from Custom metadata.
* Date : 22/04/2020
* */
    public static void updateVPSVP(List<Loaner__c> loanerList){
        system.debug('loanerList'+loanerList);
        List<String> rmsEmails = new List<String>();
        Map<String, String> emailMap = new Map<String, String>();
        Map<String, String> vpMapping = new Map<String, String>();
        Map<String, String> svpMapping = new Map<String, String>();
        for(Loaner__c loaner : loanerList){
            rmsEmails.add(loaner.RSMEmail__c);
        }
        for(VPSVP_Mapping__mdt mapping : [SELECT Id, SVP__c,VP__c, RSMName__c
                                          FROM VPSVP_Mapping__mdt 
                                          WHERE RSMName__c IN :rmsEmails]){
                                              emailMap.put(mapping.VP__c, '');
                                              vpMapping.put(mapping.RSMName__c, mapping.VP__c);
                                              if(mapping.VP__c != mapping.SVP__c){
                                                  svpMapping.put(mapping.RSMName__c, mapping.SVP__c);
                                                  emailMap.put(mapping.SVP__c, '');
                                              }
                                          }
        for(User usr : [SELECT Id, Name FROM User
                        WHERE Name IN : emailMap.keySet() AND isActive = true]){
                            emailMap.put(usr.Name, usr.Id);
                        }
        system.debug('emailMap'+emailMap);
        system.debug('vpMapping'+vpMapping);
        system.debug('svpMapping'+svpMapping);
        for(Loaner__c loaner : loanerList){
            system.debug('loaner.RSMEmail__c'+loaner.RSMEmail__c);
            if(vpMapping.containsKey(loaner.RSMEmail__c)){
                system.debug('loaner.RSMEmail__c'+loaner.RSMEmail__c);
                if(emailMap.get(vpMapping.get(loaner.RSMEmail__c)) != ''){
                    loaner.VP_PLD_Finisar__c = emailMap.get(vpMapping.get(loaner.RSMEmail__c));
                }
            }
            if(svpMapping.containsKey(loaner.RSMEmail__c)){
                if(emailMap.get(svpMapping.get(loaner.RSMEmail__c)) != ''){
                    loaner.SVP__c = emailMap.get(svpMapping.get(loaner.RSMEmail__c));
                }
            } else if(emailMap.get(vpMapping.get(loaner.RSMEmail__c)) != '') {
                loaner.SVP__c = emailMap.get(vpMapping.get(loaner.RSMEmail__c));
            }
            system.debug('loaner.SVP__c'+loaner.SVP__c);
        }
    }
    //Added for WSS
    public static void updateBuonLoaner(List<Loaner_Line__c> deletedLines){
        List<Id> loanerIds = new List<Id>();
        List<Id> productIds = new List<Id>();
        Map<Id, String> loanerMap = new Map<Id, String>();
        for(Loaner_Line__c line : deletedLines){
            loanerMap.put(line.Loaner__c, null);
        }
        for(Loaner_Line__c lline : [SELECT Id, Product__c, Product__r.Bu_Code__c, Product__r.Product_Family__c, Loaner__c
                                   FROM Loaner_Line__c 
                                    WHERE Loaner__c IN: loanerMap.keySet()]){
                                       //loanerMap 
                                       if(lline.Product__r.Bu_Code__c == '0040' &&
                                          lline.Product__r.Product_Family__c != 'WSS-OCM' &&
                                          lline.Product__r.Product_Family__c != 'WSS-OIG'){
                                             loanerMap.put(lline.Loaner__c, 'WSS'); 
                                          } else if(loanerMap.get(lline.Loaner__c) == null){
                                              loanerMap.put(lline.Loaner__c, 'Non WSS');
                                          }
                                    }
        List<Loaner__c> loaners = new List<Loaner__c>();
        for(Id loanerId : loanerMap.keySet() ){
            loaners.add(new Loaner__c(Id = loanerId, BuCode__c = loanerMap.get(loanerId)));
        }
        if(loaners != null && !loaners.isEmpty()){
            update loaners;
        }
}
}