src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Address_ship_to__c.field-meta.xml
<CustomField>
    <fullName>Address_ship_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ship to Locations for Company Name Ship to</description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (1 AND 3)) AND 4 AND 5 AND 6</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Company_Name_Ship_To__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Company_Name_Ship_To__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Code__c</field>
            <operation>equals</operation>
            <value>SHIP_TO</value>
        </filterItems>
        <filterItems>
            <field>Account.Site_Use_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account.Org_ID__c</field>
            <operation>equals</operation>
            <value>2</value>
        </filterItems>
        <infoMessage>If a Company Ship to is selected, then, the address related to company ship to is shown by default. User can override this filter</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loaners (Address)</relationshipLabel>
    <relationshipName>ShiptoLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Est_Production_Date__c.field-meta.xml
<CustomField>
    <fullName>Est_Production_Date__c</fullName>
    <label>Est Production Date</label>
    <type>Date</type>
</CustomField>

src/objects/Loaner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity #</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loaners</relationshipLabel>
    <relationshipName>Loaners</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Loaner__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Select &quot;New Opportunity&quot; only if this loaner links to an Opportunity in Salesforce.Then there should only be 1 P/N on this loaner which matches to the Opportunity P/N.Select any other choice if this is a stand-alone loaner which can include multiple P/Ns.</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Opportunity</fullName>
            </value>
            <value>
                <fullName>New Opportunity - &lt; 100K SAM</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity -  Demand already forecasted</fullName>
            </value>
            <value>
                <fullName>Not New Opportunity - Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Loaner__c/fields/Status_Approval__c.field-meta.xml
<CustomField>
    <fullName>Status_Approval__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loaner_Line_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Est_Annual_Qty__c.field-meta.xml
<CustomField>
    <fullName>Est_Annual_Qty__c</fullName>
    <label>Est Annual Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Price_100_999_column_price__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Price_100_999_column_price__c</fullName>
    <inlineHelpText>Fill out if system does not auto-populate.</inlineHelpText>
    <label>Loaner Price (100-999 column price)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Qty__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Qty__c</fullName>
    <label>Loaner Qty</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected, Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/globalValueSets/Loaner_Line_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Sales Order</fullName>
    </customValue>
    <masterLabel>Loaner Line Approval Status</masterLabel>
</GlobalValueSet>

src/classes/LoanerIntegrationTest.cls
@isTest
private class LoanerIntegrationTest {
    
    @isTest 
    static void testValidateLoanerCallout()
    {
        TestDataUtilityClass.preparetestData();
        List<Loaner__c> loaners  = [select Id,Name,Opportunity_Type__c,Opportunity__c,Est_Production_Date__c ,(select Id,Product__c,Name,Est_Annual_Qty__c From Loaner_Lines__r ) From Loaner__c where  Opportunity_Type__c='New Opportunity - < 100K SAM' Limit 1];
        Test.setMock(WebServiceMock.class, new LoanerIntegrationMockResponse());
        LoanerIntegration_Wsdl.LoanerParameter loanerparameter = new LoanerIntegration_Wsdl.LoanerParameter();
        loanerparameter.loanerId =loaners[0].Id;
        List<LoanerIntegration_Wsdl.LoanerParameter> loanerparameters = new   List<LoanerIntegration_Wsdl.LoanerParameter> ();
        loanerparameters.add(loanerparameter);
        List<String> errormessages = LoanerIntegration_Wsdl.invokeService(loanerparameters);
        
        for(String msg:errormessages )
        {
            System.assertEquals('You have uncommitted work pending. Please commit or rollback before calling out' ,msg);
        }
        
        
    }
    @isTest 
    static void testValidateRecords()
    {
        
        TestDataUtilityClass.preparetestData();
        Test.startTest();
        Loaner__c loaner1  = [select Id,Name,Opportunity_Type__c,Opportunity__c,Est_Production_Date__c ,(select Id,Product__c,Name,Est_Annual_Qty__c From Loaner_Lines__r ) From Loaner__c where  Opportunity_Type__c='New Opportunity - < 100K SAM' Limit 1]; 
        String actualmsg1=LoanerIntegration_Wsdl.validateRecords(loaner1.Id);
        String expectedmsg1= 'Required Field '+'Est Annual Qty'+' Must be Filled For Line Item '+loaner1.get('Name');
        
        
        
        Loaner__c loaner2  = [select Id,Opportunity__c,Est_Production_Date__c,Opportunity_Type__c,Address_ship_to__c,(select Id,Product__c,Name,Loaner_Qty__c,Est_Annual_Qty__c,Loaner_Price_100_999_column_price__c From Loaner_Lines__r )  From Loaner__c where Project_Name__c ='Test2Invaliddata' and Opportunity_Type__c='New Opportunity' and  Status_Approval__c ='Draft']; 
        String actualmsg2=LoanerIntegration_Wsdl.validateRecords(loaner2.Id);
        String expectedmsg2='Required Field Est Production Date Must be Filled';
        
        
        Loaner__c loaner3  = [select Id,Opportunity__c,Est_Production_Date__c,Opportunity_Type__c,Address_ship_to__c,(select Id,Product__c,Name,Loaner_Qty__c,Est_Annual_Qty__c,Loaner_Price_100_999_column_price__c From Loaner_Lines__r )  From Loaner__c where Project_Name__c ='Test2OpportunityTest' and Opportunity_Type__c='New Opportunity' and  Status_Approval__c ='Draft']; 
        String actualmsg3=LoanerIntegration_Wsdl.validateRecords(loaner3.Id);
        
        
        Test.stopTest();
        
        
    }
}