src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner__c/fields/Qual_Sample_Finisar__c.field-meta.xml
<CustomField>
    <fullName>Qual_Sample_Finisar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Qual Sample</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/LoanerEmailCustomComponentController.cls
/*
 * 
 *  
 * 
 * 
 * 
 * 
*/

public class LoanerEmailCustomComponentController {
    
   
    public Id recordId { get;set; }
  public String recordObject { get;set; }
 /*   public boolean lonerSummary {get;set;}
    public boolean LineItemApprovalList{get;set;}
    public boolean lineItemsApproval {get;set;}
    public boolean LoanerlineItems {get;set;}
    public boolean lineItemFooter {get;set;} */
   	public Id recipientId {get;set;} 
   /*
    public list<Loaner_Line__c> getLineItems(){
        List<Loaner_Line__c> lineItems;
        lineItems = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(recordId,recipientId);
        System.debug('lineItems'+lineItems);
        return lineItems;
    }
    
        public list<Loaner_Line__c> getAllLineItems(){
        List<Loaner_Line__c> lineItems;
        List<String> statusList = New List<String>{'Approved','Rejected','Draft','Approval Pending','Cancelled'};    
        lineItems = RecordApprovalDao.getLineItemsRecordsForApprovalEmail(recordId,statusList);
        System.debug('lineItems'+lineItems);
        return lineItems;
    } */
    
    public Loaner__c getLoaner(){
        Loaner__c sobj;
        sobj =(Loaner__c) RecordApprovalDao.getHeaderRecord(recordId);
       
        return sobj;
    }
    public String getQualSample(){
        Loaner__c sobj;
        string Qual ;
        sobj =(Loaner__c) RecordApprovalDao.getHeaderRecord(recordId);
        if(sobj.Qual_Sample_Finisar__c){
            Qual = 'Yes';
                }else{
                 Qual = 'No';   
                }
        return Qual;
    }
     public Loaner__c getExtension()
    {
        String recId =recordId;
        String querytofields = Label.Loaner_Fields;
        String extensionlinefields = Label.Extension_Lines_Fields;
        String query= 'SELECT '+ querytofields +' ,( SELECT ' +extensionlinefields +' FROM Loaner_Lines__r ) FROM Loaner__c  WHERE Id = :recordId';
        System.debug(query);
        Loaner__c loaner =Database.query(query);
        return loaner;
    }
    
    public List<Loaner_line__c> getErrorLineItems(){
        return RecordApprovalDao.getInvalidLoanersLineItemsRecords(recordId);
    }
    
}