src/objects/Product2/fields/Marketing_P_N__c.field-meta.xml
<CustomField>
    <fullName>Marketing_P_N__c</fullName>
    <label>Marketing P/N</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Agreed_Upon_Share__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Upon_Share__c</fullName>
    <label>Agreed Upon Share %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/Quote_Item__c/fields/Competitor_Info__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Info__c</fullName>
    <label>Competitor Info</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/objects/Quote_Item__c/fields/Competitor_Price__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Price__c</fullName>
    <label>Competitor Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Disti_Margin__c.field-meta.xml
<CustomField>
    <fullName>Disti_Margin__c</fullName>
    <formula>( Disti_Resale_Price__c  -  Target_Price__c ) /  Disti_Resale_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Disti Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/objects/Quote_Item__c/fields/Disti_Resale_Price__c.field-meta.xml
<CustomField>
    <fullName>Disti_Resale_Price__c</fullName>
    <label>Disti Resale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Lost - Delivery</fullName>
            </value>
            <value>
                <fullName>Lost - Price</fullName>
            </value>
            <value>
                <fullName>Lost - Technical</fullName>
            </value>
            <value>
                <fullName>One Time Order Processed</fullName>
            </value>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Canceled</fullName>
            </value>
            <value>
                <fullName>Project Cancelled</fullName>
            </value>
            <value>
                <fullName>Approval Cycle Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/PLM_Approver__c.field-meta.xml
<CustomField>
    <fullName>PLM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PLM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>PLM Approver</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>PLD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>MVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Finisar&apos;s PN ID#</inlineHelpText>
    <label>ID#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Available__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/RSM_Approver__c.field-meta.xml
<CustomField>
    <fullName>RSM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RSM Approver will be auto populated on Save if kept empty</inlineHelpText>
    <label>RSM Approver</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSM</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>RSD</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>SVP</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>startsWith</operation>
            <value>EVP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/classes/QuotePendingNotifications.cls
public class QuotePendingNotifications implements Database.Batchable<sObject> {
    public static final string STATUSPENDING ='0Q01N000001NfM5SAK';
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select Id, Status,(Select id,Line_Status__c,Name,Product__r.Name,Product__r.Marketing_P_N__c,Quantity__c,Target_Price__c,Disti_Resale_Price__c,Disti_Margin__c,Agreed_Upon_Share__c,Competitor_Info__c,Competitor_Price__c,RSM_Approver__c,PLM_Approver__c '+
                                        'from Quote_Items__r) FROM Quote Where ID =:STATUSPENDING');
    }
    
    public void execute(Database.BatchableContext BC, List<Quote> scope){
        List<Id> quoteItems = new List<Id>();
        Map<Id, String> quoteuser = new Map<Id,String>();
        Map<Id, List<ProcessInstanceWorkitem>> itemProcessMap = new Map<Id, List<ProcessInstanceWorkitem>>();
        Map<Id, List<Quote_Item__c>> quoteItemsMap = new Map<Id, List<Quote_Item__c>>();
        //List<Quote> quotes = new List<Quote>(scope);
        for(Quote qt : scope){
            quoteItemsMap.put(qt.Id, qt.Quote_Items__r);
            for(Quote_Item__c qtItm :qt.Quote_Items__r){
                quoteItems.add(qtItm.Id);
            }
        }
        for(processInstance proc :[Select id, targetobjectId, 
                                   (Select id, ActorId, OriginalActorId from workitems) 
                                   from processInstance 
                                   where TargetObjectid IN :quoteItems and status ='Pending']){
                                       itemProcessMap.put(proc.targetobjectId, proc.workitems);  
                                       quoteuser.put(proc.targetobjectId, proc.workitems[0].ActorId);
                                   }
        Map<Id,String> userNames = new Map<Id,String>();
        for(User usr :[Select id,name From User 
                       Where ID IN :quoteuser.values()]){
                           userNames.put(usr.Id, usr.Name);
                       }
        List < Messaging.SingleEmailMessage > mailList = new List < Messaging.SingleEmailMessage > ();
        for(Quote qt : scope){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            //mail.setTemplateId(et.id);
            mail.setToAddresses(new list<Id>{'005c0000005s1iNAAQ'});
           // mail.setTargetObjectId(qt.Id);
            mail.setSaveAsActivity(false);
            mail.setWhatId(qt.Id);
            string emailBody ='<html><style>table, th, td {border: 1px solid black;}<table style="width:100%"> <tr ><th>Line #</th><th>ID#</th><th>Product</th><th>Quantity</th><th>Target Price</th><th>Disti Resale Price</th><th>Disti Margin %</th><th>Agreed Upon Share %</th><th>Competitor Info</th><th>Competitor Price</th><th>Status</th><th>Pending With</th></tr>';
            for(Quote_Item__c qtItm :qt.Quote_Items__r){
                emailBody = emailBody+'<tr><td>'+qtItm.Name+'</td><td>'+qtItm.Product__r.Name+'</td><td>'+
                    qtItm.Product__r.Marketing_P_N__c+'</td><td>'+qtItm.Quantity__c+'</td><td>'+qtItm.Target_Price__c+
                    '</td><td>'+qtItm.Disti_Resale_Price__c+'</td><td>'+qtItm.Disti_Margin__c+'</td><td>'+qtItm.Agreed_Upon_Share__c+'</td><td>'+qtItm.Competitor_Info__c
                    +'</td><td>'+qtItm.Competitor_Price__c+'</td>' ;
                if(qtItm.Line_Status__c == 'Approved'){
                    emailBody = emailBody+'<td>'+qtItm.Line_Status__c+'</td>';
                }else{
                    if(qtItm.RSM_Approver__c == quoteuser.get(qtItm.Id)){
                        emailBody = emailBody+'<td>'+qtItm.Line_Status__c+'</td><td>RSM :'+  userNames.get(quoteuser.get(qtItm.Id))+'</td>';
                    } else{
                        emailBody = emailBody+'<td>'+qtItm.Line_Status__c+'</td><td>PLM :'+  userNames.get(quoteuser.get(qtItm.Id))+'</td>';
                    }
                    
                }
            }
            emailBody = emailBody+'</tr></table></html>';
            mail.setHtmlBody(emailBody);
            mailList.add(mail);
        }
        Messaging.sendEmail(mailList);
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
}