src/objects/Order/fields/HROCM_Order__c.field-meta.xml
<CustomField>
    <fullName>HROCM_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HROCM Order</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Order/recordTypes/PoS_Order.recordType-meta.xml
<RecordType>
    <fullName>PoS_Order</fullName>
    <active>true</active>
    <label>PoS Order</label>
</RecordType>

src/objects/Order_Line__c/Order_Line__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OrderLine-{0000}</displayFormat>
        <label>Order Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line__c/fields/HROCM_Line__c.field-meta.xml
<CustomField>
    <fullName>HROCM_Line__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HROCM Line</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the order to which this Line Item is related</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>RMA_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Order_Line__c/fields/Ship_From_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Inventory__c</fullName>
    <inlineHelpText>For RMA Orders, this is the Receiving site. Otherwise, it is the Ship from site.</inlineHelpText>
    <label>Warehouse</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10G-300ER</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300IR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300LR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300SR</fullName>
    </customValue>
    <customValue>
        <fullName>10G-300VSR</fullName>
    </customValue>
    <customValue>
        <fullName>200GAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-DQPSK</fullName>
    </customValue>
    <customValue>
        <fullName>40G-NRZ</fullName>
    </customValue>
    <customValue>
        <fullName>40G-ODB</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-NR</fullName>
    </customValue>
    <customValue>
        <fullName>ANALOG-RES</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI P2P</fullName>
    </customValue>
    <customValue>
        <fullName>BIDI PON</fullName>
    </customValue>
    <customValue>
        <fullName>BUS DOCTOR</fullName>
    </customValue>
    <customValue>
        <fullName>CABLE</fullName>
    </customValue>
    <customValue>
        <fullName>CATV</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310PR</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1310ST</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550ND</fullName>
    </customValue>
    <customValue>
        <fullName>CATV1550QM</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-FTTH</fullName>
    </customValue>
    <customValue>
        <fullName>CATV-XMOD</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI</fullName>
    </customValue>
    <customValue>
        <fullName>CAUI-4</fullName>
    </customValue>
    <customValue>
        <fullName>CDAUI-8</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-4D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-8D</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-CCM</fullName>
    </customValue>
    <customValue>
        <fullName>CKTPK-OLA</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OCM</fullName>
    </customValue>
    <customValue>
        <fullName>WSS-OIG</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

src/classes/ordersBatch.cls
public class ordersBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC ){
        if(!Test.isRunningTest()){
            return Database.getQueryLocator([select id,Warehouse__c from order where Warehouse__c = null  ]);  
        } else {
            return Database.getQueryLocator([select id,Warehouse__c from order where Warehouse__c = null AND recordtype.developername='PoS_Order' LIMIT 200]);
        }
        
    }
    public void execute(Database.BatchableContext BC, List<Order> scope) {
        List<Order> orderList = new List<Order>();
        Set<Id> hrOCM = New Set<Id>();
        List<Order_Line__c> orderLineList = new List<Order_Line__c>();
        Map<String, String> orderWarehouseMap = new Map<String, String>();
        for(Order_Line__c line : [SELECT Id, order__c, Ship_From_Inventory__c, Part_Number__r.Product_Family__c 
                                  FROM Order_Line__c 
                                  WHERE order__c IN :scope]){
                                      if(!orderWarehouseMap.containsKey(line.Order__c)){
                                          orderWarehouseMap.put(line.Order__c, line.Ship_From_Inventory__c);
                                      } else if(orderWarehouseMap.get(line.Order__c) != 'SYD'){
                                          orderWarehouseMap.put(line.Order__c, line.Ship_From_Inventory__c);
                                      }
                                      if(line.Ship_From_Inventory__c == 'WXI' && (
                                          line.Part_Number__r.Product_Family__c =='WSS-OCM' ||
                                          line.Part_Number__r.Product_Family__c =='WSS-OIG')){
                                              line.HROCM_Line__c = true;
                                              hrOCM.add(line.Order__c);
                                              orderLineList.add(line);
                                          }
                                  }
        for(Order ord : scope){
            ord.Warehouse__c = orderWarehouseMap.get(ord.Id);
            if(hrOCM.contains(ord.Id)){
                ord.HROCM_Order__c = true;
            }
            orderList.add(ord);
        }
        update orderList;
    }
    public void finish(Database.BatchableContext BC) {
        
    }
}