src/objects/Order/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Quote/recordTypes/Quote_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Quote_Record_Type</fullName>
    <active>true</active>
    <label>Normal Quote</label>
</RecordType>

src/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <description>to track quote items</description>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <defaultValue>99999</defaultValue>
    <label>Target Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Quote_Item__c/fields/TQ_Currency__c.field-meta.xml
<CustomField>
    <fullName>TQ_Currency__c</fullName>
    <label>TQ Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Quote_Item__c/fields/Transfer_Currency_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Currency_Amount__c</fullName>
    <label>Transfer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/QuoteRatePlan__c/QuoteRatePlan__c.object-meta.xml
<CustomObject>
    <label>Quote Rate Plan</label>
    <nameField>
        <displayFormat>QRP-{00000}</displayFormat>
        <label>Quote Rate Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuoteRatePlan__c/fields/LeadTime__c.field-meta.xml
<CustomField>
    <fullName>LeadTime__c</fullName>
    <label>Lead Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Rate Plans</relationshipLabel>
    <relationshipName>Quote_Rate_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/QuoteRatePlan__c/fields/TQ_Currency__c.field-meta.xml
<CustomField>
    <fullName>TQ_Currency__c</fullName>
    <label>TQ Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/QuoteRatePlan__c/fields/Transfer_Price__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Price__c</fullName>
    <label>Transfer Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/classes/QuoteRatePlan_Controller.cls
public with sharing class QuoteRatePlan_Controller {
    public List<QuoteRatePlan__c> quoteTier{get; set;}
    public Quote_Item__c qtLine{get; set;}
    public Boolean transfrQuote{get; set;}
    public Map<String, Double> rateConvertionMap;
    public QuoteRatePlan_Controller(ApexPages.StandardController controller) {
        transfrQuote = false;
        rateConvertionMap = new Map<String, Double>();
        Id qtRecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Quote_Record_Type').getRecordTypeId();
        if(!test.isRunningTest()){
            controller.addFields(New List<String> {'Target_Price__c', 'Quantity__c','Quote__r.RecordtypeId','TQ_Currency__c','CurrencyIsoCode'});    
        }
        qtLine = (Quote_Item__c)controller.getRecord();
        system.debug('oppline id '+qtLine.Id);
        if(qtLine.Quote__r.RecordtypeId != qtRecordTypeId){
            transfrQuote = true;
            for(DatedConversionRate conVal : [SELECT Id,Isocode, StartDate,NextStartDate, ConversionRate 
                                              FROM DatedConversionRate 
                                              WHERE StartDate <= :date.today() and NextStartDate > :date.today()]){
                                                  rateConvertionMap.put(conVal.IsoCode, conVal.ConversionRate); 
                                              }
        }
        List<QuoteRatePlan__c> plans = [SELECT Id, QuoteLineItem__c, SalesPrice__c, SequenceNumber__c, LeadTime__c,
                                        QuoteLineItem__r.Quote__r.RecordtypeId,Transfer_Price__c, TQ_Currency__c
                                        FROM QuoteRatePlan__c 
                                        WHERE QuoteLineItem__c = :qtLine.Id ORDER BY SequenceNumber__c asc];
        if(plans != null && !plans.isEmpty()){
            quoteTier = plans;
        } else {
            quoteTier = new List<QuoteRatePlan__c>();
            QuoteRatePlan__c rate = new QuoteRatePlan__c();
            rate.TQ_Currency__c = qtLine.TQ_Currency__c;
            quoteTier.add(rate);
        }
    }
    public pageReference addNewRow(){
        QuoteRatePlan__c rate = new QuoteRatePlan__c();
        rate.TQ_Currency__c = qtLine.TQ_Currency__c;
        /* for(QuoteRatePlan__c rp: quoteTier){
system.debug('rp'+rp);
if(rp.Transfer_Price__c != 0 && rp.SalesPrice__c == null){
system.debug('rp'+rp);
rp.SalesPrice__c = (rp.Transfer_Price__c / rateConvertionMap.get(rp.TQ_Currency__c)) * rateConvertionMap.get(qtLine.CurrencyIsoCode);
}
}*/
        system.debug('quoteTier'+quoteTier);
        quoteTier.add(rate);
        return null;
    }
    public pageReference saveAction(){
        List<QuoteRatePlan__c> plans = new List<QuoteRatePlan__c>();
        for(QuoteRatePlan__c plan : quoteTier ){
            if(plan.SequenceNumber__c != null && (plan.SalesPrice__c !=0 || plan.Transfer_Price__c != 0)){
                plan.QuoteLineItem__c = qtline.Id;
                plans.add(plan);
                if(plan.SequenceNumber__c < qtLine.Quantity__c){
                    if(plan.SalesPrice__c != 0)
                        qtLine.Target_Price__c = plan.SalesPrice__c;
                    if(plan.Transfer_Price__c != 0)
                        qtLine.Transfer_Currency_Amount__c = plan.Transfer_Price__c;
                }
            }
        }
        if(plans != null && !plans.isEmpty()){
            upsert plans;
            update qtLine;
        }
        return new pageReference('/'+qtLine.Id);
    }
    public pageReference CancelAction(){
        return new pageReference('/'+qtLine.Id);
    }
    public pageReference updatesalesPrice(){
        for(QuoteRatePlan__c rp: quoteTier){
            if(rp.Transfer_Price__c != null && rp.Transfer_Price__c != 0 ){
                rp.SalesPrice__c = (rp.Transfer_Price__c / rateConvertionMap.get(rp.TQ_Currency__c)) * rateConvertionMap.get(qtLine.CurrencyIsoCode);
            }
        }
        return null;
    }
}