src/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Forecast__c/fields/PLM__c.field-meta.xml
<CustomField>
    <fullName>PLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PLM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Forecast__c/fields/PLM_User_Active__c.field-meta.xml
<CustomField>
    <fullName>PLM_User_Active__c</fullName>
    <formula>PLM__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLM User Active</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Forecast__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Forecasts1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Forecast__c/fields/RSM_User_Active__c.field-meta.xml
<CustomField>
    <fullName>RSM_User_Active__c</fullName>
    <formula>RSM__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSM User Active</label>
    <type>Checkbox</type>
</CustomField>

src/classes/ForecastShareTriggerHelper.cls
public class ForecastShareTriggerHelper {
     public static void accessToPLMS(Map<Id,Forecast__c> forecastMap){
         List<Forecast__Share> fctsharelist = new List<Forecast__Share>();
         for(Forecast__c fct : forecastMap.values()){
             if(fct.PLM__c!=null && fct.PLM_User_Active__c){
                 Forecast__Share fctshare = new Forecast__Share();
                 fctshare.parentId = fct.Id;
                 fctshare.AccessLevel ='Read';
                 fctshare.UserOrGroupId = fct.PLM__c;
                 fctsharelist.add(fctshare);
             }
             if(fct.RSM__c!=null && fct.RSM_User_Active__c){
                 Forecast__Share fctshare = new Forecast__Share();
                 fctshare.parentId = fct.Id;
                 fctshare.AccessLevel ='Read';
                 fctshare.UserOrGroupId = fct.RSM__c;
                 fctsharelist.add(fctshare);
             }
         }
         If(fctsharelist!=null && fctsharelist.size()>0){
            upsert fctsharelist;
        }
     }
}