src/objects/Conversion_Details__c/Conversion_Details__c.object-meta.xml
<CustomObject>
    <label>Conversion Detail</label>
    <nameField>
        <displayFormat>CD-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversion Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conversion_Details__c/fields/Conversion_Date__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Date__c</fullName>
    <label>Conversion Date</label>
    <type>Date</type>
</CustomField>

src/objects/Conversion_Details__c/fields/Conversion_Qty__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Qty__c</fullName>
    <label>Conversion Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Conversion_Details__c/fields/Disposition_Transfer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Disposition_Transfer_Detail__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Disposition/Transfer Detail</label>
    <referenceTo>Disposition_Transfer_Details__c</referenceTo>
    <relationshipLabel>Conversion Details</relationshipLabel>
    <relationshipName>Conversion_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Disposition_Transfer_Details__c/Disposition_Transfer_Details__c.object-meta.xml
<CustomObject>
    <label>Disposition/Transfer Detail</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disposition/Transfer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Disposition_Transfer_Details__c/fields/Return_Detail__c.field-meta.xml
<CustomField>
    <fullName>Return_Detail__c</fullName>
    <label>Return Detail</label>
    <referenceTo>Return_Detail__c</referenceTo>
    <relationshipLabel>Disposition/Transfer Details</relationshipLabel>
    <relationshipName>Disposition_Transfer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Disposition_Transfer_Details__c/recordTypes/Disposition.recordType-meta.xml
<RecordType>
    <fullName>Disposition</fullName>
    <active>true</active>
    <label>Disposition</label>
</RecordType>

src/objects/Loaner__c/Loaner__c.object-meta.xml
<CustomObject>
    <label>Loaner</label>
    <nameField>
        <displayFormat>Loaner-{00000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/Loaner_Line__c.object-meta.xml
<CustomObject>
    <label>Loaner Line</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Loaner Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loaner Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loaner_Line__c/fields/Loaner__c.field-meta.xml
<CustomField>
    <fullName>Loaner__c</fullName>
    <label>Loaner</label>
    <referenceTo>Loaner__c</referenceTo>
    <relationshipLabel>Loaner Lines</relationshipLabel>
    <relationshipName>Loaner_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Loaner_Line__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Loaner Item  which it is extended by number of days</description>
    <label>Loaner Requestor Line</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item</value>
        </filterItems>
        <filterItems>
            <field>Loaner_Line__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Loaner Item Read Only</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Extension Lines</relationshipLabel>
    <relationshipName>Extension_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Return_Detail__c/Return_Detail__c.object-meta.xml
<CustomObject>
    <label>Return Detail</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Return_Detail__c/fields/Loaner_Line__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Line__c</fullName>
    <label>Loaner Line</label>
    <referenceTo>Loaner_Line__c</referenceTo>
    <relationshipLabel>Return Details</relationshipLabel>
    <relationshipName>Return_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/ConversionDetailsHelperTest.cls
@isTest
private class ConversionDetailsHelperTest {
    
    @testsetup 
    static void preparetestdata()
    {
        TestDataUtilityClass.preparetestData();
        
    }
    static testmethod void performNegativetestScenarios()
    {
        Test.startTest();
        Conversion_Details__c cd= new Conversion_Details__c();
        cd.Conversion_Date__c=System.today() + 10;
        
        Loaner__c loaner = [select Id From Loaner__c where Project_Name__c ='Test' Limit 1];
        Loaner_Line__c loanerline = [select Id From Loaner_Line__c where Loaner__c =:loaner.Id Limit 1];
        Return_Detail__c returnDet = [select Id From Return_Detail__c where Loaner_Line__c =:loanerline.Id Limit 1];
        Disposition_Transfer_Details__c dtdetail = [select Id,Quantity__c From Disposition_Transfer_Details__c where Return_Detail__c =:returnDet.Id];
        cd.Disposition_Transfer_Detail__c = dtdetail.Id;
        cd.Conversion_Qty__c =6;
        
        try{
            insert cd;
            
        }
        catch(Exception e)
        {
            
            SYSTEM.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Disposition Quantity5should be greater or equal to  Conversion Qty 6: []', E.getMessage());
            
        }
        Conversion_Details__c cd1= new Conversion_Details__c();
        cd1.Conversion_Date__c=System.today() + 10;
        cd1.Disposition_Transfer_Detail__c = dtdetail.Id;
        cd1.Conversion_Qty__c =5;
        insert cd1;
        cd1.Conversion_Qty__c = 4;
        try{
            update cd1;
        }
        catch(Exception e)
        {
            System.assertEquals('Update failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION,Disposition Quantity should be greater than Conversion Qty', e.getMessage());
        }
        Test.stopTest();
        
    }
    
    static testmethod void performPostiveTestScenarios()
    {
        Test.startTest();
        
        Conversion_Details__c cd= new Conversion_Details__c();
        cd.Conversion_Date__c=System.today() + 10;
        
        Loaner__c loaner = [select Id From Loaner__c where Project_Name__c ='Test' Limit 1];
        Loaner_Line__c loanerline = [select Id From Loaner_Line__c where Loaner__c =:loaner.Id Limit 1];
        Return_Detail__c returnDet = [select Id From Return_Detail__c where Loaner_Line__c =:loanerline.Id Limit 1];
        Disposition_Transfer_Details__c dtdetail = [select Id From Disposition_Transfer_Details__c where Return_Detail__c =:returnDet.Id];
        cd.Disposition_Transfer_Detail__c = dtdetail.Id;
        cd.Conversion_Qty__c =5;
        insert cd;
        
        Conversion_Details__c cd1 =[select Id ,Conversion_Qty__c from Conversion_Details__c where Disposition_Transfer_Detail__c =:dtdetail.Id];
        cd1.Conversion_Qty__c =4;
        update cd1;
        Conversion_Details__c cd2 =[select Id ,Conversion_Qty__c from Conversion_Details__c where Disposition_Transfer_Detail__c =:dtdetail.Id];
        cd1.Conversion_Qty__c =5;
        update cd2;
        Test.stopTest();
    }
}